Repository tektoncd/pipeline, pull requests merged in 2018-09, with the labels that each got.

#41 add test/presubmit-tests.sh script required by prow
  test/presubmit-tests.sh
Labels: approved, lgtm

#48 fix presubmit-test.sh script for
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#54 Add values for `type`s in resources
  DEVELOPMENT.md
  config/crds/pipeline_v1beta1_pipelineparams.yaml
  config/crds/pipeline_v1beta1_pipelinerun.yaml
  config/crds/pipeline_v1beta1_taskrun.yaml
  config/samples/pipeline_v1beta1_pipelineparams.yaml
  config/samples/pipeline_v1beta1_pipelinerun.yaml
  config/samples/pipeline_v1beta1_taskrun.yaml
  examples/invocations/kritis-pipeline-run.yaml
  examples/invocations/run-kritis-test.yaml
  examples/pipelineparams.yaml
  pkg/apis/pipeline/v1beta1/pipelineparams_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#53 Add badges and some code review details
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm, size/S

#39 Initial design ideas for Source
  README.md
  config/crds/pipeline_v1beta1_pipeline.yaml
  config/crds/pipeline_v1beta1_pipelineparams.yaml
  config/crds/pipeline_v1beta1_pipelinerun.yaml
  config/crds/pipeline_v1beta1_resource.yaml
  config/crds/pipeline_v1beta1_task.yaml
  config/crds/pipeline_v1beta1_taskrun.yaml
  config/samples/pipeline_v1beta1_pipeline.yaml
  config/samples/pipeline_v1beta1_pipelineparams.yaml
  config/samples/pipeline_v1beta1_pipelinerun.yaml
  config/samples/pipeline_v1beta1_resources.yaml
  config/samples/pipeline_v1beta1_task.yaml
  config/samples/pipeline_v1beta1_taskrun.yaml
  crds.png
  examples/build_task.yaml
  examples/deploy_tasks.yaml
  examples/pipelineparams.yaml
  examples/pipelines/guestbook-resources.yaml
  examples/pipelines/guestbook.yaml
  examples/pipelines/kritis-pipeline.png
  examples/pipelines/kritis-resources.yaml
  examples/pipelines/kritis.yaml
  examples/test_tasks.yaml
  pkg/apis/pipeline/v1beta1/git_source.go
  pkg/apis/pipeline/v1beta1/image_source.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipelineparams_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/resource_types.go
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#56 add optional comment on fields
  pkg/apis/pipeline/v1beta1/git_source.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipelineparams_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/resource_types.go
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#60 Add cluster and cluster bindings
  config/crds/pipeline_v1beta1_pipeline.yaml
  config/crds/pipeline_v1beta1_pipelineparams.yaml
  config/crds/pipeline_v1beta1_task.yaml
  config/samples/pipeline_v1beta1_pipeline.yaml
  examples/pipelines/guestbook.yaml
  examples/pipelines/kritis.yaml
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipelineparams_types.go
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: lgtm, size/L

#67 Add issue number to commit message requirements
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#70 add instructions in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, lgtm, size/S

#80 Make sure dep is a no-op on every PR
  CONTRIBUTING.md
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M
