Repository tektoncd/pipeline, pull requests merged in 2018-12, with the labels that each got.

#293 Add more vendored deps required for `dep-collector` 🤣
  Gopkg.lock
  vendor/github.com/sergi/go-diff/AUTHORS
  vendor/github.com/sergi/go-diff/CONTRIBUTORS
  vendor/github.com/sergi/go-diff/LICENSE
  vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/diffmatchpatch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/match.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/mathutil.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/stringutil.go
Labels: approved, lgtm, size/XXL

#288 Make verify-codegen.sh also check /vendor
  hack/verify-codegen.sh
Labels: approved, lgtm, size/XS

#298 Fix typo / copy pasta in example Pipeline
  examples/pipeline.yaml
Labels: approved, lgtm, size/XS

#296 Add dep-collector to the list of required tools in Gopkg.toml
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XS

#309 Fix spelling errors
  pkg/reconciler/v1alpha1/taskrun/resources/taskspec.go
Labels: approved, lgtm, size/XS

#306 Remove ServiceAccountName from Task
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, lgtm, size/M

#308 Format markdown
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  code-of-conduct.md
  docs/Concepts.md
  docs/cuj/README.md
  docs/cuj/exercises/exercise1/Exercise1.md
  docs/cuj/exercises/exercise2/Exercise2.md
  docs/cuj/exercises/exercise3/Exercise3.md
  docs/cuj/exercises/exercise4/Excercise4.md
  docs/task-parameters.md
  docs/using.md
  examples/README.md
  hack/README.md
  hack/release.md
  test/README.md
Labels: approved, lgtm, size/XL

#307 Remove default namespace from samples 😅
  examples/build-task.yaml
  examples/default-cluster-admin.yaml
  examples/deploy-task.yaml
  examples/output-pipeline.yaml
  examples/output-tasks.yaml
  examples/pipeline.yaml
  examples/resources.yaml
  examples/run/output-pipeline-run.yaml
  examples/run/pipeline-run.yaml
Labels: approved, lgtm, size/S

#316 Remove PipelineParams from building blocks image
  docs/images/building-blocks.png
Labels: approved, lgtm, size/XS

#318 Format markdown
  docs/Concepts.md
  docs/using.md
Labels: approved, lgtm, size/S

#311 Update test-infra to include latest features of release.sh
  Gopkg.lock
  hack/release.md
  hack/release.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#322 golang format tools
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/controller.go
Labels: approved, lgtm, size/M

#324 Format markdown
  hack/release.md
  test/README.md
Labels: approved, lgtm, size/S

#329 Format markdown
  docs/tutorial.md
Labels: approved, lgtm, size/XL

#328 Add ServiceAccount part into `docs/using.md`
  docs/using.md
Labels: approved, lgtm, size/M

#331 Format markdown
  docs/using.md
Labels: approved, lgtm, size/XS

#330 Small refactoring in `test` to declare test Helpers
  test/build_logs.go
  test/clients.go
  test/crd.go
  test/init_test.go
  test/taskrun_test.go
Labels: approved, lgtm, size/M

#334 Unexport methods which were only exported to avoid dependency cycle
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/controller.go
Labels: approved, lgtm, size/L

#338 Format markdown
  test/builder/README.md
Labels: approved, lgtm, size/M

#337 Fix spelling errors
  test/builder/pipeline.go
Labels: approved, lgtm, size/XS

#339 Format markdown
  README.md
  docs/developers/README.md
  docs/using.md
Labels: approved, lgtm, size/L

#335 Migrate more unit test using builder 🏗
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  pkg/reconciler/v1alpha1/taskrun/validate_test.go
  test/builder/examples_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
  test/builder/task.go
  test/builder/task_test.go
Labels: approved, lgtm, size/XXL

#343 golang format tools
  test/builder/task_test.go
Labels: approved, lgtm, size/XS

#342 Add docs and validation for `providedBy`
  docs/using.md
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, lgtm, size/L

#346 Format markdown
  docs/using.md
Labels: approved, lgtm, size/M

#347 Fix doc links
  examples/README.md
Labels: approved, lgtm, size/XS

#336 Add script to tail logs for pipelinerun and taskruns
  docs/using.md
  test/logs/README.md
  test/logs/color/color.go
  test/logs/kodata/LICENSE
  test/logs/kodata/VENDOR-LICENSE
  test/logs/main.go
  test/logs/pipelinerun/logs.go
  test/logs/pod/watcher.go
  test/logs/taskrun/logs.go
Labels: approved, lgtm, size/XXL

#340 Extract common WaitState functions 🔨
  test/cluster_resource_test.go
  test/crd_checks.go
  test/helm_task_test.go
  test/kaniko_task_test.go
  test/pipelinerun_test.go
  test/status_test.go
  test/taskrun_test.go
Labels: approved, lgtm, size/L

#359 Update test-infra
  Gopkg.lock
  third_party/VENDOR-LICENSE
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#352 Fix nil pointer bug in TaskRun SetDefaults
  pkg/apis/pipeline/v1alpha1/taskrun_defaults.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#349 Format markdown
  test/logs/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S
