Repository tektoncd/pipeline, pull requests merged in 2019-06, with the labels that each got.

#946 Use a fixed version for helm
  test/helm_task_test.go
Labels: approved, cla: yes, lgtm, size/XS

#948 Bump tektoncd/plumbing to fix ./hack/ scripts
  Gopkg.lock
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#940 Move TaskResource to task_types.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/task_types.go
Labels: approved, cla: yes, lgtm, size/M

#950 Reuse the function v1alpha1.GetPvcMount
  pkg/apis/pipeline/v1alpha1/artifact_pvc.go
  pkg/apis/pipeline/v1alpha1/artifact_pvc_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
  pkg/reconciler/v1alpha1/taskrun/resources/volume.go
Labels: approved, cla: yes, lgtm, size/M

#957 Remove the dollar sign and print correct kubeconfig info
  test/README.md
  test/init_test.go
Labels: approved, cla: yes, lgtm, size/S

#959 Format markdown
  test/README.md
Labels: approved, cla: yes, lgtm, size/XS

#962 Add API godoc in task_types.go
  pkg/apis/pipeline/v1alpha1/task_types.go
Labels: approved, cla: yes, lgtm, size/M

#952 Move TaskResourceBinding to taskrun_types.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
Labels: approved, cla: yes, lgtm, size/M

#945 Add pod output to build logs
  test/artifact_bucket_test.go
  test/build_logs.go
  test/helm_task_test.go
  test/init_test.go
Labels: approved, cla: yes, lgtm, size/M

#967 Update install.md to mention required minimum k8s version
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#968 Format markdown
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#949 tekton task to run unit tests
  tekton/ci-unit-test-run.yaml
  tekton/ci-unit-test.yaml
Labels: approved, cla: yes, lgtm, size/M

#966 Adds PipelineTask.name metadata label in TaskRun
  pkg/apis/pipeline/register.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/L

#969 Fix typo in auth docs serviceAccount name
  docs/auth.md
Labels: approved, cla: yes, lgtm, size/XS

#970 Initialize PipelineResources in declared order 📝
  api_compatibility_policy.md
  pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
Labels: approved, cla: yes, lgtm, size/S

#974 golang format tools
  pkg/apis/pipeline/register.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/M

#972 Update documentation on how to dev to a custom namespace
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/M

#928 Update the tekton release tasks for the imageDigestExporter image.
  tekton/publish-run.yaml
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/S

#982 Add support for secret and configMap valueFrom and envFrom fields in …
  docs/tasks.md
  pkg/reconciler/v1alpha1/taskrun/resources/apply.go
  pkg/reconciler/v1alpha1/taskrun/resources/apply_test.go
Labels: approved, cla: yes, lgtm, size/L

#963 Sort the steps of taskrun based on the steps of task
  docs/taskruns.md
  docs/tasks.md
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  pkg/status/stepstatesorter.go
  pkg/status/stepstatesorter_test.go
  test/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#986 Add tests for system/names
  pkg/system/names.go
  pkg/system/names_test.go
Labels: approved, cla: yes, lgtm, size/M

#936 Graceful sidecar support
  cmd/entrypoint/main.go
  cmd/entrypoint/main_test.go
  cmd/nop/main.go
  docs/developers/README.md
  docs/taskruns.md
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go
  pkg/reconciler/v1alpha1/taskrun/sidecars/stop.go
  pkg/reconciler/v1alpha1/taskrun/sidecars/stop_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  pkg/status/taskrunpod.go
  pkg/status/taskrunpod_test.go
  pkg/status/taskrunreasons.go
  test/kaniko_task_test.go
  test/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#902 Adding possibility to configure multiple service accounts for different tasks
  docs/pipelineruns.md
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
Labels: approved, cla: yes, lgtm, size/L

#987 Annotate controller jobs to prevent node eviction
  config/controller.yaml
  config/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#955 Remove API compatibility references to Knative in docs
  api_compatibility_policy.md
  tekton/koparse/test_release.yaml
Labels: approved, cla: yes, lgtm, size/M

#997 examples/README: filename had changed
  examples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1006 Implement templating within containerTemplate.
  pkg/reconciler/v1alpha1/taskrun/resources/apply.go
  pkg/reconciler/v1alpha1/taskrun/resources/apply_test.go
Labels: approved, cla: yes, lgtm, size/L

#1011 Add the revisions of plumbing and test-infra
  Gopkg.lock
  Gopkg.toml
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/M

#1003 Fix Pipeline error with ClusterTasks
  examples/pipelineruns/clustertask-pipelinerun.yaml
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/v1alpha1/taskrun/resources/taskresourceresolution.go
  pkg/reconciler/v1alpha1/taskrun/resources/taskresourceresolution_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/M

#1007 If no resources are linked, don't make a PVC 🗑️
  pkg/artifacts/artifact_storage_test.go
  pkg/artifacts/artifacts_storage.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/L

#1028 Remove unused Params field from TaskRunOutputs.
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/XS
