Repository tektoncd/pipeline, pull requests merged in 2019-05, with the labels that each got.

#822 Artifact bucket storage volume name should be consistent with mounts
  pkg/apis/pipeline/v1alpha1/artifact_bucket.go
  pkg/apis/pipeline/v1alpha1/artifact_bucket_test.go
  pkg/apis/pipeline/v1alpha1/artifact_pvc.go
  pkg/apis/pipeline/v1alpha1/artifact_pvc_test.go
  pkg/artifacts/artifacts_storage.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
Labels: approved, cla: yes, lgtm, size/M

#820 Fix TestStorageBucketPipelineRun to actually, y'know, run.
  test/artifact_bucket_test.go
Labels: approved, cla: yes, lgtm, size/S

#825 Merge steps and containerTemplate during Task validation
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1alpha1/task_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#830 Update ko Dockerfile to point to new ko repo
  tekton/ko/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#658 feat(retries) Design and implement retries
  docs/pipelines.md
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/taskspec.go
  test/builder/pipeline.go
  test/builder/task.go
  test/cancel_test.go
  test/pipelinerun_test.go
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#829 Storage end to end test can run without env var credentials ✨
  test/README.md
  test/gcs_taskrun_test.go
  test/kaniko_task_test.go
  test/secret.go
Labels: approved, cla: yes, lgtm, size/L

#831 Changes logging for _timeout_handler_ in order to use Infof when has …
  pkg/reconciler/timeout_handler.go
Labels: approved, cla: yes, lgtm, size/XS

#834 Try go get codecov to ignore generated files
  codecov.yml
Labels: approved, cla: yes, lgtm, size/XS

#800 Aggregate pipeline roles to built-in clusterroles
  config/clusterrole-aggregate-edit.yaml
  config/clusterrole-aggregate-view.yaml
Labels: approved, cla: yes, lgtm, size/M

#844 Fix spelling errors
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/XS

#839 Update README.md
  docs/README.md
Labels: approved, cla: yes, lgtm, size/XS

#838 Format markdown
  docs/pipelines.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/S

#797 Add info for installing with MiniShift
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#840 Correct the output path in the Developer docs
  docs/developers/README.md
Labels: approved, cla: yes, lgtm, size/XS

#846 Remove dead code: sync.Map in TimeoutSet struct
  pkg/reconciler/timeout_handler.go
Labels: approved, cla: yes, lgtm, size/XS

#847 fix outputs wording
  docs/tasks.md
Labels: approved, cla: yes, lgtm, size/XS

#814 Fix lots of lint errors.
  pkg/apis/pipeline/v1alpha1/build_gcs_resource.go
  pkg/apis/pipeline/v1alpha1/dag.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/resource_defaults.go
  pkg/apis/pipeline/v1alpha1/task_defaults.go
  pkg/artifacts/artifacts_storage.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go
  pkg/reconciler/v1alpha1/taskrun/resources/apply_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
  test/builder/doc.go
  test/logs/main.go
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/XXL

#849 Format markdown
  docs/README.md
  docs/developers/README.md
Labels: approved, cla: yes, lgtm, size/XS

#854 Test builder helpers
  test/builder/pipeline.go
  test/builder/pipeline_test.go
Labels: approved, cla: yes, lgtm, size/M

#801 fix build uncorrect status
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/S

#842 Allow user define specific path for output resource
  docs/developers/README.md
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
Labels: approved, cla: yes, lgtm, size/M

#862 Add third_party/VENDOR-LICENSE file back
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/XXL

#863 Format markdown
  docs/developers/README.md
Labels: approved, cla: yes, lgtm, size/XS

#864 golang format tools
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/XS

#857 Remove the Trigger field from TaskRun/PipelineRun.
  docs/taskruns.md
  docs/tutorial.md
  examples/pipelineruns/output-pipelinerun.yaml
  examples/pipelineruns/pipelinerun.yaml
  examples/taskruns/gcs-resource-spec-taskrun.yaml
  examples/taskruns/git-resource-spec-taskrun.yaml
  examples/taskruns/private-taskrun.yaml
  examples/taskruns/taskrun.yaml
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_validation.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  tekton/ci-images-run.yaml
  tekton/publish-run.yaml
  test/builder/pipeline.go
  test/builder/pipeline_test.go
  test/builder/task.go
  test/builder/task_test.go
  test/cluster_resource_test.go
Labels: approved, cla: yes, lgtm, size/L

#865 Use tektoncd/plumbing instead of knative/test-infra
  Gopkg.lock
  Gopkg.toml
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/README.md
  test/e2e-common.sh
  test/e2e-tests-yaml.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/tools/dep-collector/README.md
  vendor/github.com/tektoncd/plumbing/LICENSE
  vendor/github.com/tektoncd/plumbing/scripts/README.md
  vendor/github.com/tektoncd/plumbing/scripts/dummy.go
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/markdown-link-check-config.rc
  vendor/github.com/tektoncd/plumbing/scripts/markdown-lint-config.rc
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XXL

#861 Correct message to avoid misunderstanding in the PV sharing
  docs/developers/README.md
Labels: approved, cla: yes, lgtm, size/XS

#870 Update doc to remove taskSpec as an alternative to pipelineRef in a pipelineRun
  docs/pipelineruns.md
Labels: approved, cla: yes, lgtm, size/XS

#867 Fix the last of the lint errors and add lint checking to presubmits.
  .errcheck.txt
  .golangci.yml
  pkg/reconciler/reconciler_test.go
  pkg/reconciler/timeout_handler_test.go
  pkg/reconciler/v1alpha1/pipelinerun/cancel_test.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/v1alpha1/taskrun/cancel_test.go
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/apply_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/artifact_bucket_test.go
  test/controller.go
  test/gcs_taskrun_test.go
  test/gohelloworld/main.go
  test/kaniko_task_test.go
  test/logs/pod/watcher.go
  test/presubmit-tests.sh
  test/wait_test.go
Labels: approved, cla: yes, lgtm, size/L

#871 Enforce Default TaskRun Timeout
  docs/taskruns.md
  pkg/reconciler/timeout_handler.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#875 Format markdown
  docs/pipelineruns.md
Labels: approved, cla: yes, lgtm, size/XS

#874 golang format tools
  pkg/artifacts/artifact_storage_test.go
  test/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/XS

#883 Correct setting for kaniko in tasks
  docs/taskruns.md
  docs/tutorial.md
  examples/pipelineruns/pipelinerun.yaml
  examples/taskruns/taskrun.yaml
Labels: approved, cla: yes, lgtm, size/S

#881 Modify the section about installing in custom namespace
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#876 Surface resource constraint problems in TaskRun Status
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/M

#886 Format markdown
  DEVELOPMENT.md
  docs/taskruns.md
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/S

#892 Format markdown
  docs/developers/README.md
  docs/resources.md
Labels: approved, cla: yes, lgtm, size/M

#893 golang format tools
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/XS

#891 Generalize messages when TaskRun errs during pod creation
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/XS

#904 Skip TestStorageTaskRun if GCP_SERVICE_ACCOUNT_KEY_PAT is not defined
  test/gcs_taskrun_test.go
Labels: approved, cla: yes, lgtm, size/XS

#903 Fix typo
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/XS

#866 Allow configuration of PVC size from ConfigMap
  config/config-artifact-pvc.yaml
  docs/install.md
  pkg/apis/pipeline/v1alpha1/artifact_pvc.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/artifacts/artifact_storage_test.go
  pkg/artifacts/artifacts_storage.go
Labels: approved, cla: yes, lgtm, size/L

#910 Format markdown
  docs/install.md
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/S

#913 remove "trigger" residue
  docs/pipelineruns.md
  docs/taskruns.md
  examples/taskruns/task-output-image.yaml
Labels: approved, cla: yes, lgtm, size/XS

#918 Fix minor typos in API
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
Labels: approved, cla: yes, lgtm, size/XS

#894 Propagate annotations from Pipeline/Task to PipelineRun/TaskRun
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/builder/pipeline.go
  test/builder/task.go
  test/builder/task_test.go
  test/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/L

#919 Use tetkoncd build-base base image for the release
  .ko.yaml.release
Labels: approved, cla: yes, lgtm, size/XS

#909 Remove some references to knative/build-pipeline ✂️
  tekton/koparse/test_koparse.py
  tekton/koparse/test_release.yaml
  test/README.md
Labels: approved, cla: yes, lgtm, size/M

#920 Add godoc for missing Pipeline fields
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
Labels: approved, cla: yes, lgtm, size/S

#878 Add a specific verion for the image gcr.io/kaniko-project/executor
  docs/taskruns.md
  docs/tutorial.md
  examples/pipelineruns/pipelinerun.yaml
  examples/taskruns/taskrun.yaml
  tekton/ci-images.yaml
  tekton/publish.yaml
  test/helm_task_test.go
  test/kaniko_task_test.go
Labels: approved, cla: yes, lgtm, size/S

#911 Add an nightly script that would push image nightly 👼
  hack/nightly.sh
Labels: approved, cla: yes, lgtm, size/S

#925 Format markdown
  hack/README.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/S

#921 Add type-level godoc for various API types
  pkg/apis/pipeline/v1alpha1/cluster_task_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
Labels: approved, cla: yes, lgtm, size/S

#905 Reattempt pod creation in the face of ResourceQuota errors
  cmd/controller/main.go
  pkg/reconciler/timeout_handler.go
  pkg/reconciler/timeout_handler_test.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#930 Update dev guide to have GKE cluster install instructions 📝
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/M

#916 Poll multiple times that the pvc is deleted in TestPipelineRun
  test/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/S

#933 Format markdown
  DEVELOPMENT.md
  docs/tasks.md
Labels: approved, cla: yes, lgtm, size/XS

#934 Update tektoncd/plumbing vendor directory.
  Gopkg.lock
  third_party/VENDOR-LICENSE
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#935 Add docs on how to access Run logs 🗎
  DEVELOPMENT.md
  docs/README.md
  docs/logs.md
  docs/pipelineruns.md
  docs/taskruns.md
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/M

#938 Format markdown
  docs/logs.md
Labels: approved, cla: yes, lgtm, size/S
