Repository tektoncd/pipeline, pull requests merged in 2019-02, with the labels that each got.

#467 Update OWNERS b/c @aaron-prindle is changing teams 🚢
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#460 Update docs such that they can be used in knative/docs
  README.md
  docs/Concepts.md
  docs/README.md
  docs/auth.md
  docs/container-contract.md
  docs/images/building-blocks.png
  docs/pipelineruns.md
  docs/pipelines.md
  docs/resources.md
  docs/task-parameters.md
  docs/taskruns.md
  docs/tasks.md
  docs/tutorial.md
  docs/using.md
  examples/README.md
  hack/release.md
  pipe.png
Labels: approved, cla: yes, lgtm, size/XXL

#466 Add @vdemeester as an owner! 🙌
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#464 alternate git ssh port
  pkg/credentials/gitcreds/creds_test.go
  pkg/credentials/gitcreds/ssh.go
Labels: approved, cla: yes, lgtm, size/M

#469 Fixes broken link
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/XS

#459 Update test-infra to fix release script
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#394 creds-init: add support for kubernetes.io/dockerconfigjson and kubernetes.io/dockercfg
  examples/0-secrets.yaml
  examples/1-bots.yaml
  examples/README.md
  examples/run/private-taskrun.yaml
  pkg/credentials/dockercreds/creds.go
  pkg/credentials/dockercreds/creds_test.go
Labels: approved, cla: yes, lgtm, size/L

#470 Fix bad format string in resource handling error message
  pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
Labels: approved, cla: yes, lgtm, size/XS

#472 Task validation : fix variable validation in case of multiple variables 👼
  docs/tasks.md
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1alpha1/task_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#474 fix broken links in docs/tutorial.md
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/S

#468 Remove OWNERS file from test dir
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#442 POC Pipeline resource interface
  cmd/git-init/main.go
  pkg/apis/pipeline/v1alpha1/cluster_resource.go
  pkg/apis/pipeline/v1alpha1/cluster_resource_test.go
  pkg/apis/pipeline/v1alpha1/gcs_resource.go
  pkg/apis/pipeline/v1alpha1/gcs_resource_test.go
  pkg/apis/pipeline/v1alpha1/git_resource.go
  pkg/apis/pipeline/v1alpha1/image_resource.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/storage_resource.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#479 Only copy certain output resource to intermediate storage
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
Labels: approved, cla: yes, lgtm, size/M

#475 Fix pvc vs bucket detection case 🌵
  pkg/artifacts/artifact_storage_test.go
  pkg/artifacts/artifacts_storage.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
Labels: approved, cla: yes, lgtm, size/L

#478 Update broken link in pipeline tutorial doc
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/XS

#476 Add more contribution docs
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/M

#483 Format markdown
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  api_compatibility_policy.md
  docs/README.md
  docs/auth.md
  docs/developers/README.md
  docs/pipelineruns.md
  docs/pipelines.md
  docs/resources.md
  docs/taskruns.md
  docs/tasks.md
  docs/tutorial.md
  docs/using.md
  examples/README.md
  hack/release.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/XL

#482 golang format tools
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/apply.go
  pkg/reconciler/v1alpha1/templating/templating_test.go
Labels: approved, cla: yes, lgtm, size/XS

#486 Fix GCS unit tests which do not test the intended.
  pkg/apis/pipeline/v1alpha1/gcs_resource_test.go
Labels: approved, cla: yes, lgtm, size/XS

#487 Fix README error for running end to end yaml tests.
  test/README.md
Labels: approved, cla: yes, lgtm, size/XS

#489 Fix table of contents in resources docs 📜
  docs/resources.md
Labels: approved, cla: yes, lgtm, size/S

#494 Remove redundant label added to Pods
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/S

#497 Fix more links in docs/README.md 😱
  docs/README.md
Labels: approved, cla: yes, lgtm, size/XS

#499 Format markdown
  docs/README.md
Labels: approved, cla: yes, lgtm, size/XS

#498 golang format tools
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  test/builder/owner_reference.go
Labels: approved, cla: yes, lgtm, size/S

#495 Add instructions to run pipeline tutorial locally
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/M

#503 golang format tools
  test/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/XS

#504 Format markdown
  docs/pipelineruns.md
  docs/resources.md
  docs/taskruns.md
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/M

#507 Add documentation for BuildGCS resource.
  docs/resources.md
Labels: approved, cla: yes, lgtm, size/M

#515 Make docs accurate for 0.1 release
  docs/container-contract.md
  docs/pipelines.md
  docs/resources.md
  docs/taskruns.md
  docs/tasks.md
  docs/tutorial.md
  examples/README.md
  examples/pipelineruns/pipelinerun.yaml
  examples/taskruns/taskrun.yaml
Labels: approved, cla: yes, lgtm, size/L

#514 Add release notes and submitter checklist to pull request template
  .github/pull_request_template.md
  CONTRIBUTING.md
  hack/release.md
Labels: approved, cla: yes, lgtm, size/M

#516 Fix flaky e2e tests
  pkg/reconciler/v1alpha1/pipelinerun/cancel.go
  test/cancel_test.go
  test/e2e-common.sh
  test/wait.go
Labels: approved, cla: yes, lgtm, size/M

#519 Added toc for labels.
  docs/pipelineruns.md
Labels: approved, cla: yes, lgtm, size/XS

#520 Format markdown
  docs/resources.md
  docs/taskruns.md
  docs/tasks.md
  docs/tutorial.md
  examples/README.md
  hack/release.md
Labels: approved, cla: yes, lgtm, size/L

#521 Rename external tutorial repo to reflect project name
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/XS

#517 Propagate labels from Pipeline/Task to PipelineRun/TaskRun
  docs/README.md
  docs/labels.md
  docs/pipelineruns.md
  docs/taskruns.md
  pkg/apis/pipeline/register.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/taskrun/resources/taskspec.go
  pkg/reconciler/v1alpha1/taskrun/resources/taskspec_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/L

#525 Format markdown
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  api_compatibility_policy.md
  docs/README.md
  docs/auth.md
  docs/taskruns.md
  docs/tutorial.md
  hack/release.md
Labels: approved, cla: yes, lgtm, size/L

#523 Add support for volume templating for PVC, secrets
  docs/tasks.md
  examples/taskruns/taskrun-volume-secret-args.yaml
  pkg/reconciler/v1alpha1/taskrun/resources/apply.go
  pkg/reconciler/v1alpha1/taskrun/resources/apply_test.go
Labels: approved, cla: yes, lgtm, size/L

#526 Remove usage of K8S_CLUSTER_OVERRIDE and friends
  test/README.md
Labels: approved, cla: yes, lgtm, size/S

#545 Format markdown
  DEVELOPMENT.md
  docs/install.md
  docs/labels.md
  docs/tasks.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/L

#542 update release file path in the install guide
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#546 Fix minor typo in install.md
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#547 fix(tutorial.md): Fix kubectl sample command
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/XS

#548 dep update github.com/knative/test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#551 Enable fan-in fan-out e2e test
  test/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/M

#554 Work around markdown lint bug 😭
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/XS

#557 Minor: fix mispelling in pull request template
  .github/issue-template.md
  .github/pull_request_template.md
Labels: approved, cla: yes, lgtm, size/M

#560 release: fail if ko is missing or fails
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#561 Fix markdownlint on all *.md files
  .github/pull_request_template.md
  README.md
  api_compatibility_policy.md
  docs/auth.md
  docs/container-contract.md
  docs/developers/README.md
  docs/install.md
  docs/pipelineruns.md
  docs/resources.md
  docs/taskruns.md
  docs/tasks.md
  hack/release.md
  test/logs/README.md
  test/markdown-lint-config.rc
Labels: approved, cla: yes, lgtm, size/L
