Repository tektoncd/pipeline, pull requests merged in 2019-12, with the labels that each got.

#1653 Support stepTemplate alongside script mode
  pkg/apis/pipeline/v1alpha1/merge.go
  pkg/pod/entrypoint_lookup_test.go
  pkg/pod/pod_test.go
  pkg/pod/script.go
Labels: approved, cla: yes, lgtm, size/M

#1658 Fix tiny typo
  cmd/entrypoint/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1660 Add versioned links to docs and examples for v0.9.0
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1655 Split out step resource request management
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/resource_request.go
  pkg/pod/resource_request_test.go
Labels: approved, cla: yes, lgtm, size/L

#1666 Don't fail if there are no comments, labels or statuses.
  cmd/pullrequest-init/disk.go
  cmd/pullrequest-init/disk_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1664 Generate Pod name using names package
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/M

#1656 Allow args with script mode
  docs/tasks.md
  examples/taskruns/step-script.yaml
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1alpha1/task_validation_test.go
  pkg/pod/pod_test.go
  pkg/pod/script.go
Labels: approved, cla: yes, lgtm, size/M

#1667 Restore builder/home for publish nightly
  tekton/publish-nightly.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1625 Add workingdir integration test
  test/workingdir_test.go
Labels: approved, cla: yes, lgtm, size/L

#1668 Set default resource requests in Pod test builder
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/builder/pod.go
  test/builder/pod_test.go
Labels: approved, cla: yes, lgtm, size/L

#1669 Add copyright headers in pkg/pod
  pkg/pod/resource_request.go
  pkg/pod/resource_request_test.go
Labels: approved, cla: yes, lgtm, size/M

#1662 Fetch {Cluster}Tasks using generated client
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/XS

#1671 Remove the support for legacy image output paths.
  cmd/imagedigestexporter/main.go
Labels: approved, cla: yes, lgtm, size/S

#1550 Add gitlab support to the PR resource.
  Gopkg.lock
  cmd/pullrequest-init/github.go
  cmd/pullrequest-init/github_test.go
  cmd/pullrequest-init/main.go
  docs/resources.md
  pkg/apis/pipeline/v1alpha1/pull_request_resource.go
  pkg/apis/pipeline/v1alpha1/pull_request_resource_test.go
  pkg/pullrequest/api.go
  pkg/pullrequest/api_test.go
  pkg/pullrequest/disk.go
  pkg/pullrequest/disk_test.go
  pkg/pullrequest/scm.go
  pkg/pullrequest/scm_test.go
  vendor/github.com/jenkins-x/go-scm/scm/const.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/fake/data.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/fake/pr.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/github/webhook.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/content.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/git.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/gitlab.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/issue.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/org.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/pr.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/repo.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/review.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/user.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/util.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/webhook.go
  vendor/github.com/jenkins-x/go-scm/scm/pr.go
  vendor/github.com/jenkins-x/go-scm/scm/webhook.go
Labels: approved, cla: yes, lgtm, size/XXL

#1675 Fix bug in entrypoint lookup for steps by digest
  Gopkg.lock
  cmd/pullrequest-init/main.go
  examples/taskruns/step-by-digest.yaml
  pkg/pod/entrypoint_lookup_impl.go
  pkg/pod/entrypoint_lookup_impl_test.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/mutate.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/rebase.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/write.go
Labels: approved, cla: yes, lgtm, size/XXL

#1672 Remove support for the name parameter to cluster resources.
  pkg/apis/pipeline/v1alpha1/cluster_resource.go
  pkg/apis/pipeline/v1alpha1/cluster_resource_test.go
  pkg/apis/pipeline/v1alpha1/pipelineresource_validation.go
Labels: approved, cla: yes, lgtm, size/S

#1650 Store tektoncd/pipeline release version to a variable during build
  pkg/version/version.go
  tekton/publish-nightly.yaml
  tekton/publish.yaml
  tekton/release-pipeline.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1678 Use dogfooding `ko` image during release and nightly 🌞
  tekton/ci-images.yaml
  tekton/publish-nightly.yaml
  tekton/publish.yaml
  tekton/release-pipeline-nightly.yaml
  tekton/resources.yaml
Labels: approved, cla: yes, lgtm, size/L

#1688 Handle injected sidecars more correctly
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/status.go
Labels: approved, cla: yes, lgtm, size/M

#1691 Allow script mode to accept scripts that do not start with a shebang.
  docs/tasks.md
  examples/taskruns/step-script.yaml
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1alpha1/task_validation_test.go
  pkg/pod/pod_test.go
  pkg/pod/script.go
  pkg/pod/script_test.go
Labels: approved, cla: yes, lgtm, size/M

#1686 Move image data extraction into entrypoint_lookup.go
  pkg/pod/entrypoint_lookup.go
  pkg/pod/entrypoint_lookup_impl.go
  pkg/pod/entrypoint_lookup_impl_test.go
  pkg/pod/entrypoint_lookup_test.go
Labels: approved, cla: yes, lgtm, size/L

#1679 Allow unused resource in Pipelines 🎐
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation_test.go
Labels: approved, cla: yes, lgtm, size/S

#1685 Add read-only copy of pull request object in resource output.
  cmd/pullrequest-init/example/base.json
  cmd/pullrequest-init/example/comments/505233618.json
  cmd/pullrequest-init/example/comments/505476017.json
  cmd/pullrequest-init/example/comments/505482755.json
  cmd/pullrequest-init/example/comments/505529049.json
  cmd/pullrequest-init/example/comments/505616303.json
  cmd/pullrequest-init/example/comments/505676294.json
  cmd/pullrequest-init/example/comments/505798994.json
  cmd/pullrequest-init/example/comments/505890656.json
  cmd/pullrequest-init/example/comments/505923534.json
  cmd/pullrequest-init/example/comments/506032472.json
  cmd/pullrequest-init/example/comments/506082430.json
  cmd/pullrequest-init/example/comments/506082465.json
  cmd/pullrequest-init/example/comments/507732301.json
  cmd/pullrequest-init/example/comments/507763725.json
  cmd/pullrequest-init/example/comments/508007084.json
  cmd/pullrequest-init/example/head.json
  cmd/pullrequest-init/example/labels/approved
  cmd/pullrequest-init/example/labels/cla%3A+yes
  cmd/pullrequest-init/example/labels/lgtm
  cmd/pullrequest-init/example/labels/size%2FL
  cmd/pullrequest-init/example/pr.json
  cmd/pullrequest-init/example/status/cla%2Fgoogle.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-build-tests.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-go-coverage.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-integration-tests.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-unit-tests.json
  cmd/pullrequest-init/example/status/tide.json
  docs/resources.md
  pkg/pullrequest/disk.go
  pkg/pullrequest/disk_test.go
Labels: approved, cla: yes, lgtm, size/L

#1698 Add read-only copy of pull request object in resource output.
  cmd/pullrequest-init/example/base.json
  cmd/pullrequest-init/example/comments/505233618.json
  cmd/pullrequest-init/example/comments/505476017.json
  cmd/pullrequest-init/example/comments/505482755.json
  cmd/pullrequest-init/example/comments/505529049.json
  cmd/pullrequest-init/example/comments/505616303.json
  cmd/pullrequest-init/example/comments/505676294.json
  cmd/pullrequest-init/example/comments/505798994.json
  cmd/pullrequest-init/example/comments/505890656.json
  cmd/pullrequest-init/example/comments/505923534.json
  cmd/pullrequest-init/example/comments/506032472.json
  cmd/pullrequest-init/example/comments/506082430.json
  cmd/pullrequest-init/example/comments/506082465.json
  cmd/pullrequest-init/example/comments/507732301.json
  cmd/pullrequest-init/example/comments/507763725.json
  cmd/pullrequest-init/example/comments/508007084.json
  cmd/pullrequest-init/example/head.json
  cmd/pullrequest-init/example/labels/approved
  cmd/pullrequest-init/example/labels/cla%3A+yes
  cmd/pullrequest-init/example/labels/lgtm
  cmd/pullrequest-init/example/labels/size%2FL
  cmd/pullrequest-init/example/pr.json
  cmd/pullrequest-init/example/status/cla%2Fgoogle.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-build-tests.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-go-coverage.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-integration-tests.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-unit-tests.json
  cmd/pullrequest-init/example/status/tide.json
  docs/resources.md
  pkg/pullrequest/disk.go
  pkg/pullrequest/disk_test.go
Labels: approved, cla: yes, lgtm, size/L

#1640 remove PipelineStatus and PipelineResourceStatus
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/pipeline/v1alpha1/fake/fake_pipeline.go
  pkg/client/clientset/versioned/typed/pipeline/v1alpha1/fake/fake_pipelineresource.go
  pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipeline.go
  pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipelineresource.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1695 Use script mode in even more examples
  examples/taskruns/build-gcs-targz.yaml
  examples/taskruns/build-gcs-zip.yaml
  examples/taskruns/build-push-kaniko.yaml
  examples/taskruns/cloud-event.yaml
  examples/taskruns/clustertask.yaml
  examples/taskruns/configmap.yaml
  examples/taskruns/custom-env.yaml
  examples/taskruns/docker-creds.yaml
  examples/taskruns/gcs-resource.yaml
  examples/taskruns/git-resource.yaml
  examples/taskruns/home-is-set.yaml
  examples/taskruns/home-volume.yaml
  examples/taskruns/old-home-volume.yaml
  examples/taskruns/pull-private-image.yaml
  examples/taskruns/pullrequest.yaml
  examples/taskruns/secret-env.yaml
  examples/taskruns/sidecar-ready.yaml
  examples/taskruns/steptemplate-env-merge.yaml
  examples/taskruns/task-multiple-output-image.yaml
  examples/taskruns/task-output-image.yaml
  examples/taskruns/unnamed-steps.yaml
  examples/taskruns/workingdir.yaml
  examples/taskruns/workspace-volume.yaml
Labels: approved, cla: yes, lgtm, size/L

#1693 Set scm.PR.Sha to scm.PR.Head.Sha when loading from disk.
  pkg/pullrequest/disk.go
  pkg/pullrequest/disk_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1699 Bump plumbing to get latest fixes 👨‍🚀
  Gopkg.lock
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#1700 Remove /builder/home mount
  examples/taskruns/old-home-volume.yaml
  pkg/pod/pod.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/M

#1708 Fix lint failure
  pkg/artifacts/artifact_storage_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1711 Remove imports of golang.org/x/xerrors
  Gopkg.lock
  cmd/entrypoint/waiter.go
  pkg/apis/pipeline/v1alpha1/build_gcs_resource.go
  pkg/apis/pipeline/v1alpha1/cluster_resource.go
  pkg/apis/pipeline/v1alpha1/gcs_resource.go
  pkg/apis/pipeline/v1alpha1/git_resource.go
  pkg/apis/pipeline/v1alpha1/image_resource.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/storage_resource.go
  pkg/apis/pipeline/v1alpha2/resource_types.go
  pkg/artifacts/artifacts_storage.go
  pkg/credentials/dockercreds/creds.go
  pkg/credentials/gitcreds/basic.go
  pkg/credentials/gitcreds/ssh.go
  pkg/entrypoint/entrypointer_test.go
  pkg/git/git.go
  pkg/list/diff.go
  pkg/pullrequest/api.go
  pkg/reconciler/pipeline/dag/dag.go
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/conditionresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinespec.go
  pkg/reconciler/pipelinerun/resources/pipelinespec_test.go
  pkg/reconciler/pipelinerun/resources/validate_params.go
  pkg/reconciler/taskrun/resources/image_exporter.go
  pkg/reconciler/taskrun/resources/input_resources.go
  pkg/reconciler/taskrun/resources/output_resource.go
  pkg/reconciler/taskrun/resources/taskresourceresolution.go
  pkg/reconciler/taskrun/resources/taskresourceresolution_test.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/taskrun/validate_resources.go
  pkg/reconciler/timeout_handler_test.go
  test/cancel_test.go
  test/helm_task_test.go
  test/init_test.go
  test/ko_test.go
  test/secret.go
  test/timeout_test.go
  test/wait.go
  third_party/VENDOR-LICENSE
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XXL

#1719 Fix linter errors in log messages
  test/cancel_test.go
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1724 Don't hard-code the name of the webhook service
  cmd/webhook/main.go
  config/webhook.yaml
Labels: approved, cla: yes, lgtm, size/S

#1702 Simplify variable substitution tests ⚗️
  pkg/reconciler/taskrun/resources/apply_test.go
Labels: approved, cla: yes, lgtm, size/L

#1732 Fix golint error strings.
  cmd/entrypoint/waiter.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha2/resource_types.go
  pkg/credentials/dockercreds/creds.go
  pkg/credentials/gitcreds/basic.go
  pkg/credentials/gitcreds/ssh.go
  pkg/git/git.go
  pkg/list/diff.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_lookup.go
  pkg/pod/entrypoint_lookup_impl.go
  pkg/reconciler/pipeline/dag/dag.go
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/conditionresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinespec.go
  pkg/reconciler/taskrun/resources/cloudevent/cloudevent.go
  pkg/reconciler/taskrun/resources/cloudevent/cloudevent_test.go
  pkg/reconciler/taskrun/resources/image_exporter.go
  pkg/reconciler/taskrun/resources/input_resources.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/validate_resources.go
  test/helm_task_test.go
  test/pipelinerun_test.go
  test/wait.go
Labels: approved, cla: yes, lgtm, size/L

#1730 Rename constants.go to storagetypes.go 💎
  pkg/apis/pipeline/storagetypes.go
Labels: approved, cla: yes, lgtm, size/XS

#1731 Fixes flaky metrics unit tests
  pkg/reconciler/pipelinerun/metrics_test.go
  pkg/reconciler/taskrun/metrics_test.go
Labels: approved, cla: yes, lgtm, size/S

#1718 Cleanup the prow nightly release task and pipeline
  tekton/README.md
  tekton/publish-nightly.yaml
  tekton/publish.yaml
  tekton/release-pipeline-nightly.yaml
  tekton/resources.yaml
Labels: approved, cla: yes, lgtm, size/L

#1728 Format pullrequest-init example JSON files.
  cmd/pullrequest-init/example/README.md
  cmd/pullrequest-init/example/base.json
  cmd/pullrequest-init/example/comments/505233618.json
  cmd/pullrequest-init/example/comments/505476017.json
  cmd/pullrequest-init/example/comments/505482755.json
  cmd/pullrequest-init/example/comments/505529049.json
  cmd/pullrequest-init/example/comments/505616303.json
  cmd/pullrequest-init/example/comments/505676294.json
  cmd/pullrequest-init/example/comments/505798994.json
  cmd/pullrequest-init/example/comments/505890656.json
  cmd/pullrequest-init/example/comments/505923534.json
  cmd/pullrequest-init/example/comments/506032472.json
  cmd/pullrequest-init/example/comments/506082430.json
  cmd/pullrequest-init/example/comments/506082465.json
  cmd/pullrequest-init/example/comments/507732301.json
  cmd/pullrequest-init/example/comments/507763725.json
  cmd/pullrequest-init/example/comments/508007084.json
  cmd/pullrequest-init/example/head.json
  cmd/pullrequest-init/example/pr.json
  cmd/pullrequest-init/example/status/cla%2Fgoogle.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-build-tests.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-go-coverage.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-integration-tests.json
  cmd/pullrequest-init/example/status/pull-tekton-pipeline-unit-tests.json
  cmd/pullrequest-init/example/status/tide.json
Labels: approved, cla: yes, lgtm, size/L

#1720 Move context*.go to pkg/contexts and add tests 🎐
  cmd/webhook/main.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_defaults.go
  pkg/apis/pipeline/v1alpha1/taskrun_defaults_test.go
  pkg/contexts/contexts.go
  pkg/contexts/contexts_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/M

#1638 Update v1alpha1 status types to inline fields
  pkg/apis/pipeline/v1alpha1/condition_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/pod/status_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/conditionresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/builder/pipeline_test.go
  test/builder/task_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1734 Use the ko image with gcloud for release
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1721 Pin the version of golangci-lint in release pipeline
  tekton/release-pipeline-nightly.yaml
  tekton/release-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1737 Fix nightly modules tags
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/M

#1738 Fix the release docs
  tekton/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1743 (Temporarly) disable markdown link check 😅
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1729 Parameterize git clone depth and fix disabling submodules
  cmd/git-init/main.go
  docs/resources.md
  pkg/apis/pipeline/v1alpha1/git_resource.go
  pkg/apis/pipeline/v1alpha1/git_resource_test.go
  pkg/git/git.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1736 Script mode set -xe by default when no shebang used
  docs/tasks.md
  pkg/pod/script.go
  pkg/pod/script_test.go
Labels: approved, cla: yes, lgtm, size/S

#1601 Allow Resources to be Optional in Task, ClusterTask, and Condition
  docs/resources.md
  examples/pipelineruns/conditional-pipelinerun-with-optional-resources.yaml
  examples/taskruns/optional-resources-with-clustertask.yaml
  examples/taskruns/optional-resources.yaml
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/task_validation_test.go
  pkg/apis/pipeline/v1alpha2/resource_types.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/resources/input_resources.go
  pkg/reconciler/taskrun/resources/output_resource.go
  pkg/reconciler/taskrun/resources/output_resource_test.go
  pkg/reconciler/taskrun/validate_resources.go
  pkg/reconciler/taskrun/validate_resources_test.go
  test/builder/task.go
  test/builder/task_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1701 Reserve /tekton/ paths and "tekton-internal-" volume names
  cmd/entrypoint/README.md
  docs/developers/README.md
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1alpha1/task_validation_test.go
  pkg/credentials/initialize.go
  pkg/pod/creds_init.go
  pkg/pod/creds_init_test.go
  pkg/pod/entrypoint.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/script.go
  pkg/pod/script_test.go
  pkg/pod/workingdir_init.go
  pkg/pod/workingdir_init_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#1709 Don't rely on .status.podName to find Pod associated with a TaskRun
  pkg/reconciler/taskrun/cancel.go
  pkg/reconciler/taskrun/cancel_test.go
  pkg/reconciler/taskrun/metrics.go
  pkg/reconciler/taskrun/metrics_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1756 Restrict length of volumes generated from secret names
  pkg/names/generate.go
  pkg/names/generate_test.go
  pkg/pod/creds_init.go
  pkg/pod/pod.go
Labels: approved, cla: yes, lgtm, size/M

#1639 Add workspace types for Task and TaskRun with validation
  docs/pipelineruns.md
  docs/pipelines.md
  docs/taskruns.md
  docs/tasks.md
  examples/taskruns/custom-volume.yaml
  examples/taskruns/workspace.yaml
  pkg/apis/pipeline/paths.go
  pkg/apis/pipeline/v1alpha1/git_resource.go
  pkg/apis/pipeline/v1alpha1/pull_request_resource.go
  pkg/apis/pipeline/v1alpha1/pull_request_resource_test.go
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1alpha1/task_validation_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go
  pkg/apis/pipeline/v1alpha1/workspace_types.go
  pkg/apis/pipeline/v1alpha1/workspace_validation.go
  pkg/apis/pipeline/v1alpha1/workspace_validation_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/workingdir_init.go
  pkg/pod/workingdir_init_test.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
  pkg/workspace/validate.go
  pkg/workspace/validate_test.go
  test/builder/task.go
  test/builder/task_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1759 Fix task.md typo workingdir to workingDir
  docs/tasks.md
Labels: approved, cla: yes, lgtm, size/XS

#1757 Call `gcloud auth activate-service-account` if GOOGLE_APPLICATION_CREDENTIALS is set
  go.mod
  pkg/apis/pipeline/v1alpha1/gcs_resource.go
  pkg/apis/pipeline/v1alpha1/gcs_resource_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
Labels: approved, cla: yes, lgtm, size/L

#1762 Keep Pipeline.status field for backward compatibility 👾
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/S

#1766 Keep PipelineResource.status field for backward compatibility 👾
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/S

#1774 Fix link
  docs/pipelines.md
Labels: approved, cla: yes, lgtm, size/XS

#1772 Fix spelling errors
  cmd/git-init/main.go
  pkg/apis/pipeline/v1alpha1/storage_resource.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1760 readOnly flag on workspace declarations
  docs/tasks.md
  examples/taskruns/workspace-readonly.yaml
  pkg/apis/pipeline/v1alpha1/workspace_types.go
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
  test/builder/step.go
  test/builder/task.go
  test/builder/task_test.go
  test/workspace_test.go
Labels: approved, cla: yes, lgtm, size/L

#1780 Correcting Comment Typos and Updating cancelPipelineRun Error Message
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/taskrun/cancel.go
Labels: approved, cla: yes, lgtm, size/XS

#1778 Ignore code coverage for auto generated file
  codecov.yml
Labels: approved, cla: yes, lgtm, size/XS

#1781 Add additional useful fields to the pod template
  docs/pipelineruns.md
  docs/taskruns.md
  pkg/apis/pipeline/v1alpha1/pod.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L
