Repository tektoncd/pipeline, pull requests merged in 2019-04, with the labels that each got.

#703 Define PodSecurityPolicy
  config/101-podsecuritypolicy.yaml
  config/200-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/M

#708 fix issue: cannot checkout git repo with SSH url
  docs/auth.md
Labels: approved, cla: yes, lgtm, size/XS

#711 Hide e2e test's example_test under a build tag
  test/wait_example_test.go
Labels: approved, cla: yes, lgtm, size/XS

#713 Remove @tejal29 as owner and add alumni 🎓
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#720 Bind webhook controller to a non priviliged port
  cmd/webhook/main.go
  config/400-webhook-service.yaml
Labels: approved, cla: yes, lgtm, size/XS

#699 Add a section for installing Tekton Pipelines on OpenShift
  docs/install.md
Labels: approved, cla: yes, lgtm, size/S

#732 Skip temporarly TestTaskRunTimeout as it is flakey.
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/XS

#710 Skip some tests if KO_DOCKER_REPO is missing…
  test/helm_task_test.go
  test/kaniko_task_test.go
  test/ko_test.go
Labels: approved, cla: yes, lgtm, size/M

#722 Remove some mentions of "knative" and "build-pipeline"
  cmd/bash/main.go
  cmd/gsutil/main.go
  config/300-clustertask.yaml
  config/300-pipeline.yaml
  config/300-pipelinerun.yaml
  config/300-resource.yaml
  config/300-task.yaml
  config/300-taskrun.yaml
  docs/container-contract.md
  docs/tutorial.md
  hack/release.sh
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  pkg/system/names.go
  tekton/README.md
  test/README.md
  test/adoc.go
Labels: approved, cla: yes, lgtm, size/M

#716 Updating some tests to not require the docker socket
  examples/taskruns/private-taskrun.yaml
  examples/taskruns/taskrun-docker-basic.yaml
  test/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/M

#735 e2e test: remove debug fmt.Println 🤕
  test/ko_test.go
Labels: approved, cla: yes, lgtm, size/XS

#704 Don't use goroutine on loop iterator 🛑
  test/cancel_test.go
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/M

#736 Format markdown
  docs/container-contract.md
  docs/install.md
  tekton/README.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/M

#737 Use gsutil rsync instead of cp for buckets
  pkg/apis/pipeline/v1alpha1/gcs_resource.go
  pkg/apis/pipeline/v1alpha1/gcs_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
Labels: approved, cla: yes, lgtm, size/S

#738 Remove the actual running of external test in example yaml
  examples/pipelineruns/pipelinerun.yaml
Labels: approved, cla: yes, lgtm, size/XS

#740 Set TaskRun Completion time in case of Failure or Success 🏁
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/S

#718 Enhance the output of "kubectl get taskruns"
  config/300-taskrun.yaml
Labels: approved, cla: yes, lgtm, size/S

#745 Fix command for openshift installation
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#730 Improve Pipelinerun description and printcolumn fields
  config/300-pipelinerun.yaml
Labels: approved, cla: yes, lgtm, size/S

#741 Set PipelineRun Completion time in case of Failure or Success 🏁
  pkg/reconciler/v1alpha1/pipelinerun/cancel.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/S

#748 Wrap nop final step with entrypoint
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#747 git-init don't assume the image is running as root
  Gopkg.lock
  cmd/git-init/main.go
  vendor/github.com/mitchellh/go-homedir/LICENSE
  vendor/github.com/mitchellh/go-homedir/homedir.go
Labels: approved, cla: yes, lgtm, size/L

#750 git-init: trim spaces from url (and remove dead code)
  cmd/git-init/main.go
Labels: approved, cla: yes, lgtm, size/S

#723 Make generated pods only request the maximum necessary resources
  docs/tasks.md
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/builder/container.go
  test/builder/pod_test.go
Labels: approved, cla: yes, lgtm, size/L

#743 Adds shortname for taskrun and pipelinerun
  config/300-pipelinerun.yaml
  config/300-taskrun.yaml
  examples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#756 Fix spelling errors
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
Labels: approved, cla: yes, lgtm, size/XS

#759 Format markdown
  examples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#707 Support Pod tolerations
  docs/pipelineruns.md
  docs/taskruns.md
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  test/builder/pipeline.go
  test/builder/task.go
Labels: approved, cla: yes, lgtm, size/M

#757 Update TaskRun status even if PipelineRun is done
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  test/builder/pipeline.go
Labels: approved, cla: yes, lgtm, size/L

#762 Fix sample yaml
  docs/pipelines.md
Labels: approved, cla: yes, lgtm, size/S

#763 Refactor the git-init container code so the logic can be exposed as a…
  cmd/git-init/main.go
  pkg/git/git.go
Labels: approved, cla: yes, lgtm, size/L

#764 Fix a couple of small name issues in tutorial pipeline
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/S

#766 Minor cleanups to resource code.
  pkg/apis/pipeline/v1alpha1/cluster_resource.go
  pkg/apis/pipeline/v1alpha1/git_resource.go
  pkg/apis/pipeline/v1alpha1/image_resource.go
Labels: approved, cla: yes, lgtm, size/XS

#768 Update CONTRIBUTING.md to link to guidelines in community repo 😎
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/L

#772 Update link for github pull-request template 🍶
  .github/pull_request_template.md
Labels: approved, cla: yes, lgtm, size/XS

#773 fixes task's document
  docs/tasks.md
Labels: approved, cla: yes, lgtm, size/XS

#774 Remove first WaitTaskRun call when creating TR pod
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/XS

#767 Add container template configuration to Task
  Gopkg.lock
  docs/tasks.md
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/merge/merge.go
  pkg/merge/merge_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/builder/task.go
  test/builder/task_test.go
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/XXL

#776 Make first example of running e2e tests include longer timeout ⏱️
  test/README.md
Labels: approved, cla: yes, lgtm, size/XS

#657 Add the step name in taskrun status
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/M

#787 Move test infra to plumbing repo 🚚
  infra/README.md
  infra/boskos/boskos-config.yaml
  infra/boskos/boskos.yaml
  infra/boskos/storage-class.yaml
  infra/gubernator/config.yaml
  infra/prow/config.yaml
  infra/prow/ingress.yaml
  infra/prow/plugins.yaml
  tekton/README.md
Labels: approved, cla: yes, lgtm, size/L

#785 Update code of conduct to use tekton mailing list
  code-of-conduct.md
Labels: approved, cla: yes, lgtm, size/XS

#784 Allow controller to watch specified namespace only
  cmd/controller/main.go
Labels: approved, cla: yes, lgtm, size/XS

#758 Recreate pod on TaskRun's pod deletion
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#790 Add docs to help ppl new to the project ramp up on the context 🏫
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#793 Remove redundant error check
  cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, size/XS

#798 Minor style nits affecting YAML output
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
Labels: approved, cla: yes, lgtm, size/M

#795 Remove the release scripts and docs from knative's era
  hack/release.md
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/L

#789 Update release docs re who has access to prod resources 🔑
  tekton/README.md
Labels: approved, cla: yes, lgtm, size/S

#802 Fixing image release task ⛏
  tekton/publish-run.yaml
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/XS

#804 Fix git-init failure with git ssh creds 🔑
  pkg/git/git.go
Labels: approved, cla: yes, lgtm, size/S

#805 Fix e2e yaml false success report
  test/e2e-common.sh
  test/e2e-tests-yaml.sh
Labels: approved, cla: yes, lgtm, size/S

#807 golang format tools
  pkg/merge/merge.go
Labels: approved, cla: yes, lgtm, size/XS

#806 Format markdown
  CONTRIBUTING.md
  DEVELOPMENT.md
  code-of-conduct.md
  docs/tasks.md
  tekton/README.md
Labels: approved, cla: yes, lgtm, size/M

#809 change gitlab to git repository
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/XS

#761 Update 300-pipelinerun.yaml
  config/300-pipelinerun.yaml
Labels: approved, cla: yes, lgtm, size/S

#817 Use os.Geteuid instead of user.Current in git-init.
  pkg/git/git.go
Labels: approved, cla: yes, lgtm, size/XS
