Repository tektoncd/pipeline, pull requests merged in 2019-01, with the labels that each got.

#371 Fix example using private GCS bucket
  docs/using.md
Labels: approved, lgtm, size/XS

#373 Remove parallelization flag from `gsutil`
  cmd/gsutil/main.go
Labels: approved, lgtm, size/XS

#344 Migrate some end-to-end test to use test builders 🎧
  test/builder/pipeline.go
  test/builder/task.go
  test/builder/task_test.go
  test/cluster_resource_test.go
  test/helm_task_test.go
  test/kaniko_task_test.go
  test/pipelinerun_test.go
Labels: approved, lgtm, size/XXL

#380 Format markdown
  docs/using.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#388 Collapse comment
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#389 Format markdown
  roadmap-2019.md
Labels: approved, lgtm, size/M

#345 Enhance godoc for the test package 👼
  test/README.md
  test/adoc.go
  test/clients.go
  test/randstring.go
  test/wait.go
  test/wait_example_test.go
  test/wait_test.go
Labels: approved, lgtm, size/L

#350 Fix #332: Use lru cache to expire entrypoint items
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
Labels: approved, lgtm, size/M

#391 Remove `./third_party/config/build/release.yaml` from DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#392 Format markdown
  test/README.md
Labels: approved, lgtm, size/XS

#395 Update test/README.md to incorporate the k8s document style guidelines.
  test/README.md
Labels: approved, lgtm, size/L

#396 Added digest cache, store digest instead of tags, added test
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
Labels: approved, lgtm, size/L

#397 Update Concept.md to incorporate k8s document style guidelines 📖
  docs/Concepts.md
Labels: approved, lgtm, size/L

#393 Update resource path to be prefixed with resource name
  docs/developers/README.md
  docs/tutorial.md
  docs/using.md
  pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/helm_task_test.go
  test/kaniko_task_test.go
Labels: approved, lgtm, size/L

#405 golang format tools
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go
Labels: approved, lgtm, size/XS

#362 Fixes #186: Use Event Recorder to verify failure cases instead of logs
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/L

#407 Update resource path (again)
  pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/helm_task_test.go
  test/kaniko_task_test.go
Labels: approved, lgtm, size/L

#408 Format markdown
  docs/Concepts.md
  docs/developers/README.md
  docs/tutorial.md
  docs/using.md
  test/README.md
Labels: approved, lgtm, size/L

#413 Fix invalid error message for storage output resource
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
Labels: approved, lgtm

#404 Fix GCS resource authentication bug
  cmd/gsutil/main.go
  pkg/apis/pipeline/v1alpha1/gcs_resource.go
  pkg/apis/pipeline/v1alpha1/gcs_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
  test/README.md
  test/gcs_taskrun_test.go
  test/init_test.go
  test/pipelinerun_test.go
Labels: approved, lgtm, size/L

#419 fix to get TaskRun tutorial to run
  docs/tutorial.md
  docs/using.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#411 Fix indentation in YAML examples
  docs/developers/README.md
Labels: approved, lgtm, size/M

#414 Only copy output resource to PVC for storage/git output
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
Labels: approved, lgtm, size/M

#381 Add possibility for a client to cancel a {task,pipeline}run
  docs/using.md
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/reconciler/v1alpha1/pipelinerun/cancel.go
  pkg/reconciler/v1alpha1/pipelinerun/cancel_test.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/taskrun/cancel.go
  pkg/reconciler/v1alpha1/taskrun/cancel_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/builder/pipeline.go
  test/builder/task.go
  test/cancel_test.go
Labels: approved, lgtm, size/XL

#421 Format markdown
  docs/using.md
Labels: approved, lgtm, size/S

#420 golang format tools
  pkg/reconciler/v1alpha1/pipelinerun/cancel_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
Labels: approved, lgtm, size/S

#423 Fix c.Logger.Error(f) usage in reconcilier ➿
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
Labels: approved, lgtm, size/S

#436 Remove user study examples
  docs/cuj/README.md
  docs/cuj/answers/exercise3/go-test.yaml
  docs/cuj/answers/exercise4/checkout-pipeline.yaml
  docs/cuj/exercises/exercise1/Exercise1.md
  docs/cuj/exercises/exercise2/Exercise2.md
  docs/cuj/exercises/exercise2/build-push-task.yaml
  docs/cuj/exercises/exercise2/hipster-pipeline-run.yaml
  docs/cuj/exercises/exercise2/hipster-pipeline.yaml
  docs/cuj/exercises/exercise2/resources.yaml
  docs/cuj/exercises/exercise3/Exercise3.md
  docs/cuj/exercises/exercise4/Excercise4.md
Labels: approved, cla: yes, lgtm, size/L

#433 Fix spelling errors
  test/builder/pipeline.go
Labels: approved, cla: yes, lgtm, size/XS

#434 golang format tools
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, cla: yes, lgtm, size/XS

#438 Fix flaky unit tests in resources package
  pkg/reconciler/v1alpha1/pipelinerun/resources/input_output_steps_test.go
Labels: approved, cla: yes, lgtm, size/S

#437 Rename `providedBy` to `from`
  docs/developers/README.md
  docs/tutorial.md
  docs/using.md
  examples/README.md
  examples/output-pipeline.yaml
  examples/pipeline.yaml
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/pipeline/resources/dag.go
  pkg/reconciler/v1alpha1/pipeline/resources/dag_test.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/input_output_steps.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/input_output_steps_test.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
  test/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/L

#441 Format markdown
  docs/developers/README.md
  docs/tutorial.md
  docs/using.md
  examples/README.md
Labels: approved, cla: yes, lgtm, size/M

#445 Update test-infra to the latest
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
  vendor/github.com/knative/test-infra/scripts/markdown-lint-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/tools/dep-collector/README.md
Labels: approved, cla: yes, lgtm, size/XL

#440 Allow taskrun to embed resource spec in inputs & outputs
  docs/using.md
  examples/README.md
  examples/run/task-run-resource-spec.yaml
  pkg/apis/pipeline/v1alpha1/pipelineresource_validation.go
  pkg/apis/pipeline/v1alpha1/pipelineresource_validation_test.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/taskrun/resources/apply.go
  pkg/reconciler/v1alpha1/taskrun/resources/apply_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/taskresourceresolution.go
  pkg/reconciler/v1alpha1/taskrun/resources/taskresourceresolution_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/builder/task.go
  test/builder/task_test.go
  test/cancel_test.go
  test/crd.go
Labels: approved, cla: yes, lgtm, size/XL

#425 Help users who want to develop locally
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#446 Fix release script after updating test-infra
  hack/release.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#450 Make integration tests run in parallel.
  test/cancel_test.go
  test/cluster_resource_test.go
  test/gcs_taskrun_test.go
  test/helm_task_test.go
  test/kaniko_task_test.go
  test/pipelinerun_test.go
  test/status_test.go
  test/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/S

#355 Add Pipeline-level timeouts
  docs/using.md
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation_test.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
  test/builder/task.go
  test/taskrun_test.go
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/XL

#443 Remove extra log PVC
  docs/using.md
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/cancel_test.go
  test/crd.go
  test/embed_test.go
  test/logs/README.md
  test/pipelinerun_test.go
  test/status_test.go
  test/taskrun_test.go
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/XL
