Repository tektoncd/pipeline, pull requests merged in 2019-11, with the labels that each got.

#1510 Remove cmd/nop
  cmd/controller/main.go
  cmd/nop/kodata/HEAD
  cmd/nop/kodata/LICENSE
  cmd/nop/kodata/VENDOR-LICENSE
  cmd/nop/main.go
  config/controller.yaml
  pkg/apis/pipeline/v1alpha1/build_gcs_resource_test.go
  pkg/artifacts/artifact_storage_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  tekton/koparse/test_koparse.py
  tekton/koparse/test_release.yaml
  tekton/resources.yaml
Labels: approved, cla: yes, lgtm, size/M

#1517 Stop race condition on cloud event YAML test
  examples/taskruns/cloud-event.yaml
Labels: approved, cla: yes, lgtm, size/M

#1525 Disable colour in tkn logs
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#1495 Make PipelineSpec/PipelineRef in PipelineRun consistent with TaskRun
  pkg/apis/pipeline/v1alpha1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_validation.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/metrics.go
  pkg/reconciler/pipelinerun/resources/pipelinespec.go
  pkg/reconciler/pipelinerun/resources/pipelinespec_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/M

#1528 types: group vars 👼
  pkg/apis/pipeline/v1alpha1/cluster_task_types.go
  pkg/apis/pipeline/v1alpha1/condition_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
Labels: approved, cla: yes, lgtm, size/M

#1532 Fix Pull Request resource example file structure
  docs/resources.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1502 Tag published images
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1533 Added s3 bucket configuration doc/example
  docs/developers/README.md
  docs/install.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1540 Fix typo in cloud event resources documentation
  docs/resources.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1544 Linting yamls with yamllint 🏷
  .yamllint
  config/config-artifact-bucket.yaml
  config/config-artifact-pvc.yaml
  examples/pipelineruns/output-pipelinerun.yaml
  examples/pipelineruns/pipelinerun.yaml
  examples/taskruns/build-push-kaniko.yaml
  examples/taskruns/git-volume.yaml
  examples/taskruns/pull-private-image.yaml
  examples/taskruns/task-multiple-output-image.yaml
  examples/taskruns/task-output-image.yaml
  tekton/ci-images.yaml
  tekton/release-pipeline-nightly.yaml
  tekton/resources.yaml
Labels: approved, cla: yes, lgtm, size/L

#1556 Re-add support for github auth from the GITHUB_TOKEN env variable.
  cmd/pullrequest-init/github.go
  cmd/pullrequest-init/github_test.go
  cmd/pullrequest-init/main.go
Labels: approved, cla: yes, lgtm, size/S

#1560 Add securityContext to run as root for kaniko example 🤖
  examples/taskruns/build-push-kaniko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1545 Only make a PVC for a PipelineRun if we need to. 🗑️
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/artifacts/artifact_storage_test.go
  pkg/artifacts/artifacts_storage.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/resources/input_resources.go
  pkg/reconciler/taskrun/resources/output_resource.go
  pkg/reconciler/taskrun/resources/output_resource_test.go
  test/dag_test.go
Labels: approved, cla: yes, lgtm, size/L

#1563 Make kanikotest skip on environment using scc
  test/kaniko_task_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1562 Apply param replacements in step scripts
  examples/taskruns/step-script.yaml
  pkg/apis/pipeline/v1alpha1/step_replacements.go
  pkg/apis/pipeline/v1alpha1/step_replacements_test.go
Labels: approved, cla: yes, lgtm, size/L

#1564 Update the kaniko executor image version to 0.14.0
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1566 Bump plumbing to latest changes 🔗
  Gopkg.lock
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1571 Move Validatable/Defaultable interface checks out
  pkg/apis/pipeline/v1alpha1/cluster_task_defaults.go
  pkg/apis/pipeline/v1alpha1/cluster_task_types.go
  pkg/apis/pipeline/v1alpha1/cluster_task_validation.go
  pkg/apis/pipeline/v1alpha1/condition_defaults.go
  pkg/apis/pipeline/v1alpha1/condition_types.go
  pkg/apis/pipeline/v1alpha1/condition_validation.go
  pkg/apis/pipeline/v1alpha1/pipeline_defaults.go
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/pipelineresource_validation.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_validation.go
  pkg/apis/pipeline/v1alpha1/resource_defaults.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/task_defaults.go
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1alpha1/taskrun_defaults.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation.go
Labels: approved, cla: yes, lgtm, size/M

#1577 Add kube client oidc authentication support for testing
  Gopkg.lock
  test/init_test.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1580 Make sure v1alpha1.Condition satisfy webhook.GenericCRD ⚙
  pkg/apis/pipeline/v1alpha1/types_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1579 Do not hardcode APIVersion in GetTaskRunRef 👼
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
Labels: approved, cla: yes, lgtm, size/XS

#1581 Extract artifacts constants out of v1alpha1 package 🍳
  pkg/apis/pipeline/constants.go
  pkg/apis/pipeline/v1alpha1/artifact_bucket.go
  pkg/apis/pipeline/v1alpha1/artifact_pvc.go
  pkg/artifacts/artifact_storage_test.go
  pkg/artifacts/artifacts_storage.go
  pkg/reconciler/pipelinerun/config/store.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/resources/input_resources.go
  pkg/reconciler/taskrun/resources/output_resource.go
  pkg/reconciler/taskrun/resources/output_resource_test.go
  test/artifact_bucket_test.go
Labels: approved, cla: yes, lgtm, size/L

#1582 Extract dag function out of v1alpha1 ⚙
  pkg/apis/pipeline/v1alpha1/dag.go
  pkg/apis/pipeline/v1alpha1/dag_test.go
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/pipeline/dag/dag.go
  pkg/reconciler/pipeline/dag/dag_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1578 Add empty v1alpha2 package 🎐
  hack/update-codegen.sh
  pkg/apis/pipeline/v1alpha2/register.go
  pkg/apis/pipeline/v1alpha2/task_types.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/pipeline/v1alpha2/doc.go
  pkg/client/clientset/versioned/typed/pipeline/v1alpha2/fake/doc.go
  pkg/client/clientset/versioned/typed/pipeline/v1alpha2/fake/fake_pipeline_client.go
  pkg/client/clientset/versioned/typed/pipeline/v1alpha2/generated_expansion.go
  pkg/client/clientset/versioned/typed/pipeline/v1alpha2/pipeline_client.go
Labels: approved, cla: yes, lgtm, size/M

#1588 Fix potential bug caught by gobugs
  pkg/reconciler/pipeline/dag/dag.go
Labels: approved, cla: yes, lgtm, size/XS

#1591 Add Terminated, Running, and Waiting Container States to Test Builder
  test/builder/task.go
Labels: approved, cla: yes, lgtm, size/S

#1593 Fix nightly (and non-nightly) release Task and Pipeline 👼
  tekton/README.md
  tekton/publish-nightly.yaml
  tekton/publish.yaml
  tekton/release-pipeline-nightly.yaml
  tekton/release-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/M

#1595 Move GetPod from pod.go to taskrun.go
  pkg/reconciler/taskrun/resources/pod.go
  pkg/reconciler/taskrun/resources/pod_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#1596 Move working dir initialization out to pkg/pod/
  pkg/pod/workingdir_init.go
  pkg/pod/workingdir_init_test.go
  pkg/reconciler/taskrun/resources/pod.go
  pkg/reconciler/taskrun/resources/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#1598 Add link to docs on how to run a local registry
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#1599 Move creds-init to pkg/pod
  pkg/pod/creds_init.go
  pkg/pod/creds_init_test.go
  pkg/pod/doc.go
  pkg/pod/workingdir_init.go
  pkg/pod/workingdir_init_test.go
  pkg/reconciler/taskrun/resources/pod.go
  pkg/reconciler/taskrun/resources/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#1600 Document odd kubectl get output for pods w/ sidecars
  docs/developers/README.md
  docs/taskruns.md
Labels: approved, cla: yes, lgtm, size/S

#1609 Readd mounting volumes in workingdir
  pkg/pod/workingdir_init.go
  pkg/pod/workingdir_init_test.go
  pkg/reconciler/taskrun/resources/pod.go
  pkg/reconciler/taskrun/resources/pod_test.go
Labels: approved, cla: yes, lgtm, size/M

#1613 Increase linter timeout to 5m
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1614 Extract validateObjectMetadata to a validate package ✂
  pkg/apis/pipeline/v1alpha1/cluster_task_validation.go
  pkg/apis/pipeline/v1alpha1/condition_validation.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/pipelineresource_validation.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_validation.go
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation.go
  pkg/apis/validate/metadata.go
  pkg/apis/validate/metadata_test.go
Labels: approved, cla: yes, lgtm, size/M

#1616 Split out entrypoint resolution and injection, and script conversion
  cmd/controller/main.go
  examples/taskruns/steps-run-in-order.yaml
  pkg/apis/pipeline/images.go
  pkg/apis/pipeline/v1alpha1/build_gcs_resource_test.go
  pkg/artifacts/artifact_storage_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_lookup.go
  pkg/pod/entrypoint_lookup_test.go
  pkg/pod/entrypoint_test.go
  pkg/pod/script.go
  pkg/pod/script_test.go
  pkg/pod/workingdir_init.go
  pkg/pod/workingdir_init_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/entrypoint/entrypoint.go
  pkg/reconciler/taskrun/entrypoint/entrypoint_test.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/resources/pod.go
  pkg/reconciler/taskrun/resources/pod_test.go
  pkg/reconciler/taskrun/sidecars/stop.go
  pkg/reconciler/taskrun/sidecars/stop_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/status/taskrunpod.go
  test/builder/pod.go
Labels: approved, cla: yes, lgtm, size/XXL

#1618 Remove deprecated serviceAccount field from *Run 🌳
  examples/pipelineruns/clustertask-pipelinerun.yaml
  examples/pipelineruns/conditional-pipelinerun.yaml
  examples/pipelineruns/output-pipelinerun.yaml
  examples/pipelineruns/pipelinerun-with-resourcespec.yaml
  examples/pipelineruns/pipelinerun.yaml
  examples/taskruns/docker-creds.yaml
  examples/taskruns/git-ssh-creds.yaml
  examples/taskruns/pull-private-image.yaml
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/resources/pod.go
  pkg/reconciler/taskrun/resources/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/builder/pipeline.go
  test/builder/task.go
Labels: approved, cla: yes, lgtm, size/L

#1615 Align pull request resource and pullrequest-init
  pkg/apis/pipeline/v1alpha1/pull_request_resource.go
  pkg/apis/pipeline/v1alpha1/pull_request_resource_test.go
Labels: approved, cla: yes, lgtm, size/S

#1474 Remove the custom "name" parameter from cluster resources.
  docs/resources.md
  pkg/apis/pipeline/v1alpha1/cluster_resource.go
  pkg/apis/pipeline/v1alpha1/pipelineresource_validation.go
  pkg/apis/pipeline/v1alpha1/pipelineresource_validation_test.go
Labels: approved, cla: yes, lgtm, size/S

#1622 Add an example that demonstrates waiting for a sidecar to become Ready
  examples/taskruns/sidecar-ready.yaml
Labels: approved, cla: yes, lgtm, size/M

#1611 Extract substitution code out of v1alpha1 ✂
  pkg/apis/pipeline/v1alpha1/param_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/step_replacements.go
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
Labels: approved, cla: yes, lgtm, size/M

#1623 Split entrypoint_lookup implementation and interface
  pkg/pod/entrypoint_lookup.go
  pkg/pod/entrypoint_lookup_impl.go
Labels: approved, cla: yes, lgtm, size/L

#1626 Move /builder/{tools,downward,scripts} to /tekton/
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/script.go
  pkg/pod/script_test.go
  pkg/reconciler/taskrun/resources/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#1621 Move MakePod to pkg/pod and unexport things
  pkg/pod/creds_init.go
  pkg/pod/creds_init_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_lookup.go
  pkg/pod/entrypoint_lookup_test.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/script.go
  pkg/pod/script_test.go
  pkg/pod/workingdir_init.go
  pkg/pod/workingdir_init_test.go
  pkg/reconciler/taskrun/resources/input_resources.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#1620 Fix issue: Params in multiple condition of one task will be overwrite
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, cla: yes, lgtm, size/M

#1469 Update some simple examples to use script mode
  docs/tasks.md
  examples/taskruns/custom-volume.yaml
  examples/taskruns/dind-sidecar.yaml
  examples/taskruns/git-ssh-creds.yaml
  examples/taskruns/secret-volume-params.yaml
  examples/taskruns/secret-volume.yaml
  examples/taskruns/task-volume-args.yaml
  examples/taskruns/template-volume.yaml
Labels: approved, cla: yes, lgtm, size/M

#1627 Move PodStatus->TaskRunStatus code to pkg/pod
  pkg/pod/entrypoint.go
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/status/stepstatesorter.go
  pkg/status/stepstatesorter_test.go
  pkg/status/taskrunpod.go
  pkg/status/taskrunreasons.go
Labels: approved, cla: yes, lgtm, size/XXL

#1634 Fix a gocritic lint issue: use switch instead of ifelse 🏑
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1491 Fix incorrect logic in output resource handling
  pkg/reconciler/taskrun/resources/output_resource.go
  pkg/reconciler/taskrun/resources/output_resource_test.go
Labels: approved, cla: yes, lgtm, size/M

#1644 Move workingDir initialization after script conversion
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/workingdir_init.go
  pkg/pod/workingdir_init_test.go
Labels: approved, cla: yes, lgtm, size/M
