Repository tektoncd/pipeline, pull requests merged in 2019-03, with the labels that each got.

#566 Preserve GCS directory structures
  docs/resources.md
  pkg/apis/pipeline/v1alpha1/artifact_bucket.go
  pkg/apis/pipeline/v1alpha1/artifact_bucket_test.go
  pkg/apis/pipeline/v1alpha1/gcs_resource.go
  pkg/apis/pipeline/v1alpha1/gcs_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go
Labels: approved, cla: yes, lgtm, size/S

#572 Fix WebHook controller crashing on minishift
  config/200-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#563 Remove `logsURL` from step status
  docs/tutorial.md
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
Labels: approved, cla: yes, lgtm, size/M

#575 Fix spelling errors
  test/dag_test.go
Labels: approved, cla: yes, lgtm, size/XS

#565 Use truncated base TaskRun name for lookup
  Gopkg.lock
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, cla: yes, lgtm, size/L

#577 Move `templating` package outside of `reconcilier`
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/apply.go
  pkg/reconciler/v1alpha1/taskrun/resources/apply.go
  pkg/templating/templating.go
  pkg/templating/templating_test.go
Labels: approved, cla: yes, lgtm, size/S

#581 pipeline example taskRef name not match
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, size/XS

#580 Container names must end with an alphanumeric character
  pkg/names/generate.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go
Labels: approved, cla: yes, lgtm, size/M

#585 ServiceAccount without ImagePullSecrets should not fail to fetch
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go
Labels: approved, cla: yes, lgtm, size/L

#583 Fixes RBAC permissions for task and pipeline runs for openshift
  config/200-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#588 Disable markdown linting
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#589 golang format tools
  pkg/names/generate.go
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go
Labels: approved, cla: yes, lgtm, size/XS

#590 Format markdown
  docs/container-contract.md
  docs/developers/README.md
  docs/pipelineruns.md
  docs/pipelines.md
  docs/resources.md
  docs/taskruns.md
  docs/tasks.md
  docs/tutorial.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/L

#579 Add information on RBAC setup for installation
  docs/install.md
Labels: approved, cla: yes, lgtm, size/S

#592 Update go-containerregistry to latest master.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/google/go-containerregistry/pkg/name/digest.go
  vendor/github.com/google/go-containerregistry/pkg/v1/config.go
  vendor/github.com/google/go-containerregistry/pkg/v1/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/compressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/uncompressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/with.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/stream/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/v1util/zip.go
Labels: approved, cla: yes, lgtm, size/L

#595 Move CRD type assertions to a test
  pkg/apis/pipeline/v1alpha1/cluster_task_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/types_test.go
Labels: approved, cla: yes, lgtm, size/M

#597 Format markdown
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#600 Create directory with configs for our prow and other CI infrastructure.
  infra/README.md
  infra/boskos/boskos-config.yaml
  infra/boskos/boskos.yaml
  infra/boskos/storage-class.yaml
  infra/config.yaml
  infra/gubernator/config.yaml
  infra/prow/config.yaml
  infra/prow/plugins.yaml
Labels: approved, cla: yes, lgtm, size/L

#602 golang format tools
  cmd/controller/main.go
  cmd/creds-init/main.go
  cmd/webhook/main.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/artifacts/artifact_storage_test.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
  pkg/reconciler/v1alpha1/pipelinerun/cancel.go
  pkg/reconciler/v1alpha1/pipelinerun/cancel_test.go
  pkg/reconciler/v1alpha1/pipelinerun/config/store.go
  pkg/reconciler/v1alpha1/pipelinerun/config/store_test.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/v1alpha1/taskrun/cancel.go
  pkg/reconciler/v1alpha1/taskrun/cancel_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/apply.go
  pkg/reconciler/v1alpha1/taskrun/resources/apply_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resources.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/artifact_bucket_test.go
  test/builder/build_test.go
  test/builder/examples_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
  test/builder/task.go
  test/builder/task_test.go
  test/clients.go
  test/cluster_resource_test.go
  test/controller.go
  test/dag_test.go
  test/embed_test.go
  test/gcs_taskrun_test.go
  test/git_checkout_test.go
  test/helm_task_test.go
  test/init_test.go
  test/pipelinerun_test.go
  test/timeout_test.go
  test/wait.go
  test/wait_test.go
Labels: approved, cla: yes, lgtm, size/L

#607 Make Roadmap moar exciting!! 🤩
  roadmap-2019.md
Labels: approved, cla: yes, lgtm, size/M

#608 Add two more worker projects for CI.
  infra/boskos/boskos-config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#610 Updated knative reference to Tekton
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#603 Port duplicate pod test from knative/build 🏗
  test/duplicate_test.go
Labels: approved, cla: yes, lgtm, size/M

#612 Change path to tektoncd in fork instructions
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#613 Fix OWNER link in CONTRIBUTING 👼
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#616 Add t.Parallel() to some more e2e tests.
  test/artifact_bucket_test.go
  test/dag_test.go
  test/embed_test.go
Labels: approved, cla: yes, lgtm, size/XS

#620 entrypoint image lookup: change auth order
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go
Labels: approved, cla: yes, lgtm, size/S

#622 Add Security and SCM sections to the roadmap.
  roadmap-2019.md
Labels: approved, cla: yes, lgtm, size/S

#605 Specify `Command` field for internal containers (creds-init, …)
  DEVELOPMENT.md
  pkg/apis/pipeline/v1alpha1/artifact_bucket.go
  pkg/apis/pipeline/v1alpha1/artifact_bucket_test.go
  pkg/apis/pipeline/v1alpha1/artifact_pvc.go
  pkg/apis/pipeline/v1alpha1/artifact_pvc_test.go
  pkg/apis/pipeline/v1alpha1/build_gcs_resource_test.go
  pkg/apis/pipeline/v1alpha1/cluster_resource.go
  pkg/apis/pipeline/v1alpha1/cluster_resource_test.go
  pkg/apis/pipeline/v1alpha1/gcs_resource.go
  pkg/apis/pipeline/v1alpha1/gcs_resource_test.go
  pkg/apis/pipeline/v1alpha1/git_resource.go
  pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/output_resource_test.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod.go
  pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#625 remove extra line from DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#628 Format markdown
  CONTRIBUTING.md
  DEVELOPMENT.md
  docs/install.md
  infra/README.md
  roadmap-2019.md
Labels: approved, cla: yes, lgtm, size/M

#640 Add link to Tekton Pipelines Working Group calendar event 📱
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/S

#643 export SOURCE_DATE_EPOCH env variable to avoid wrong image created time
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#638 Remove nader ziada and shashwathi from owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#635 Switch prow configs to use Let's Encrypt https address.
  infra/README.md
  infra/config.yaml
  infra/gubernator/config.yaml
  infra/prow/config.yaml
  infra/prow/ingress.yaml
Labels: approved, cla: yes, lgtm, size/L

#645 Fix some prow configs.
  infra/gubernator/config.yaml
  infra/prow/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#650 Move WG meeting to Tuesdays
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#621 Update taskrun/pipelinerun timeout logic to not rely on resync behavior
  cmd/controller/main.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types_test.go
  pkg/reconciler/timeout_handler.go
  pkg/reconciler/timeout_handler_test.go
  pkg/reconciler/v1alpha1/pipelinerun/cancel.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go
  pkg/reconciler/v1alpha1/taskrun/cancel.go
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
  test/controller.go
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/XL

#651 Create our test clusters in us-central1 🌍
  infra/prow/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#653 Expand test infra docs 🏭
  CONTRIBUTING.md
  infra/README.md
Labels: approved, cla: yes, lgtm, size/M

#656 Add feature proposal guidelines 💡
  CONTRIBUTING.md
  api_compatibility_policy.md
Labels: approved, cla: yes, lgtm, size/M

#663 Add the community repo to prow for tide merging.
  infra/prow/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#672 golang format tools
  pkg/reconciler/timeout_handler_test.go
Labels: approved, cla: yes, lgtm, size/XS

#671 Format markdown
  CONTRIBUTING.md
  hack/release.md
  infra/README.md
  tekton/README.md
Labels: approved, cla: yes, lgtm, size/L

#674 Timeout handler : WaitTaskRun only if the pod got created successfully
  pkg/reconciler/v1alpha1/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/XS

#675 Add `latest` tag to most recently released images 🔖
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/XS

#654 Point to new ko repo
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#678 Fix docs/tasks.md wrong apiVersion 📖
  docs/tasks.md
Labels: approved, cla: yes, lgtm, size/XS

#677 cmd/git-init: check for errors or at least log them
  cmd/git-init/main.go
Labels: approved, cla: yes, lgtm, size/S

#679 Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#681 timeout_handler small fixes
  pkg/reconciler/timeout_handler.go
  pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go
Labels: approved, cla: yes, lgtm, size/S

#684 fix #683: broken link to approver requirments doc
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#686 Require `ko` >= 0.1 and simplify entrypoint copy container args
  DEVELOPMENT.md
  pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint.go
  pkg/reconciler/v1alpha1/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/S

#688 e2e tests: use sync.Once on initializeLogsAndMetrics
  test/init_test.go
Labels: approved, cla: yes, lgtm, size/S

#689 Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#687 entrypoint: in case of step command failure, write postfile
  cmd/entrypoint/main.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  test/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#690 Update release dogfood to work against prod 😌
  docs/install.md
  tekton/README.md
  tekton/account.yaml
  tekton/publish-run.yaml
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/L

#692 Format markdown
  docs/install.md
  tekton/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#693 Fix typo in README
  tekton/README.md
Labels: approved, cla: yes, lgtm, size/XS

#694 Add additionalPrinterColumns to taskrun CRD
  config/300-taskrun.yaml
Labels: approved, cla: yes, lgtm, size/S

#695 Add additionalPrinterColumns to pipelinerun CRD
  config/300-pipelinerun.yaml
Labels: approved, cla: yes, lgtm, size/S

#697 Format markdown
  tekton/README.md
Labels: approved, cla: yes, lgtm, size/XS

#676 Some code improvements
  pkg/apis/pipeline/v1alpha1/storage_resource.go
  pkg/reconciler/v1alpha1/taskrun/resources/taskspec.go
Labels: approved, cla: yes, lgtm, size/S

#700 Update install.md
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS
