Repository tektoncd/pipeline, pull requests merged in 2020-05, with the labels that each got.

#2472 taskrun/resources: allow input and output storage resources
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/resources/input_resources.go
  pkg/reconciler/taskrun/resources/output_resource.go
  pkg/reconciler/taskrun/resources/output_resource_test.go
  pkg/reconciler/taskrun/resources/volume.go
Labels: approved, lgtm, ok-to-test, size/XL

#2512 Documentation and Example on Running Step Containers as Non Root
  docs/pipelineruns.md
  docs/taskruns.md
  docs/tasks.md
  examples/v1beta1/taskruns/run-steps-as-non-root.yaml
Labels: approved, lgtm, size/L

#2329 Emit events for all TaskRun lifecycle events
  docs/events.md
  docs/pipelineruns.md
  docs/taskruns.md
  pkg/reconciler/event.go
  pkg/reconciler/event_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/resources/cloudevent/cloud_event_controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#2516 Tighten up the language for clarity and flow.
  docs/variables.md
Labels: approved, lgtm, size/L

#2525 Add comments to the event emitting code in taskrun
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/S

#2535 Use a better name for generate name of sample pr
  examples/v1beta1/pipelineruns/pipelinerun-using-different-subpaths-of-workspace.yaml
Labels: approved, lgtm, size/XS

#2532 Track deprecated Beta features w/ earliest date of removal
  README.md
  docs/deprecations.md
Labels: approved, lgtm, size/S

#2528 Add validation for condition check name
  pkg/apis/pipeline/v1alpha1/condition_validation.go
  pkg/apis/pipeline/v1alpha1/condition_validation_test.go
Labels: approved, lgtm, size/S

#2546 Remove example with parallel tasks with a fan-in task
  docs/workspaces.md
  examples/v1beta1/pipelineruns/pipelinerun-with-parallel-tasks-using-pvc.yaml
Labels: approved, kind/documentation, lgtm, ok-to-test, size/M

#2551 golangci-lint: limit concurrency and never colorize
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#2544 Add a link from API Policy to Deprecations Table
  api_compatibility_policy.md
Labels: approved, kind/documentation, lgtm, size/XS

#2549 Makefile: add more linters to be used 🌊
  Makefile
Labels: approved, lgtm, size/M

#2554 Switch to ko-gcloud for release
  tekton/publish.yaml
Labels: approved, kind/misc, lgtm, size/XS

#2548 Split ResolveResultRefs in two
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  pkg/reconciler/pipelinerun/resources/validate_params.go
Labels: approved, kind/cleanup, lgtm, size/L

#2519 Correct the message for "step" failed in "taskrun"
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: approved, lgtm, size/XS

#2561 Unlock nightly builds
  config/controller.yaml
  config/webhook.yaml
Labels: approved, lgtm, size/S

#2564 Remove abayer as OWNER for now ❤️
  OWNERS
Labels: approved, lgtm, size/XS

#2539 Rewrite the alpha-to-beta migration guide for clarity and flow.
  docs/migrating-v1alpha1-to-v1beta1.md
Labels: approved, lgtm, size/L

#2556 scripts: use GOPATH or GOBIN prefix 🙏
  hack/generate-groups.sh
  hack/generate-knative.sh
  hack/update-codegen.sh
Labels: approved, kind/cleanup, lgtm, size/S

#2567 Update golangci configuration ☕
  .golangci.yml
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M

#2568 webhook.go: golint pass 👼
  cmd/webhook/main.go
Labels: approved, lgtm, size/M

#2530 Update .ko.yaml based on the publish task 🌮
  .ko.yaml
  .ko.yaml.release
  tekton/publish.yaml
Labels: approved, kind/misc, lgtm, size/S

#2504 refactor pipeline validation
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
Labels: approved, lgtm, size/L

#2543 Improvements on pipeline cancel
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/cancel_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/metrics.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, lgtm, size/M

#2579 Use the condition name in tekton.dev/conditionCheck
  pkg/apis/pipeline/register.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, kind/bug, lgtm, size/S

#2576 reconciler: fix store*Spec tests 🐛
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, area/testing, kind/misc, lgtm, size/XS

#2585 Fix PipelineResources link
  docs/tasks.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#2583 Add validation for "ServiceAccountNames" to avoid wrong taskname
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, kind/bug, lgtm, size/M

#2389 Fix for #2362, adding support per TaskRun runtime settings.
  docs/pipelineruns.md
  examples/v1beta1/pipelineruns/pipelinerun-taskrunspecs.yaml
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, area/api, cla: yes, kind/api-change, lgtm, ok-to-test, size/L

#2570 Bump knative to release-0.14 ⏺
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/factory.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/README.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, kind/misc, lgtm, size/S

#2593 Makefile: update ram package path 📦
  Makefile
Labels: approved, lgtm, size/XS

#2434 Only mark PipelineRun as cancelled if actually cancelled 🛑
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/M

#2602 Fix typo introduced in git-init (#2598)
  pkg/git/git.go
Labels: approved, kind/bug, lgtm, ok-to-test, size/XS

#2482 Update end to end example to use workspaces and results ✨
  examples/v1beta1/pipelineruns/pipelinerun.yaml
  examples/v1beta1/taskruns/build-push-kaniko.yaml
Labels: approved, lgtm, size/L

#2536 Add PodSecurityPolicy access to webhook's clusterrole
  config/200-clusterrole.yaml
Labels: approved, kind/bug, lgtm, needs-cherry-pick, size/XS

#2608 Propagate annotations from Conditions to TaskRuns/Pods
  docs/conditions.md
  internal/builder/v1alpha1/condition.go
  internal/builder/v1alpha1/condition_test.go
  internal/builder/v1alpha1/task.go
  internal/builder/v1alpha1/task_test.go
  internal/builder/v1beta1/task.go
  internal/builder/v1beta1/task_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/M

#2575 Git PipelineResource errs when HOME != /tekton/home & UID is non-zero
  pkg/apis/pipeline/paths.go
  pkg/apis/resource/v1alpha1/git/git_resource.go
  pkg/apis/resource/v1alpha1/git/git_resource_test.go
  pkg/pod/creds_init.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/bug, lgtm, size/M

#2581 refactor pipeline validation unit tests v1beta1
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, kind/cleanup, lgtm, size/XXL

#2526 Emit events when we fail to update the taskrun
  pkg/reconciler/event.go
  pkg/reconciler/event_test.go
  pkg/reconciler/taskrun/taskrun.go
  test/cancel_test.go
Labels: approved, kind/feature, lgtm, size/L

#2426 Add Signal Forwarding to Entrypoint Runner
  cmd/entrypoint/runner.go
  cmd/entrypoint/runner_test.go
Labels: approved, cla: yes, kind/feature, lgtm, size/M

#2501 Add recommended k8s labels
  config/100-namespace.yaml
  config/101-podsecuritypolicy.yaml
  config/200-clusterrole.yaml
  config/200-role.yaml
  config/200-serviceaccount.yaml
  config/201-clusterrolebinding.yaml
  config/201-rolebinding.yaml
  config/300-clustertask.yaml
  config/300-condition.yaml
  config/300-imagecache.yaml
  config/300-pipeline.yaml
  config/300-pipelinerun.yaml
  config/300-resource.yaml
  config/300-task.yaml
  config/300-taskrun.yaml
  config/500-webhooks.yaml
  config/clusterrole-aggregate-edit.yaml
  config/clusterrole-aggregate-view.yaml
  config/config-artifact-bucket.yaml
  config/config-artifact-pvc.yaml
  config/config-defaults.yaml
  config/config-feature-flags.yaml
  config/config-leader-election.yaml
  config/config-logging.yaml
  config/config-observability.yaml
  config/controller.yaml
  config/webhook.yaml
  docs/developers/resources-labelling.md
Labels: approved, kind/feature, lgtm, size/L

#2618 Add a dummy.go file to allow vendoring config
  config/dummy.go
Labels: approved, kind/misc, lgtm, size/S

#2615 Link the Docs Contributor and Style Guides
  CONTRIBUTING.md
Labels: approved, kind/documentation, lgtm, size/M

#2619 Replace devel on all yamls 🌳
  tekton/publish.yaml
Labels: approved, kind/bug, lgtm, needs-cherry-pick, size/XS

#2624 Revert "config: prefixes image names with ko:// scheme"
  config/controller.yaml
  config/webhook.yaml
Labels: approved, kind/misc, lgtm, size/XS

#2625 Revert "config: prefixes image names with ko:// scheme 📠"
  config/controller.yaml
Labels: approved, kind/misc, lgtm, size/S

#2627 Add example and docs links for v0.12.1
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#2629 Link the task results doc section to their usage in pipelines
  docs/tasks.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#2632 Improve TaskRun workspaces documentation
  docs/workspaces.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/M

#2606 Run tekton containers as nonroot 🐰
  .ko.yaml
  config/controller.yaml
Labels: approved, kind/feature, lgtm, size/S

#2646 Fix a typo, "space names" -> "namespaces"
  docs/tasks.md
Labels: approved, kind/documentation, lgtm, size/XS

#2644 Add replacement for cluster resource in v1alpha1 to v1beta1 migration docs
  docs/migrating-v1alpha1-to-v1beta1.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#2641 Fix 'Edit this page' and 'Create an issue' links on the website
  docs/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#2636 Improve documentation about guarding Task execution using Conditions
  docs/pipelines.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/M

#2633 Various documentation fixes
  docs/README.md
  docs/conditions.md
  docs/pipelineruns.md
  docs/tasks.md
Labels: approved, kind/misc, lgtm, ok-to-test, size/S

#2634 Improve Pod template documentation
  docs/pipelineruns.md
  docs/podtemplates.md
  docs/taskruns.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/S

#2652 Fix helm chart for deprecated extensions/v1beta1
  test/gohelloworld/gohelloworld-chart/templates/deployment.yaml
  test/helm_task_test.go
Labels: approved, kind/bug, lgtm, size/XS

#2483 Provide more guidance on not using PipelineResources 🚧
  docs/migrating-v1alpha1-to-v1beta1.md
  docs/resources.md
Labels: approved, kind/documentation, lgtm, size/L

#2573 Sync the pipelinerun status from the informers
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/conditionresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, kind/feature, lgtm, size/XL

#2653 Update nop, gsutil and shell images
  config/controller.yaml
Labels: approved, kind/feature, lgtm, size/S

#2658 The deployments v1 the selector is mandatory
  test/gohelloworld/gohelloworld-chart/templates/deployment.yaml
Labels: approved, kind/bug, lgtm, size/XS

#2455 Find first error step based on "FinishAt" and "StartAt"
  pkg/entrypoint/entrypointer.go
  pkg/pod/status.go
Labels: approved, cla: yes, kind/bug, lgtm, size/S

#2663 Document git ssh symlink requirement
  docs/auth.md
Labels: approved, kind/documentation, lgtm, size/S

#2654 Re enable helm test
  test/helm_task_test.go
Labels: approved, kind/bug, lgtm, size/XS

#2669 Improve formatting of Docker Desktop instructions
  DEVELOPMENT.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/M

#2655 Move events to a common package
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/events/cloudevent/cloudevent.go
  pkg/reconciler/events/cloudevent/cloudevent_test.go
  pkg/reconciler/events/cloudevent/cloudeventclient.go
  pkg/reconciler/events/cloudevent/cloudeventsfakeclient.go
  pkg/reconciler/events/doc.go
  pkg/reconciler/events/event.go
  pkg/reconciler/events/event_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/cleanup, lgtm, size/M

#2601 Add variable expansion for params in Projected Volume fields
  docs/tasks.md
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/M

#2691 Fix typo in migration guide
  docs/migrating-v1alpha1-to-v1beta1.md
Labels: approved, kind/documentation, lgtm, size/S

#2674 Fix typos in docs/tasks.md
  docs/tasks.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#2686 Update doc.go to correct version v1beta1
  pkg/apis/pipeline/v1beta1/doc.go
Labels: approved, kind/misc, lgtm, ok-to-test, size/XS

#2687 Fix typo sometines to sometimes
  docs/developers/resources-labelling.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#2681 Fix documentation about TaskRunSpecs within PipelineRun
  docs/pipelineruns.md
Labels: approved, kind/documentation, lgtm, size/M

#2498 [master] Fix spelling errors
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, size/XS

#2626 Invalid length of container termination message
  cmd/entrypoint/main.go
  docs/tasks.md
  pkg/termination/write.go
  pkg/termination/write_test.go
Labels: approved, kind/bug, lgtm, size/M

#2467 Sort and remove duplicate when set "taskrun.status.taskResults"
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, kind/bug, lgtm, size/L

#2706 Make it easier to find results docs
  docs/tasks.md
Labels: approved, kind/documentation, lgtm, size/XS

#2705 apply_test files mixed up diffs (want, got) and (got, want)
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/apply_test.go
Labels: approved, kind/cleanup, lgtm, size/S

#2713 Change the sha for the nop image
  config/controller.yaml
Labels: approved, kind/misc, lgtm, size/XS
