Repository tektoncd/pipeline, pull requests merged in 2020-01, with the labels that each got.

#1799 Python2 has been deprecated
  tekton/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1758 Reflect tektoncd/pipeline release version as an annotation on pod
  config/controller.yaml
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/version/version.go
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1804 Change variable name: non-existent variable of testCluster
  docs/resources.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1793 Fix parallel test + for range value overwrite bug
  test/cancel_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1807 Use vendor-ed version of plumbing instead of go get 🦸
  test/e2e-common.sh
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1812 Mark task as failed if OOMKilled.
  docs/taskruns.md
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1813 Fix passing -submodules flag to git-init
  pkg/apis/pipeline/v1alpha1/git_resource.go
  pkg/apis/pipeline/v1alpha1/git_resource_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1787 Propagate Condition labels to the TaskRun/Pod
  docs/conditions.md
  docs/labels.md
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  test/builder/condition.go
  test/builder/condition_test.go
  test/builder/task.go
  test/builder/task_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1817 PullRequest Resource: Derive API URL from PR URL
  docs/resources.md
  pkg/pullrequest/scm.go
  pkg/pullrequest/scm_test.go
Labels: approved, cla: yes, lgtm, size/L

#1798 Add script mode for Conditions
  docs/conditions.md
  examples/pipelineruns/conditional-pipelinerun-with-optional-resources.yaml
  examples/pipelineruns/conditional-pipelinerun.yaml
  pkg/apis/pipeline/v1alpha1/condition_types.go
  pkg/apis/pipeline/v1alpha1/condition_validation.go
  pkg/apis/pipeline/v1alpha1/condition_validation_test.go
  pkg/reconciler/pipelinerun/resources/conditionresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  test/builder/condition.go
  test/builder/condition_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1821 Fix typo and some comments on uppercase variables in pkg/pod.
  pkg/pod/resource_request.go
  pkg/pod/status.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#1722 Correctly report step start times
  cmd/entrypoint/main.go
  cmd/git-init/main.go
  cmd/imagedigestexporter/main.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod_test.go
  pkg/pod/status.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/termination/termination.go
  pkg/termination/termination_test.go
  test/builder/container.go
  test/start_time_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1810 Allow keeping namespaces after running tests for investigation
  test/README.md
  test/init_test.go
Labels: approved, cla: yes, lgtm, size/S

#1837 Ignore all generated files in pkg/client for golangci
  .golangci.yml
Labels: approved, cla: yes, lgtm, size/XS

#1835 Make sure all alpine packages are updated to their latest versions.
  images/Dockerfile
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1827 Factor out a method to parse termination messages
  go.mod
  pkg/pod/status.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/termination/parse.go
  pkg/termination/parse_test.go
  pkg/termination/write.go
  pkg/termination/write_test.go
Labels: approved, cla: yes, lgtm, size/L

#1834 Update go.mod comment with the correct k8s version 😈
  go.mod
Labels: approved, cla: yes, lgtm, size/XS

#1847 Use the same kaniko version everywhere (and update to latest)
  docs/taskruns.md
  docs/tutorial.md
  examples/pipelineruns/pipelinerun.yaml
  examples/taskruns/build-push-kaniko.yaml
  tekton/publish.yaml
  test/helm_task_test.go
  test/kaniko_task_test.go
Labels: approved, cla: yes, lgtm, size/S

#1850 Rename some test to be closer to golang naming convention 💅
  pkg/apis/pipeline/v1alpha1/build_gcs_resource_test.go
  pkg/apis/pipeline/v1alpha1/cloud_event_resource_test.go
  pkg/apis/pipeline/v1alpha1/cluster_resource_test.go
  pkg/apis/pipeline/v1alpha1/git_resource_test.go
  pkg/apis/pipeline/v1alpha1/image_resource_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go
  pkg/pullrequest/disk_test.go
  pkg/pullrequest/scm_test.go
  pkg/reconciler/event_test.go
  pkg/reconciler/taskrun/resources/volume_test.go
  pkg/system/names_test.go
Labels: approved, cla: yes, lgtm, size/M

#1848 Unexport validate Workspace function 👼
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation.go
Labels: approved, cla: yes, lgtm, size/S

#1527 Add support for `from` usage in Pipeline Conditions
  docs/pipelines.md
  examples/pipelineruns/conditional-pipelinerun.yaml
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/pipeline/dag/dag_test.go
  pkg/reconciler/pipelinerun/resources/conditionresolution.go
  pkg/reconciler/pipelinerun/resources/input_output_steps.go
  pkg/reconciler/pipelinerun/resources/input_output_steps_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
Labels: approved, cla: yes, lgtm, size/L

#1842 Explain why resource code generation is separate 🥚
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/XS

#1849 Fix spelling errors
  pkg/apis/resource/v1alpha1/pipeline_resource_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1770 Enable sidecars to partake in substitution
  docs/tasks.md
  examples/taskruns/sidecar-interp.yaml
  pkg/apis/pipeline/v1alpha1/container_replacements.go
  pkg/apis/pipeline/v1alpha1/container_replacements_test.go
  pkg/apis/pipeline/v1alpha1/step_replacements.go
  pkg/apis/pipeline/v1alpha1/step_replacements_test.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1851 Deduplicate and sort termination message items
  pkg/termination/parse.go
  pkg/termination/parse_test.go
Labels: approved, cla: yes, lgtm, size/M

#1854 Correct "outputs.resources.%s.path"
  pkg/apis/pipeline/v1alpha1/resource_paths.go
  pkg/reconciler/taskrun/resources/apply_test.go
Labels: approved, cla: yes, lgtm, size/S

#1852 Use correct name for embedded pipelines to prevent reconciler panic
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
Labels: approved, cla: yes, lgtm, size/M

#1865 Group pipeline_validation_test together 😁
  pkg/apis/pipeline/v1alpha1/pipeline_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#1858 An example in the taskrun doc is not runnable
  docs/taskruns.md
Labels: approved, cla: yes, lgtm, size/M

#1853 Separate pod template doc
  docs/pipelineruns.md
  docs/podtemplates.md
  docs/taskruns.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1800 Add ConfigMap volume source support to workspaces
  docs/taskruns.md
  examples/taskruns/workspace.yaml
  pkg/apis/pipeline/v1alpha1/workspace_types.go
  pkg/apis/pipeline/v1alpha1/workspace_validation_test.go
  pkg/apis/pipeline/v1alpha2/workspace_types.go
  pkg/apis/pipeline/v1alpha2/workspace_validation.go
  pkg/apis/pipeline/v1alpha2/workspace_validation_test.go
  pkg/apis/pipeline/v1alpha2/zz_generated.deepcopy.go
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
Labels: approved, cla: yes, lgtm, size/L

#1873 Add JSON struct tag for Workspaces field
  pkg/apis/pipeline/v1alpha1/task_types.go
Labels: approved, cla: yes, lgtm, size/XS

#1869 Add missing podTemplate element
  docs/resources.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1875 Add Description to ResourceDeclaration
  examples/taskruns/optional-resources.yaml
  pkg/apis/resource/v1alpha1/pipeline_resource_types.go
Labels: approved, area/api, cla: yes, lgtm, ok-to-test, size/XS

#1863 Issue 1862: Gitlab status upload fails with missing commit error
  go.sum
  pkg/pullrequest/disk.go
  pkg/pullrequest/disk_test.go
Labels: approved, cla: yes, lgtm, size/M

#1828 Update service port naming inline with istio naming conventions
  config/400-controller-service.yaml
  config/400-webhook-service.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1801 Add Secret volume source support to workspaces
  docs/taskruns.md
  examples/taskruns/workspace.yaml
  pkg/apis/pipeline/v1alpha1/workspace_types.go
  pkg/apis/pipeline/v1alpha1/workspace_validation_test.go
  pkg/apis/pipeline/v1alpha2/workspace_types.go
  pkg/apis/pipeline/v1alpha2/workspace_validation.go
  pkg/apis/pipeline/v1alpha2/workspace_validation_test.go
  pkg/apis/pipeline/v1alpha2/zz_generated.deepcopy.go
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
Labels: approved, cla: yes, lgtm, size/L

#1889 CI: Fix shell expansion when creating resources
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#1554 Adding support for taskSpec with pipelineSpec
  docs/pipelineruns.md
  examples/pipelineruns/pipelinerun-with-pipelinespec-and-taskspec.yaml
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation_test.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/artifacts/artifact_storage_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinespec_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
Labels: approved, cla: yes, lgtm, size/L

#1885 Update documentation to add points on PVC binding
  docs/pipelineruns.md
Labels: approved, cla: yes, lgtm, size/XS

#1893 Make default managed-by label configurable
  config/config-defaults.yaml
  pkg/apis/config/default.go
  pkg/apis/config/default_test.go
  pkg/apis/config/testdata/config-defaults.yaml
  pkg/apis/pipeline/v1alpha1/taskrun_defaults.go
  pkg/apis/pipeline/v1alpha1/taskrun_defaults_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#1884 Use `tekton` instead of all as categories 🎿
  config/300-clustertask.yaml
  config/300-condition.yaml
  config/300-pipeline.yaml
  config/300-pipelinerun.yaml
  config/300-resource.yaml
  config/300-task.yaml
  config/300-taskrun.yaml
Labels: approved, cla: yes, lgtm, size/S

#1895 Address review comments from #1893
  pkg/pod/pod_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1891 fix: camel spelling
  pkg/reconciler/timeout_handler.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1899 code simplify of bool check and return
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1897 test/builder.Step name is optional
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/taskrun/validate_resources_test.go
  pkg/reconciler/timeout_handler_test.go
  test/artifact_bucket_test.go
  test/builder/examples_test.go
  test/builder/step.go
  test/builder/task.go
  test/builder/task_test.go
  test/cancel_test.go
  test/cluster_resource_test.go
  test/dag_test.go
  test/duplicate_test.go
  test/embed_test.go
  test/entrypoint_test.go
  test/git_checkout_test.go
  test/helm_task_test.go
  test/kaniko_task_test.go
  test/pipelinerun_test.go
  test/sidecar_test.go
  test/status_test.go
  test/taskrun_test.go
  test/timeout_test.go
  test/workingdir_test.go
  test/workspace_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1901 Add support for default pod template
  config/config-defaults.yaml
  docs/install.md
  docs/podtemplates.md
  hack/update-codegen.sh
  pkg/apis/config/default.go
  pkg/apis/config/default_test.go
  pkg/apis/config/testdata/config-defaults-pod-template-err.yaml
  pkg/apis/config/testdata/config-defaults-timeout-err.yaml
  pkg/apis/config/testdata/config-defaults-with-pod-template.yaml
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/pipeline/pod/doc.go
  pkg/apis/pipeline/pod/template.go
  pkg/apis/pipeline/pod/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pod.go
  pkg/apis/pipeline/v1alpha1/taskrun_defaults.go
  pkg/apis/pipeline/v1alpha1/taskrun_defaults_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
  test/builder/task.go
  test/builder/task_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1892 doc(dev): never use "here" as a link
  docs/developers/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1908 Add missing docs link to README 🔁
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1907 Avoid stuck on pending when hit "CreateContainerConfigError"
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: approved, cla: yes, lgtm, size/M

#1906 Correct the output of a "failed" taskrun
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: approved, cla: yes, lgtm, size/M

#1866 Introduce workspaces to Pipelines.
  docs/pipelineruns.md
  docs/pipelines.md
  docs/taskruns.md
  examples/pipelineruns/workspaces.yaml
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation_test.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_validation.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1alpha1/workspace_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1alpha2/workspace_types.go
  pkg/apis/pipeline/v1alpha2/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
  test/workspace_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1881 Issue 1880: Adds ability to disable certificate validation in pullrequest resource
  cmd/pullrequest-init/main.go
  docs/resources.md
  pkg/apis/pipeline/v1alpha1/pull_request_resource.go
  pkg/apis/pipeline/v1alpha1/pull_request_resource_test.go
  pkg/pullrequest/scm.go
  pkg/pullrequest/scm_test.go
Labels: approved, cla: yes, lgtm, size/L

#1914 Fix lint on master 🚚
  cmd/pullrequest-init/main.go
  pkg/pod/status.go
Labels: approved, cla: yes, lgtm, size/XS

#1888 Changes to add results to a task
  cmd/entrypoint/main.go
  docs/developers/README.md
  pkg/apis/pipeline/paths.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/entrypoint/entrypointer.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod.go
Labels: approved, area/api, cla: yes, kind/api-change, lgtm, size/L

#1911 TaskRun reconcile and timeout found, updateTaskRunStatusForTimeout delete pod optimization
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1924 Fix some typo in the release doc 📖
  tekton/README.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/XS

#1829 Create a additional release.notags.yaml with only digests 💫
  docs/install.md
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/S

#1923 Add v0.10.0 links to README 😌
  README.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/XS

#1927 Avoid a panic when sorting container statuses
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: approved, cla: yes, lgtm, size/S

#1928 Update dind-sidecar example
  examples/taskruns/dind-sidecar.yaml
Labels: approved, cla: yes, lgtm, size/M

#1930 Remove comment about Condition being WIP
  docs/conditions.md
  docs/pipelines.md
Labels: approved, cla: yes, lgtm, size/XS

#1925 Fix params-applied example
  examples/taskruns/step-script.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1934 Fail step-script if param value is not applied
  examples/taskruns/step-script.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1932 Update dind example to connect to daemon using TCP+TLS
  examples/taskruns/dind-sidecar.yaml
Labels: approved, cla: yes, lgtm, size/M

#1921 Update task run status with results
  docs/developers/README.md
  docs/taskruns.md
  docs/tasks.md
  examples/taskruns/task-result.yaml
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/L

#1935 Make pipelinerun as "cancelled" when taskrun is "cancelled"
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, cla: yes, lgtm, size/S

#1942 Add tekton.dev/release annotation to the webhook 🏋
  config/controller.yaml
  config/webhook.yaml
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1943 [cherry-pick v0.10.x] Avoid a panic when sorting container statuses
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: approved, cla: yes, lgtm, size/S

#1952 Extra space!
  docs/tasks.md
Labels: approved, cla: yes, lgtm, size/XS

#1945 [cherry-pick v0.10.x] Add tekton.dev/release annotation to the webhook 🏋
  config/controller.yaml
  config/webhook.yaml
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1948 Port TaskResults and TaskRunResults to v1alpha2 🎋
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1alpha2/task_types.go
  pkg/apis/pipeline/v1alpha2/taskrun_types.go
  pkg/apis/pipeline/v1alpha2/taskrun_types_test.go
  pkg/apis/pipeline/v1alpha2/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/M

#1937 Leave Max Container Request Values at Original Indices
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/resource_request.go
  pkg/pod/resource_request_test.go
Labels: approved, cla: yes, lgtm, size/L

#1954 Use named field in test tables 🌮
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
Labels: approved, cla: yes, lgtm, size/S

#1959 Fix release yaml for openshift install 🐸
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#1962 leave max container request values at original index
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/resource_request.go
  pkg/pod/resource_request_test.go
Labels: approved, cla: yes, lgtm, size/L

#1964 Document default-managed-by-label
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#1949 Port Workspace in pipeline support to v1alpha2 🎋
  pkg/apis/pipeline/v1alpha2/pipeline_types.go
  pkg/apis/pipeline/v1alpha2/pipeline_validation.go
  pkg/apis/pipeline/v1alpha2/pipeline_validation_test.go
  pkg/apis/pipeline/v1alpha2/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/M

#1967 Remove Code Comment From v1alpha2 taskrun_types_test.go
  pkg/apis/pipeline/v1alpha2/taskrun_types_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1966 Ensure taskRef (optional param) is non nil before setting defaults
  pkg/apis/pipeline/v1alpha1/pipeline_defaults.go
  pkg/apis/pipeline/v1alpha2/pipeline_defaults.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1963 [cherry-pick v0.10.x] Fix release yaml for openshift install 🐸
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#1971 Revert "Don't rely on .status.podName to find Pod associated with a T…
  pkg/reconciler/taskrun/cancel.go
  pkg/reconciler/taskrun/cancel_test.go
  pkg/reconciler/taskrun/metrics.go
  pkg/reconciler/taskrun/metrics_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1972 Fix spelling errors
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1973 [cherry-pick v0.10.x] Revert "Don't rely on .status.podName to find Pod associated with a T…
  pkg/reconciler/taskrun/cancel.go
  pkg/reconciler/taskrun/cancel_test.go
  pkg/reconciler/taskrun/metrics.go
  pkg/reconciler/taskrun/metrics_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1970 [cherry-pick 0.10.x] Ensure taskRef is non nil before setting defaults as this is an optio…
  pkg/apis/pipeline/v1alpha1/pipeline_defaults.go
  pkg/apis/pipeline/v1alpha2/pipeline_defaults.go
Labels: approved, cla: yes, lgtm, size/S

#1975 Add e2e test to cover TaskRun retries
  test/artifact_bucket_test.go
  test/retry_test.go
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/L

#1981 Add v0.10.1 to the readme 📖
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1985 Increase timeout for e2e test_retry test
  test/retry_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1982 Prepend tekton-bucket resource name with pipeline 💊
  tekton/README.md
  tekton/resources.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1988 minor fix for a broken link in task results
  docs/taskruns.md
Labels: approved, cla: yes, lgtm, size/XS

#1989 pipeline cancelled related spelling fix
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
