Repository tektoncd/pipeline, pull requests merged in 2020-11, with the labels that each got.

#3477 Fix link to bundle contract doc
  docs/pipelineruns.md
  docs/pipelines.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3478 Instruments more timeout_test with logstream
  test/timeout_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#3482 pkg/git: fix ssh credentials detection 🦀
  pkg/git/git.go
Labels: approved, kind/bug, lgtm, needs-cherry-pick, release-note, size/XS

#3484 [cherry-pick] pkg/git: fix ssh credentials detection 🦀
  pkg/git/git.go
Labels: approved, kind/bug, lgtm, release-note, size/XS

#3485 [cherry-pick] Avoid dangling symlinks in git-init
  pkg/git/git.go
Labels: approved, kind/bug, lgtm, release-note, size/M

#3470 remove the parameter is not used in func
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#3486 Use Webhook v1 APIs
  config/500-webhooks.yaml
Labels: approved, kind/misc, lgtm, release-note, size/S

#3379 Add feature flag to disable creds-init
  config/config-feature-flags.yaml
  docs/auth.md
  pkg/apis/config/feature_flags.go
  pkg/pod/creds_init.go
  pkg/pod/creds_init_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: approved, kind/feature, lgtm, release-note, size/L

#3453 Use proper platform for ko in examples test
  test/examples_test.go
  test/multiarch_utils.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#3125 Consolidating local setup instructions into single document
  DEVELOPMENT.md
  docs/developers/local-setup.md
  docs/tutorial.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/L

#3068 avoid requeuing taskrun in case of permanent error
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#3479 Have the timeout handler decorate log lines with "key".
  pkg/timeout/handler.go
Labels: approved, kind/cleanup, lgtm, release-note, size/S

#3496 Eliminate redundant Pod Get.
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/bug, lgtm, release-note-none, size/M

#3489 Add readiness and liveness probes in controller
  cmd/controller/main.go
  config/controller.yaml
Labels: approved, kind/feature, lgtm, release-note, size/M

#3501 Refactor Skip
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, kind/cleanup, lgtm, release-note, size/S

#3418 Add docs around HA support for the pipeline controller
  docs/developers/enabling-ha.md
  docs/install.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/M

#3503 adding links for 0.17.3 in README
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3502 Hide changes to go.sum by default from GitHub diffs
  .gitattributes
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3494 Use PATCH to update ready annotation
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
Labels: approved, kind/cleanup, lgtm, release-note, size/M

#3492 Put Tekton OCI bundles behind a feature flags 🎏
  config/config-feature-flags.yaml
  docs/install.md
  docs/pipelineruns.md
  docs/pipelines.md
  docs/taskruns.md
  examples/v1beta1/taskruns/no-ci/tekton-bundles.yaml
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/substitution.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/taskrun.go
  test/tektonbundles_test.go
Labels: approved, kind/misc, lgtm, release-note, size/XL

#3493 tests: fix potential races with t.Parallel and loops ➿
  pkg/reconciler/pipelinerun/resources/apply_test.go
  test/cancel_test.go
  test/examples_test.go
  test/git_checkout_test.go
  test/pipelinerun_test.go
  test/v1alpha1/cancel_test.go
  test/v1alpha1/git_checkout_test.go
  test/v1alpha1/pipelinerun_test.go
Labels: approved, area/testing, kind/bug, lgtm, release-note-none, size/S

#3500 Refactor the way timeouts are handled
  go.mod
  go.sum
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/timeout/handler.go
  pkg/timeout/handler_test.go
  third_party/github.com/PuerkitoBio/purell/LICENSE
  third_party/github.com/PuerkitoBio/urlesc/LICENSE
  third_party/github.com/emicklei/go-restful/LICENSE
  third_party/github.com/go-openapi/jsonpointer/LICENSE
  third_party/github.com/go-openapi/jsonreference/LICENSE
  third_party/github.com/go-openapi/spec/LICENSE
  third_party/github.com/go-openapi/swag/LICENSE
  third_party/github.com/hashicorp/errwrap/errwrap_test.go
  third_party/github.com/hashicorp/go-multierror/append_test.go
  third_party/github.com/hashicorp/go-multierror/flatten_test.go
  third_party/github.com/hashicorp/go-multierror/format_test.go
  third_party/github.com/hashicorp/go-multierror/group_test.go
  third_party/github.com/hashicorp/go-multierror/multierror_test.go
  third_party/github.com/hashicorp/go-multierror/prefix_test.go
  third_party/github.com/hashicorp/go-multierror/sort_test.go
  third_party/github.com/hashicorp/golang-lru/2q_test.go
  third_party/github.com/hashicorp/golang-lru/arc_test.go
  third_party/github.com/hashicorp/golang-lru/lru_test.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_test.go
  third_party/github.com/mailru/easyjson/LICENSE
  third_party/k8s.io/kube-openapi/pkg/LICENSE
  third_party/vendor/golang.org/x/crypto/LICENSE
  third_party/vendor/golang.org/x/net/LICENSE
  third_party/vendor/golang.org/x/sys/cpu/LICENSE
  third_party/vendor/golang.org/x/text/LICENSE
Labels: approved, kind/cleanup, lgtm, release-note, size/XL

#3511 updating readme with 0.18
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3507 Correct the disabled link
  docs/taskruns.md
Labels: approved, kind/documentation, lgtm, release-note-action-required, size/XS

#3514 Use dogfooding buildx image for multi-arch builds
  tekton/build-push-ma-base-image.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3519 Use dogfooding skopeo image for e2e and examples tests
  examples/v1alpha1/taskruns/docker-creds.yaml
  examples/v1alpha1/taskruns/pull-private-image.yaml
  examples/v1beta1/taskruns/docker-creds.yaml
  examples/v1beta1/taskruns/pull-private-image.yaml
  test/multiarch_utils.go
  test/pipelinerun_test.go
  test/v1alpha1/pipelinerun_test.go
Labels: approved, kind/misc, lgtm, release-note-none, size/S

#3520 Fix markdown styling
  docs/runs.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#3454 Add an unsuccessful TaskRun testcase in conformance tests
  test/conformance_test.go
Labels: approved, kind/feature, lgtm, release-note-none, size/L

#3530 Use logstream in the duplicate_test
  test/duplicate_test.go
  test/v1alpha1/duplicate_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/S

#3531 Change the webhook name to pipeline-webhook
  cmd/webhook/main.go
Labels: approved, kind/bug, lgtm, needs-cherry-pick, release-note, size/XS

#3533 [cherry-pick] Change the webhook name to pipeline-webhook
  cmd/webhook/main.go
Labels: approved, kind/bug, lgtm, release-note, size/XS

#3526 Fix script step on CRI-O runtime
  config/controller.yaml
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#3528 Update docs "when" with version info
  docs/pipelines.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#3527 Refresh list of s390x excluded test
  examples/v1alpha1/pipelineruns/demo-optional-resources.yaml
  examples/v1alpha1/pipelineruns/pipelinerun.yaml
  examples/v1alpha1/taskruns/build-push-kaniko.yaml
  examples/v1beta1/pipelineruns/demo-optional-resources.yaml
  examples/v1beta1/pipelineruns/pipelinerun.yaml
  examples/v1beta1/taskruns/authenticating-git-commands.yaml
  test/helm_task_test.go
  test/kaniko_task_test.go
  test/multiarch_utils.go
  test/v1alpha1/kaniko_task_test.go
Labels: approved, kind/misc, lgtm, release-note-none, size/M

#3508 Add a document to tell users how to configure Thread, QPS and Burst
  docs/install.md
  docs/tekton-controller-performance-configuration.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/M

#3537 updating readme for 0.18.1
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3538 fix link to owners file in release readme
  tekton/README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3536 Move the High Availability doc out of the developers subdirectory
  docs/enabling-ha.md
  docs/install.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/S

#3542 Consider not-found pod as permanent error when taskrun is done
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/bug, lgtm, release-note, size/XS

#3547 Format workspaces description and correct unclear words
  docs/workspaces.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note-none, size/M

#3422 Update plumbing dep to update google/go-licenses
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/DEVELOPMENT.md
  vendor/github.com/tektoncd/plumbing/Makefile
  vendor/github.com/tektoncd/plumbing/OWNERS
  vendor/github.com/tektoncd/plumbing/README.md
  vendor/github.com/tektoncd/plumbing/addpermissions.py
  vendor/github.com/tektoncd/plumbing/dummy.go
  vendor/github.com/tektoncd/plumbing/gcp.md
  vendor/github.com/tektoncd/plumbing/go.mod
  vendor/github.com/tektoncd/plumbing/go.sum
  vendor/github.com/tektoncd/plumbing/roadmap.md
  vendor/github.com/tektoncd/plumbing/scripts/README.md
  vendor/github.com/tektoncd/plumbing/scripts/deploy-release.sh
  vendor/github.com/tektoncd/plumbing/scripts/dummy.go
  vendor/modules.txt
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3488 Add variable expansion for ImagePullPolicy in Tasks. See #3423
  docs/variables.md
  examples/v1beta1/taskruns/image-params.yaml
  pkg/apis/pipeline/v1beta1/container_replacements.go
  pkg/apis/pipeline/v1beta1/container_replacements_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/M

#3556 deleting redundant test file
  pkg/reconciler/pipeline/dag/dag_test.go
  pkg/reconciler/pipeline/dag/dagv1beta1_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XXL

#3539 fix cycle detection logic in dag
  pkg/reconciler/pipeline/dag/dag.go
  pkg/reconciler/pipeline/dag/dag_test.go
Labels: approved, kind/bug, lgtm, release-note-none, size/M

#3535 Clarify input and output pipeline resource usage with PVC
  docs/developers/README.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/M

#3555 Plumb the "TEKTON_RESOURCE_NAME" env var into the cluster and PR reso…
  pkg/apis/resource/v1alpha1/cluster/cluster_resource.go
  pkg/apis/resource/v1alpha1/cluster/cluster_resource_test.go
  pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource.go
  pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
Labels: approved, kind/feature, lgtm, release-note, size/M

#3546 fix commen typo
  pkg/apis/pipeline/images.go
Labels: approved, kind/misc, lgtm, ok-to-test, release-note, size/XS

#3523 Add some tests for pkg/git/git.go
  pkg/git/git.go
  pkg/git/git_test.go
Labels: approved, kind/misc, lgtm, release-note-none, size/L

#3570 Add deprecated PascalCase fields in WhenExpressions to deprecated table
  docs/deprecations.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#3567 Fix the internal document link typo in docs/auth.md
  docs/auth.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/S

#3562 fixing broken links
  docs/pipelineruns.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS
