Repository tektoncd/pipeline, pull requests merged in 2020-10, with the labels that each got.

#3309 Fix validation error on parameters 🐒
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
Labels: approved, kind/bug, lgtm, release-note-none, size/M, size/XS

#3316 Derive cancel patch bytes once at controller startup
  pkg/reconciler/pipelinerun/cancel.go
Labels: approved, kind/cleanup, lgtm, release-note, size/M

#3308 Add a short example of using optional workspaces in when expressions
  docs/pipelines.md
  examples/v1beta1/pipelineruns/using-optional-workspaces-in-when-expressions.yaml
Labels: approved, kind/documentation, lgtm, release-note, size/M

#3106 tekton: migrate release task and pipeline to v1beta1
  tekton/publish.yaml
  tekton/release-pipeline-nightly.yaml
  tekton/release-pipeline.yaml
Labels: approved, kind/misc, lgtm, release-note, size/M

#3254 refactoring PipelineRunState to simplify logic for retrieving next tasks
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/L

#3156 Make DefaultThreadsPerController, QPS and Burst configurable via flags
  cmd/controller/main.go
  pkg/pod/entrypoint.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/S

#3318 Replace variables in Sidecar Script block
  docs/variables.md
  pkg/apis/pipeline/v1beta1/sidecar_replacements.go
  pkg/apis/pipeline/v1beta1/sidecar_replacements_test.go
  pkg/reconciler/taskrun/resources/apply.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#2859 Emit an event if overwriting PodTemplate affinity
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/M

#3315 Fix issue where workspace volume variable and pod volume conf differ
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
  test/workspace_test.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#3328 Fix annotation on v1beta1 field.
  pkg/apis/pipeline/v1beta1/pipeline_types.go
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#3292 Accept CloudEvents in any order for CE reconcile test
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/flake, lgtm, release-note-none, size/M

#3329 Add a clarifying comment to new workspace test
  test/workspace_test.go
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3326 refactoring pipelinerunstate - no logic changed at all
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/L

#3332 Fix the pipelinerun docs about completion time
  docs/pipelineruns.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#3281 Remove test builders from validate_params_test.go
  pkg/reconciler/pipelinerun/resources/validate_params_test.go
Labels: approved, area/testing, kind/cleanup, lgtm, release-note, size/L

#3322 Add docs demonstrating how to share a Workspace with Sidecars
  docs/workspaces.md
  examples/v1beta1/taskruns/workspace-in-sidecar.yaml
Labels: approved, kind/documentation, lgtm, release-note, size/M

#3334 Update -shell-image to a multi-arch version
  config/controller.yaml
Labels: approved, kind/feature, lgtm, release-note, size/XS

#3299 Add ability to replace image names for examples tests based on arch
  test/examples_test.go
  test/multiarch_utils.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#3340 Fix the logic for the disable-ha flag
  cmd/controller/main.go
Labels: approved, kind/bug, lgtm, release-note, size/XS

#3342 config: fix runAsUser inconsistency with images 🍨
  config/controller.yaml
  config/webhook.yaml
Labels: approved, kind/bug, lgtm, needs-cherry-pick, release-note, size/XS

#3343 release-cheat-sheet: remove duplicate image resource
  tekton/release-cheat-sheet.md
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3300 docs: update catalog links in v1beta1 migration doc 📖
  docs/migrating-v1alpha1-to-v1beta1.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3341 README.md: add 0.17.0 links
  README.md
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3333 When Expressions Status
  docs/pipelineruns.md
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
Labels: approved, kind/feature, lgtm, release-note, size/M

#3087 Step timeout
  cmd/entrypoint/main.go
  cmd/entrypoint/runner.go
  cmd/entrypoint/runner_test.go
  docs/tasks.md
  examples/v1beta1/taskruns/workspace-in-sidecar.yaml
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/script.go
  pkg/pod/status.go
  test/timeout_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#3344 Take -version into account in the controller ☕️
  cmd/controller/main.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/version/version.go
  test/taskrun_test.go
Labels: approved, kind/bug, lgtm, needs-cherry-pick, release-note, size/M

#3348 Attempt to fix another structured-merge-diff failures.
  internal/builder/v1beta1/pipeline.go
  internal/builder/v1beta1/pipeline_test.go
  pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  test/cancel_test.go
  test/git_checkout_test.go
  test/retry_test.go
  third_party/github.com/hashicorp/errwrap/errwrap_test.go
  third_party/github.com/hashicorp/go-multierror/append_test.go
  third_party/github.com/hashicorp/go-multierror/flatten_test.go
  third_party/github.com/hashicorp/go-multierror/format_test.go
  third_party/github.com/hashicorp/go-multierror/group_test.go
  third_party/github.com/hashicorp/go-multierror/multierror_test.go
  third_party/github.com/hashicorp/go-multierror/prefix_test.go
  third_party/github.com/hashicorp/go-multierror/sort_test.go
  third_party/github.com/hashicorp/golang-lru/2q_test.go
  third_party/github.com/hashicorp/golang-lru/arc_test.go
  third_party/github.com/hashicorp/golang-lru/lru_test.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_test.go
Labels: approved, kind/bug, lgtm, release-note-action-required, size/M

#3353 Only send cloud events when condition changes
  docs/events.md
  pkg/reconciler/events/event.go
Labels: approved, kind/bug, lgtm, needs-cherry-pick, release-note, size/S

#3325 refactoring get condition status for pipeline method in pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/L

#3346 Avoid dangling symlinks in git-init
  pkg/git/git.go
Labels: approved, kind/bug, lgtm, release-note, size/M

#3337 Fixes #3086 - amd64 images are pulled on all the architectures
  pkg/pod/entrypoint_lookup_impl.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/S

#3302 perf: create (pipeline|task)run timeout checks in background
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/taskrun/controller.go
  pkg/timeout/handler_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/S

#3372 Refresh list of s390x excluded tests
  examples/v1beta1/taskruns/authenticating-git-commands.yaml
  test/helm_task_test.go
  test/multiarch_utils.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#3371 [cherry-pick] Fix the logic for the disable-ha flag
  cmd/controller/main.go
Labels: approved, kind/bug, lgtm, release-note, size/XS

#3363 Update the revision used with kaniko.
  test/kaniko_task_test.go
  test/v1alpha1/kaniko_task_test.go
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#3370 [cherry-pick] Only send cloud events when condition changes
  docs/events.md
  pkg/reconciler/events/event.go
Labels: approved, kind/bug, lgtm, release-note, size/S

#3368 [cherry-pick] config: fix runAsUser inconsistency with images 🍨
  config/controller.yaml
  config/webhook.yaml
Labels: approved, kind/bug, lgtm, release-note, size/XS

#3360 Refactor pipelinerun resolution to clarify status
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#3369 [cherry-pick] Take -version into account in the controller ☕️
  cmd/controller/main.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/version/version.go
  test/taskrun_test.go
Labels: approved, kind/bug, lgtm, release-note, size/M

#3376 release: fix the publish task definition 📑
  tekton/publish.yaml
Labels: approved, kind/bug, lgtm, release-note-none, size/M

#3394 Make ConditionCheck container names DNS-safe
  pkg/reconciler/pipelinerun/resources/conditionresolution.go
  pkg/reconciler/pipelinerun/resources/conditionresolution_test.go
Labels: approved, kind/bug, lgtm, release-note, size/S

#3392 Add timestaps in logs
  config/config-logging.yaml
Labels: approved, kind/feature, lgtm, release-note, size/XS

#3405 Fix invalid comment on Task Script 👼
  pkg/apis/pipeline/v1beta1/task_types.go
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3403 Fix typo in resources.md
  docs/resources.md
Labels: approved, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#3349 Switch webhook liveness/readiness probes to use http ports
  cmd/webhook/main.go
  config/webhook.yaml
Labels: approved, kind/bug, lgtm, release-note, size/M

#3395 Mark failure to copy cred to user home as warning
  docs/auth.md
  pkg/credentials/initialize.go
Labels: approved, kind/documentation, lgtm, release-note, size/M

#3407 release: fix koparse behavior on finding images 🖌
  tekton/koparse/koparse.py
  tekton/koparse/test_release.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/S

#3410 [Automated] Fix misspellings
  docs/auth.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3409 Add kind label to pull request template
  .github/pull_request_template.md
Labels: approved, kind/misc, lgtm, release-note-none, size/S

#3414 Update PR template to try and avoid /kind being automatically set
  .github/pull_request_template.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3375 Check that events are at least expected ones
  test/cancel_test.go
  test/v1alpha1/cancel_test.go
Labels: approved, kind/flake, lgtm, release-note, size/M

#3413 release: enhance koparse 🙃
  tekton/koparse/koparse.py
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3389 Fix json annotations in WhenExpressions
  pkg/apis/pipeline/v1beta1/when_types.go
  pkg/apis/pipeline/v1beta1/when_validation.go
  pkg/apis/pipeline/v1beta1/when_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
Labels: approved, kind/cleanup, lgtm, needs-cherry-pick, release-note, size/L

#3400 Init conformance test
  test/conformance_test.go
  test/init_test.go
Labels: approved, kind/feature, lgtm, release-note, size/L

#3406 Update -shell-image to a multi-arch version with s390x addition
  config/controller.yaml
Labels: approved, kind/misc, lgtm, release-note, size/XS

#3421 [cherry-pick] Fix json annotations in WhenExpression
  pkg/apis/pipeline/v1beta1/when_types.go
  pkg/apis/pipeline/v1beta1/when_validation.go
  pkg/apis/pipeline/v1beta1/when_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#3420 tests: Add a PipelineRun ServiceAccounts test 🍊
  test/serviceaccount_test.go
Labels: approved, kind/misc, lgtm, release-note-none, size/L

#3142 Introduces Tekton bundles: take 2
  docs/pipelineruns.md
  docs/pipelines.md
  docs/taskruns.md
  docs/tekton-bundle-contracts.md
  examples/v1beta1/taskruns/tekton-bundles.yaml
  go.mod
  go.sum
  internal/builder/v1alpha1/task.go
  internal/builder/v1beta1/pipeline.go
  internal/builder/v1beta1/pipeline_test.go
  internal/builder/v1beta1/task.go
  internal/builder/v1beta1/task_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/remote/oci/resolver.go
  pkg/remote/oci/resolver_test.go
  test/remote.go
  test/remote_test.go
  test/tektonbundles_test.go
  test/wait.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/XXL

#3432 Fix the link to the tekton bundle example
  docs/taskruns.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3434 Fix the regex to match image in koparse
  tekton/koparse/koparse.py
  tekton/koparse/test_koparse.py
  tekton/koparse/test_release.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3430 Fix TaskRunSpec overrides when empty
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  test/serviceaccount_test.go
Labels: approved, kind/bug, lgtm, needs-cherry-pick, release-note, size/L

#3436 Fix koparse... again.
  tekton/koparse/koparse.py
  tekton/koparse/test_koparse.py
  tekton/koparse/test_release.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3425 Make t.Parallel() come first
  test/timeout_test.go
  test/v1alpha1/timeout_test.go
Labels: approved, kind/bug, lgtm, release-note-none, size/S

#2538 updating doc to add note on task results
  docs/pipelines.md
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, kind/documentation, lgtm, release-note-none, size/S

#3141 use status helper functions in pod status unit tests
  pkg/pod/status_test.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, release-note-none, size/L

#3426 Add logstream to v1alpha1 timeout_test.go
  test/v1alpha1/init_test.go
  test/v1alpha1/timeout_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#3402 Add Task to build base multi-arch image
  tekton/build-push-ma-base-image.yaml
  tekton/publish.yaml
  tekton/release-pipeline-nightly.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/L

#3441 [cherry-pick] Fix TaskRunSpec overrides when empty 🗜
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  test/serviceaccount_test.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#3445 Pass test ctx to taskrun reconciler instead of background ctx
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/flake, lgtm, release-note-none, size/XS

#3447 Don't "Follow" when dumping test pod logs.
  test/build_logs.go
  test/v1alpha1/build_logs.go
Labels: approved, kind/bug, lgtm, release-note-none, size/S

#3437 distinguish task dependencies: ordering vs resource
  pkg/apis/pipeline/v1beta1/pipeline_types.go
Labels: approved, kind/misc, lgtm, release-note, size/M

#3442 Document usage of chown on /tekton as another cause of error
  docs/auth.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/S

#3448 Include message on reason-mismatch failures
  test/v1alpha1/wait.go
  test/wait.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#3321 update submodules with --init flag
  pkg/git/git.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/XS

#3451 Added suport for building multi-arch images
  tekton/publish.yaml
Labels: approved, kind/misc, lgtm, ok-to-test, release-note, size/XS

#3455 [release-v0.17.x] tekton: port koparse fix to release-0.17.x
  tekton/koparse/koparse.py
  tekton/koparse/test_koparse.py
  tekton/koparse/test_release.yaml
Labels: approved, kind/misc, lgtm, release-note, size/S

#3456 Make the main releases multi-arch
  tekton/publish.yaml
  tekton/release-pipeline.yaml
Labels: approved, kind/misc, lgtm, release-note, size/S

#2787 Add registry cert config map to support self-signed private registry
  config/200-role.yaml
  config/config-registry-cert.yaml
  config/controller.yaml
  docs/install.md
Labels: approved, kind/misc, lgtm, ok-to-test, size/M

#3462 Update TestPipelineRunWithServiceAccountNameAndTaskRunSpec to use different podtemplate field
  test/serviceaccount_test.go
Labels: approved, kind/misc, lgtm, release-note, size/XS

#3433 Add documents for conformance tests
  test/README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/S

#3431 Update bundle tests to use IP of service to avoid cluster domain rules
  test/registry_test.go
  test/tektonbundles_test.go
Labels: approved, kind/failing-test, lgtm, ok-to-test, release-note-none, size/S

#3464 fix finally e2e test
  test/pipelinefinally_test.go
Labels: approved, kind/bug, lgtm, release-note-none, size/M

#3419 Update roadmap.md url in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#3473 Add v0.17.2 and v0.17.1 links to docs and examples
  README.md
Labels: approved, kind/cleanup, lgtm, release-note, size/XS

#3081 Generate OpenAPI specification and Swagger file
  cmd/spec-gen/main.go
  go.mod
  hack/README.md
  hack/update-codegen.sh
  hack/update-openapigen.sh
  pkg/apis/pipeline/pod/doc.go
  pkg/apis/pipeline/pod/template.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/XXL

#3471 Refactor TestIsSkipped to allow checking multiple tasks
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/L

#3474 Fix error path through test.
  test/timeout_test.go
  test/v1alpha1/timeout_test.go
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#3475 Moved spec-gen from cmd to hack directory
  hack/spec-gen/main.go
  hack/update-openapigen.sh
Labels: approved, kind/misc, lgtm, release-note, size/XS
