Repository tektoncd/pipeline, pull requests merged in 2020-02, with the labels that each got.

#1993 Fix deleting namespaces after running the e2e tests
  test/init_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1910 Enabling Pipeline Resources to be marked as Optional
  docs/resources.md
  examples/pipelineruns/demo-optional-resources.yaml
  pkg/apis/pipeline/v1alpha2/pipeline_types.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, cla: yes, kind/feature, lgtm, size/L

#1997 [DOCS] fix wrong default pod template example
  docs/install.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2000 Remove messages about kodata in task logs
  cmd/creds-init/main.go
  cmd/git-init/main.go
  cmd/pullrequest-init/main.go
  go.mod
  pkg/entrypoint/entrypointer.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2003 golang format tools
  cmd/creds-init/main.go
  cmd/git-init/main.go
  pkg/entrypoint/entrypointer.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2006 Fix goimport linting again 😅
  cmd/creds-init/main.go
  cmd/git-init/main.go
  pkg/entrypoint/entrypointer.go
Labels: approved, cla: yes, lgtm, size/XS

#2007 linting: show all the issues 👿
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1996 Correct the number of expected pods created in e2e test case of "retry"
  test/retry_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2008 Update v1alpha2 PodTemplate pointer 🌷
  go.mod
  pkg/apis/pipeline/v1alpha2/taskrun_defaults.go
  pkg/apis/pipeline/v1alpha2/taskrun_defaults_test.go
  pkg/apis/pipeline/v1alpha2/taskrun_types.go
  pkg/apis/pipeline/v1alpha2/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/M

#2009 Add LimitRangeName to v1alpha2.PipelineRun 🌷
  pkg/apis/pipeline/v1alpha2/pipelinerun_types.go
Labels: approved, cla: yes, lgtm, size/XS

#2004 Add LimitRange Examples for PipelineRun and TaskRun
  docs/pipelineruns.md
  docs/taskruns.md
  examples/pipelineruns/no-ci/limitrange.yaml
  examples/taskruns/no-ci/limitrange.yaml
Labels: approved, cla: yes, lgtm, size/L

#2015 Remove unused link
  docs/tasks.md
Labels: approved, cla: yes, lgtm, size/XS

#2011 Remove deprecated fields from PipelineResourceResult 🍠
  cmd/imagedigestexporter/main.go
  docs/resources.md
  examples/taskruns/cloud-event.yaml
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1alpha2/resource_types.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/termination/parse_test.go
  pkg/termination/write_test.go
Labels: approved, cla: yes, lgtm, size/M

#2012 Updating to include Tekton installtion
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2024 Correct message of Pipelinerun when timeout
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, cla: yes, lgtm, size/XS

#2018 Adding substitution for result path variable
  docs/developers/README.md
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/M

#2022 Enhance reconcile of taskrun to avoid extra pod creation
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/status.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/M

#2033 Make testcase of "retry" raise error rather than just log
  test/retry_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2030 Rewrite the Tekton Pipelines overview for clarity and flow
  docs/README.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/L

#2046 Linking to conditions-doc insteadof self
  docs/pipelines.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2052 Indicate minimum cluster version is now 1.15 🚓
  DEVELOPMENT.md
  docs/install.md
Labels: approved, cla: yes, lgtm, size/S

#2054 Add a description field to pipeline workspace declarations
  pkg/apis/pipeline/v1alpha2/workspace_types.go
Labels: approved, cla: yes, lgtm, size/XS

#2048 Add random suffix when make volumn from secret
  pkg/pod/creds_init.go
  pkg/pod/creds_init_test.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, cla: yes, lgtm, size/S

#2020 Don't Require User Input to Account for LimitRange Min
  docs/pipelineruns.md
  docs/taskruns.md
  examples/pipelineruns/no-ci/limitrange.yaml
  examples/taskruns/no-ci/limitrange.yaml
  pkg/apis/pipeline/v1alpha1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_conversion.go
  pkg/apis/pipeline/v1alpha1/taskrun_conversion_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha2/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha2/taskrun_types.go
  pkg/pod/pod.go
  pkg/pod/resource_request.go
  pkg/pod/resource_request_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, cla: yes, lgtm, size/L

#2034 Add authority for resource deployments.apps to tutorial-role
  docs/tutorial.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2040 Use vendor folder to speed up CI 🥄
  go.mod
  go.sum
  tekton/publish.yaml
  tekton/release-pipeline.yaml
  vendor/github.com/tektoncd/plumbing/gcp.md
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2064 Adding a version label to controller and webhook 🏋
  config/controller.yaml
  config/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2059 Reduce arguments for substitution.ValidateVariable 📼
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1alpha2/pipeline_validation.go
  pkg/apis/pipeline/v1alpha2/task_validation.go
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/M

#2038 Add Timeout to PipelineTask
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1alpha2/pipeline_types.go
  pkg/apis/pipeline/v1alpha2/taskrun_types.go
  pkg/apis/pipeline/v1alpha2/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  third_party/contrib.go.opencensus.io/exporter/ocagent/LICENSE
  third_party/github.com/docker/cli/cli/config/LICENSE
  third_party/github.com/docker/cli/cli/config/NOTICE
  third_party/github.com/docker/docker-credential-helpers/LICENSE
  third_party/github.com/docker/docker/pkg/homedir/LICENSE
  third_party/github.com/docker/docker/pkg/homedir/NOTICE
  third_party/github.com/gobuffalo/envy/LICENSE
  third_party/github.com/gobuffalo/envy/LICENSE.txt
  third_party/github.com/gregjones/httpcache/LICENSE.txt
  third_party/github.com/grpc-ecosystem/grpc-gateway/LICENSE.txt
  third_party/github.com/hashicorp/errwrap/errwrap_test.go
  third_party/github.com/hashicorp/errwrap/go.mod
  third_party/github.com/hashicorp/go-multierror/append_test.go
  third_party/github.com/hashicorp/go-multierror/flatten_test.go
  third_party/github.com/hashicorp/go-multierror/format_test.go
  third_party/github.com/hashicorp/go-multierror/go.mod
  third_party/github.com/hashicorp/go-multierror/multierror_test.go
  third_party/github.com/hashicorp/go-multierror/prefix_test.go
  third_party/github.com/hashicorp/go-multierror/sort_test.go
  third_party/github.com/hashicorp/golang-lru/2q_test.go
  third_party/github.com/hashicorp/golang-lru/arc_test.go
  third_party/github.com/hashicorp/golang-lru/lru_test.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_test.go
  third_party/github.com/openzipkin/zipkin-go/model/LICENSE
  third_party/github.com/peterbourgon/diskv/LICENSE
  third_party/github.com/rogpeppe/go-internal/semver/LICENSE
  third_party/github.com/vdemeester/k8s-pkg-credentialprovider/LICENSE
  third_party/golang.org/x/xerrors/LICENSE
  third_party/k8s.io/legacy-cloud-providers/azure/auth/LICENSE
  third_party/k8s.io/utils/LICENSE
Labels: approved, area/api, cla: yes, kind/api-change, lgtm, size/XXL

#1696 Refining status when Condition failed
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, cla: yes, lgtm, size/S

#2070 Use -mod=vendor for golangci-lint too 👼
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2067 Fix formatting.
  docs/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2083 add SidecarState to test builder
  test/builder/task.go
  test/builder/task_test.go
Labels: approved, cla: yes, lgtm, size/M

#2090 Correct the wrong MD format for document: podTemplates
  docs/podtemplates.md
Labels: approved, cla: yes, lgtm, size/XS

#2091 Fix spelling errors
  test/pullrequest/e2e_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2092 PipelineTask Timeout e2e Test
  test/builder/pipeline.go
  test/builder/pipeline_test.go
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/L

#2075 Add ContainerState and ContainerName for Sidecars
  pkg/apis/pipeline/v1alpha2/taskrun_types.go
  pkg/apis/pipeline/v1alpha2/zz_generated.deepcopy.go
  pkg/pod/entrypoint.go
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/builder/sidecar.go
  test/builder/task.go
  test/builder/task_test.go
  test/sidecar_test.go
Labels: approved, cla: yes, lgtm, size/L

#2098 Add group information on deepcopy generation 🦌
  hack/generate-groups.sh
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#2101 Increase PipelineTask Timeout by 10s in e2e Test
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2108 Fix Broken Link and Typo for LimitRange Docs
  docs/pipelineruns.md
  docs/taskruns.md
Labels: approved, cla: yes, lgtm, size/XS

#2109 Make third_party folder as generated for GitHub ⚙
  .gitattributes
Labels: approved, cla: yes, lgtm, size/XS

#2044 Allow disabling implicit HOME overwrite
  config/config-feature-flags.yaml
  docs/developers/README.md
  docs/install.md
  docs/taskruns.md
  go.mod
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: approved, cla: yes, lgtm, needs-rebase, size/L

#2115 Add handling of working directory
  config/config-feature-flags.yaml
  docs/install.md
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: approved, cla: yes, lgtm, size/M

#2118 Refactoring to use a lightweight image
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2122 Increase TaskTimeout in PipelineTaskTimout Test
  test/timeout_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2103 Move Resources implementation to their package 🎗
  cmd/imagedigestexporter/main.go
  cmd/kubeconfigwriter/main.go
  hack/update-codegen.sh
  pkg/apis/pipeline/v1alpha1/resource_types.go
  pkg/apis/pipeline/v1alpha1/storage_resource.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/resource/resource.go
  pkg/apis/resource/v1alpha1/cloudevent/cloud_event_resource.go
  pkg/apis/resource/v1alpha1/cloudevent/cloud_event_resource_test.go
  pkg/apis/resource/v1alpha1/cluster/cluster_resource.go
  pkg/apis/resource/v1alpha1/cluster/cluster_resource_test.go
  pkg/apis/resource/v1alpha1/git/git_resource.go
  pkg/apis/resource/v1alpha1/git/git_resource_test.go
  pkg/apis/resource/v1alpha1/image/image_resource.go
  pkg/apis/resource/v1alpha1/image/image_resource_test.go
  pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource.go
  pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource_test.go
  pkg/apis/resource/v1alpha1/storage/artifact_bucket.go
  pkg/apis/resource/v1alpha1/storage/artifact_bucket_test.go
  pkg/apis/resource/v1alpha1/storage/artifact_pvc.go
  pkg/apis/resource/v1alpha1/storage/artifact_pvc_test.go
  pkg/apis/resource/v1alpha1/storage/build_gcs.go
  pkg/apis/resource/v1alpha1/storage/build_gcs_test.go
  pkg/apis/resource/v1alpha1/storage/gcs.go
  pkg/apis/resource/v1alpha1/storage/gcs_test.go
  pkg/apis/resource/v1alpha1/storage/secret.go
  pkg/apis/resource/v1alpha1/storage/storage.go
  pkg/apis/resource/v1alpha1/storage/zz_generated.deepcopy.go
  pkg/artifacts/artifact_storage_test.go
  pkg/artifacts/artifacts_storage.go
  pkg/reconciler/pipelinerun/config/store.go
  pkg/reconciler/pipelinerun/resources/conditionresolution.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/cloudevent/cloud_event_controller.go
  pkg/reconciler/taskrun/resources/image_exporter.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/resources/input_resources.go
  pkg/reconciler/taskrun/resources/output_resource.go
  pkg/reconciler/taskrun/resources/output_resource_test.go
  pkg/reconciler/taskrun/taskrun.go
  third_party/github.com/hashicorp/errwrap/errwrap_test.go
  third_party/github.com/hashicorp/go-multierror/append_test.go
  third_party/github.com/hashicorp/go-multierror/flatten_test.go
  third_party/github.com/hashicorp/go-multierror/format_test.go
  third_party/github.com/hashicorp/go-multierror/multierror_test.go
  third_party/github.com/hashicorp/go-multierror/prefix_test.go
  third_party/github.com/hashicorp/go-multierror/sort_test.go
  third_party/github.com/hashicorp/golang-lru/2q_test.go
  third_party/github.com/hashicorp/golang-lru/arc_test.go
  third_party/github.com/hashicorp/golang-lru/lru_test.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_test.go
Labels: approved, area/api, cla: yes, kind/cleanup, lgtm, size/XXL
