Repository tektoncd/pipeline, pull requests merged in 2020-08, with the labels that each got.

#2991 Add .status.extraFields to the RunStatus type
  pkg/apis/pipeline/v1alpha1/run_types.go
  pkg/apis/pipeline/v1alpha1/run_types_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
Labels: approved, area/api, kind/misc, lgtm, release-note-none, size/M

#3042 Add kodata for the nop image
  cmd/nop/kodata/HEAD
  cmd/nop/kodata/LICENSE
  cmd/nop/kodata/refs
  cmd/nop/kodata/third_party
Labels: approved, kind/misc, lgtm, release-note, size/XS

#3043 Add v0.15.0 links to docs and examples
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3041 Add the nop image to the nightly pipeline release
  tekton/release-pipeline-nightly.yaml
Labels: approved, kind/misc, lgtm, release-note, size/XS

#3017 Add context variables for PipelineRun & TaskRun UIDs and add validation for all context variables
  docs/variables.md
  examples/v1beta1/pipelineruns/using_context_variables.yaml
  examples/v1beta1/taskruns/using_context_variables.yaml
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
Labels: approved, kind/feature, lgtm, release-note, size/L

#3046 Add v0.14.3 links to docs and examples
  README.md
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#3028 Deprecate PipelineRun.Spec.ServiceAccountNames 🦌
  docs/deprecations.md
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, kind/cleanup, lgtm, release-note, size/M

#2967 PodSecurityPolicy Config fixes to allow runnning in restricted envs.
  config/101-podsecuritypolicy.yaml
  config/200-clusterrole.yaml
  config/200-role.yaml
  config/controller.yaml
  config/webhook.yaml
Labels: approved, kind/bug, lgtm, release-note, size/S

#3053 Include More Details on Pod Deletion for Cancelled/Timed Out TaskRuns
  docs/taskruns.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/S

#3055 Ensure pullrequest-init is based on a root image
  .ko.yaml
  examples/v1beta1/taskruns/pullrequest_input_copystep_output.yaml
  tekton/publish.yaml
Labels: approved, kind/bug, lgtm, needs-cherry-pick, release-note, size/M

#3056 Cherry-pick "Ensure pullrequest-init is based on a root image"
  .ko.yaml
  examples/v1beta1/taskruns/pullrequest_input_copystep_output.yaml
  tekton/publish.yaml
Labels: do-not-merge/hold, kind/bug, release-note-none, size/M

#3058 Remove the pkg/logging directory.
  cmd/kubeconfigwriter/main.go
  pkg/logging/config.go
  pkg/pod/status_test.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/termination/write_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#2965 Cleanup some code in artifact storage.
  pkg/apis/resource/v1alpha1/storage/artifact_pvc.go
  pkg/apis/resource/v1alpha1/storage/storage.go
  pkg/artifacts/artifacts_storage.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#3062 Add links to v0.15.1 docs
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3061 fix TestTaskRunStatus e2e test to run on s390x
  test/taskrun_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/XS

#3065 Update Docker Desktop setup and separate out MiniKube setup
  DEVELOPMENT.md
  docs/tutorial.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/M

#3071 fix(substition): fix configmap and secret volume param substition
  docs/variables.md
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/S

#2943 Add initial documentation for Runs
  docs/README.md
  docs/runs.md
Labels: approved, kind/documentation, lgtm, release-note, size/L

#3084 Add docs link for 0.15.2
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3074 Fix small typo in install doc for default workspace config
  docs/install.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#3079 Make this example actually run 🏃
  examples/v1beta1/taskruns/task-result.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#3077 Separate Step and Sidecar types
  .gitignore
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/pod/script.go
  pkg/pod/script_test.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, release-note-none, size/M

#3066 Rewrite the "Authentication" doc for clarity and flow.
  docs/auth.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XL

#3095 Fix broken link in auth.md
  docs/auth.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3096 Validate missing volume configs in Workspace Bindings
  pkg/apis/pipeline/v1alpha1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/workspace_validation.go
Labels: approved, kind/bug, lgtm, release-note, size/M

#3093 fix(typo): fix typos in docs
  DEVELOPMENT.md
  docs/auth.md
  docs/conditions.md
  docs/container-contract.md
  docs/events.md
  docs/install.md
  docs/pipelines.md
  docs/resources.md
  docs/variables.md
  roadmap.md
Labels: approved, kind/misc, lgtm, ok-to-test, release-note, size/S

#3101 Add yamllint check and fix errors
  config/201-clusterrolebinding.yaml
  config/config-artifact-bucket.yaml
  config/config-defaults.yaml
  examples/v1beta1/pipelineruns/pipelinerun-with-extra-params.yaml
  examples/v1beta1/pipelineruns/using_context_variables.yaml
  examples/v1beta1/taskruns/creds-init-only-mounts-provided-credentials.yaml
  examples/v1beta1/taskruns/run-steps-as-non-root.yaml
  test/presubmit-tests.sh
Labels: approved, kind/misc, lgtm, release-note, size/M

#3002 Bump controller's required image versions
  config/controller.yaml
Labels: approved, cncf-cla: yes, kind/misc, lgtm, release-note, size/XS

#3107 Add multiarch specific fixes to the pipeline tests
  test/examples_test.go
  test/git_checkout_test.go
  test/init_test.go
  test/kaniko_task_test.go
  test/multiarch_utils.go
  test/pipelinerun_test.go
  test/registry_test.go
  test/taskrun_test.go
Labels: approved, kind/misc, lgtm, ok-to-test, release-note, size/L

#2902 Use `ko://` in e2e tests to exercices current code 🙃
  examples/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml
  examples/v1beta1/pipelineruns/pipelinerun.yaml
  test/.ko.yaml
Labels: approved, area/testing, kind/bug, lgtm, release-note-none, size/S

#2975 Add URL to the ResourcesResults returned by resources.
  cmd/git-init/main.go
  cmd/imagedigestexporter/main.go
  docs/resources.md
  test/kaniko_task_test.go
  test/v1alpha1/kaniko_task_test.go
Labels: approved, kind/feature, lgtm, release-note, size/M

#3006 Add Git LFS Support to build-base image used by git-init to solve #2997
  images/Dockerfile
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/XS

#3069 Allow skipping some YAML tests
  test/examples_test.go
Labels: approved, area/testing, kind/misc, lgtm, release-note-none, size/S

#3114 Update Openshift installation documentation
  docs/install.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3073 Fix an error formatting in taskrun reconciler
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#2826 adding metadata to taskSpec in PipelineTask
  docs/pipelineruns.md
  examples/v1beta1/pipelineruns/pipelinerun-with-pipelinespec-and-taskspec.yaml
  internal/builder/v1beta1/pipeline.go
  internal/builder/v1beta1/pipeline_test.go
  pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  test/retry_test.go
Labels: approved, kind/feature, lgtm, release-note, size/L

#3130 Add concurrency limit to roadmap
  roadmap.md
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3128 Allow to specify target cluster architecture for tests
  test/README.md
  test/multiarch_utils.go
Labels: approved, kind/misc, lgtm, ok-to-test, release-note, size/S

#3088 Update TaskRun Step States After Cancellation or Timeout
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/cancel_test.go
  test/timeout_test.go
Labels: approved, kind/feature, lgtm, release-note, size/L

#3143 Remove /bin/ash from examples
  examples/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml
  examples/v1beta1/pipelineruns/pipelinerun.yaml
Labels: approved, kind/misc, lgtm, release-note, size/XS

#3147 Add documentation on how to install nightly releases.
  docs/install.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS
