Repository tektoncd/pipeline, pull requests merged in 2020-12, with the labels that each got.

#3558 Fix duplicate TaskRuns when Pipeline/PipelineRun labels are changed
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#3560 Fix PipelineRun serviceAccountNames for finally tasks
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/L

#3574 Do not set the gitconfig option globally
  pkg/git/git.go
Labels: approved, kind/misc, lgtm, release-note, size/XS

#3573 Add disable-creds-init property for feature-flags setting
  docs/install.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#3572 pkg/apis: remove duplicate MergeStepsWithStepTemplate function
  pkg/apis/pipeline/v1alpha1/merge.go
  pkg/apis/pipeline/v1alpha1/merge_test.go
  pkg/apis/pipeline/v1alpha1/task_validation.go
Labels: approved, kind/misc, lgtm, release-note-none, size/L

#3575 pkg/apis: refactor GetTaskRunSpecs function
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, kind/misc, lgtm, release-note-none, size/M

#3579 pkg/apis: remove duplicate substitution code.
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/substitution.go
  pkg/apis/pipeline/v1beta1/when_types.go
Labels: approved, kind/misc, lgtm, release-note-none, size/L

#3578 pkg/apis: unexport ApplyContainerReplacements
  pkg/apis/pipeline/v1beta1/container_replacements.go
  pkg/apis/pipeline/v1beta1/container_replacements_test.go
  pkg/apis/pipeline/v1beta1/sidecar_replacements.go
  pkg/apis/pipeline/v1beta1/step_replacements.go
Labels: approved, kind/misc, lgtm, release-note-none, size/L

#3583 retrieving deps outside of dag.build
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/reconciler/pipeline/dag/dag.go
  pkg/reconciler/pipeline/dag/dag_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: approved, kind/misc, lgtm, release-note-none, size/M

#3577 pkg/apis: use pod.Template instead of v1beta1.PodTemplate
  internal/builder/v1beta1/pipeline.go
  internal/builder/v1beta1/pipeline_test.go
  internal/builder/v1beta1/task.go
  internal/builder/v1beta1/task_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/serviceaccount_test.go
Labels: approved, kind/misc, lgtm, release-note-none, size/M

#3576 tracker: use TrackReference instead of deprecated Track function
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/misc, lgtm, release-note-none, size/L

#3589 pkg/apis: rename {Task,Pipeline}Interface into *Object
  pkg/apis/pipeline/v1alpha1/cluster_task_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_interface.go
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/task_interface.go
  pkg/apis/pipeline/v1alpha1/task_types.go
  pkg/apis/pipeline/v1beta1/cluster_task_types.go
  pkg/apis/pipeline/v1beta1/pipeline_interface.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/task_interface.go
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinespec.go
  pkg/reconciler/pipelinerun/resources/pipelinespec_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
Labels: approved, kind/misc, lgtm, release-note-none, size/L

#3601 Do not allow use of deprecated Conditions with custom tasks
  docs/pipelines.md
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, kind/feature, lgtm, release-note, size/S

#3582 Add a "dropNetworking" function and unit tests to the runner package.
  cmd/entrypoint/namespaces.go
  cmd/entrypoint/namespaces_linux.go
  cmd/entrypoint/namespaces_test.go
Labels: approved, kind/feature, lgtm, release-note-none, size/L

#3599 Updates to the HA document
  config/config-leader-election.yaml
  docs/enabling-ha.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#3613 Revert "Add a "dropNetworking" function and unit tests to the runner package
  cmd/entrypoint/namespaces.go
  cmd/entrypoint/namespaces_linux.go
  cmd/entrypoint/namespaces_test.go
Labels: approved, kind/bug, lgtm, release-note-none, size/L

#3616 Revert "Revert "Add a "dropNetworking" function and unit tests to the…
  cmd/entrypoint/namespaces.go
  cmd/entrypoint/namespaces_linux.go
  cmd/entrypoint/namespaces_test.go
Labels: approved, kind/feature, lgtm, release-note-none, size/L

#3622 Fix missing "s" in pod template docs
  docs/podtemplates.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3620 Add Jerop as an owner 🎉
  OWNERS_ALIASES
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3615 Add v0.19.0 to the README
  README.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#3611 Run controller and webhook also as non-root group. Drop capabilities.
  config/controller.yaml
  config/webhook.yaml
Labels: approved, kind/misc, lgtm, ok-to-test, release-note-none, size/XS

#3632 Fix integration test failures in dind.
  examples/v1alpha1/taskruns/dind-sidecar.yaml
  examples/v1beta1/taskruns/dind-sidecar.yaml
Labels: approved, kind/failing-test, lgtm, release-note-none, size/XS

#3629 Add a "set -e" to the dind-sidecar test script.
  examples/v1alpha1/taskruns/dind-sidecar.yaml
  examples/v1beta1/taskruns/dind-sidecar.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#3621 build: run ko resolve on build presubmit 🙃
  test/presubmit-tests.sh
Labels: approved, kind/misc, lgtm, release-note, size/XS

#3634 Fix broken link in doc
  docs/enabling-ha.md
  docs/tekton-controller-performance-configuration.md
Labels: approved, kind/bug, lgtm, release-note, size/S

#3639 Change leader-election RBAC to be namespaced
  config/200-clusterrole.yaml
  config/200-role.yaml
  config/201-clusterrolebinding.yaml
  config/201-rolebinding.yaml
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/M

#3640 Remove v1beta1 from possible AdmissionReview versions
  config/500-webhooks.yaml
Labels: approved, kind/cleanup, lgtm, ok-to-test, release-note, size/XS

#3633 Add SYSTEM_NAMESPACE introduction in test README
  test/README.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#3636 Improve documentation around variable behaviour and gotchas
  docs/README.md
  docs/pipelines.md
  docs/tasks.md
  docs/variables.md
Labels: approved, kind/documentation, lgtm, release-note, size/M
