Repository tektoncd/pipeline, pull requests merged in 2020-04, with the labels that each got.

#2216 config: prefixes image names with ko:// scheme
  config/controller.yaml
  config/webhook.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2312 config: prefixes image names with ko:// scheme 📠
  config/controller.yaml
Labels: approved, cla: yes, lgtm, size/S

#2315 Add Header to Workspaces Doc for Website
  docs/auth.md
  docs/conditions.md
  docs/container-contract.md
  docs/labels.md
  docs/logs.md
  docs/metrics.md
  docs/migrating-from-knative-build.md
  docs/podtemplates.md
  docs/resources.md
  docs/workspaces.md
Labels: approved, cla: yes, lgtm, size/S

#2313 Fix link in install doc
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#2133 Add `--upgrade` to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2317 Rewrite the `Tasks` documentation for clarity and flow.
  docs/tasks.md
Labels: approved, cla: yes, lgtm, size/XL

#2333 Fix default-timeout from config not correctly set 😓
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults.go
Labels: approved, cla: yes, kind/bug, lgtm, size/S

#2178 Add pipeline results
  docs/pipelineruns.md
  docs/pipelines.md
  examples/v1beta1/pipelineruns/pipelinerun-results.yaml
  go.mod
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/param_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/resultref.go
  pkg/apis/pipeline/v1beta1/resultref_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  pkg/reconciler/taskrun/taskrun.go
  test/builder/pipeline.go
Labels: approved, cla: yes, lgtm, size/XXL

#2275 Update roadmap for 2020 🛣️
  README.md
  roadmap-2019.md
  roadmap.md
Labels: approved, cla: yes, lgtm, size/L

#2231 Doc about migrating from v1alpha1 to v1beta1
  docs/migrating-v1alpha1-to-v1beta1.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/L

#2340 Add labels to namespaces created during end to end tests
  test/init_test.go
  test/v1alpha1/init_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2347 Correct unavailable sample for LimitRanges
  examples/v1beta1/pipelineruns/no-ci/limitrange.yaml
  examples/v1beta1/taskruns/no-ci/limitrange.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2348 Update year that rolebinding was created
  config/201-rolebinding.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2349 Update README with 0.11.1 docs links
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#2350 Add link from migrate doc to GCS task in catalog
  docs/migrating-v1alpha1-to-v1beta1.md
Labels: approved, cla: yes, kind/documentation, lgtm

#2351 Add a link to the v1alpha1 migration doc
  README.md
Labels: approved, cla: yes, lgtm, needs-cherry-pick, size/S

#2352 Add a link to the Workspaces doc from docs/README.md
  docs/README.md
Labels: approved, cla: yes, lgtm, needs-cherry-pick, size/XS

#2353 Update dev docs with inverted resources/inputs/outputs
  docs/developers/README.md
Labels: approved, cla: yes, lgtm, size/S

#2356 Update guide to install tools and set up GCP
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2358 Document Tekton's Many Variables
  docs/README.md
  docs/pipelines.md
  docs/tasks.md
  docs/variables.md
Labels: approved, cla: yes, kind/documentation, lgtm, needs-cherry-pick, size/L

#2360 Fix references to API version in Tasks and PipelineRuns docs
  docs/pipelineruns.md
  docs/tasks.md
Labels: approved, cla: yes, lgtm, size/S

#2354 Handle conditions in task result substitution
  examples/v1beta1/pipelineruns/pipeline-result-conditions.yaml
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/reconciler/pipeline/dag/dag_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/taskrun/resources/apply.go
Labels: approved, cla: yes, lgtm, size/L

#2302 Add e2e Test for when LimitRange Present in Namespace
  test/pipelinerun_test.go
Labels: approved, cla: yes, lgtm, size/M

#2363 Make feature-flags config map name customizable
  config/controller.yaml
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2379 Correct format for document of "task"
  docs/tasks.md
Labels: approved, cla: yes, lgtm, size/XS

#2310 Makefile: initial setup 🌮
  .gitignore
  Makefile
Labels: approved, cla: yes, lgtm, size/L

#2369 PipelineRun Cancellation is not working
  go.mod
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/cancel_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
  test/cancel_test.go
Labels: approved, cla: yes, lgtm, size/M

#2384 Add docs on customizing config maps names
  docs/install.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2366 Improvement in the kubeconfigwriter
  cmd/kubeconfigwriter/main.go
  docs/resources.md
  docs/variables.md
  pkg/apis/resource/v1alpha1/cluster/cluster_resource.go
  pkg/apis/resource/v1alpha1/cluster/cluster_resource_test.go
  pkg/apis/resource/v1alpha1/pipelineresource_validation.go
  pkg/apis/resource/v1alpha1/pipelineresource_validation_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2378 Validate PullRequest resource secrets fields
  pkg/apis/resource/v1alpha1/pipelineresource_validation.go
  pkg/apis/resource/v1alpha1/pipelineresource_validation_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2368 e2e tests - fix helm deploy test
  test/gohelloworld/gohelloworld-chart/values.yaml
  test/helm_task_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2359 Mark PipelienResourceBinding as inlined 🏑
  pkg/apis/pipeline/v1beta1/taskrun_types.go
Labels: approved, cla: yes, lgtm, needs-cherry-pick, size/XS

#2326 Add volumeClaimTemplate as a Workspace volume source
  docs/workspaces.md
  examples/v1beta1/pipelineruns/workspace-from-volumeclaimtemplate.yaml
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/apis/pipeline/v1beta1/workspace_types.go
  pkg/apis/pipeline/v1beta1/workspace_validation.go
  pkg/apis/pipeline/v1beta1/workspace_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/volumeclaim/pvchandler.go
  pkg/reconciler/volumeclaim/pvchandler_test.go
  test/builder/pipeline.go
  test/builder/task.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#2346 Split controller RBAC into cluster-wide and tenant roles
  config/200-clusterrole.yaml
  config/200-role.yaml
  config/201-clusterrolebinding.yaml
  config/201-rolebinding.yaml
  docs/developers/README.md
Labels: approved, cla: yes, lgtm, size/L

#2392 Change signature on pr.GetOwnerReference()
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/artifacts/artifact_storage_test.go
  pkg/artifacts/artifacts_storage.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2393 Fix task result substitution (#2387)
  examples/v1beta1/pipelineruns/pipelinerun-results-with-params.yml
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/resultref.go
Labels: approved, cla: yes, lgtm, size/L

#2394 Verify status fields before uploading PullRequest
  pkg/pullrequest/api.go
  pkg/pullrequest/api_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2390 Add tekton.dev/clusterTask in taskrun of clustertask
  docs/labels.md
  pkg/apis/pipeline/register.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/M

#2406 Fix default-timeout-minutes from Config Not Being Set Correctly for v1alpha1
  pkg/apis/pipeline/v1alpha1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1alpha1/taskrun_defaults.go
Labels: approved, cla: yes, lgtm, size/S

#2402 Remove namespaces/list from tenant ClusterRole
  config/200-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2405 Add config-leader-election configmap
  config/200-role.yaml
  config/controller.yaml
  config/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2403 Reference utility images from Dockerhub by digest
  config/controller.yaml
Labels: approved, cla: yes, lgtm, size/S

#2386 Add validation for "cencel" of "taskrun" and "pipelinerun"
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#2400 Add comment linking configmap names in deployments to names in role
  config/controller.yaml
  config/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2355 Rewrite the Pipelines documentation for clarity and flow.
  docs/pipelines.md
Labels: approved, cla: yes, lgtm, needs-cherry-pick, size/L

#2414 Mark vendor/ folder as generated 🧞
  .gitattributes
Labels: approved, cla: yes, lgtm, size/XS

#2365 Consolidate cancel and timeout logic
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/reconciler/pipelinerun/metrics_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/cancel.go
  pkg/reconciler/taskrun/cancel_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/taskrun/timeout_check.go
  pkg/reconciler/taskrun/timeout_check_test.go
Labels: approved, cla: yes, lgtm, size/XL

#2427 Add links for 0.11.2 docs
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#2418 Try to make path usage less confusing 🛣️
  docs/tutorial.md
  examples/v1beta1/pipelineruns/pipelinerun.yaml
Labels: approved, cla: yes, lgtm, size/S

#2397 Update install.md to add --cluster-version=latest
  docs/install.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2431 Correct order of TaskRun step status when there are unnamed steps
  pkg/pod/status.go
Labels: approved, cla: yes, lgtm, size/XS

#2422 Change IsComplete to IsSuccess for IsSuccess() Code Comment
  pkg/reconciler/pipelinerun/resources/conditionresolution.go
Labels: approved, cla: yes, lgtm, size/XS

#2342 [master] Fix spelling errors
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2325 Add HostNetwork Support to PodTemplate in TaskRun Pod
  docs/taskruns.md
  pkg/apis/pipeline/pod/template.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: approved, cla: yes, lgtm, size/M

#2320 Introduce optional "refspec" to git PipelineResource, refactor
  cmd/git-init/main.go
  docs/resources.md
  pkg/apis/pipeline/v1alpha1/pipeline_resource_types.go
  pkg/apis/resource/v1alpha1/git/git_resource.go
  pkg/apis/resource/v1alpha1/git/git_resource_test.go
  pkg/git/git.go
  test/git_checkout_test.go
  test/v1alpha1/git_checkout_test.go
Labels: approved, cla: yes, kind/feature, lgtm, ok-to-test, size/L

#2429 Set "startedAt" in skipped case
  pkg/entrypoint/entrypointer.go
Labels: approved, cla: yes, lgtm, size/S

#2447 Document PipelineResource's Alpha State
  docs/resources.md
Labels: approved, cla: yes, lgtm, size/M

#2451 Correct unavailable link in pipeliines.md
  docs/pipelines.md
Labels: approved, cla: yes, lgtm, size/S

#2456 Re-add tekton.dev/task label to taskruns from ClusterTasks
  docs/labels.md
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2459 Reorganizes the two `results` sections.
  docs/pipelines.md
Labels: approved, cla: yes, lgtm, size/M

#2457 Add propagated labels to API Compatibility Policy
  api_compatibility_policy.md
Labels: approved, cla: yes, lgtm, size/XS

#2460 Improve documentation about volumeClaimTemplate workspaces
  docs/workspaces.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2468 Fix PipelineTask timeout not correctly set 💦
  pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  pkg/apis/pipeline/v1alpha1/pipeline_conversion_test.go
  test/timeout_test.go
Labels: approved, cla: yes, kind/bug, lgtm, needs-cherry-pick, size/XS

#2341 Rewrite the TaskRuns documentation for clarity and flow.
  docs/taskruns.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/L

#2470 Add version labels on CRDs 🏷
  config/300-clustertask.yaml
  config/300-condition.yaml
  config/300-pipeline.yaml
  config/300-pipelinerun.yaml
  config/300-resource.yaml
  config/300-task.yaml
  config/300-taskrun.yaml
Labels: approved, lgtm, size/S

#2453 Allow omitting metadata in volumeclaimtemplate
  pkg/reconciler/volumeclaim/pvchandler.go
  pkg/reconciler/volumeclaim/pvchandler_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2475 Fix artifact log
  pkg/artifacts/artifacts_storage.go
Labels: approved, lgtm, size/XS

#2478 Add DAG tests for v1beta1 as well as v1alpha1 📈
  pkg/reconciler/pipeline/dag/dagv1beta1_test.go
Labels: approved, lgtm, size/XL

#2479 WIP 0.11.3 Prerelease testing
  pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  pkg/apis/pipeline/v1alpha1/pipeline_conversion_test.go
  test/timeout_test.go
Labels: do-not-merge/work-in-progress, size/XS

#2444 Dereference the TaskSpec into TaskRun.Status.
  docs/taskruns.md
  go.mod
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/taskrun_test.go
Labels: approved, cla: yes, lgtm, size/M

#2484 Fix Broken Link for Task Workspace in Docs
  docs/tasks.md
Labels: approved, lgtm, size/XS

#2428 Provide a "cheat sheet" for official Tekton Pipelines releases
  tekton/release-cheat-sheet.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/L

#2486 Fixing codegen scripts 😅
  hack/generate-groups.sh
  hack/generate-knative.sh
  hack/update-codegen.sh
Labels: approved, lgtm, size/S

#2481 Add doc links for 0.11.3
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#2485 Temporary disable yaml linting 😓
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#2421 Split reconcile into prepare and reconcile
  pkg/pod/status.go
  pkg/reconciler/event.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/cancel_test.go
  test/init_test.go
  test/pipelinerun_test.go
  test/v1alpha1/pipelinerun_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/L

#2489 Dereference the PipelineSpec into PipelineRun.Status
  docs/pipelineruns.md
  go.mod
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/M

#2496 Make webhook secret configurable
  cmd/webhook/main.go
  config/webhook.yaml
Labels: approved, lgtm, size/XS

#2395 Refactor to the remote image library and task references
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/remote/oci.go
  pkg/remote/oci/resolver.go
  pkg/remote/oci/resolver_test.go
  pkg/remote/oci_test.go
  pkg/remote/resolver.go
  test/builder/task.go
  test/builder/task_test.go
  test/remote.go
  test/remote_test.go
  third_party/github.com/hashicorp/errwrap/go.mod
Labels: approved, cla: yes, lgtm, size/XXL

#2502 Also document volumeClaimTemplate for TaskRun
  README.md
  docs/workspaces.md
Labels: approved, lgtm, ok-to-test, size/S

#2491 Add subPath to WorkspacePipelineTaskBinding
  docs/workspaces.md
  examples/v1beta1/pipelineruns/pipelinerun-using-different-subpaths-of-workspace.yaml
  pkg/apis/pipeline/v1alpha1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/workspace_types.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  test/builder/pipeline.go
  test/builder/pipeline_test.go
  test/v1alpha1/workspace_test.go
Labels: approved, lgtm, ok-to-test, size/L

#2495 Validate result.name for Task
  pkg/apis/pipeline/v1beta1/resultref.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: approved, lgtm, size/M

#2500 Add default for condition
  pkg/apis/pipeline/v1alpha1/condition_defaults.go
  pkg/apis/pipeline/v1alpha1/condition_defaults_test.go
Labels: approved, lgtm, size/L

#2506 Add variable substitution for PVC name
  docs/variables.md
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
Labels: approved, lgtm, ok-to-test, size/S

#2511 Mark step and sidecar state inline
  pkg/apis/pipeline/v1beta1/taskrun_types.go
Labels: approved, lgtm, size/S

#2515 Add doc links for the v0.12.0 release
  README.md
Labels: approved, lgtm, size/XS
