Repository tektoncd/pipeline, pull requests merged in 2020-06, with the labels that each got.

#2722 Remove a bunch of dead logic in the base.
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/taskrun/controller.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, size/M

#2718 Add results linking to execution order docs 🔗
  docs/pipelines.md
Labels: approved, kind/documentation, lgtm, size/XS

#2630 Add Node Affinity for TaskRuns that share PVC workspace
  config/200-clusterrole.yaml
  docs/install.md
  docs/labels.md
  docs/tasks.md
  docs/workspaces.md
  examples/v1beta1/pipelineruns/pipeline-run-with-parallel-tasks-using-pvc.yaml
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/workspace/affinity_assistant_names.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/XL

#2723 Fix unavaiable sidecar link
  docs/tasks.md
Labels: approved, kind/bug, lgtm, size/XS

#2716 Update development guide to recommend ko v0.5.0
  DEVELOPMENT.md
Labels: approved, kind/documentation, lgtm, size/XS

#2727 Pin base Dockerfile image to 3.12
  images/Dockerfile
Labels: approved, kind/bug, lgtm, size/XS

#2683 Propagate TaskRunSpecs to created TaskRuns
  examples/v1beta1/pipelineruns/no-ci/pipelinerun-taskrunspecs.yaml
  internal/builder/v1beta1/pipeline.go
  internal/builder/v1beta1/task.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, kind/bug, lgtm, size/L

#2730 events: rename EmitEvent and EmitErrorEvent 🌲
  pkg/reconciler/events/event.go
  pkg/reconciler/events/event_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/cleanup, lgtm, size/M

#2743 Propagate NodeSelector and Tolerations to Affinity Assistant
  docs/install.md
  docs/workspaces.md
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
Labels: approved, kind/feature, lgtm, size/M

#2158 Optimize start time for TaskRuns with no sidecars
  config/config-feature-flags.yaml
  docs/install.md
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: approved, cla: yes, kind/misc, lgtm, size/L

#2717 Use PipelineWorkspaceDeclaration instead of WorkspacePipelineDeclaration 👷‍♀️
  internal/builder/v1alpha1/pipeline.go
  internal/builder/v1alpha1/pipeline_test.go
  internal/builder/v1beta1/pipeline.go
  internal/builder/v1beta1/pipeline_test.go
  pkg/apis/pipeline/v1alpha1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1alpha1/pipeline_types.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/workspace_types.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/workspace_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  test/builder/pipeline_test.go
  test/workspace_test.go
Labels: approved, kind/cleanup, lgtm, size/M

#2749 Use a helper for setting the Succeeded condition on PipelineRun.
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, kind/bug, lgtm, size/L

#2750 Add disable-affinity-assistant feature flag to config
  config/config-feature-flags.yaml
Labels: approved, kind/misc, lgtm, size/XS

#2754 [master] Fix spelling errors
  pkg/pod/pod_test.go
Labels: approved, kind/misc, lgtm, size/XS

#2757 Pin to Alpine 3.11 so upgrade doesnt try to delete /var/run 📌
  images/Dockerfile
Labels: approved, kind/bug, lgtm, size/XS

#2547 Allow for setting imagePullSecrets
  docs/podtemplates.md
  pkg/apis/pipeline/pod/template.go
  pkg/apis/pipeline/pod/zz_generated.deepcopy.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/M

#2744 Update example paths and yaml names in README
  examples/README.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#2733 Refactoring in sidecar test
  test/sidecar_test.go
  test/v1alpha1/sidecar_test.go
Labels: approved, kind/flake, lgtm, size/S

#2690 Improve performance of pipeline results
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#2765 Updates to release docs 📝
  tekton/README.md
Labels: approved, kind/documentation, lgtm, size/M

#2775 Fix missing apostrophe in tasks.md
  docs/tasks.md
Labels: approved, kind/misc, lgtm, size/XS

#2650 adding finally type (without implementation) at the pipeline level
  docs/pipelines.md
  pkg/apis/pipeline/v1alpha1/conversion_error.go
  pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  pkg/apis/pipeline/v1alpha1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: approved, kind/feature, lgtm, size/XXL

#2776 Fix typo in install.md
  docs/install.md
Labels: approved, kind/misc, lgtm, ok-to-test, size/XS

#2762 Disentangle metric reporting from the actual reconciler.
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/metrics.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/metrics.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/bug, lgtm, size/M

#2781 Remove tag+digest on shell-image 🍶
  config/controller.yaml
Labels: approved, kind/bug, lgtm, needs-cherry-pick, size/XS

#2780 Add links to 0.13 tagged docs
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#2677 Add support for more cloud events
  docs/pipelineruns.md
  docs/taskruns.md
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/events/cloudevent/cloudevent.go
  pkg/reconciler/events/cloudevent/cloudevent_test.go
  pkg/reconciler/events/cloudevent/interface.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/reconciler_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/timeout_test.go
  test/v1alpha1/cancel_test.go
  test/v1alpha1/timeout_test.go
Labels: approved, kind/feature, lgtm, size/XL

#2783 Revert "Use a helper for setting the Succeeded condition on PipelineRun."
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, kind/bug, lgtm, size/L

#2745 Lower the CPU request for the Affinity Assistant
  pkg/reconciler/pipelinerun/affinity_assistant.go
Labels: approved, kind/misc, lgtm, size/XS

#2771 Migrate the TaskRun controller to genreconciler.
  pkg/apis/config/default_test.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/store_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/controller.go
  pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go
  pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/stub/controller.go
  pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/stub/reconciler.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/testing/logger.go
  test/controller.go
Labels: approved, kind/cleanup, lgtm, size/L

#2751 Externalize Affinity Assistant image
  cmd/controller/main.go
  config/controller.yaml
  pkg/apis/pipeline/images.go
  pkg/apis/resource/v1alpha1/storage/build_gcs_test.go
  pkg/artifacts/artifact_storage_test.go
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/misc, lgtm, needs-cherry-pick, size/M

#2774 Set pipeline status when all tasks complete
  docs/events.md
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, kind/feature, lgtm, size/XL

#2803 Pass port to ssh-keyscan when known_hosts not provided
  docs/auth.md
  pkg/credentials/gitcreds/ssh.go
  pkg/credentials/gitcreds/ssh_test.go
Labels: approved, kind/bug, lgtm, size/M

#2697 Fix PipelineResource name handling.
  cmd/git-init/main.go
  cmd/imagedigestexporter/main.go
  docs/deprecations.md
  go.mod
  go.sum
  pkg/apis/pipeline/v1beta1/resource_types.go
  pkg/apis/resource/resource.go
  pkg/apis/resource/v1alpha1/cloudevent/cloud_event_resource.go
  pkg/apis/resource/v1alpha1/cloudevent/cloud_event_resource_test.go
  pkg/apis/resource/v1alpha1/cluster/cluster_resource.go
  pkg/apis/resource/v1alpha1/cluster/cluster_resource_test.go
  pkg/apis/resource/v1alpha1/git/git_resource.go
  pkg/apis/resource/v1alpha1/git/git_resource_test.go
  pkg/apis/resource/v1alpha1/image/image_resource.go
  pkg/apis/resource/v1alpha1/image/image_resource_test.go
  pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource.go
  pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource_test.go
  pkg/apis/resource/v1alpha1/storage/build_gcs.go
  pkg/apis/resource/v1alpha1/storage/build_gcs_test.go
  pkg/apis/resource/v1alpha1/storage/gcs.go
  pkg/apis/resource/v1alpha1/storage/gcs_test.go
  pkg/apis/resource/v1alpha1/storage/storage.go
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/pipelinerun/resources/conditionresolution.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/image_exporter.go
  pkg/reconciler/taskrun/resources/image_exporter_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/resources/output_resource_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/cluster_resource_test.go
  test/v1alpha1/cluster_resource_test.go
Labels: approved, kind/bug, lgtm, size/L

#2810 Remove tag+digest on shell-image 🍶
  config/controller.yaml
Labels: approved, kind/bug, lgtm, size/XS

#2809 Add links to 0.13.1 and 0.13.2 releases
  README.md
Labels: approved, kind/documentation, lgtm

#2818 Cleanup logic for API convertion errors
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/cleanup, lgtm, size/S

#2811 Add docs on creating a patch release
  tekton/README.md
Labels: approved, kind/documentation, lgtm, size/L

#2820 Add checklist item for release notes ✅
  .github/pull_request_template.md
Labels: approved, kind/documentation, lgtm, size/XS

#2719 Validate PipelineRun Parameters
  docs/pipelineruns.md
  examples/v1beta1/pipelineruns/pipelinerun-with-extra-params.yaml
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/validate_params.go
  pkg/reconciler/pipelinerun/resources/validate_params_test.go
Labels: approved, kind/feature, lgtm, size/L

#2817 Return error if there are multiple same name params
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, kind/bug, lgtm, ok-to-test, size/M

#2805 Define a common function to exit ReconcileKind
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/cleanup, lgtm, size/M

#2824 Fix an internal link to point to correct volume variable example
  docs/tasks.md
Labels: approved, kind/documentation, lgtm, size/XS

#2778 Add OWNERS_ALIASES to define teams 🥜
  OWNERS_ALIASES
Labels: approved, kind/misc, lgtm, size/M

#2841 Add the missing RBAC for leaderelection
  config/200-clusterrole.yaml
  config/200-role.yaml
  config/201-clusterrolebinding.yaml
Labels: approved, kind/bug, lgtm, size/M

#2845 Fix link to "why arent pipelineresources in beta"
  docs/migrating-v1alpha1-to-v1beta1.md
Labels: approved, kind/documentation, lgtm, size/XS

#2685 Run CI YAML Example tests using `go test`
  examples/v1alpha1/pipelineruns/clustertask-pipelinerun.yaml
  examples/v1alpha1/taskruns/clustertask.yaml
  examples/v1alpha1/taskruns/optional-resources-with-clustertask.yaml
  examples/v1beta1/taskruns/clustertask.yaml
  examples/v1beta1/taskruns/optional-resources-with-clustertask.yaml
  test/README.md
  test/clients.go
  test/e2e-common.sh
  test/e2e-tests-upgrade.sh
  test/e2e-tests-yaml.sh
  test/e2e-tests.sh
  test/examples_test.go
  test/init_test.go
Labels: approved, kind/misc, lgtm, ok-to-test, size/L

#2847 Activate SA creds before running ko
  tekton/publish.yaml
Labels: approved, kind/bug, lgtm, size/S

#2833 Add bumping catalog dependency to process of creating a release
  tekton/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#2853 adding unit tests
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, area/testing, kind/misc, lgtm, size/M

#2835 Fix git-init in case `master` is not the default branch
  docs/resources.md
  pkg/apis/resource/v1alpha1/git/git_resource.go
  pkg/apis/resource/v1alpha1/git/git_resource_test.go
  pkg/git/git.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/git_checkout_test.go
  test/v1alpha1/git_checkout_test.go
Labels: approved, kind/bug, lgtm, ok-to-test, size/L

#2849 Fix pipelinerun_taskrun_duration_seconds metric
  pkg/reconciler/taskrun/metrics.go
Labels: approved, kind/bug, lgtm, ok-to-test, size/XS

#2860 Emit event only once
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, kind/bug, lgtm, size/XS

#2782 Fix typo in conditional examples
  examples/v1alpha1/pipelineruns/conditional-pipelinerun-with-optional-resources.yaml
  examples/v1alpha1/pipelineruns/conditional-pipelinerun.yaml
  examples/v1beta1/pipelineruns/conditional-pipelinerun-with-optional-resources.yaml
  examples/v1beta1/pipelineruns/conditional-pipelinerun.yaml
Labels: approved, kind/misc, lgtm, size/XS

#2798 Use permanent errors in the pipelinerun reconciler
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#2661 implementing pipeline level finally
  docs/pipelines.md
  examples/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml
  internal/builder/v1beta1/pipeline.go
  internal/builder/v1beta1/pipeline_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  test/pipelinefinally_test.go
Labels: approved, kind/feature, lgtm, size/XXL

#2866 [master] Fix spelling errors
  test/pipelinefinally_test.go
Labels: approved, kind/misc, lgtm, size/XS

#2858 Add credentials to pipelines' roadmap
  roadmap.md
Labels: approved, area/roadmap, kind/documentation, lgtm, size/XS

#2802 Use permanent errors in the taskrun reconciler
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#2870 refactor - dropping named return value from IsDone() functions
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, kind/cleanup, lgtm, size/S

#2873 [master] Fix spelling errors
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/misc, lgtm, size/XS

#2878 Add missing quotation marks
  docs/developers/resources-labelling.md
Labels: approved, kind/documentation, lgtm, size/XS

#2869 refactor GetPipelineConditionStatus - drop unexported function isdagstopped
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#2868 Update to the latest release of the CloudEvents SDK - 2.1
  go.mod
  go.sum
  third_party/github.com/hashicorp/errwrap/errwrap_test.go
  third_party/github.com/hashicorp/go-multierror/append_test.go
  third_party/github.com/hashicorp/go-multierror/flatten_test.go
  third_party/github.com/hashicorp/go-multierror/format_test.go
  third_party/github.com/hashicorp/go-multierror/group_test.go
  third_party/github.com/hashicorp/go-multierror/multierror_test.go
  third_party/github.com/hashicorp/go-multierror/prefix_test.go
  third_party/github.com/hashicorp/go-multierror/sort_test.go
  third_party/github.com/hashicorp/golang-lru/2q_test.go
  third_party/github.com/hashicorp/golang-lru/arc_test.go
  third_party/github.com/hashicorp/golang-lru/lru_test.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_test.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/client/http_receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_validation.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/result.go
  vendor/modules.txt
Labels: approved, kind/cleanup, lgtm, size/S

#2874 Finish setting up events for pipeline runs
  docs/events.md
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, kind/feature, lgtm, size/L

#2879 .github: add multiple issues template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/free-form.md
Labels: approved, kind/misc, lgtm, size/S

#2881 Fixing typo in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS
