Repository tektoncd/pipeline, pull requests merged in 2021-07, with the labels that each got.

#4065 Update comment on RunControllerName const
  pkg/apis/pipeline/controller.go
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#4070 cleaning up task results constant
  pkg/apis/pipeline/paths.go
  pkg/pod/pod.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#3945 docs: update metrics name
  docs/metrics.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note-none, size/S

#4058 Updates to pipeline tutorial to handle skaffold Dockerfile and keep the yq syntax working
  docs/tutorial.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#4057 Merge *Run's PodTemplate with Default 🧙
  docs/podtemplates.md
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults_test.go
Labels: approved, kind/feature, lgtm, release-note, size/L

#4081 Set HOME="/tekton/home" for GCS PipelineResources
  pkg/apis/resource/v1alpha1/storage/gcs.go
  pkg/apis/resource/v1alpha1/storage/gcs_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/resources/output_resource_test.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#3857 Add debug with breakpoint onFailure to TaskRun Spec
  cmd/entrypoint/main.go
  cmd/entrypoint/waiter.go
  cmd/entrypoint/waiter_test.go
  docs/debug.md
  docs/taskruns.md
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/script.go
  pkg/pod/script_test.go
  pkg/pod/scripts_constants.go
Labels: approved, kind/feature, lgtm, release-note, size/XXL

#4077 Modify wrong equirement of kubernetes Version for Installation of v0.24.0
  docs/install.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#4073 Set fake AWS credentials on controller to workaround aws-sdk bug
  config/controller.yaml
Labels: approved, kind/misc, lgtm, release-note, size/S

#4088 Add issue link to comment in controller yaml
  config/controller.yaml
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#4045 Cleanup multi-arch tests
  test/helm_task_test.go
  test/multiarch_utils.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#4094 Fix misplaced fields in API spec
  docs/api-spec.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#4091 Add WhenExpressions to variable substitution documentation
  docs/variables.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#4095 Get default sa from configmap defaultconfigs
  test/init_test.go
Labels: approved, kind/misc, lgtm, release-note, size/S

#4100 Loosen permission checks on TestCp to handle umasks.
  cmd/entrypoint/subcommands/cp_test.go
Labels: approved, kind/bug, lgtm, release-note, size/S

#4079 cleanup - `homeDir` constant and hardcoded path
  cmd/entrypoint/main.go
  pkg/pod/pod.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#4089 updating readme to include 0.26
  README.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#4110 Take advantage of `kmeta.OwnerRefable`.
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/run_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/artifacts/artifact_storage_test.go
  pkg/artifacts/artifacts_storage.go
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/L

#4104 docs: rename `whenexpressions` to `when` expressions
  docs/conditions.md
  docs/deprecations.md
  docs/pipelineruns.md
  docs/pipelines.md
  examples/v1beta1/pipelineruns/conditional-pipelinerun-with-optional-resources.yaml
  examples/v1beta1/pipelineruns/conditional-pipelinerun-with-same-condition-refer.yaml
  examples/v1beta1/pipelineruns/conditional-pipelinerun.yaml
  examples/v1beta1/pipelineruns/demo-optional-resources.yaml
  examples/v1beta1/pipelineruns/pipeline-result-conditions.yaml
  examples/v1beta1/pipelineruns/pipelinerun-with-resourcespec.yaml
Labels: approved, kind/documentation, lgtm, release-note, size/L

#4109 minor doc fix
  docs/tasks.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#4111 Drop the tracker.
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/S

#4113 Use `controller.FilterController(&v1beta1.TaskRun{})`
  pkg/reconciler/taskrun/controller.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#4120 GoogleContainerTools/skaffold mainline branch is called 'main' other than 'master'
  docs/tutorial.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#4124 Mark webhook and controller as safe-to-evict
  config/controller.yaml
  config/webhook.yaml
  docs/enabling-ha.md
Labels: approved, kind/bug, lgtm, release-note, size/S
