Repository tektoncd/pipeline, pull requests merged in 2021-09, with the labels that each got.

#4206 Bump golangci-lint to v1.42.0 from v1.30.0.
  Makefile
  pkg/apis/pipeline/v1beta1/version_validation.go
  pkg/apis/pipeline/v1beta1/workspace_validation.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#4203 Add doc links for 0.27.2 and 0.27.3
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4204 Adjust the way `{pipeline,task}run` metrics are surfaced.
  pkg/pipelinerunmetrics/fake/fake.go
  pkg/pipelinerunmetrics/injection.go
  pkg/pipelinerunmetrics/metrics.go
  pkg/pipelinerunmetrics/metrics_test.go
  pkg/reconciler/pipelinerun/cancel_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/taskrunmetrics/fake/fake.go
  pkg/taskrunmetrics/injection.go
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#4209 Don't rely on condition ordering.
  pkg/pipelinerunmetrics/metrics.go
  pkg/taskrunmetrics/metrics.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#4208 Remove the pkg/jsonpath library.
  pkg/jsonpath/expand.go
  pkg/jsonpath/expand_test.go
Labels: approved, lgtm, size/XL, release-note, kind/cleanup

#4213 Poll for the status of Runs
  test/wait.go
Labels: approved, lgtm, size/S, release-note, kind/misc

#4128 Add script mode support to windows tasks
  cmd/controller/main.go
  config/controller.yaml
  docs/tasks.md
  pkg/apis/pipeline/images.go
  pkg/apis/pipeline/images_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/pod/pod.go
  pkg/pod/script.go
  pkg/pod/script_test.go
  test/windows_script_test.go
Labels: kind/feature, approved, lgtm, size/XL, ok-to-test, release-note

#4212 Switch the linter from golint to revive, and fix warnings.
  .golangci.yml
  cmd/webhook/main.go
  pkg/apis/pipeline/controller.go
  pkg/apis/pipeline/v1alpha1/cluster_task_conversion.go
  pkg/apis/pipeline/v1alpha1/condition_validation.go
  pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1alpha1/run_validation.go
  pkg/apis/pipeline/v1alpha1/task_conversion.go
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1alpha1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/cluster_task_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1beta1/resource_types_validation.go
  pkg/apis/pipeline/v1beta1/task_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/pullrequest/disk.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/termination/write.go
  test/controller.go
  test/v1alpha1/controller.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#4201 Add Configuration for Metrics Cardinality Simplification
  config/config-observability.yaml
  pkg/apis/config/metrics.go
  pkg/apis/config/metrics_test.go
  pkg/apis/config/store.go
  pkg/apis/config/store_test.go
  pkg/apis/config/testdata/config-observability-empty.yaml
  pkg/apis/config/testdata/config-observability-namespacelevel.yaml
  pkg/apis/config/testdata/config-observability.yaml
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/pipelinerunmetrics/injection.go
  pkg/pipelinerunmetrics/metrics.go
  pkg/pipelinerunmetrics/metrics_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/taskrunmetrics/injection.go
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#4221 Skipping the CI secret sauce 🦕
  examples/v1alpha1/taskruns/no-ci/docker-creds.yaml
  examples/v1alpha1/taskruns/no-ci/pull-private-image.yaml
  examples/v1beta1/taskruns/no-ci/docker-creds.yaml
  examples/v1beta1/taskruns/no-ci/pull-private-image.yaml
  internal/builder/v1beta1/pod.go
  test/pipelinerun_test.go
  test/v1alpha1/pipelinerun_test.go
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#4217 Support activeDeadlineSeconds for Tekton pods 🦌
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#4222 Fix Concurrency issue in the metrics
  pkg/pipelinerunmetrics/metrics.go
  pkg/taskrunmetrics/metrics.go
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#4218 Docs for Metrics Configuration
  docs/metrics.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#4168 Add controller flag to turn off built-in resolution
  cmd/controller/main.go
  config/controller.yaml
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/L, release-note, kind/misc

#4186 Converts ResultType from string to int enum
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/resource_types.go
  pkg/apis/pipeline/v1beta1/resource_types_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/pod/status_test.go
Labels: approved, lgtm, size/L, release-note, kind/cleanup

#4127 Implement implicit parameter resolution.
  config/200-role.yaml
  config/webhook.yaml
  docs/pipelineruns.md
  docs/taskruns.md
  examples/v1beta1/pipelineruns/alpha/pipelinerun-implicit-params.yaml
  examples/v1beta1/taskruns/alpha/implicit-params.yaml
  pkg/apis/pipeline/v1beta1/param_context.go
  pkg/apis/pipeline/v1beta1/param_context_test.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1beta1/task_defaults.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/validate_resources.go
  pkg/reconciler/taskrun/validate_resources_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#4176 Revamp how pipeline supports Limitranges
  docs/limitrange.md
  docs/pipelineruns.md
  docs/taskruns.md
  internal/builder/v1beta1/pod.go
  internal/builder/v1beta1/pod_test.go
  pkg/internal/limitrange/doc.go
  pkg/internal/limitrange/limitrange.go
  pkg/internal/limitrange/transformer.go
  pkg/internal/limitrange/transformer_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/resource_request.go
  pkg/pod/resource_request_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#4234 Use an Informer to list LimitRanges 🥼
  internal/builder/v1beta1/pod.go
  internal/builder/v1beta1/pod_test.go
  pkg/internal/limitrange/limitrange.go
  pkg/internal/limitrange/transformer.go
  pkg/internal/limitrange/transformer_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/controller.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/limitrange/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/limitrange/limitrange.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#4238 Revamp Tekton developer docs for /tekton paths.
  docs/developers/README.md
Labels: approved, lgtm, size/L, kind/documentation, release-note-none

#4242 Mount entrypoint volume as read-only.
  cmd/entrypoint/README.md
  docs/debug.md
  docs/developers/README.md
  internal/builder/v1beta1/container.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/script.go
  pkg/pod/script_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/cleanup

#4246 Document Alpha Features
  docs/install.md
Labels: approved, lgtm, size/S, kind/documentation, release-note

#4244 pkg/pod: simplify orderContainers returns
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#4236 Mark Downward API VolumeMount as readonly.
  pkg/pod/entrypoint.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#4252 adding links to pipeline release 0.28
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4231 Test and Document Disable Resolution Flag
  docs/developers/README.md
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note, needs-cherry-pick

#4254 include `onError` while merging step specifications with a template
  examples/v1beta1/pipelineruns/alpha/ignore-step-error.yaml
  pkg/apis/pipeline/v1beta1/merge.go
  pkg/apis/pipeline/v1beta1/merge_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note, needs-cherry-pick

#4255 enforce step timeout
  pkg/apis/pipeline/v1beta1/merge.go
  test/timeout_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note, needs-cherry-pick

#4262 Make sure images stored in registry mirrors are signed
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc
