Repository tektoncd/pipeline, pull requests merged in 2021-05, with the labels that each got.

#3909 Add a nodeAffinity rule to the controller and webhook deployments
  config/controller.yaml
  config/webhook.yaml
Labels: approved, kind/misc, lgtm, ok-to-test, release-note, size/S

#3908 Enable Bundles and Custom Tasks when feature gate is set to "alpha"
  docs/developers/README.md
  docs/install.md
  docs/taskruns.md
  examples/v1beta1/taskruns/workspace-in-sidecar.yaml
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-bundles-and-custom-tasks.yaml
  pkg/apis/config/testdata/feature-flags-enable-api-fields-overrides-bundles-and-custom-tasks.yaml
  test/custom_task_test.go
  test/gate.go
  test/tektonbundles_test.go
Labels: approved, kind/misc, lgtm, release-note, size/L

#3700 Add Step and Sidecar Workspaces feature
  DEVELOPMENT.md
  docs/install.md
  docs/workspaces.md
  examples/v1beta1/pipelineruns/alpha/isolated-workspaces.yaml
  examples/v1beta1/taskruns/alpha/authenticating-git-commands.yaml
  examples/v1beta1/taskruns/alpha/workspace-in-sidecar.yaml
  examples/v1beta1/taskruns/alpha/workspace-isolation.yaml
  hack/verify-codegen.sh
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/workspace_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
Labels: approved, kind/feature, lgtm, release-note, size/XXL

#3914 Test multiple scripts in one task executing with different UIDs
  examples/v1alpha1/taskruns/step-script.yaml
  examples/v1beta1/taskruns/step-script.yaml
Labels: approved, kind/misc, lgtm, release-note, size/S

#3888 Fix issue with "$$" in Script blocks
  examples/v1alpha1/taskruns/step-script.yaml
  examples/v1beta1/taskruns/step-script.yaml
  pkg/pod/pod_test.go
  pkg/pod/script.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#3817 an aggregate status of tasks in finally
  docs/pipelines.md
  docs/variables.md
  examples/v1beta1/pipelineruns/pipelinerun-task-execution-status.yaml
  examples/v1beta1/pipelineruns/pipelinerun-with-when-expressions.yaml
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  test/pipelinefinally_test.go
Labels: approved, kind/feature, lgtm, release-note, size/L

#3926 Fix lint issues
  cmd/entrypoint/namespaces.go
  cmd/kubeconfigwriter/main.go
  hack/spec-gen/main.go
  pkg/apis/resource/v1alpha1/cluster/cluster_resource.go
  pkg/apis/resource/v1alpha1/git/git_resource.go
  pkg/apis/resource/v1alpha1/storage/gcs.go
  pkg/entrypoint/entrypointer.go
  pkg/jsonpath/expand_test.go
  pkg/pod/pod_test.go
  pkg/pod/script.go
  pkg/pod/status.go
  pkg/reconciler/pipeline/dag/dag.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/termination/parse.go
  pkg/termination/write.go
  test/cluster_resource_test.go
  test/init_test.go
  test/multiarch_utils.go
  test/v1alpha1/cluster_resource_test.go
  test/v1alpha1/init_test.go
Labels: approved, kind/misc, lgtm, release-note-none, size/M

#3919 adding clear explanation of the context variables 🤞
  docs/pipelines.md
  docs/variables.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/S

#3917 Add "alpha" feature gate tests (integration & examples) to our CI
  docs/workspaces.md
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
  test/e2e-tests.sh
  test/tektonbundles_test.go
Labels: approved, kind/misc, lgtm, release-note, size/L

#3878 Disable the default workingDir and HOME overrides
  config/config-feature-flags.yaml
  docs/deprecations.md
  docs/install.md
  examples/v1alpha1/taskruns/dind-sidecar.yaml
  examples/v1alpha1/taskruns/gcs-resource.yaml
  examples/v1alpha1/taskruns/git-resource.yaml
  examples/v1alpha1/taskruns/home-is-set.yaml
  examples/v1alpha1/taskruns/step-script.yaml
  examples/v1alpha1/taskruns/workingdir.yaml
  examples/v1beta1/taskruns/alpha/authenticating-git-commands.yaml
  examples/v1beta1/taskruns/authenticating-git-commands.yaml
  examples/v1beta1/taskruns/dind-sidecar.yaml
  examples/v1beta1/taskruns/gcs-resource.yaml
  examples/v1beta1/taskruns/git-resource.yaml
  examples/v1beta1/taskruns/home-is-set.yaml
  examples/v1beta1/taskruns/step-script.yaml
  examples/v1beta1/taskruns/workingdir.yaml
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/entrypoint_test.go
  test/v1alpha1/entrypoint_test.go
Labels: approved, kind/feature, lgtm, release-note-action-required, size/L

#3933 Add links to v0.24.0 docs and examples
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3932 😅 Fix issue where AddSidecarVolumeMount unit tests did not actually run
  pkg/workspace/apply_test.go
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3923 Remove deprecated PascalCase fields in WhenExpressions
  docs/deprecations.md
  go.sum
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/when_types.go
  pkg/apis/pipeline/v1beta1/when_validation.go
  pkg/apis/pipeline/v1beta1/when_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: approved, kind/cleanup, lgtm, release-note, size/L

#3938 Revert "Fix issue with "$$" in Script blocks"
  examples/v1alpha1/taskruns/step-script.yaml
  examples/v1beta1/taskruns/step-script.yaml
  pkg/pod/pod_test.go
  pkg/pod/script.go
Labels: approved, kind/misc, lgtm, needs-cherry-pick, release-note, size/L

#3942 Revert "Fix issue with "$$" in Script blocks"
  examples/v1alpha1/taskruns/step-script.yaml
  examples/v1beta1/taskruns/step-script.yaml
  pkg/pod/pod_test.go
  pkg/pod/script.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#3946 Update pipelines.md
  docs/pipelines.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3930 Change the way we run e2e tests with feature gates in pipelines
  test/e2e-tests.sh
Labels: approved, kind/misc, lgtm, release-note-none, size/S

#3960 Update tektoncd/plumbing.
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#3956 Add support for experiemental hermetic execution mode to TaskRuns
  cmd/entrypoint/runner.go
  docs/hermetic.md
  docs/install.md
  docs/taskruns.md
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  test/README.md
  test/hermetic_taskrun_test.go
Labels: approved, kind/feature, lgtm, release-note, size/L

#3967 docs(pipelines): specify how to reference an array parameter
  docs/pipelines.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note-none, size/S

#3961 Document the safe-to-evict annotation on the webhook deployment
  docs/enabling-ha.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3955 Organize DEVELOPMENT.md, provide consistent examples & reflect go mod support
  DEVELOPMENT.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/L

#3977 Validate run for both ref and spec as nil.
  pkg/apis/pipeline/v1alpha1/run_validation.go
  pkg/apis/pipeline/v1alpha1/run_validation_test.go
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#3958 Add missing frontmatter to some docs
  docs/auth.md
  docs/conditions.md
  docs/container-contract.md
  docs/deprecations.md
  docs/enabling-ha.md
  docs/events.md
  docs/install.md
  docs/labels.md
  docs/logs.md
  docs/metrics.md
  docs/migrating-from-knative-build.md
  docs/migrating-v1alpha1-to-v1beta1.md
  docs/pipelineruns.md
  docs/pipelines.md
  docs/podtemplates.md
  docs/resources.md
  docs/runs.md
  docs/taskruns.md
  docs/tasks.md
  docs/tekton-bundle-contracts.md
  docs/tekton-controller-performance-configuration.md
  docs/variables.md
  docs/workspaces.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note-none, size/M

#3987 Fix list of proposed kind labels for PRs
  .github/pull_request_template.md
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS
