Repository tektoncd/pipeline, pull requests merged in 2021-01, with the labels that each got.

#3658 examples/tests: fix yq task
  examples/v1alpha1/pipelineruns/pipelinerun.yaml
  examples/v1beta1/pipelineruns/pipelinerun.yaml
  test/yamls/v1beta1/pipelineruns/pipelinerun.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3642 fix typo in a parameter of the v1beta1 example
  docs/migrating-v1alpha1-to-v1beta1.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#3660 Allow custom tasks to use workspaces, service accounts, pod templates
  docs/pipelineruns.md
  docs/pipelines.md
  docs/runs.md
  pkg/apis/pipeline/v1alpha1/run_defaults.go
  pkg/apis/pipeline/v1alpha1/run_types.go
  pkg/apis/pipeline/v1alpha1/run_validation.go
  pkg/apis/pipeline/v1alpha1/run_validation_test.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, kind/feature, lgtm, release-note, size/XL

#3614 Add some more release process details 🤓
  tekton/release-cheat-sheet.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/L

#3665 Remove creds-init image from build and deploy
  .ko.yaml
  cmd/controller/main.go
  cmd/creds-init/README.md
  cmd/creds-init/kodata/HEAD
  cmd/creds-init/kodata/LICENSE
  cmd/creds-init/kodata/refs
  cmd/creds-init/kodata/third_party
  cmd/creds-init/main.go
  cmd/entrypoint/main.go
  config/controller.yaml
  examples/v1beta1/taskruns/authenticating-git-commands.yaml
  hack/nightly.sh
  pkg/apis/pipeline/images.go
  pkg/apis/pipeline/images_test.go
  pkg/apis/pipeline/paths.go
  pkg/apis/pipeline/v1alpha1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/resource/v1alpha1/storage/build_gcs_test.go
  pkg/artifacts/artifact_storage_test.go
  pkg/credentials/initialize.go
  pkg/pod/creds_init_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  tekton/koparse/test_koparse.py
  tekton/koparse/test_release.yaml
  tekton/release-cheat-sheet.md
  tekton/resources.yaml
Labels: approved, kind/cleanup, lgtm, release-note, size/L

#3674 Remove creds-init image from release/nightly pipelines
  tekton/publish.yaml
  tekton/release-pipeline-nightly.yaml
  tekton/release-pipeline.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/S

#3662 Tekton Pipelines Topical Ownership
  CONTRIBUTING.md
  topical-ownership.md
Labels: approved, kind/misc, lgtm, release-note, size/S

#3680 Update docs on termination message size to correctly reflect k8s info
  docs/developers/README.md
  docs/tasks.md
Labels: approved, kind/documentation, lgtm, release-note, size/S

#3472 Fix bug where PipelineRun emits task results that were never produced
  docs/pipelines.md
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/conditionresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
Labels: approved, kind/bug, lgtm, release-note, size/XL

#3390 access execution status of any task in finally
  docs/pipelines.md
  docs/variables.md
  examples/v1beta1/pipelineruns/pipelinerun-task-execution-status.yaml
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
  test/pipelinefinally_test.go
Labels: approved, kind/feature, lgtm, release-note, size/XL

#3683 Fix the publish task
  tekton/publish.yaml
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#3671 Fix the broken link of pipeline previous yaml file
  tekton/README.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#3177 Remove pkg/system.
  cmd/webhook/main.go
  pkg/pod/creds_init_test.go
  pkg/pod/pod_test.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/system/names.go
  pkg/system/names_test.go
  test/custom_task_test.go
  test/tektonbundles_test.go
Labels: approved, kind/cleanup, lgtm, release-note, size/L

#3686 Add link to docs and exmples for v0.20.0
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3684 Move resolution of Pipeline Results to end of completed/successful reconcile
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, kind/bug, lgtm, release-note-none, size/S

#3685 Ignore generated openapi code when running golangci-lint
  .golangci.yml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3689 taskrun: fix log message
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/XS

#3679 Fix bug where step status ordering did not match step container ordering
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#3696 Update taskruns.md doc
  docs/taskruns.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#3691 param validation - execution status variable
  docs/pipelines.md
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
Labels: approved, kind/misc, lgtm, needs-cherry-pick, release-note-none, size/L

#3653 Skip the dropNetworking test if it doesn't have the correct privileges.
  cmd/entrypoint/namespaces_test.go
Labels: approved, kind/failing-test, lgtm, release-note-none, size/S

#3697 [cherry-pick] validate execution status variable
  docs/pipelines.md
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
Labels: approved, kind/misc, lgtm, release-note, size/L

#3698 updating readme with 0.20.1
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3659 Support multiple secrets of type dockercfg and dockerconfigjson
  pkg/credentials/dockercreds/creds.go
  pkg/credentials/dockercreds/creds_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/M

#3242 consuming task results in finally
  docs/pipelines.md
  examples/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  test/pipelinefinally_test.go
  test/yamls/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml
Labels: approved, kind/feature, lgtm, release-note, size/XL

#3702 Fix stuck PipelineRun caused by optional workspace
  examples/v1beta1/pipelineruns/optional-workspaces.yaml
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, kind/bug, lgtm, needs-cherry-pick, release-note, size/L

#3708 Fix duplicate Pods when TaskRun or Pod labels are changed
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#3709 Fix typo in auth.md
  docs/auth.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/XS

#3714 Small updates for s390x tests
  test/helm_task_test.go
  test/multiarch_utils.go
Labels: approved, kind/misc, lgtm, release-note-none, size/M

#3646 add sparse checkout to git
  cmd/git-init/main.go
  pkg/git/git.go
  pkg/git/git_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#3717 release: publish only on a given list of platforms 💻
  tekton/build-push-ma-base-image.yaml
  tekton/publish.yaml
  tekton/release-pipeline.yaml
Labels: approved, area/release, kind/misc, lgtm, release-note, size/S

#3719 Correct workspace doc on behaviour of mountPath
  docs/workspaces.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#3522 Implement Pending PipelineRun status (TEP-0015)
  docs/pipelineruns.md
  internal/builder/v1beta1/pipeline.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  test/pipelinerun_test.go
  test/wait.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#3722 Fix TestPipelineLevelFinally_OneDAGTaskFailed test to avoid false negative error
  test/pipelinefinally_test.go
Labels: approved, kind/failing-test, lgtm, release-note-none, size/XS

#3723 Add comment to PipelineRunSpecStatusPending
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3668 Fix replace go mod of client-go
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, kind/misc, lgtm, ok-to-test, release-note, size/S

#3711 Validate dependencies between resolved resources in a PipelineRun
  examples/v1beta1/pipelineruns/using-optional-workspaces-in-when-expressions.yaml
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/resultref.go
  pkg/apis/pipeline/v1beta1/resultref_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/validate_dependencies.go
  pkg/reconciler/pipelinerun/resources/validate_dependencies_test.go
  test/pipelinefinally_test.go
Labels: approved, kind/misc, lgtm, release-note, size/XL

#3728 Document deprecation of the build-gcs PipelineResource type
  docs/resources.md
  docs/variables.md
  examples/v1alpha1/taskruns/build-gcs-targz.yaml
  examples/v1alpha1/taskruns/build-gcs-zip.yaml
  examples/v1beta1/taskruns/build-gcs-targz.yaml
  examples/v1beta1/taskruns/build-gcs-zip.yaml
  pkg/apis/resource/v1alpha1/pipeline_resource_types.go
Labels: approved, kind/cleanup, lgtm, release-note, size/S

#3597 adding unit tests for pipelineTaskList.Deps
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
Labels: approved, lgtm, release-note-none, size/L

#3729 Refactor IsFinallySkipped Tests
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, kind/cleanup, lgtm, release-note, size/S

#3733 Validate Context Variables in Finally Tasks
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, kind/bug, lgtm, release-note, size/M
