Repository tektoncd/pipeline, pull requests merged in 2021-10, with the labels that each got.

#4267 adding an entry for v0.28.1 📢
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4269 Updates webhook cluster role to work with Owner References
  config/200-clusterrole.yaml
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#4249 Remove sbwsg from OWNERS_ALIAS file
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#4270 Removing internal/builder/v1alpha1 and all usages
  internal/builder/v1alpha1/condition.go
  internal/builder/v1alpha1/container.go
  internal/builder/v1alpha1/doc.go
  internal/builder/v1alpha1/owner_reference.go
  internal/builder/v1alpha1/param.go
  internal/builder/v1alpha1/pipeline.go
  internal/builder/v1alpha1/sidecar.go
  internal/builder/v1alpha1/step.go
  internal/builder/v1alpha1/task.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/conditionresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  test/pipelinerun_test.go
  test/v1alpha1/artifact_bucket_test.go
  test/v1alpha1/cluster_resource_test.go
  test/v1alpha1/duplicate_test.go
  test/v1alpha1/embed_test.go
  test/v1alpha1/kaniko_task_test.go
  test/v1alpha1/pipelinerun_test.go
  test/v1alpha1/status_test.go
  test/v1alpha1/taskrun_test.go
  test/v1alpha1/timeout_test.go
  test/v1alpha1/workingdir_test.go
  test/v1alpha1/workspace_test.go
Labels: approved, lgtm, size/XXL, release-note, kind/cleanup

#4275 Remove upgrade via defaulting
  cmd/webhook/main.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1alpha1/task_defaults.go
  pkg/apis/pipeline/v1alpha1/taskrun_defaults.go
  pkg/apis/pipeline/v1alpha1/taskrun_defaults_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults_test.go
  pkg/contexts/contexts.go
  pkg/contexts/contexts_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, lgtm, size/L, ok-to-test, release-note, kind/cleanup

#4268 Support for single-quote bracket notation for params
  docs/tasks.md
  docs/variables.md
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
  test/pipelinerun_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#4274 Fix Example in Service Account Documentation
  docs/taskruns.md
Labels: approved, lgtm, size/S, kind/documentation, release-note

#4277 Removing internal/builder completely
  internal/builder/README.md
  internal/builder/v1beta1/container.go
  internal/builder/v1beta1/doc.go
  internal/builder/v1beta1/examples_test.go
  internal/builder/v1beta1/owner_reference.go
  internal/builder/v1beta1/param.go
  internal/builder/v1beta1/pipeline.go
  internal/builder/v1beta1/pipeline_test.go
  internal/builder/v1beta1/pod.go
  internal/builder/v1beta1/pod_test.go
  internal/builder/v1beta1/resource.go
  internal/builder/v1beta1/resource_test.go
  internal/builder/v1beta1/sidecar.go
  internal/builder/v1beta1/step.go
  internal/builder/v1beta1/task.go
  internal/builder/v1beta1/task_test.go
  pkg/apis/resource/v1alpha1/cloudevent/cloud_event_resource_test.go
  pkg/apis/resource/v1alpha1/cluster/cluster_resource_test.go
  pkg/apis/resource/v1alpha1/git/git_resource_test.go
  pkg/apis/resource/v1alpha1/image/image_resource_test.go
  pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource_test.go
  pkg/apis/resource/v1alpha1/storage/gcs_test.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/taskrun/validate_resources_test.go
  pkg/remote/oci/resolver_test.go
  pkg/taskrunmetrics/metrics_test.go
  test/artifact_bucket_test.go
  test/cluster_resource_test.go
  test/helm_task_test.go
  test/kaniko_task_test.go
  test/pipelinerun_test.go
Labels: approved, lgtm, size/XXL, release-note-none, kind/cleanup

#4283 Only add gcr.io images to publish results
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note, kind/misc
