Repository tektoncd/pipeline, pull requests merged in 2021-12, with the labels that each got.

#4380 Put workspace-in-sidecar example into no-ci
  examples/v1beta1/taskruns/alpha/no-ci/workspace-in-sidecar.yaml
  examples/v1beta1/taskruns/no-ci/workspace-in-sidecar.yaml
Labels: approved, lgtm, size/XS, kind/flake, release-note-none

#4392 Retry TaskRef resolution on etcd errors
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#4387 Refactor CloudEvent related tests to use common set of helpers
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/events/cloudevent/testing.go
  pkg/reconciler/events/event_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/L, kind/flake, release-note-none

#4414 Document that k8s 1.20 is the minimum required
  DEVELOPMENT.md
  README.md
  docs/api-spec.md
  docs/install.md
  docs/podtemplates.md
Labels: approved, lgtm, size/S, kind/documentation, release-note

#4413 Add v0.30.0 to the README
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#4405 Move Events test helpers to test package
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/events/event_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/events/events.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#4424 Explicitly annotate TaskRuns with release version.
  pkg/pod/pod.go
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#4416 make debug scripts comply with new /tekton/run
  docs/developers/README.md
  pkg/pod/script_test.go
  pkg/pod/scripts_constants.go
Labels: kind/bug, approved, lgtm, size/M, release-note-action-required

#4419 Fix `TestDAGPipelineRun` flakiness.
  test/dag_test.go
  test/v1alpha1/dag_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#4406 Merge default PodTemplate's affinity field
  pkg/apis/pipeline/v1beta1/taskrun_defaults.go
Labels: kind/bug, approved, lgtm, size/XS, ok-to-test, release-note

#4423 Bump GoogleContainerTools/skaffold revision from v0.32.0 to v1.32.0
  examples/v1alpha1/pipelineruns/pipelinerun.yaml
  examples/v1alpha1/taskruns/build-push-kaniko.yaml
  examples/v1beta1/pipelineruns/pipelinerun.yaml
  test/multiarch_utils.go
  test/yamls/v1beta1/pipelineruns/pipelinerun.yaml
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note-none

#4429 updating README to include v0.31.0 release links
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note
