Repository tektoncd/pipeline, pull requests merged in 2021-08, with the labels that each got.

#4133 Switch `Errorf` to `Fatalf` in retry tests.
  test/retry_test.go
  test/v1alpha1/retry_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#4132 Invalidate passing `Results` between `Finally Tasks`
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, kind/bug, lgtm, release-note, size/M

#4136 Graceful Termination: Cancelled `Task` is Failed (even with `Retries`)
  docs/pipelineruns.md
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#4075 support referencing array params in when expression values
  docs/pipelines.md
  examples/v1beta1/pipelineruns/pipelinerun-with-when-expressions.yaml
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/param_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/when_types.go
  pkg/apis/pipeline/v1beta1/when_types_test.go
  pkg/apis/pipeline/v1beta1/when_validation.go
  pkg/reconciler/pipelinerun/resources/apply.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#4121 adding label `memberOf` to identify a taskRun in the pipeline
  docs/labels.md
  pkg/apis/pipeline/register.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, kind/feature, lgtm, release-note, size/M

#4140 Fix Example with Completed and Succeeded Execution Status
  examples/v1beta1/pipelineruns/pipelinerun-with-when-expressions.yaml
Labels: approved, lgtm, size/S, release-note, kind/misc

#3934 Add variable expansion in the workspaces.mountPath field of Tasks
  docs/variables.md
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4106 TEP-0040 implementation - specifying `onError` in a step
  cmd/entrypoint/main.go
  cmd/entrypoint/post_writer.go
  cmd/entrypoint/post_writer_test.go
  docs/developers/README.md
  docs/tasks.md
  docs/variables.md
  examples/v1beta1/pipelineruns/alpha/ignore-step-error.yaml
  examples/v1beta1/taskruns/alpha/ignore-step-error.yaml
  internal/builder/v1beta1/step.go
  pkg/apis/pipeline/paths.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/ignore_step_error_test.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#4090 Always refer to "finally" tasks 📖
  docs/pipelineruns.md
  docs/pipelines.md
Labels: approved, lgtm, size/L, kind/documentation, release-note-none

#4149 Small entrypoint unit test fixes prior to 0.27 release
  cmd/entrypoint/post_writer_test.go
  pkg/entrypoint/entrypointer_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#4151 Change "fail" to "stopAndFail" 🧐
  cmd/entrypoint/main.go
  docs/tasks.md
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/entrypoint_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#4156 Add metadata to our publish task for Tekton Chains to observe & sign
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note, kind/misc

#4131 Replace snooze with NewRequeueKey
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#4152 Update docs with 0.27.0 info
  README.md
  docs/install.md
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4162 Update readme with release 0.27.1 links
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4154 cleaning up label keys 🧹
  pkg/apis/pipeline/register.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/metrics_test.go
  pkg/reconciler/taskrun/resources/input_resources.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/duplicate_test.go
  test/pipelinerun_test.go
  test/v1alpha1/duplicate_test.go
  test/v1alpha1/pipelinerun_test.go
Labels: approved, lgtm, size/L, release-note, kind/cleanup

#4161 Set the scripts dir to readonly after init
  pkg/pod/pod_test.go
  pkg/pod/script.go
  pkg/pod/script_test.go
Labels: kind/bug, approved, lgtm, size/S, ok-to-test, release-note

#4147 (cleanup) use skipping reason instead of existence of variables
  pkg/apis/pipeline/v1beta1/when_types.go
  pkg/apis/pipeline/v1beta1/when_types_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: approved, lgtm, size/L, release-note, kind/cleanup

#4163 Propagate Pipeline name label to PipelineRun
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note, needs-cherry-pick

#4171 Remove confusing comment (◎_◎;)
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#4175 pkg/entrypoint: clean after running tests
  pkg/entrypoint/entrypointer_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#4180 Don't modify the lister cache's copy.
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#4174 cherry-pick to 0.27.x: Propagate Pipeline name label to PipelineRun
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#4178 Switch from -Z to -w
  test/pullrequest/e2e_test.go
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#4181 Fix a small copy/pasta typo
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#4182 Adjust several log lines
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#4183 Add CE Client to dynamic injection
  pkg/reconciler/events/cloudevent/cloudeventclient.go
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#4189 Deduplicate timeout constants.
  test/cancel_test.go
  test/dag_test.go
  test/examples_test.go
  test/ignore_step_error_test.go
  test/pipelinerun_test.go
  test/serviceaccount_test.go
  test/status_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#4191 Improve the logging in pkg/git testing
  pkg/git/git_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#4192 Configure `user.name` in `git_test.go` `run` method.
  pkg/git/git_test.go
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#4197 Un-randomize TestConvertScripts_WithBreakpoint_OnFailure
  pkg/pod/script.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none
