Repository tektoncd/pipeline, pull requests merged in 2021-11, with the labels that each got.

#4359 Add docs for missing variable substitution fields
  docs/variables.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#4360 TestTaskRunTimeout: Reduce timeout 30s -> 1s.
  test/timeout_test.go
Labels: approved, lgtm, size/XS, kind/flake, release-note

#4363 docs: fixing my name in topical-ownership 💅
  topical-ownership.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#4349 Rewrite flakey workspace-in-sidecar example
  examples/v1beta1/taskruns/alpha/workspace-in-sidecar.yaml
  examples/v1beta1/taskruns/workspace-in-sidecar.yaml
Labels: approved, lgtm, size/M, kind/flake, release-note-none

#4367 Improve test coverage for pkg/git
  pkg/git/git.go
  pkg/git/git_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#4371 Set explicit timeoutSeconds on example's readinessProbe
  examples/v1alpha1/taskruns/sidecar-ready.yaml
  examples/v1beta1/taskruns/sidecar-ready.yaml
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#4370 Minor refactoring of taskRef validation.
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note-none, kind/cleanup

#4372 Breakout sidecar stopping if TaskSpec has no sidecar
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note

#4369 Updates helm task e2e test to use v1 rbac api
  test/helm_task_test.go
Labels: approved, lgtm, size/XS, release-note, kind/cleanup

#4376 Deprecate `PipelineResources`
  docs/README.md
  docs/auth.md
  docs/conditions.md
  docs/deprecations.md
  docs/developers/README.md
  docs/developers/local-setup.md
  docs/install.md
  docs/migrating-from-knative-build.md
  docs/migrating-v1alpha1-to-v1beta1.md
  docs/pipelineruns.md
  docs/pipelines.md
  docs/resources.md
  docs/taskruns.md
  docs/tasks.md
  docs/tutorial.md
  docs/variables.md
  examples/v1beta1/pipelineruns/conditional-pipelinerun-with-optional-resources.yaml
  examples/v1beta1/pipelineruns/conditional-pipelinerun.yaml
  examples/v1beta1/pipelineruns/demo-optional-resources.yaml
  examples/v1beta1/pipelineruns/output-pipelinerun.yaml
  examples/v1beta1/pipelineruns/pipelinerun-with-resourcespec.yaml
  examples/v1beta1/taskruns/cloud-event.yaml
  examples/v1beta1/taskruns/gcs-resource.yaml
  examples/v1beta1/taskruns/git-resource.yaml
  examples/v1beta1/taskruns/git-ssh-creds-without-known_hosts.yaml
  examples/v1beta1/taskruns/git-ssh-creds.yaml
  examples/v1beta1/taskruns/optional-resources.yaml
  examples/v1beta1/taskruns/pullrequest.yaml
  examples/v1beta1/taskruns/pullrequest_input_copystep_output.yaml
  examples/v1beta1/taskruns/task-multiple-output-image.yaml
  examples/v1beta1/taskruns/task-output-image.yaml
Labels: approved, lgtm, size/L, release-note, kind/misc

#4361 Use kmeta.ChildName for child resources
  docs/events.md
  docs/pipelineruns.md
  docs/taskruns.md
  docs/tutorial.md
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#4379 Add instructions for replacing CloudEvent PipelineResource to pipeline docs
  docs/migrating-v1alpha1-to-v1beta1.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4345 Fix ignore annotation for gosec
  pkg/pullrequest/scm.go
Labels: kind/bug, approved, lgtm, size/XS, ok-to-test, release-note-none

#4346 Remove experimental disable resolution controller flag
  cmd/controller/main.go
  config/controller.yaml
  docs/developers/README.md
  pkg/apis/pipeline/options.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/L, release-note, kind/misc

#4353 Reduce integration test run times
  test/duplicate_test.go
  test/sidecar_test.go
  test/start_time_test.go
  test/v1alpha1/duplicate_test.go
  test/v1alpha1/sidecar_test.go
  test/v1alpha1/start_time_test.go
  test/v1alpha1/timeout_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#4385 docs: update metrics name
  docs/metrics.md
Labels: approved, size/S, kind/documentation, release-note-none

#4384 docs: update metrics name
  docs/metrics.md
Labels: approved, size/S, kind/documentation, release-note-none

#4383 docs: update metrics name
  docs/metrics.md
Labels: approved, size/S, kind/documentation, release-note-none

#4390 docs: add myself as topical owner for debug
  topical-ownership.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4382 docs: update metrics name
  docs/metrics.md
Labels: approved, size/S, kind/documentation, release-note-none

#4395 Fix conflicting docs for /tekton/steps API Compatibility.
  docs/developers/README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-action-required
