Repository tektoncd/pipeline, pull requests merged in 2021-02, with the labels that each got.

#3571 set task as failed
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: approved, kind/bug, lgtm, release-note, size/M

#3743 Update TOC in Pipelines documentation
  docs/pipelines.md
Labels: approved, kind/cleanup, lgtm, release-note, size/S

#3747 Use main branch for community repository 🧙
  CONTRIBUTING.md
  cmd/pullrequest-init/example/pr.json
  docs/deprecations.md
  docs/pipelines.md
  docs/runs.md
  examples/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml
  roadmap.md
  test/yamls/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#3725 Change to use the FilteredPodInformer to only watch Tekton relevant pods
  cmd/controller/main.go
  pkg/apis/pipeline/v1alpha1/taskrun_defaults.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults.go
  pkg/reconciler/pipelinerun/metrics_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/metrics_test.go
  pkg/reconciler/testing/logger.go
  test/controller.go
  test/v1alpha1/controller.go
  test/v1alpha1/wait_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/filtered/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/filtered/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/fake/fake_filtered_factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/filtered_factory.go
  vendor/modules.txt
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/M

#3740 Make volume mount names RFC1123 DNS label strict
  pkg/pod/creds_init.go
  pkg/pod/creds_init_test.go
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/M

#3738 WhenExpressions in Finally Tasks
  docs/pipelines.md
  examples/v1beta1/pipelineruns/pipelinerun-with-when-expressions.yaml
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  test/pipelinefinally_test.go
Labels: approved, kind/feature, lgtm, release-note, size/XL

#3752 tekton controller logger key
  cmd/controller/main.go
Labels: approved, kind/misc, lgtm, release-note, size/XS

#3735 Add docs about cloud events structure
  docs/events.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/L

#3754 Add kustomize.yaml to the Tekton folder
  tekton/kustomization.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3727 Add nonroot user to pipeline's build-base image
  images/Dockerfile
Labels: approved, kind/misc, lgtm, release-note, size/XS

#3753 updating doc - pipelineResult referencing results of a finally task
  docs/pipelines.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/S

#3755 Use crane cp to move images, instead of gcloud
  tekton/README.md
  tekton/publish.yaml
Labels: approved, kind/cleanup, lgtm, release-note, size/S

#3765 Add v0.21.0 to the README
  README.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#3768 Re-enable test now that HEAD is fixed
  test/helm_task_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#3630 Adding power (ppc64le) architecture image mappings
  test/multiarch_utils.go
Labels: approved, kind/misc, lgtm, ok-to-test, release-note-none, size/M

#3772 Fix the pipeline nightly
  tekton/ko/Dockerfile
  tekton/koparse/koparse.py
  tekton/koparse/test_koparse.py
  tekton/koparse/test_release.yaml
  tekton/publish.yaml
Labels: approved, kind/bug, lgtm, release-note-none, size/XL

#3775 Fix the cr URL for crane
  tekton/publish.yaml
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#3776 Fix nightly builds (again)
  tekton/publish.yaml
Labels: approved, kind/bug, lgtm, release-note-none, size/M

#3777 Move the secret mount to the correct step
  tekton/publish.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3773 Fix a broken link to the service account docs
  docs/pipelines.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3780 Use legacy build and test golang tasks
  tekton/release-pipeline-nightly.yaml
  tekton/release-pipeline.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3783 Cleanup s390x exclude test list with build-gcs tests
  test/multiarch_utils.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#3784 Set minAvailable:1 to unblock node upgrades
  config/webhook-hpa.yaml
Labels: approved, kind/bug, lgtm, release-note, size/XS

#3788 Rework the release pipeline to use workspaces
  tekton/account.yaml
  tekton/build-push-ma-base-image.yaml
  tekton/kustomization.yaml
  tekton/publish.yaml
  tekton/release-cheat-sheet.md
  tekton/release-pipeline-nightly.yaml
  tekton/release-pipeline.yaml
  tekton/resources.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XL

#3761 Short term fix for Cloud Event Source
  pkg/reconciler/events/cloudevent/cloudevent.go
  pkg/reconciler/events/cloudevent/cloudevent_test.go
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/S

#3789 Update roadmap for 2021! 🛣️
  roadmap.md
Labels: approved, kind/misc, lgtm, release-note-none, size/L
