Repository tektoncd/pipeline, pull requests merged in 2021-03, with the labels that each got.

#3791 Refine the comment for git init base image
  .ko.yaml
Labels: approved, kind/misc, lgtm, ok-to-test, release-note, size/XS

#3801 Remove Test Builders from remote_tests.go
  test/remote_test.go
Labels: approved, kind/cleanup, lgtm, release-note, size/S

#3805 Update docs to use Kubernetes 1.17 as the minimum version
  DEVELOPMENT.md
  README.md
  docs/api-spec.md
  docs/install.md
  docs/podtemplates.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/S

#3795 Change to avoid error when service account has empty secret name
  pkg/pod/creds_init.go
  pkg/pod/creds_init_test.go
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/M

#3793 Add PipelineRun and TaskRun Status work to the Roadmap
  roadmap.md
Labels: approved, kind/misc, lgtm, release-note, size/XS

#3802 Remove Test Builders from pipelinerunstate_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: approved, kind/cleanup, lgtm, release-note, size/S

#3779 Losslessly roundtrip Pipelines with Finally from beta to alpha and back
  pkg/apis/pipeline/v1alpha1/conversion_error.go
  pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  pkg/apis/pipeline/v1alpha1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, kind/bug, lgtm, release-note, size/M

#3809 Add documenation about setting resource limits on a Task step
  docs/taskruns.md
  docs/tasks.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note-none, size/M

#3808 cleaning up the function parameter
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XS

#3816 Serialize and deserialize Finally in PipelineRuns too
  pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_conversion_test.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#3764 Remove tekton.dev/task label from taskrun of clustertasks
  docs/labels.md
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/cleanup, lgtm, release-note, size/XS

#3787 Disable Webhook PDB by default, document enabling it
  config/webhook-hpa.yaml
  docs/enabling-ha.md
Labels: approved, kind/bug, lgtm, release-note, size/L

#3823 Fix the pipeline release cheat-sheet
  tekton/release-cheat-sheet.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/M

#3810 Add Dockerfile for pullrequest nonroot build base image
  images/git-init/Dockerfile
  images/pullrequest-init/Dockerfile
  tekton/build-push-ma-base-image.yaml
Labels: approved, kind/misc, lgtm, ok-to-test, release-note, size/S

#3825 updating release cheat sheet
  tekton/release-cheat-sheet.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#3831 Remove cluster-wide write access to ServiceAccounts and Secrets
  config/200-clusterrole.yaml
Labels: approved, kind/cleanup, lgtm, release-note, size/XS

#3834 Use "no-cache" in the buildkit based builds
  tekton/build-push-ma-base-image.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3828 Change to use new base images for git and pullrequest images
  .ko.yaml
  images/Dockerfile
  tekton/build-push-ma-base-image.yaml
  tekton/publish.yaml
Labels: approved, kind/misc, lgtm, ok-to-test, release-note, size/S

#3832 Further limit cluster-wide read-write permissions
  config/200-clusterrole.yaml
Labels: approved, kind/cleanup, lgtm, release-note, size/S

#3842 Remove YAML merge and variable from config YAML
  config/300-clustertask.yaml
  config/300-pipeline.yaml
  config/300-pipelinerun.yaml
  config/300-task.yaml
  config/300-taskrun.yaml
Labels: approved, kind/feature, lgtm, release-note, size/L

#3847 Add ability to run e2e tests on top of nightly release
  test/taskrun_test.go
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#3850 Remove unused image-cache CRD
  config/300-imagecache.yaml
Labels: approved, kind/misc, lgtm, release-note, size/M

#3856 PVC: Use Owner UIDs instead of Owner names.
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/volumeclaim/pvchandler.go
  pkg/reconciler/volumeclaim/pvchandler_test.go
Labels: approved, kind/bug, lgtm, release-note, size/M

#3852 Remove mention of absolute vs relative path from workspaces doc
  docs/workspaces.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#3848 refactor pipelineTask validation
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/XL

#3859 Use v1 instead of v1beta1 for `ClusterRoleBinding` 🤖
  config/201-clusterrolebinding.yaml
Labels: approved, kind/cleanup, lgtm, release-note, size/XS

#3860 Correct url in migration doc and modify to main branch in doc urls
  docs/migrating-v1alpha1-to-v1beta1.md
  docs/pipelines.md
  docs/tasks.md
  docs/tekton-controller-performance-configuration.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note, size/M
