Repository tektoncd/pipeline, pull requests merged in 2022-02, with the labels that each got.

#4538 Bump knative.dev/pkg vendoring. Use klog/v2
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/doc.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS, release-note

#4535 Make record of resources used to release 0.28.3
  tekton/build-push-ma-base-image.yaml
  tekton/gcs-upload.yaml
  tekton/git-clone.yaml
  tekton/golang-build.yaml
  tekton/golang-test.yaml
  tekton/kustomization.yaml
  tekton/pipeline-tekton-bucket.yaml
  tekton/plumbing.yaml
  tekton/prerelease-checks.yaml
  tekton/publish.yaml
  tekton/release-pipeline.yaml
  tekton/release-service-account.yaml
Labels: approved, lgtm, size/XXL, release-note-none

#4539 Add validation for PR infinite timeouts
  docs/pipelineruns.md
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#4537 Fix kustomize invocation typo
  tekton/README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4520 add default seccomp profile
  config/101-podsecuritypolicy.yaml
Labels: kind/bug, approved, lgtm, size/XS, ok-to-test, release-note-none

#4549 Drop resource `requests:` from `gohelloworld`.
  test/gohelloworld/gohelloworld-chart/values.yaml
Labels: approved, lgtm, size/XS, release-note

#4550 Ignore variant when looking up command for platform in entrypoint
  cmd/entrypoint/main.go
  cmd/entrypoint/namespaces.go
  cmd/entrypoint/namespaces_test.go
  cmd/entrypoint/platform_test.go
  cmd/entrypoint/runner.go
  cmd/entrypoint/runner_windows.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#4541 Increase lease time of controller and webhook
  config/config-leader-election.yaml
Labels: approved, lgtm, size/XS, release-note

#4547 Add taskSpec resources validation
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/taskrun/validate_resources.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#4528 [refactor] Remove ImplicitParamEnabled context.
  pkg/apis/pipeline/v1beta1/implicit_params_test.go
  pkg/apis/pipeline/v1beta1/param_context.go
  pkg/apis/pipeline/v1beta1/param_context_test.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1beta1/task_defaults.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults.go
Labels: approved, lgtm, size/XL, release-note, kind/cleanup

#4502 Add resolution types to the API
  docs/install.md
  docs/pipelineruns.md
  docs/taskruns.md
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipelineref_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/resolver_types.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/taskref_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#4564 cleanup - ApplyContext parameters
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#4570 Update write_test.go
  pkg/termination/write_test.go
Labels: approved, lgtm, size/XS, ok-to-test, release-note, kind/cleanup

#4572 Fix links to Why Aren't PipelineResources in Beta?
  docs/migrating-v1alpha1-to-v1beta1.md
  docs/resources.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4469 Fix tekton_pipelines_controller_taskrun_count recount bug
  pkg/reconciler/taskrun/taskrun.go
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: approved, lgtm, size/L, release-note

#4577 Fix links to Why Aren't PipelineResources in Beta? v0.30.x
  docs/migrating-v1alpha1-to-v1beta1.md
  docs/resources.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#4576 Fix links to Why Aren't PipelineResources in Beta? v0.29.x
  docs/install.md
  docs/migrating-v1alpha1-to-v1beta1.md
  docs/resources.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#4578 Fix links to Why Aren't PipelineResources in Beta? v0.31.x
  docs/migrating-v1alpha1-to-v1beta1.md
  docs/resources.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#4579 Fix links to Why Aren't PipelineResources in Beta? v0.32.x
  docs/migrating-v1alpha1-to-v1beta1.md
  docs/resources.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#4573 debug is an alpha feature
  docs/debug.md
  docs/install.md
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#4569 Consider osversion when determining platform uniqueness
  cmd/entrypoint/main.go
  go.mod
  go.sum
  pkg/pod/entrypoint_lookup_impl.go
  pkg/pod/entrypoint_lookup_impl_test.go
  third_party/LICENSE
  third_party/vendor/golang.org/x/crypto/LICENSE
  third_party/vendor/golang.org/x/net/LICENSE
  third_party/vendor/golang.org/x/sys/cpu/LICENSE
  third_party/vendor/golang.org/x/text/LICENSE
  vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/auth.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/v1/layout/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/platform.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/options.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/ping.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/zz_deepcopy_generated.go
  vendor/github.com/klauspost/compress/.goreleaser.yml
  vendor/github.com/klauspost/compress/README.md
  vendor/github.com/klauspost/compress/huff0/decompress.go
  vendor/github.com/klauspost/compress/zstd/bitreader.go
  vendor/github.com/klauspost/compress/zstd/bitwriter.go
  vendor/github.com/klauspost/compress/zstd/blockdec.go
  vendor/github.com/klauspost/compress/zstd/blockenc.go
  vendor/github.com/klauspost/compress/zstd/decodeheader.go
  vendor/github.com/klauspost/compress/zstd/enc_base.go
  vendor/github.com/klauspost/compress/zstd/enc_fast.go
  vendor/github.com/klauspost/compress/zstd/encoder_options.go
  vendor/github.com/klauspost/compress/zstd/fse_decoder.go
  vendor/github.com/klauspost/compress/zstd/fse_encoder.go
  vendor/github.com/klauspost/compress/zstd/internal/xxhash/xxhash_amd64.s
  vendor/github.com/klauspost/compress/zstd/internal/xxhash/xxhash_arm64.s
  vendor/github.com/klauspost/compress/zstd/internal/xxhash/xxhash_asm.go
  vendor/github.com/klauspost/compress/zstd/internal/xxhash/xxhash_other.go
  vendor/github.com/klauspost/compress/zstd/seqdec.go
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/credentials/insecure/insecure.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/grpclog/loggerv2.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/grpclog/grpclog.go
  vendor/google.golang.org/grpc/internal/grpcutil/regex.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/L, release-note

#4586 Update the deprecations table
  docs/deprecations.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4588 Fix for some arm64 machines.
  config/controller.yaml
Labels: kind/bug, approved, lgtm, size/XS, ok-to-test, release-note

#4575 Add Step and Sidecar Overrides to TaskRun API
  docs/install.md
  docs/pipelineruns.md
  docs/taskruns.md
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#4599 Bump k8schain dep to avoid some log spam
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/containerregistry/runtime/2019-08-15-preview/containerregistry/dataplane_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/aws/aws-sdk-go-v2/config/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/config/config.go
  vendor/github.com/aws/aws-sdk-go-v2/config/go.mod
  vendor/github.com/aws/aws-sdk-go-v2/config/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/config/shared_config.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/ini/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/ini/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/ini/literal_tokens.go
  vendor/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/ecr.go
  vendor/github.com/containerd/stargz-snapshotter/estargz/estargz.go
  vendor/github.com/containerd/stargz-snapshotter/estargz/go.mod
  vendor/github.com/containerd/stargz-snapshotter/estargz/go.sum
  vendor/github.com/docker/distribution/registry/client/auth/challenge/authchallenge.go
  vendor/github.com/golang-jwt/jwt/v4/README.md
  vendor/github.com/golang-jwt/jwt/v4/claims.go
  vendor/github.com/golang-jwt/jwt/v4/errors.go
  vendor/github.com/golang-jwt/jwt/v4/map_claims.go
  vendor/github.com/golang-jwt/jwt/v4/parser_option.go
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/github.com/golang-jwt/jwt/v4/types.go
  vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/README.md
  vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/go.mod
  vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/go.sum
  vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/k8schain.go
  vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/authn/kubernetes/go.mod
  vendor/github.com/google/go-containerregistry/pkg/authn/kubernetes/go.sum
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/layer.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_alarm.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_386.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
Labels: approved, lgtm, size/M, release-note, kind/cleanup

#4607 Replace Clock package with k8s Clock package
  cmd/controller/main.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1alpha1/run_types.go
  pkg/apis/pipeline/v1alpha1/run_types_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/clock/clock.go
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#4612 TEP-0058: Graceful Termination - `PipelineRunCancelled` is deprecated
  docs/deprecations.md
Labels: approved, lgtm, size/XS, release-note, kind/cleanup

#4602 Remove broken link in development doc
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#4601 TEP-0090: Matrix - Update `Pipeline` API definition
  docs/pipelines.md
Labels: approved, lgtm, size/L, kind/documentation, release-note

#4624 Replace remaining implementations of TestClock
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#4622 refactor TestReconcile_PipelineSpecTaskSpec objects
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note-none, kind/cleanup

#4619 clean up TestReconcile_CloudEvents YAML parsing
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note-none, kind/cleanup

#4595 Add links to docs and examples for v0.33.0
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4600 TEP-0090: Matrix - API Change and Feature Flag
  docs/install.md
  docs/matrix.md
  docs/pipelines.md
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  third_party/LICENSE
  third_party/vendor/golang.org/x/crypto/LICENSE
  third_party/vendor/golang.org/x/net/LICENSE
  third_party/vendor/golang.org/x/sys/cpu/LICENSE
  third_party/vendor/golang.org/x/text/LICENSE
Labels: kind/feature, approved, lgtm, size/L, release-note

#4628 test reconcile on cancelled refactor
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note, kind/cleanup
