Repository tektoncd/pipeline, pull requests merged in 2022-07, with the labels that each got.

#5062 TEP-0090: Matrix - implement `isRunning` for `Runs`
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#5043 Relax result type validation to avoid nightly build failure
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/result_types.go
  pkg/apis/pipeline/v1beta1/result_validation.go
  pkg/apis/pipeline/v1beta1/result_validation_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
Labels: kind/bug, approved, lgtm, size/L, release-note, needs-cherry-pick

#5061 TEP-0090: Matrix - implement `getNextTasks`
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/misc

#5063 TEP-0090: Matrix - Consume Results
  docs/matrix.md
  examples/v1beta1/pipelineruns/alpha/pipelinerun-with-matrix-and-results.yaml
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/resultref.go
  pkg/apis/pipeline/v1beta1/resultref_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/validate_dependencies_test.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#5022 Remove deprecated `PipelineRunSpecStatusCancelledDeprecated`
  docs/deprecations.md
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/pipelinerunmetrics/metrics.go
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/cancel_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  test/cancel_test.go
Labels: approved, lgtm, size/L, release-note, kind/cleanup

#5045 Clarify error message for PipelineRun alpha fields
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#4857 Extract parameter name without any pattern.
  pkg/substitution/substitution.go
Labels: approved, lgtm, size/XS, release-note, kind/misc

#4920 [TEP-0076]Validate Results type and object properties
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/result_types.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/validate_resources.go
  pkg/reconciler/taskrun/validate_resources_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4965 [TEP-0076]Pipeline results support array
  docs/pipelines.md
  examples/v1beta1/pipelineruns/alpha/pipeline-array-results.yaml
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/resultref.go
  pkg/apis/pipeline/v1beta1/resultref_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/validate_dependencies_test.go
  test/custom_task_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4904 TEP-0075: Implement object var replacement on task&taskrun level
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5073 Export ValidateObjectKeys function
  pkg/apis/pipeline/v1beta1/task_validation.go
Labels: approved, lgtm, size/XS, release-note, kind/misc

#4908 [TEP-0076]Support Array Results substitution
  docs/pipelines.md
  docs/variables.md
  examples/v1beta1/pipelineruns/alpha/pipelinerun-array-results-substitution.yaml
  pkg/apis/pipeline/v1beta1/result_types.go
  pkg/apis/pipeline/v1beta1/resultref.go
  pkg/apis/pipeline/v1beta1/when_types.go
  pkg/apis/pipeline/v1beta1/when_types_test.go
  pkg/reconciler/pipeline/dag/dag_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/taskrun/validate_resources.go
  pkg/reconciler/taskrun/validate_resources_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5084 cmd/entrypoint: do not interpret anything after `--`
  cmd/entrypoint/args.go
  cmd/entrypoint/args_test.go
  cmd/entrypoint/main.go
  examples/v1beta1/taskruns/5080-entrypoint-init-regression.yaml
Labels: kind/bug, approved, lgtm, size/L, release-note

#5094 Simplify Release Notes section of the PR checklist
  .github/pull_request_template.md
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5101 Fix context.background() in workspaceBinding validation
  pkg/reconciler/taskrun/taskrun.go
  pkg/workspace/validate.go
  pkg/workspace/validate_test.go
Labels: kind/bug, approved, lgtm, size/S, ok-to-test, release-note-none

#5051 Update docs for ResourceQuota and QoS
  docs/compute-resources.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#5046 Clean up validation for task and pipeline refs
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipelineref_types.go
  pkg/apis/pipeline/v1beta1/pipelineref_validation.go
  pkg/apis/pipeline/v1beta1/pipelineref_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/taskref_types.go
  pkg/apis/pipeline/v1beta1/taskref_validation.go
  pkg/apis/pipeline/v1beta1/taskref_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/cleanup

#5095 [0.37: cherry-pick] cmd/entrypoint: do not interpret anything after `--`
  cmd/entrypoint/args.go
  cmd/entrypoint/args_test.go
  cmd/entrypoint/main.go
  examples/v1beta1/taskruns/5080-entrypoint-init-regression.yaml
Labels: kind/bug, approved, lgtm, size/L, release-note

#5083 [TEP-0075] Support Object Results substitution
  docs/pipelines.md
  docs/variables.md
  examples/v1beta1/pipelineruns/alpha/pipeline-object-results.yaml
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/taskrun/validate_resources.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5113 Move two feature flag related functions to config pkg
  pkg/apis/config/feature_flags.go
  pkg/apis/pipeline/v1beta1/pipelineref_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/result_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/taskref_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#5055 Add almost-empty v1 package
  hack/spec-gen/main.go
  hack/update-codegen.sh
  hack/update-openapigen.sh
  pkg/apis/pipeline/v1/doc.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/register.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/task_conversion.go
  pkg/apis/pipeline/v1/task_defaults.go
  pkg/apis/pipeline/v1/task_types.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/pipeline/v1/doc.go
  pkg/client/clientset/versioned/typed/pipeline/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/pipeline/v1/fake/fake_pipeline_client.go
  pkg/client/clientset/versioned/typed/pipeline/v1/fake/fake_task.go
  pkg/client/clientset/versioned/typed/pipeline/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/pipeline/v1/pipeline_client.go
  pkg/client/clientset/versioned/typed/pipeline/v1/task.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/pipeline/interface.go
  pkg/client/informers/externalversions/pipeline/v1/interface.go
  pkg/client/informers/externalversions/pipeline/v1/task.go
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/pipeline/v1/task/fake/fake.go
  pkg/client/injection/informers/pipeline/v1/task/filtered/fake/fake.go
  pkg/client/injection/informers/pipeline/v1/task/filtered/task.go
  pkg/client/injection/informers/pipeline/v1/task/task.go
  pkg/client/injection/reconciler/pipeline/v1/task/controller.go
  pkg/client/injection/reconciler/pipeline/v1/task/reconciler.go
  pkg/client/injection/reconciler/pipeline/v1/task/state.go
  pkg/client/listers/pipeline/v1/expansion_generated.go
  pkg/client/listers/pipeline/v1/task.go
Labels: approved, lgtm, size/XL, release-note-none, kind/misc

#4902 TEP-0075: Validate Pipeline object variables in value, matrix and when
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/when_validation.go
  pkg/substitution/substitution.go
Labels: approved, lgtm, size/L, release-note, kind/misc

#4953 Only create & mount Downward API volume when necessary
  config/config-feature-flags.yaml
  docs/install.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: kind/feature, approved, lgtm, size/L, ok-to-test, release-note

#5119 Exclude managed fields from e2e test failure object YAML dumps
  test/init_test.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5000 Validation for Finally Task Results referenced in Pipeline Results
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note

#5079 Move pipelinespec functions into a separate package
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinespec/pipelinespec.go
  pkg/reconciler/pipelinerun/pipelinespec/pipelinespec_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
Labels: approved, lgtm, size/S, ok-to-test, release-note-none, kind/cleanup

#5060 Publish Pipeline Results from successful TaskRuns in Failed PipelineRuns
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/feature, approved, lgtm, size/L, ok-to-test, release-note-none

#4855 [TEP-0076] Add indexing into array for pipeline params reference
  docs/variables.md
  examples/v1beta1/pipelineruns/alpha/pipelinerun-param-array-indexing.yaml
  pkg/apis/pipeline/v1beta1/param_types_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/validate_params.go
  pkg/reconciler/pipelinerun/resources/validate_params_test.go
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#5088 [TEP-0075]Pipeline results support object
  docs/pipelines.md
  examples/v1beta1/pipelineruns/alpha/pipeline-array-results.yaml
  examples/v1beta1/pipelineruns/alpha/pipeline-emitting-results.yaml
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/resultref.go
  pkg/apis/pipeline/v1beta1/resultref_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5077 Add env files for Kind-in-Prow integration test jobs
  examples/v1beta1/pipelineruns/pipelinerun.yaml
  examples/v1beta1/taskruns/no-ci/git-volume.yaml
  test/e2e-common.sh
  test/e2e-tests-kind-prow-alpha.env
  test/e2e-tests-kind-prow.env
  test/e2e-tests.sh
  test/yamls/v1beta1/pipelineruns/pipelinerun.yaml
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5139 [TEP-0076]Validate Pipeline results array index
  docs/pipelines.md
  examples/v1beta1/pipelineruns/alpha/pipeline-emitting-results.yaml
  pkg/apis/pipeline/v1beta1/resultref.go
  pkg/apis/pipeline/v1beta1/resultref_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#5132 [TEP-0076] Add indexing into array for taskrun params reference
  docs/variables.md
  examples/v1beta1/taskruns/alpha/param_array_indexing.yaml
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/taskrun/validate_resources.go
  pkg/reconciler/taskrun/validate_resources_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#4894 remove spec.replicas from tekton-pipelines-webhook Deployment
  config/webhook.yaml
Labels: kind/bug, approved, lgtm, size/XS, ok-to-test, release-note

#4882 TEP-0011: Add StdoutConfig and StderrConfig to steps.
  cmd/entrypoint/README.md
  cmd/entrypoint/io.go
  cmd/entrypoint/io_test.go
  cmd/entrypoint/main.go
  cmd/entrypoint/runner.go
  cmd/entrypoint/runner_test.go
  docs/tasks.md
  examples/v1beta1/taskruns/alpha/step-stream-results.yaml
  examples/v1beta1/taskruns/alpha/step-stream-volumes.yaml
  examples/v1beta1/taskruns/alpha/step-stream-workspace.yaml
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/merge.go
  pkg/apis/pipeline/v1beta1/merge_test.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/step_replacements.go
  pkg/apis/pipeline/v1beta1/step_replacements_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/step_output_test.go
Labels: kind/feature, approved, lgtm, size/XXL, ok-to-test, release-note

#5144 TEP-0075: Add examples with object params and results
  examples/v1beta1/pipelineruns/alpha/pipeline-object-param.yaml
  examples/v1beta1/taskruns/alpha/object-param-result.yaml
Labels: approved, lgtm, size/M, release-note, kind/misc

#5159 Update log keys to match logstream
  config/config-logging.yaml
Labels: kind/bug, approved, lgtm, size/XS, release-note-action-required

#5162 Fix the issue with empty array replacement
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/param_types_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#5147 [0.35: cherry-pick] Fix TestTaskRunRetry for k8s 1.22.9 and later
  test/retry_test.go
  test/v1alpha1/retry_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#5171 Fix flaky test by sorting slices
  pkg/apis/pipeline/v1beta1/resultref_test.go
Labels: approved, lgtm, size/XS, kind/flake, release-note-none

#5085 Add support for projected volumes as workspace type
  docs/install.md
  docs/workspaces.md
  examples/v1beta1/pipelineruns/alpha/workspaces-projected.yaml
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/workspace_types.go
  pkg/apis/pipeline/v1beta1/workspace_validation.go
  pkg/apis/pipeline/v1beta1/workspace_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
Labels: kind/feature, approved, lgtm, size/L, ok-to-test, release-note

#5178 Include Windows image builds in CI build tests
  tekton/publish.yaml
  test/presubmit-tests.sh
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#5148 [0.36: cherry-pick] Fix TestTaskRunRetry for k8s 1.22.9 and later
  test/retry_test.go
  test/v1alpha1/retry_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#5068 Relax result type validation to avoid nightly build failure
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/result_types.go
  pkg/apis/pipeline/v1beta1/result_validation.go
  pkg/apis/pipeline/v1beta1/result_validation_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
Labels: kind/bug, approved, lgtm, size/L, release-note

#5179 Move step and sidecar replacements to new package
  pkg/container/container_replacements.go
  pkg/container/sidecar_replacements.go
  pkg/container/sidecar_replacements_test.go
  pkg/container/step_replacements.go
  pkg/container/step_replacements_test.go
  pkg/reconciler/taskrun/resources/apply.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#5096 [0.36: cherry-pick] cmd/entrypoint: do not interpret anything after `--`
  cmd/entrypoint/args.go
  cmd/entrypoint/args_test.go
  cmd/entrypoint/main.go
  examples/v1beta1/taskruns/5080-entrypoint-init-regression.yaml
Labels: kind/bug, approved, lgtm, size/L, release-note

#5145 Prepare tests for impending knative/pkg version bump
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#5195 Update GCR IAM settings in Tekton development doc
  DEVELOPMENT.md
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#5201 Add TerminationMessagePolicy in container conversion
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1beta1/container_types.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5199 Add StdoutConfig and StderrorConfig to v1 Step
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1/merge.go
  pkg/apis/pipeline/v1/merge_test.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#5206 Add v0.38.0, v0.37.1, and v0.37.2 to README
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#5205 Update release cheat sheet
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#5197 TEP-0075: Add a pipeline run example with both object param and result
  examples/v1beta1/pipelineruns/alpha/pipeline-object-param-and-result.yaml
  examples/v1beta1/pipelineruns/alpha/pipeline-object-param.yaml
Labels: approved, lgtm, size/L, release-note, kind/misc

#5176 Add SetDefaults for pipelineSpec in reconciler
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/pipelinespec/pipelinespec.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none, needs-cherry-pick

#5210 Do not validate anything on delete ✂
  pkg/apis/pipeline/v1beta1/cluster_task_conversion.go
  pkg/apis/pipeline/v1beta1/cluster_task_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/task_conversion.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
Labels: approved, lgtm, size/M, release-note, kind/misc

#5213 Bump go-scm to 1.11.19
  go.mod
  go.sum
  pkg/pullrequest/api.go
  third_party/github.com/benbjohnson/clock/LICENSE
  vendor/github.com/jenkins-x/go-scm/scm/client.go
  vendor/github.com/jenkins-x/go-scm/scm/const.go
  vendor/github.com/jenkins-x/go-scm/scm/deploy.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/fake/content.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/fake/deploy.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/fake/fake.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/fake/git.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/fake/issue.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/fake/org.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/fake/pr.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/fake/repo.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/fake/review.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/github/deploy.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/github/git.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/github/issue.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/github/org.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/github/pr.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/github/repo.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/github/review.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/github/util.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/github/webhook.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/git.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/issue.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/org.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/pr.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/repo.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/review.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/user.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/util.go
  vendor/github.com/jenkins-x/go-scm/scm/driver/gitlab/webhook.go
  vendor/github.com/jenkins-x/go-scm/scm/git.go
  vendor/github.com/jenkins-x/go-scm/scm/issue.go
  vendor/github.com/jenkins-x/go-scm/scm/org.go
  vendor/github.com/jenkins-x/go-scm/scm/pr.go
  vendor/github.com/jenkins-x/go-scm/scm/repo.go
  vendor/github.com/jenkins-x/go-scm/scm/review.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#5215 Do not serve v1alpha1 for CRDs that do not exists anymore
  config/300-clustertask.yaml
  config/300-pipeline.yaml
  config/300-pipelinerun.yaml
  config/300-task.yaml
  config/300-taskrun.yaml
Labels: kind/bug, approved, lgtm, size/L, priority/critical-urgent, release-note, needs-cherry-pick

#5220 [cherry-pick: v0.38] Do not serve v1alpha1 for CRDs that do not exists anymore
  config/300-clustertask.yaml
  config/300-pipeline.yaml
  config/300-pipelinerun.yaml
  config/300-task.yaml
  config/300-taskrun.yaml
Labels: kind/bug, approved, lgtm, size/L, release-note

#5216 Add Tep 75&76 to install doc
  docs/install.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#5217 [cherry-pick: v0.38] Add SetDefaults for pipelineSpec in reconciler
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/pipelinespec/pipelinespec.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5198 Fail taskrun when results validation fails
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#5167 Fix ApplyTaskResultsToPipelineResults missing object validation
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#5142 [TEP-0075]Add more setdefaults features for taskresults
  pkg/apis/pipeline/v1/result_defaults.go
  pkg/apis/pipeline/v1/result_defaults_test.go
  pkg/apis/pipeline/v1beta1/result_defaults.go
  pkg/apis/pipeline/v1beta1/result_defaults_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5236 Use step.ImageID instead of looking into status.TaskSpec
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#5231 Skip validation for deletion of v1 task
  pkg/apis/pipeline/v1/task_validation.go
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#5228 Rename tests in TestPipelineTaskList_Deps
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5227 Remove not supported results and params variables doc
  docs/variables.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none
