Repository tektoncd/pipeline, pull requests merged in 2022-03, with the labels that each got.

#4634 workspace-in-sidecar flakey test fix
  examples/v1beta1/taskruns/alpha/workspace-in-sidecar.yaml
  examples/v1beta1/taskruns/workspace-in-sidecar.yaml
Labels: approved, lgtm, size/XS, kind/flake, release-note

#4625 Update IsFailure method to reflect Run retries
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#4635 TEP-0090: Refactor execution status validation
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, lgtm, size/L, release-note

#4627 refactor TestReconcile_PipelineSpecTaskSpec result
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note, kind/cleanup

#4616 cleaning up a unit test InvalidPipelineRuns to use YAML parser
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/cleanup

#4639 Build tekton pipelines with golang 1.17
  images/windows/entrypoint/Dockerfile
  images/windows/nop/Dockerfile
  tekton/build-push-ma-base-image.yaml
  tekton/publish.yaml
Labels: approved, lgtm, size/S, release-note, kind/misc

#4644 Remove unused windows dockerfiles
  images/windows/entrypoint/Dockerfile
  images/windows/nop/Dockerfile
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#4617 Add functions to merge step/sidecar overrides
  pkg/apis/pipeline/v1beta1/merge.go
  pkg/apis/pipeline/v1beta1/merge_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#4637 clean up reconcile unit test to use YAML parser
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note, kind/cleanup

#4650 Add links to docs and examples for 4 minor releases
  README.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#4647 Update getNextTasks to support Run retries
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#4649 go.mod: bump containerd dependency to 1.5.10
  go.mod
  go.sum
  vendor/github.com/klauspost/compress/README.md
  vendor/github.com/klauspost/compress/huff0/decompress.go
  vendor/github.com/klauspost/compress/huff0/huff0.go
  vendor/github.com/klauspost/compress/zstd/enc_fast.go
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS, release-note-none

#4646 Add log line to debg workspace-in-sidecar example
  examples/v1beta1/taskruns/alpha/workspace-in-sidecar.yaml
  examples/v1beta1/taskruns/workspace-in-sidecar.yaml
Labels: approved, lgtm, size/XS, kind/flake, release-note-none

#4632 cleanup - refactor taskRunStatus and runStatus unit tests
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  test/parse/yaml.go
Labels: approved, lgtm, size/XL, release-note-none, kind/cleanup

#4658 Add GetStatusCondition for Run
  pkg/apis/pipeline/v1alpha1/run_types.go
  pkg/reconciler/events/cloudevent/interface.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#4630 Change Default Metrics Level for Taskrun and Pipelinerun
  config/config-observability.yaml
  docs/metrics.md
  pkg/apis/config/metrics.go
  pkg/apis/config/metrics_test.go
  pkg/pipelinerunmetrics/metrics_test.go
  pkg/taskrunmetrics/metrics_test.go
Labels: approved, lgtm, size/S, release-note

#4598 Implement Step and Sidecar Overrides for TaskRun
  docs/taskruns.md
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/validate_resources.go
  pkg/reconciler/taskrun/validate_resources_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4662 Update API reference docs for TaskRun
  docs/taskruns.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4663 Implement CloudEvents for Runs
  cmd/controller/main.go
  config/config-feature-flags.yaml
  docs/events.md
  docs/install.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/reconciler/events/cache/cache.go
  pkg/reconciler/events/cache/cache_test.go
  pkg/reconciler/events/cache/cacheclient.go
  pkg/reconciler/events/cache/cachefakeclient.go
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/events/cloudevent/cloudeventclient.go
  pkg/reconciler/events/cloudevent/cloudeventsfakeclient.go
  pkg/reconciler/events/event.go
  pkg/reconciler/events/event_test.go
  pkg/reconciler/run/controller.go
  pkg/reconciler/run/run.go
  pkg/reconciler/run/run_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#4670 Refactor Pipeline Workspaces Validation
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, lgtm, size/L, release-note, kind/cleanup

#4093 Move namespace.yaml to avoid unintended deletion of other components
  DEVELOPMENT.md
  Makefile
  config/100-namespace/100-namespace.yaml
  tekton/publish.yaml
  test/README.md
  test/e2e-common.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M, kind/documentation, ok-to-test, release-note

#4638 Fix Task(Run)/Pipeline(Run) metadata propagation
  docs/labels.md
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/L, release-note

#4608 set the param type based on the default value
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/param_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#4678 Fix incorrect format specifier in test files
  test/remote_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#4679 Fix incorrect format specifier in test files
  test/remote_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#4680 Fix incorrect format specifier in test files
  test/remote_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#4685 Pipeline Context Variables - Fix Validation Tests
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, lgtm, size/S, release-note

#4684 Add validation for PipelineTask context variables
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#4677 Update the release cheatsheet to the new release drafter
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#4692 Update taskrun code example links in the documentation
  docs/taskruns.md
Labels: approved, lgtm, size/S, ok-to-test, release-note

#4689 TEP-0090: Matrix - Context Variables
  docs/matrix.md
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4693 refactor reconcile pipeline TaskSpecMetadata test
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note, kind/cleanup

#4683 Add hostAliases to podTemplate doc
  docs/podtemplates.md
Labels: approved, lgtm, size/XS, release-note

#4682 refactor create helpers in reconcile pr tests
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note, kind/cleanup

#4667 PipelineRunState cleanup: tests + comments
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#4701 Update build pipeline to golang 1.17.8
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note, kind/misc

#4700 Update build pipeline to golang 1.17.8
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note, kind/misc

#4698 Add v0.34.0 and v0.33.3 to the README
  README.md
Labels: approved, lgtm, size/L, kind/documentation, release-note

#4704 TEP-0090: `Matrix` - `Parameters`
  docs/matrix.md
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4707 TEP-0090: `Matrix` - `Results`
  docs/matrix.md
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4702 [V1] Add new API versions to /config
  config/300-pipeline.yaml
  config/300-pipelinerun.yaml
  config/300-run.yaml
  config/300-task.yaml
  config/300-taskrun.yaml
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#4703 Add example for PipelineRun namespace context variable
  docs/pipelines.md
  examples/v1beta1/pipelineruns/using_context_variables.yaml
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#4695 Fix TestReconcileOnCompletedTaskRun
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/XS, ok-to-test, release-note-none

#4592 Fix existing LGTM issues
  pkg/pod/status.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#4400 Add some switches to the e2e script ⚙️
  test/e2e-tests-kind.env
  test/e2e-tests.sh
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#4714 Fix gofmt failure on go 1.17.8
  hack/tools.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  test/artifact_bucket_test.go
  test/cancel_test.go
  test/cluster_resource_test.go
  test/conformance_test.go
  test/custom_task_test.go
  test/dag_test.go
  test/duplicate_test.go
  test/embed_test.go
  test/entrypoint_test.go
  test/examples_test.go
  test/git_checkout_test.go
  test/helm_task_test.go
  test/hermetic_taskrun_test.go
  test/ignore_step_error_test.go
  test/init_test.go
  test/kaniko_task_test.go
  test/ko_test.go
  test/path_filtering.go
  test/path_filtering_test.go
  test/pipelinefinally_test.go
  test/pipelinerun_test.go
  test/pullrequest/e2e_test.go
  test/registry_test.go
  test/retry_test.go
  test/secret.go
  test/serviceaccount_test.go
  test/start_time_test.go
  test/status_test.go
  test/taskrun_test.go
  test/tektonbundles_test.go
  test/v1alpha1/artifact_bucket_test.go
  test/v1alpha1/cancel_test.go
  test/v1alpha1/cluster_resource_test.go
  test/v1alpha1/duplicate_test.go
  test/v1alpha1/embed_test.go
  test/v1alpha1/entrypoint_test.go
  test/v1alpha1/git_checkout_test.go
  test/v1alpha1/init_test.go
  test/v1alpha1/kaniko_task_test.go
  test/v1alpha1/pipelinerun_test.go
  test/v1alpha1/registry_test.go
  test/v1alpha1/retry_test.go
  test/v1alpha1/secret.go
  test/v1alpha1/sidecar_test.go
  test/v1alpha1/start_time_test.go
  test/v1alpha1/status_test.go
  test/v1alpha1/taskrun_test.go
  test/v1alpha1/timeout_test.go
  test/v1alpha1/wait_example_test.go
  test/v1alpha1/workingdir_test.go
  test/v1alpha1/workspace_test.go
  test/wait_example_test.go
  test/windows_script_test.go
  test/windows_test.go
  test/workingdir_test.go
  test/workspace_test.go
  tools/tools.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#4715 TEP-0059: Remove `scope-when-expressions-to-task` feature flag
  config/config-feature-flags.yaml
  docs/deprecations.md
  docs/install.md
  docs/pipelines.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/apis/config/testdata/feature-flags-invalid-scope-when-expressions-to-task.yaml
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
Labels: approved, lgtm, size/L, release-note

#4719 k8s 1.21 is the minimum required
  DEVELOPMENT.md
  docs/api-spec.md
  docs/install.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#4713 Fix the xml report generation for kind e2e jobs
  go.mod
  go.sum
  test/e2e-tests-kind.env
  test/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/.gitignore
  vendor/github.com/tektoncd/plumbing/adjustpermissions.py
  vendor/github.com/tektoncd/plumbing/requirements.txt
  vendor/github.com/tektoncd/plumbing/scripts/deploy-release.sh
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#4724 Add links to readme and docs for several minor releases
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4718 PullRequest PipelineResource expects root
  .ko.yaml
  pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource.go
  pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource_test.go
  tekton/publish.yaml
Labels: approved, lgtm, size/M, release-note, kind/misc
