Repository tektoncd/pipeline, pull requests merged in 2022-01, with the labels that each got.

#4374 Avoid API server call to get Pod when sidecars are stopped
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4436 test/sidecar_test.go: replace t.Errorfs with t.Fatalfs
  test/sidecar_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#4352 Lockdown /tekton/step folders to their own steps.
  cmd/entrypoint/main.go
  cmd/entrypoint/post_writer.go
  cmd/entrypoint/post_writer_test.go
  cmd/entrypoint/subcommands/step_init.go
  cmd/entrypoint/subcommands/step_init_test.go
  cmd/entrypoint/subcommands/subcommands.go
  cmd/entrypoint/subcommands/subcommands_test.go
  docs/developers/README.md
  examples/v1beta1/taskruns/readonly-internal-dir.yaml
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#4434 Reduce RBAC permissions for Tekton controller/webhook roles.
  config/200-clusterrole.yaml
Labels: approved, lgtm, size/S, release-note, kind/cleanup

#4437 subcommands_test: Group command tests with t.Run.
  cmd/entrypoint/subcommands/subcommands_test.go
Labels: approved, lgtm, size/M, release-note, kind/cleanup

#4439 Match k8s recommended restricted PSP.
  config/101-podsecuritypolicy.yaml
Labels: kind/feature, approved, lgtm, size/S, release-note

#4451 scripts: remove set -x by default 🧣
  docs/tasks.md
  pkg/pod/script.go
  pkg/pod/script_test.go
  test/tektonbundles_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#4452 Skip creds-init-only-mounts-provided-credentials test for linux/s390x
  test/multiarch_utils.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#4447 Refactor PipelineRun timeout logic
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/L, release-note, kind/cleanup

#4456 Add image replacement for amd64 specific image
  test/multiarch_utils.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#4442 Remove `--enable-basic-auth` from the development guide
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS, release-note, kind/cleanup

#4462 Fix links in `when` expressions migrations announcements
  docs/deprecations.md
Labels: approved, lgtm, size/XS, release-note, kind/cleanup

#4441 Reduce duplication in TaskRun reconciler tests
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#4411 Don't install golangci-lint with curl|bash, use go install, introduce the tools folder
  Makefile
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: approved, lgtm, size/S, ok-to-test, release-note, kind/misc

#4464 git: Remove usage of git symbolic-ref.
  pkg/git/git.go
Labels: kind/bug, approved, lgtm, size/XS, release-note

#4459 Remove unused informers
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/M, release-note

#4450 set activeDeadlineSeconds to max for tasks with notimeouts
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#4480 Pass explicit platforms list when publishing images
  tekton/release-pipeline.yaml
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#4479 Clean up RunsToCompletion interface
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/reconciler/events/cloudevent/interface.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#4481 `Timeout` and `TaskSpec` supported in `Custom Tasks`
  pkg/apis/pipeline/v1alpha1/run_types.go
Labels: approved, lgtm, size/XS, release-note, kind/cleanup

#4482 Add docs links for v0.32.0
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4474 Include Windows builds of cmd/nop in release process
  tekton/publish.yaml
Labels: kind/feature, approved, lgtm, size/XS, release-note

#4440 Use pr.Timeouts.Pipeline in Custom Task reconcile
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#4466 Move kind development instructions to top of dev cluster instructions.
  DEVELOPMENT.md
Labels: approved, lgtm, size/M, kind/documentation, release-note

#4486 Separate buildPlatforms and publishPlatforms
  tekton/build-push-ma-base-image.yaml
  tekton/release-pipeline.yaml
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#4472 Update docs to reflect resource requests of pods
  docs/limitrange.md
  docs/tasks.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#4475 Support workingDir init on Windows
  cmd/controller/main.go
  cmd/workingdirinit/main.go
  config/controller.yaml
  pkg/apis/pipeline/images.go
  pkg/apis/pipeline/images_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/workingdir_init.go
  pkg/pod/workingdir_init_test.go
  tekton/publish.yaml
Labels: kind/feature, approved, lgtm, size/M, release-note

#4487 Provide testing implementation of time.Now()
  cmd/controller/main.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1alpha1/run_types.go
  pkg/apis/pipeline/v1alpha1/run_types_test.go
  pkg/apis/pipeline/v1alpha1/taskrun_types.go
  pkg/apis/pipeline/v1alpha1/taskrun_types_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/clock/clock.go
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#4495 Fix incorrect format specifier in test files
  test/remote_test.go
Labels: approved, lgtm, size/S, release-note-none

#4465 Update hack scripts to shim temp GOPATH as needed
  .gitignore
  hack/setup-temporary-gopath.sh
  hack/update-codegen.sh
  hack/update-openapigen.sh
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#4497 Move to Go 1.16
  go.mod
  go.sum
  third_party/LICENSE
  third_party/github.com/hashicorp/errwrap/errwrap_test.go
  third_party/github.com/hashicorp/go-multierror/.circleci/config.yml
  third_party/github.com/hashicorp/go-multierror/append_test.go
  third_party/github.com/hashicorp/go-multierror/flatten_test.go
  third_party/github.com/hashicorp/go-multierror/format_test.go
  third_party/github.com/hashicorp/go-multierror/group_test.go
  third_party/github.com/hashicorp/go-multierror/multierror_test.go
  third_party/github.com/hashicorp/go-multierror/prefix_test.go
  third_party/github.com/hashicorp/go-multierror/sort_test.go
  third_party/github.com/hashicorp/golang-lru/2q_test.go
  third_party/github.com/hashicorp/golang-lru/arc_test.go
  third_party/github.com/hashicorp/golang-lru/lru_test.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_test.go
  third_party/vendor/golang.org/x/crypto/LICENSE
  third_party/vendor/golang.org/x/net/LICENSE
  third_party/vendor/golang.org/x/text/LICENSE
  tools/go.mod
  vendor/modules.txt
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#4498 Add bash v4+ requirement to the development guide
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#4478 Fix Pipeline/Task to *Run label/annotation propagation 🥨
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note, needs-cherry-pick

#4489 Drop minishift instructions
  docs/install.md
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#4504 Revert 49a7fa to remove fake AWS creds
  config/controller.yaml
Labels: approved, lgtm, size/S, release-note, kind/misc

#4484 Implicit params: only propagate params to embedded TaskSpecs in Pipelines.
  pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note, needs-cherry-pick

#4505 Add copyright notice to clock.go
  pkg/clock/clock.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#4506 Account for PipelineRun elapsed time for timeouts
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#4507 Update README.md
  tekton/README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4511 Disable implicit param behavior for Pipeline objects.
  pkg/apis/pipeline/v1beta1/implicit_params_test.go
  pkg/apis/pipeline/v1beta1/param_context.go
  pkg/apis/pipeline/v1beta1/param_context_test.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1beta1/task_defaults.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults_test.go
  third_party/vendor/golang.org/x/sys/cpu/LICENSE
Labels: approved, lgtm, size/XL, release-note, needs-cherry-pick, kind/misc

#4521 Update Dockerfiles using golang images to Go 1.16.13
  images/windows/entrypoint/Dockerfile
  images/windows/nop/Dockerfile
Labels: approved, lgtm, size/XS, release-note, kind/misc

#4517 Update install docs to mention firewall reqs
  docs/install.md
Labels: approved, lgtm, size/XS, release-note-none

#4530 Add doc links for 0.29.1, 0.30.1, 0.31.1 and 0.32.1
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#4509 Update the release notes to describe kustomize usage
  tekton/README.md
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#4536 Add doc links for Pipelines 0.28.3
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none
