Repository tektoncd/pipeline, pull requests merged in 2022-08, with the labels that each got.

#5245 [0.37: cherry-pick] Use step.ImageID instead of looking into status.TaskSpec
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#5246 [0.38: cherry-pick] Use step.ImageID instead of looking into status.TaskSpec
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#5237 Make sure that OpenAPI rules violations errors show up in Prow build logs
  hack/update-openapigen.sh
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5244 Docs: Updated installation customizations link
  docs/matrix.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#5202 Add conversion for v1 Task
  pkg/apis/pipeline/v1/task_conversion.go
  pkg/apis/pipeline/v1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/container_conversion.go
  pkg/apis/pipeline/v1beta1/param_conversion.go
  pkg/apis/pipeline/v1beta1/result_conversion.go
  pkg/apis/pipeline/v1beta1/task_conversion.go
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/workspace_conversion.go
Labels: approved, lgtm, size/XL, release-note-none, kind/misc

#5169 Add validation for results object properties types
  pkg/apis/pipeline/v1/result_validation.go
  pkg/apis/pipeline/v1/result_validation_test.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/result_validation.go
  pkg/apis/pipeline/v1beta1/result_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#5257 Refactor compute resources compare functions
  pkg/internal/computeresources/compare/compare.go
  pkg/internal/computeresources/limitrange/limitrange.go
  pkg/internal/computeresources/limitrange/limitrange_test.go
  pkg/internal/computeresources/transformer.go
  pkg/internal/computeresources/transformer_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#5260 Bump TestSidecarTaskSupport test timeout to 2m.
  test/sidecar_test.go
Labels: approved, lgtm, size/XS, kind/flake, release-note-none

#5070 Results Lifecycle
  docs/developers/results-lifecycle.md
Labels: approved, lgtm, size/M, kind/documentation, release-note

#5207 Update docs with matrix csi workspace release number
  docs/install.md
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5212 [TEP-0104] Populate Task-level Resource Requirements from PipelineRun to TaskRun
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#5224 Add a status_msg field to fix issue 5150.
  docs/runs.md
  pkg/apis/pipeline/v1alpha1/run_types.go
  pkg/apis/pipeline/v1alpha1/run_types_test.go
  pkg/apis/pipeline/v1alpha1/run_validation.go
  pkg/apis/pipeline/v1alpha1/run_validation_test.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/cancel_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/cancel_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5273 Updates Default Fields When Creating a GKE Cluster
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#5272 Fix conversion related typos
  pkg/apis/pipeline/v1beta1/cluster_task_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#5235 Add instructions for creating a new API version
  docs/developers/adding-a-new-apiversion.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#5276 Fix a typo in 5080-entrypoint-init-regression.yaml
  examples/v1beta1/taskruns/5080-entrypoint-init-regression.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5222 [TEP-0075] Add variable usage and links to examples in docs
  docs/tasks.md
  docs/variables.md
Labels: approved, lgtm, size/S, release-note, kind/misc

#5219 Add V1 Pipeline Golang structs
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/param_types_test.go
  pkg/apis/pipeline/v1/pipeline_defaults.go
  pkg/apis/pipeline/v1/pipeline_defaults_test.go
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/register.go
  pkg/apis/pipeline/v1/resultref.go
  pkg/apis/pipeline/v1/resultref_test.go
  pkg/apis/pipeline/v1/status_validation.go
  pkg/apis/pipeline/v1/status_validation_test.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/taskref_types.go
  pkg/apis/pipeline/v1/taskref_validation.go
  pkg/apis/pipeline/v1/taskref_validation_test.go
  pkg/apis/pipeline/v1/when_types.go
  pkg/apis/pipeline/v1/when_types_test.go
  pkg/apis/pipeline/v1/when_validation.go
  pkg/apis/pipeline/v1/when_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/pipeline/v1/fake/fake_pipeline.go
  pkg/client/clientset/versioned/typed/pipeline/v1/fake/fake_pipeline_client.go
  pkg/client/clientset/versioned/typed/pipeline/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/pipeline/v1/pipeline.go
  pkg/client/clientset/versioned/typed/pipeline/v1/pipeline_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/pipeline/v1/interface.go
  pkg/client/informers/externalversions/pipeline/v1/pipeline.go
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/pipeline/v1/pipeline/fake/fake.go
  pkg/client/injection/informers/pipeline/v1/pipeline/filtered/fake/fake.go
  pkg/client/injection/informers/pipeline/v1/pipeline/filtered/pipeline.go
  pkg/client/injection/informers/pipeline/v1/pipeline/pipeline.go
  pkg/client/injection/reconciler/pipeline/v1/pipeline/controller.go
  pkg/client/injection/reconciler/pipeline/v1/pipeline/reconciler.go
  pkg/client/injection/reconciler/pipeline/v1/pipeline/state.go
  pkg/client/listers/pipeline/v1/expansion_generated.go
  pkg/client/listers/pipeline/v1/pipeline.go
Labels: approved, lgtm, size/XXL, ok-to-test, release-note-none, kind/misc

#5279 Add tests for limitrange transformer
  pkg/internal/computeresources/transformer_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#5277 Fix task conversion test typo
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5170 TEP-0116: Referencing Finally Task Results in Pipeline Results
  docs/pipelines.md
  examples/v1beta1/pipelineruns/pipelinerun-with-final-results.yaml
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/resultref.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
Labels: kind/feature, approved, lgtm, size/XL, ok-to-test, release-note

#5238 TEP-0115: Update Git Resolver example to use revision and pathInRepo fields
  docs/pipelineruns.md
  docs/taskruns.md
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#5287 Unscheduled Runs shouldn't be included in full status
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note, needs-cherry-pick

#5166 Fix the Tekton controller panic for Metrics
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#5295 v0.37.x: Unscheduled Runs shouldn't be included in full status
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5296 Unscheduled Runs shouldn't be included in full status
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5299 Update a few missing versions in the README
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#5204 Add TopologySpreadConstraints in PodTemplate
  docs/podtemplates.md
  pkg/apis/pipeline/pod/template.go
  pkg/apis/pipeline/pod/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pod.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: kind/feature, approved, lgtm, size/L, ok-to-test, release-note

#5310 Bump golangci-lint to v1.47.2 to support Go 1.18.x
  Makefile
  pkg/apis/pipeline/paths.go
  pkg/pod/creds_init.go
  tools/go.mod
  tools/go.sum
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#5284 Modified test to allow for validation
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note-none

#5312 Test feature flags
  test/featureflags.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5258 Add conversion for v1 Pipeline
  pkg/apis/pipeline/v1/pipeline_conversion.go
  pkg/apis/pipeline/v1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1beta1/param_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1beta1/resolver_conversion.go
  pkg/apis/pipeline/v1beta1/taskref_conversion.go
  pkg/apis/pipeline/v1beta1/workspace_conversion.go
Labels: approved, lgtm, size/XL, release-note-none, kind/misc

#5143 Move parameter validation from `taskspec` to `taskrunspec` when propagating parameters
  pkg/apis/config/contexts.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/cluster_task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5307 support parameterization for `steps[].onError`
  docs/variables.md
  examples/v1beta1/pipelineruns/ignore-step-error.yaml
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/container/step_replacements.go
  pkg/container/step_replacements_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5314 Reformat CustomTask within Test
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note-none, kind/cleanup

#5301 Fix typo in tekton/publish.yaml
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5124 Make container docs more tailored to Tekton
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
Labels: approved, lgtm, size/XL, kind/documentation, release-note-none

#5305 TEP-0090: Matrix - Retries
  docs/matrix.md
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5291 Move validation from `pipelinespec` to `pipelinerunspec` when propagating parameters
  pkg/apis/config/contexts.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/cluster_task_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5319 Move version validation tests into separate package
  pkg/apis/version/version_validation_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#5304 Rename ArrayOrString to ParamValues
  docs/api-spec.md
  docs/pipeline-api.md
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/param_types_test.go
  pkg/apis/pipeline/v1/pipeline_defaults_test.go
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/result_types.go
  pkg/apis/pipeline/v1/resultref_test.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1alpha1/run_types_test.go
  pkg/apis/pipeline/v1alpha1/run_validation_test.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/param_conversion.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/param_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/result_types.go
  pkg/apis/pipeline/v1beta1/resultref_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/entrypoint/entrypointer_test.go
  pkg/matrix/matrix_test.go
  pkg/matrix/matrix_types.go
  pkg/matrix/matrix_types_test.go
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/reconciler/pipeline/dag/dag_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  pkg/reconciler/pipelinerun/resources/validate_dependencies_test.go
  pkg/reconciler/pipelinerun/resources/validate_params_test.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/taskrun/validate_resources.go
  pkg/reconciler/taskrun/validate_resources_test.go
  test/custom_task_test.go
Labels: approved, lgtm, size/XXL, release-note, kind/cleanup

#5234 Add V1 version to Task CRD
  cmd/webhook/main.go
  config/300-task.yaml
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5253 V1: Add conversion for Task.Resources
  pkg/apis/pipeline/v1beta1/task_conversion.go
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/version/conversion.go
  pkg/apis/version/conversion_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#5082 [TEP-0104] Update Pod with Task-level Resource Requirements
  docs/compute-resources.md
  pkg/internal/computeresources/tasklevel/tasklevel.go
  pkg/internal/computeresources/tasklevel/tasklevel_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#5326 Make update-reference-docs.sh OSX compatible.
  hack/update-reference-docs.sh
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#5323 Uncomment tests in v1 task_validation_test.go
  pkg/apis/pipeline/v1/task_validation_test.go
Labels: kind/bug, approved, lgtm, size/XXL, release-note-none

#5322 Convert Step OnError from string to "OnErrorType" type
  docs/pipeline-api.md
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/container_conversion.go
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/container/step_replacements.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
Labels: approved, lgtm, size/L, release-note, kind/cleanup

#5333 build entrypoint image for Windows ltsc2019 and ltsc2022
  go.mod
  go.sum
  tekton/publish.yaml
  vendor/github.com/tektoncd/plumbing/cmd/combine/README.md
  vendor/github.com/tektoncd/plumbing/cmd/combine/main.go
  vendor/modules.txt
Labels: kind/feature, approved, lgtm, size/XS, release-note

#5288 Make pipeline cancel robust to missing resources
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/cancel_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5347 updating readme with the last two releases
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#5134 Switch PipelineRun timeout -> TaskRun logic to instead signal the TaskRuns to stop
  docs/taskruns.md
  pkg/apis/pipeline/v1alpha1/run_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/cancel_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/pipelinerun/timeout.go
  pkg/reconciler/pipelinerun/timeout_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/timeout_test.go
Labels: kind/bug, approved, lgtm, size/XXL, release-note

#5341 chore: change ghcr.io/distroless/* to distroless.dev/*
  .ko.yaml
  config/controller.yaml
  tekton/publish.yaml
  test/presubmit-tests.sh
Labels: approved, lgtm, size/S, release-note, kind/cleanup

#5313 Check and/or add to sent cloud event cache in one operation
  pkg/reconciler/events/cache/cache.go
  pkg/reconciler/events/cache/cache_test.go
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  test/events/events.go
Labels: approved, lgtm, size/M, kind/flake, release-note-none

#5332 TEP-0114: Custom Task E2E Test with A Controller Installed
  test/custom_task_test.go
  test/wait-task/README.md
  test/wait-task/cmd/controller/main.go
  test/wait-task/config/controller.yaml
  test/wait-task/go.mod
  test/wait-task/go.sum
  test/wait-task/pkg/reconciler/reconciler.go
  test/wait-task/pkg/reconciler/reconciler_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#5256 Clarify error message for verify-codegen.sh
  hack/verify-codegen.sh
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5354 Add CSI and Projected Workspace to V1
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/workspace_types.go
  pkg/apis/pipeline/v1/workspace_validation.go
  pkg/apis/pipeline/v1/workspace_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#5331 V1: Add conversion for Pipeline.Resources
  pkg/apis/pipeline/v1beta1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion_test.go
  pkg/apis/version/conversion_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note-none, kind/misc

#5356 TEP-0114: Tests Wait Custom Task without CRD in PipelineRun
  test/custom_task_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#5366 Update the release cheatsheet to include release resources
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#5367 Remove @sbwsg -- account deleted.
  topical-ownership.md
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#5264 Add V1 TaskRun Golang structs
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/taskrun_defaults.go
  pkg/apis/pipeline/v1/taskrun_defaults_test.go
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/taskrun_types_test.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/pipeline/v1/fake/fake_pipeline_client.go
  pkg/client/clientset/versioned/typed/pipeline/v1/fake/fake_taskrun.go
  pkg/client/clientset/versioned/typed/pipeline/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/pipeline/v1/pipeline_client.go
  pkg/client/clientset/versioned/typed/pipeline/v1/taskrun.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/pipeline/v1/interface.go
  pkg/client/informers/externalversions/pipeline/v1/taskrun.go
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/pipeline/v1/taskrun/fake/fake.go
  pkg/client/injection/informers/pipeline/v1/taskrun/filtered/fake/fake.go
  pkg/client/injection/informers/pipeline/v1/taskrun/filtered/taskrun.go
  pkg/client/injection/informers/pipeline/v1/taskrun/taskrun.go
  pkg/client/injection/reconciler/pipeline/v1/taskrun/controller.go
  pkg/client/injection/reconciler/pipeline/v1/taskrun/reconciler.go
  pkg/client/injection/reconciler/pipeline/v1/taskrun/state.go
  pkg/client/listers/pipeline/v1/expansion_generated.go
  pkg/client/listers/pipeline/v1/taskrun.go
Labels: approved, lgtm, size/XXL, release-note-none, kind/misc

#5349 Add V1 version of Pipeline CRD
  cmd/webhook/main.go
  config/300-pipeline.yaml
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5360 knative/pkg: bump to release-1.7.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5370 Log namespaces left in place after e2e testing.
  test/init_test.go
Labels: approved, lgtm, size/XS, release-note, kind/cleanup

#5274 Add conversion for v1 TaskRun
  pkg/apis/pipeline/v1/taskrun_conversion.go
  pkg/apis/pipeline/v1/taskrun_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/apis/pipeline/v1beta1/workspace_conversion.go
Labels: approved, lgtm, size/XL, release-note-none, kind/misc

#5378 V1: Add conversion for TaskRun.Resources
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5382 Get rid 'pipelienrun'
  pkg/apis/config/metrics.go
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#5380 Move over the resolver framework from Resolution.
  pkg/resolution/resolver/framework/configstore.go
  pkg/resolution/resolver/framework/configstore_test.go
  pkg/resolution/resolver/framework/controller.go
  pkg/resolution/resolver/framework/fakeresolver.go
  pkg/resolution/resolver/framework/interface.go
  pkg/resolution/resolver/framework/reconciler.go
  pkg/resolution/resolver/framework/reconciler_test.go
  pkg/resolution/resolver/framework/testing/fakecontroller.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note-none

#5386 Fix taskrun_validation_test Version
  pkg/apis/pipeline/v1/taskrun_validation_test.go
Labels: kind/bug, approved, lgtm, size/XL, release-note-none

#5385 Add ResolutionRequest to webhook and controller, add resolution docs
  cmd/controller/main.go
  cmd/webhook/main.go
  config/200-clusterrole.yaml
  docs/README.md
  docs/bundle-resolver.md
  docs/git-resolver.md
  docs/how-to-write-a-resolver.md
  docs/hub-resolver.md
  docs/install.md
  docs/resolution-getting-started.md
  docs/resolution.md
  docs/resolver-reference.md
  docs/resolver-template/README.md
  docs/resolver-template/cmd/demoresolver/main.go
  docs/resolver-template/cmd/demoresolver/main_test.go
  docs/resolver-template/config/demo-resolver-deployment.yaml
  docs/resolver-template/test-resolver-template.yaml
Labels: kind/feature, approved, lgtm, size/XXL, release-note-none

#5388 Metrics: Nil Derefence when TR/PR not found
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#5374 Replace time.After with NewTimers
  cmd/entrypoint/waiter_test.go
  pkg/pipelinerunmetrics/metrics.go
  pkg/taskrunmetrics/metrics.go
Labels: approved, lgtm, size/M, release-note, kind/security

#5387 Support parameter substitution for resolver params
  pkg/apis/pipeline/v1/taskref_validation.go
  pkg/apis/pipeline/v1/taskref_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelineref_validation.go
  pkg/apis/pipeline/v1beta1/pipelineref_validation_test.go
  pkg/apis/pipeline/v1beta1/taskref_validation.go
  pkg/apis/pipeline/v1beta1/taskref_validation_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  test/resolution.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#5379 Add V1 version of TaskRun CRD
  cmd/webhook/main.go
  config/300-taskrun.yaml
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5396 Fix TestYamls for change in `ko create`
  test/examples_test.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5252 Fix for ResourceQuotaConflictError
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note

#5395 Add resolvers deployment, with release and e2e integration
  cmd/resolvers/main.go
  config/config-feature-flags.yaml
  config/resolvers/200-clusterrole.yaml
  config/resolvers/200-role.yaml
  config/resolvers/200-serviceaccount.yaml
  config/resolvers/201-clusterrolebinding.yaml
  config/resolvers/201-rolebinding.yaml
  config/resolvers/bundleresolver-config.yaml
  config/resolvers/git-resolver-config.yaml
  config/resolvers/hubresolver-config.yaml
  config/resolvers/resolvers-deployment.yaml
  pkg/resolution/resolver/hub/resolver.go
  tekton/publish.yaml
  tekton/release-pipeline.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/featureflags.go
  test/presubmit-tests.sh
  test/resolvers_test.go
  test/tektonbundles_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-action-required
