Repository tektoncd/pipeline, pull requests merged in 2022-09, with the labels that each got.

#5410 git-resolver.md should refer to `default-revision`, not `default-branch`
  docs/git-resolver.md
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#5324 Add V1 PipelineRun Golang struct
  docs/pipeline-api.md
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/pipelineref_types.go
  pkg/apis/pipeline/v1/pipelineref_validation.go
  pkg/apis/pipeline/v1/pipelineref_validation_test.go
  pkg/apis/pipeline/v1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/apis/pipeline/v1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/pipeline/v1/fake/fake_pipeline_client.go
  pkg/client/clientset/versioned/typed/pipeline/v1/fake/fake_pipelinerun.go
  pkg/client/clientset/versioned/typed/pipeline/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/pipeline/v1/pipeline_client.go
  pkg/client/clientset/versioned/typed/pipeline/v1/pipelinerun.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/pipeline/v1/interface.go
  pkg/client/informers/externalversions/pipeline/v1/pipelinerun.go
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/pipeline/v1/pipelinerun/fake/fake.go
  pkg/client/injection/informers/pipeline/v1/pipelinerun/filtered/fake/fake.go
  pkg/client/injection/informers/pipeline/v1/pipelinerun/filtered/pipelinerun.go
  pkg/client/injection/informers/pipeline/v1/pipelinerun/pipelinerun.go
  pkg/client/injection/reconciler/pipeline/v1/pipelinerun/controller.go
  pkg/client/injection/reconciler/pipeline/v1/pipelinerun/reconciler.go
  pkg/client/injection/reconciler/pipeline/v1/pipelinerun/state.go
  pkg/client/listers/pipeline/v1/expansion_generated.go
  pkg/client/listers/pipeline/v1/pipelinerun.go
  third_party/github.com/hashicorp/errwrap/errwrap.go
Labels: approved, lgtm, size/XXL, ok-to-test, release-note-none, kind/misc

#5411 Add more unit tests for using non-exist key of an object in task step
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: approved, lgtm, size/M, release-note, kind/misc

#5418 Add docs/pipeline-api.md.backup to .gitignore
  .gitignore
  hack/update-reference-docs.sh
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5422 Bump github.com/emicklei/go-restful from v2.15.0+incompatible to v2.16.0+incompatible
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/cleanup

#5424 Restore results dependencies in v1 Pipeline
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#5398 test: use `T.Setenv` to set env vars in tests
  pkg/apis/config/artifact_bucket_test.go
  pkg/apis/config/artifact_pvc_test.go
  pkg/apis/config/feature_flags_test.go
  pkg/credentials/dockercreds/creds_test.go
  pkg/credentials/gitcreds/creds_test.go
  pkg/git/git_test.go
  pkg/resolution/resolver/git/resolver_test.go
  test/pullrequest/e2e_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note-none, kind/cleanup

#5421 Improve DAG validation for pipelines with hundreds of tasks
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/reconciler/pipeline/dag/dag.go
  pkg/reconciler/pipeline/dag/dag_test.go
  pkg/reconciler/pipeline/dag/export_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note, needs-cherry-pick

#5406 Add instructions for enabling alpha features
  docs/install.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#5434 Improve DAG validation - v1beta1 tests
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, lgtm, size/S, ok-to-test, release-note-none, kind/cleanup

#5389 TEP-0114: Timeout the Testing Wait Custom Task
  test/custom-task-ctrls/wait-task/README.md
  test/custom-task-ctrls/wait-task/cmd/controller/main.go
  test/custom-task-ctrls/wait-task/config/controller.yaml
  test/custom-task-ctrls/wait-task/go.mod
  test/custom-task-ctrls/wait-task/go.sum
  test/custom-task-ctrls/wait-task/pkg/reconciler/reconciler.go
  test/custom-task-ctrls/wait-task/pkg/reconciler/reconciler_test.go
  test/custom_task_test.go
  test/wait-task/go.mod
  test/wait-task/pkg/reconciler/reconciler_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#5426 Add conversion for v1 PipelineRun
  pkg/apis/pipeline/v1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipelineref_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/misc

#5428 Add successful git resolver e2e test
  test/resolvers_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5438 [release-v0.37.x] Fix TestYamls for change in `ko create`
  test/examples_test.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5440 [release-v0.39.x] Fix TestYamls for change in `ko create`
  test/examples_test.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5351 Fix docs and remove redundant code for LimitRanges
  docs/compute-resources.md
  pkg/internal/computeresources/transformer.go
  pkg/internal/computeresources/transformer_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5425 readable error message - double quote an invalid value in `step.onError`
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
Labels: approved, lgtm, size/S, release-note, kind/misc

#5437 Update docs for testing and enabling alpha features
  docs/install.md
  test/README.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#5413 Updated clock to use k8s.io/utils/clock
  cmd/controller/main.go
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/taskrun_types_test.go
  pkg/apis/pipeline/v1alpha1/run_types.go
  pkg/apis/pipeline/v1alpha1/run_types_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/resolutionrequest/resolutionrequest_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/resolution/resolver/framework/reconciler_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note-none, kind/cleanup

#5448 Switch remaining clock references to k8s.io/utils/clock
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/resolution/resolver/framework/testing/fakecontroller.go
  test/custom-task-ctrls/wait-task/cmd/controller/main.go
  test/custom-task-ctrls/wait-task/go.mod
  test/custom-task-ctrls/wait-task/pkg/reconciler/reconciler.go
  test/custom-task-ctrls/wait-task/pkg/reconciler/reconciler_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#5449 Describe Runtime Envs of E2E Tests
  test/README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#5435 TEP-0114: Implements Retries in The Testing Wait Custom Task
  test/custom-task-ctrls/wait-task/README.md
  test/custom-task-ctrls/wait-task/pkg/reconciler/reconciler.go
  test/custom-task-ctrls/wait-task/pkg/reconciler/reconciler_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#5306 Merge affinity from podtempalte and affinity-assistant
  pkg/internal/affinityassistant/transformer.go
  pkg/internal/affinityassistant/transformer_test.go
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
Labels: kind/feature, approved, lgtm, size/L, ok-to-test, release-note-action-required

#5451 Add examples for some resolvers
  docs/hub-resolver.md
  docs/migrating-v1beta1-to-v1.md
  examples/v1beta1/pipelineruns/no-ci/cluster-resolver.yaml
  examples/v1beta1/pipelineruns/no-ci/git-resolver.yaml
  examples/v1beta1/pipelineruns/no-ci/hub-resolver.yaml
  examples/v1beta1/taskruns/alpha/bundles-resolver.yaml
  examples/v1beta1/taskruns/alpha/git-resolver.yaml
  examples/v1beta1/taskruns/alpha/hub-resolver.yaml
  examples/v1beta1/taskruns/no-ci/cluster-resolver.yaml
  test/resolvers_yaml/pipeline-in-git.yaml
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#5383 TEP-0118: matrix: add `matrix.params` field
  docs/matrix.md
  docs/pipeline-api.md
  examples/v1beta1/pipelineruns/alpha/pipelinerun-with-matrix-and-results.yaml
  examples/v1beta1/pipelineruns/alpha/pipelinerun-with-matrix.yaml
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/resultref.go
  pkg/apis/pipeline/v1/resultref_test.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/resultref.go
  pkg/apis/pipeline/v1beta1/resultref_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/pipelinerun/resources/validate_dependencies_test.go
  pkg/reconciler/pipelinerun/resources/validate_params.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/validate_resources.go
  pkg/reconciler/taskrun/validate_resources_test.go
Labels: kind/feature, approved, lgtm, size/XXL, ok-to-test, release-note-action-required

#5462 Avoid Duplicate Reconcile Logic in Testing Wait Custom Run Controller
  test/custom-task-ctrls/wait-task/pkg/reconciler/reconciler_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#5464 Add V1 version of PipelineRun CRD
  cmd/webhook/main.go
  config/300-pipelinerun.yaml
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5467 Bump codeql-action to v2
  .github/workflows/codeql-analysis.yml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5460 Allow user to specify only tasks or finally timeout
  docs/pipelineruns.md
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#5469 Remove a stray println from resolvers main
  cmd/resolvers/main.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5427 TEP-0075: More flexible ways to provide values for object param keys
  docs/tasks.md
  examples/v1beta1/taskruns/alpha/object-param-result.yaml
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/reconciler/pipelinerun/resources/validate_params_test.go
  pkg/reconciler/taskrun/validate_resources.go
  pkg/reconciler/taskrun/validate_resources_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5473 Update releases in deprecations table
  docs/deprecations.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#5472 Fix alpha features and alpha release links for remote resolution
  docs/install.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#5476 Replace `$(context...)` values in resolver parameters
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  test/resolution.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#5381 V1: Add conversion for TaskRunSpec.TaskRef.Bundle
  pkg/apis/pipeline/v1beta1/taskref_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5477 V1: add conversion for PipelineRunSpec.PipelineRef.Bundle
  pkg/apis/pipeline/v1beta1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1beta1/pipelineref_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5479 [release-v0.36.x] de-dupe order and resource dependencies
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5482 [release-v0.37.x] de-dupe order and resource dependencies
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5483 [release-v0.38.x] de-dupe order and resource dependencies
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5484 [release-v0.39.x] de-dupe order and resource dependencies
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5081 TEP-0111 - Propagating workspaces in taskruns
  docs/install.md
  docs/taskruns.md
  docs/tasks.md
  examples/v1beta1/taskruns/alpha/propagating_workspaces.yaml
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
  pkg/workspace/validate_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5494 Update location of clock
  pkg/apis/pipeline/v1beta1/customrun_types.go
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/misc

#5498 Fail linting if k8s.io/apimachinery/pkg/util/clock is imported
  .golangci.yml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5491 TEP-119 - Add TaskRun Template in v1 PipelineRun
  dev/docs/migrating-v1beta1-to-v1.md
  docs/pipeline-api.md
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/apis/pipeline/v1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go
Labels: kind/feature, approved, lgtm, size/L, ok-to-test, release-note

#5361 Add baseimage for windows 1809 to support AKS
  tekton/publish.yaml
Labels: kind/feature, approved, lgtm, size/XS, ok-to-test, release-note

#5486 Adding template for a promotion request
  .github/ISSUE_TEMPLATE/promotion-request.md
Labels: approved, lgtm, size/M, release-note, kind/misc

#5371 Propagating object params
  docs/pipelineruns.md
  docs/taskruns.md
  examples/v1beta1/pipelineruns/alpha/propagated-pipeline-object-param.yaml
  examples/v1beta1/taskruns/alpha/propagated-object-parameters.yaml
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#5502 Revert "Add baseimage for windows 1809"
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#5463 TEP-0111 - Propagating workspaces in pipelinerun
  docs/pipelineruns.md
  examples/v1beta1/pipelineruns/alpha/propagating-workspaces.yaml
  examples/v1beta1/pipelineruns/alpha/propagating_workspaces_with_referenced_resources.yaml
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#5468 petite DAG - introduce key to identify node instead of holding a `task`
  pkg/reconciler/pipeline/dag/dag.go
  pkg/reconciler/pipeline/dag/dag_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, lgtm, size/M, release-note, kind/cleanup

#5465 hardening `looksLikeResultRef` - params and when expressions
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/resultref.go
  pkg/apis/pipeline/v1/resultref_test.go
  pkg/apis/pipeline/v1/when_validation.go
  pkg/apis/pipeline/v1/when_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/resultref.go
  pkg/apis/pipeline/v1beta1/resultref_test.go
  pkg/apis/pipeline/v1beta1/when_validation.go
  pkg/apis/pipeline/v1beta1/when_validation_test.go
Labels: approved, lgtm, size/L, release-note, kind/cleanup

#5508 Refactor ensureConfigurationConfigMapsExist to reduce duplicate code
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/run/run_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/controller.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#5506 Fix empty paramValueType conversion
  pkg/apis/pipeline/v1beta1/param_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskref_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none, needs-cherry-pick

#5503 Add developer documentation on k8s controllers
  DEVELOPMENT.md
  docs/developers/controller-logic.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#5510 Update alpha features table
  docs/install.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#5530 Remove alpha feature gate from projected workspaces
  docs/install.md
  docs/workspaces.md
  examples/v1beta1/pipelineruns/workspaces-projected.yaml
  pkg/apis/pipeline/v1/workspace_validation.go
  pkg/apis/pipeline/v1/workspace_validation_test.go
  pkg/apis/pipeline/v1beta1/workspace_validation.go
  pkg/apis/pipeline/v1beta1/workspace_validation_test.go
Labels: kind/feature, approved, lgtm, size/M, ok-to-test, release-note

#5531 Add the ability to mock more SCM data for git resolver tests
  pkg/resolution/resolver/git/resolver.go
  pkg/resolution/resolver/git/resolver_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5544 Update how-to-write-a-resolver doc
  docs/how-to-write-a-resolver.md
  docs/resolver-template/config/demo-resolver-deployment.yaml
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#5539 Update ko to v0.12.0
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5543 Fix gcloud config syntax for e2e test setup
  test/README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#5542 Change image refs: distroless.dev -> cgr.dev/chainguard
  .ko.yaml
  config/controller.yaml
  tekton/publish.yaml
  test/presubmit-tests.sh
Labels: approved, lgtm, size/S, release-note, kind/cleanup

#5493 TEP-096 - Rename 'resources' to 'computeResources' in v1 taskRun
  dev/docs/migrating-v1beta1-to-v1.md
  docs/pipeline-api.md
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/container_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
Labels: approved, lgtm, size/XL, release-note, kind/misc

#5559 Fix taskrun not working with workspace having volumeClaimTemplate
  examples/v1beta1/taskruns/workspace-with-volumeClaimTemplate.yaml
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, approved, lgtm, size/M, release-note, needs-cherry-pick

#5325 Add "beta" value to `enable-api-fields`
  config/config-feature-flags.yaml
  docs/install.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-beta-api-fields.yaml
  pkg/apis/version/version_validation.go
  pkg/apis/version/version_validation_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#5523 TEP-0114: Tests Wait Custom Task Retries and TimeOut
  test/custom_task_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#5547 OWNERS: move dlorenc to alumni
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5511 Update API spec doc to reflect the new fields introduced from TEP75&76
  docs/api-spec.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#5570 Add the openssf badge to the main README
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#5578 V1: sync v1beta1 changes for pipeline CRDs
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/pipelineref_validation.go
  pkg/apis/pipeline/v1/pipelineref_validation_test.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/taskref_validation.go
  pkg/apis/pipeline/v1/taskref_validation_test.go
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/taskrun_types_test.go
Labels: approved, lgtm, size/XXL, release-note-none, kind/misc

#5573 tekton: make sure the git workingdir is not dirty…
  tekton/publish.yaml
Labels: approved, lgtm, size/S, release-note, kind/cleanup

#5576 Write TaskRun.Status.TaskSpec with replaced spec on every reconcile run
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/L, priority/critical-urgent, release-note

#5551 Add ConfigSource field in `ResolutionRequest.status`
  docs/how-to-write-a-resolver.md
  docs/resolver-template/cmd/demoresolver/main.go
  go.sum
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/resolution/v1alpha1/resolution_request_types.go
  pkg/apis/resolution/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/resolution/v1beta1/resolution_request_types.go
  pkg/apis/resolution/v1beta1/zz_generated.deepcopy.go
  pkg/resolution/resolver/bundle/bundle.go
  pkg/resolution/resolver/cluster/resolver.go
  pkg/resolution/resolver/framework/fakeresolver.go
  pkg/resolution/resolver/framework/interface.go
  pkg/resolution/resolver/framework/reconciler.go
  pkg/resolution/resolver/framework/reconciler_test.go
  pkg/resolution/resolver/git/resolver.go
  pkg/resolution/resolver/hub/resolver.go
  pkg/resolution/resource/crd_resource.go
  pkg/resolution/resource/resource.go
  test/resolution.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5561 refactor test `Test_storePipelineSpec` to use yml parser
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/S, ok-to-test, release-note-none, kind/cleanup
