Repository tektoncd/pipeline, pull requests merged in 2022-05, with the labels that each got.

#4817 Revert "[V1] Add new API versions to /config"
  config/300-pipeline.yaml
  config/300-pipelinerun.yaml
  config/300-run.yaml
  config/300-task.yaml
  config/300-taskrun.yaml
Labels: approved, lgtm, size/L, release-note-none

#4803 Fix variable interpolation on `StepTemplate`
  examples/v1beta1/taskruns/steptemplate-variable-interop.yaml
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/step_replacements.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#4769 Omit init containers from limitrange default request calculations
  pkg/internal/limitrange/transformer.go
  pkg/internal/limitrange/transformer_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#4770 Revamp compute resources documentation
  docs/compute-resources.md
  docs/limitrange.md
  docs/pipelineruns.md
  docs/taskruns.md
  docs/tasks.md
Labels: approved, lgtm, size/L, kind/documentation, release-note-none

#4821 Fix ./hack/update-codegen.sh script
  hack/setup-temporary-gopath.sh
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none

#4823 Make `pkg/git` tests not modifying global git config
  pkg/git/git_test.go
Labels: approved, lgtm, size/S, release-note-none

#4832 Resolve Entrypoint and Cmd if there is no command and no args
  pkg/pod/entrypoint_lookup.go
  pkg/pod/entrypoint_lookup_impl.go
  pkg/pod/entrypoint_lookup_impl_test.go
  pkg/pod/entrypoint_lookup_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#4826 Merge place-tools and step-init together
  cmd/entrypoint/subcommands/init.go
  cmd/entrypoint/subcommands/init_test.go
  cmd/entrypoint/subcommands/subcommands.go
  examples/v1beta1/pipelineruns/4808-regression.yaml
  pkg/pod/entrypoint.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#4591 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#4836 Refactor duplicate code in task_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: approved, lgtm, size/M, release-note, kind/cleanup

#4841 TEP-0090: Refactor Validation of `Parameters` in `TaskRun` Reconciler
  pkg/reconciler/taskrun/validate_resources.go
Labels: approved, lgtm, size/M, release-note

#4843 Add @lbernick to pipeline approvers list
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#4775 fix typo about ths I think maybe it should be this
  docs/taskruns.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note

#4833 Added validation for parameters with bracket notation
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
Labels: approved, lgtm, size/L, ok-to-test, release-note

#4848 Enable automatic SBOM creation with spdx format
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note, kind/misc

#4839 Params: sanity check unmarshalling works with multiline json.
  pkg/apis/pipeline/v1beta1/param_types_test.go
Labels: approved, lgtm, size/M, release-note

#4851 Deprecate unusable Step/StepTemplate fields
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
Labels: approved, lgtm, size/L, release-note, kind/cleanup

#4844 TEP-0090: Include `Matrix` in Validation of `Parameters` in `TaskRun` Reconciler
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/validate_resources.go
  pkg/reconciler/taskrun/validate_resources_test.go
Labels: approved, lgtm, size/M, release-note

#4853 Add missing field to pipelineruns doc
  docs/pipelineruns.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#4852 Fix bug where PipelineRun hangs after task failure
  pkg/reconciler/pipeline/dag/dag.go
  pkg/reconciler/pipeline/dag/dag_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note, needs-cherry-pick

#4799 Validate parameter name format
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: approved, lgtm, size/M, release-note

#4850 [TEP-0100] Add status helper functions for minimal embedded status
  pkg/status/status.go
  pkg/status/status_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note, kind/tep

#4864 [PATCH] Patch knative/pkg to fix HA via StatefulSet
  hack/patches/0001-PATCH-Patch-knative-pkg-to-fix-HA-via-StatefulSet.patch
  vendor/knative.dev/pkg/leaderelection/context.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#4868 Stop using GO111MODULE=off in builds
  tekton/publish.yaml
Labels: kind/bug, approved, lgtm, size/XS, release-note

#4859 Add taskRef remote resolution support
  docs/taskruns.md
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/remote/resolution/resolver.go
  pkg/remote/resolution/resolver_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#4835 Remove validation of parameter variables after substitution
  pkg/apis/config/contexts.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, lgtm, size/L, ok-to-test, release-note-none

#4871 Set explicit parallelism for e2e tests, increase Kaniko e2e test timeouts
  test/e2e-tests.sh
  test/kaniko_task_test.go
  test/v1alpha1/kaniko_task_test.go
Labels: approved, lgtm, size/XS, kind/flake, release-note-none

#4880 Extract full parameter name when using dots in bracket notation.
  docs/tasks.md
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
Labels: approved, lgtm, size/L, release-note

#4881 Add constant backoff for TaskRun retry
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, approved, lgtm, size/XS, ok-to-test, release-note-none

#4866 Rename deprecated Step and StepTemplate fields
  docs/deprecations.md
  hack/ignored-openapi-violations.list
  hack/update-openapigen.sh
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L, release-note, kind/cleanup

#4888 Fix metadata section in the example yaml file
  examples/v1beta1/pipelineruns/pipelinerun-results-with-params.yaml
Labels: approved, lgtm, size/XS, release-note

#4846 Bubble up the image related error reason to taskrun status
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note-none

#4806 Add validation for duplicated param names in TaskSpec
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: approved, lgtm, size/S, ok-to-test, release-note

#4818 [TEP-0076] Add array support for emitting results
  docs/tasks.md
  examples/v1beta1/taskruns/alpha/emit-array-results.yaml
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/param_types_test.go
  pkg/apis/pipeline/v1beta1/result_types.go
  pkg/apis/pipeline/v1beta1/result_validation.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  pkg/termination/parse_test.go
  test/ignore_step_error_test.go
Labels: approved, lgtm, size/XL, release-note

#4468 Fix Metric tekton_pipelines_controller_pipelinerun_count
  pkg/pipelinerunmetrics/metrics.go
  pkg/pipelinerunmetrics/metrics_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, lgtm, size/L, release-note

#4906 Deprecated implicit parameters
  docs/pipelineruns.md
  docs/taskruns.md
  examples/v1beta1/pipelineruns/alpha/pipelinerun-implicit-params.yaml
  examples/v1beta1/taskruns/alpha/implicit-params.yaml
  pkg/apis/pipeline/v1beta1/implicit_params_test.go
  pkg/apis/pipeline/v1beta1/param_context.go
  pkg/apis/pipeline/v1beta1/param_context_test.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1beta1/task_defaults.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#4845 TEP-0107: Implement Parameter Propagation
  docs/pipelineruns.md
  docs/taskruns.md
  examples/v1beta1/pipelineruns/alpha/propagating_params_implicit_parameters.yaml
  examples/v1beta1/pipelineruns/alpha/propagating_params_with_scope_precedence.yaml
  examples/v1beta1/pipelineruns/alpha/propagating_params_with_scope_precedence_default_only.yaml
  examples/v1beta1/taskruns/alpha/propagating_params_implicit.yaml
  pkg/apis/pipeline/v1alpha1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
Labels: kind/feature, approved, lgtm, size/XL, ok-to-test, release-note

#4887 TEP-0108: Mapping Workspaces
  docs/pipelines.md
  examples/v1beta1/pipelineruns/mapping-workspaces.yaml
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/workspace_types.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4914 Allow PipelineTaskRunSpec.Metadata to be optional.
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#4891 Update PipelineSpec and TaskSpec fields of PipelineRun and TaskRun Status fields
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#4918 docs: add a note on result size and containers
  docs/tasks.md
Labels: approved, lgtm, size/S, release-note-none

#4919 Update gopkg.in/yaml.v3 to v3.0.1
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/cleanup

#4899 double MaximumBundleObjects and update tests
  docs/pipelines.md
  pkg/remote/oci/resolver.go
  pkg/remote/oci/resolver_test.go
Labels: approved, lgtm, size/L, ok-to-test, release-note-none, kind/misc
