Repository tektoncd/pipeline, pull requests merged in 2023-02, with the labels that each got.

#6098 cleaning up examples to avoid writing to results using path
  examples/v1/pipelineruns/ignore-step-error.yaml
  examples/v1/pipelineruns/pipelinerun-with-when-expressions.yaml
  examples/v1/pipelineruns/pipelinerun.yaml
  examples/v1/taskruns/task-result.yaml
  examples/v1beta1/pipelineruns/ignore-step-error.yaml
  examples/v1beta1/pipelineruns/pipelinerun-with-when-expressions.yaml
  examples/v1beta1/pipelineruns/pipelinerun.yaml
  examples/v1beta1/taskruns/alpha/large-task-result.yaml
  examples/v1beta1/taskruns/task-result.yaml
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#6065 Clean up cloudevents package
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/events/cloudevent/cloudevent.go
  pkg/reconciler/events/cloudevent/cloudevent_test.go
  pkg/reconciler/events/cloudevent/cloudeventsfakeclient.go
  pkg/reconciler/events/cloudevent/cloudeventsfakeclient_test.go
  pkg/reconciler/events/event_test.go
  pkg/reconciler/testing/logger.go
Labels: approved, lgtm, size/XL, release-note-none, kind/cleanup

#6073 remove results from status when type mismatched and add more logs
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/taskrun/validate_resources.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#6011 [TEP074] Remove Pullrequest pipelineResources
  docs/resources.md
  docs/variables.md
  examples/v1beta1/taskruns/pullrequest.yaml
  examples/v1beta1/taskruns/pullrequest_input_copystep_output.yaml
  pkg/apis/pipeline/v1beta1/resource_types.go
  pkg/apis/resource/resource.go
  pkg/apis/resource/v1alpha1/pipeline_resource_types.go
  pkg/apis/resource/v1alpha1/pipelineresource_validation.go
  pkg/apis/resource/v1alpha1/pipelineresource_validation_test.go
  pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource.go
  pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource_test.go
Labels: approved, lgtm, size/XL, release-note-action-required, kind/misc

#6060 updating an example pipelinerun with array indexing
  examples/v1beta1/pipelineruns/alpha/pipelinerun-param-array-indexing.yaml
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#6100 Switch the release pipeline to use GitHub API for task resolution
  tekton/release-pipeline.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6104 unit test added for task result type mismatch
  pkg/reconciler/taskrun/validate_resources_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#6029 Update git resolver documentation
  docs/git-resolver.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6049 [TEP0100] Remove `EmbeddedStatus` Feature Flag
  config/config-feature-flags.yaml
  docs/install.md
  docs/matrix.md
  docs/pipelineruns.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/apis/config/testdata/feature-flags-invalid-embedded-status.yaml
  pkg/apis/config/testing/feature_flags.go
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/status_validation.go
  pkg/apis/pipeline/v1/status_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1beta1/status_validation.go
  pkg/apis/pipeline/v1beta1/status_validation_test.go
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/cancel_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/pipelinerun_updatestatus_test.go
  pkg/reconciler/pipelinerun/timeout_test.go
  pkg/status/status.go
  pkg/status/status_test.go
  test/conversion_test.go
  test/custom_task_test.go
  test/e2e-tests-kind-prow-alpha.env
  test/e2e-tests.sh
  test/featureflags.go
  test/retry_test.go
  test/status_test.go
Labels: approved, lgtm, size/XXL, ok-to-test, release-note, kind/misc

#5646 feat: support to extract init container failure message
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: kind/feature, approved, lgtm, size/L, ok-to-test, release-note

#6092 when expressions with array results (doc and example)
  docs/pipelines.md
  examples/v1beta1/pipelineruns/alpha/pipeline-with-when-expressions-using-array-results.yaml
Labels: approved, lgtm, size/L, kind/documentation, release-note

#6055 updating an existing example pipelinerun with array results
  examples/v1beta1/pipelineruns/alpha/pipelinerun-array-results-substitution.yaml
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5806 Refactor installation documentation
  docs/additional-configs.md
  docs/install.md
Labels: approved, lgtm, size/XXL, kind/documentation, release-note-none

#5777 fix:the pvc creation failure does not print the success log
  pkg/reconciler/volumeclaim/pvchandler.go
  pkg/reconciler/volumeclaim/pvchandler_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note-none

#6108 Bumb up dependency versions for wait-task custom controllers
  test/custom-task-ctrls/wait-task-alpha/go.mod
  test/custom-task-ctrls/wait-task-alpha/go.sum
  test/custom-task-ctrls/wait-task-beta/go.mod
  test/custom-task-ctrls/wait-task-beta/go.sum
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#6124 Include CustomRuns in failed integration test YAML dump
  test/init_test.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6122 Replace hardcoded value
  pkg/apis/config/feature_flags.go
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/misc

#6138 Add security context for example PRs using catalog git-clone
  examples/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml
  examples/v1beta1/pipelineruns/pipelinerun.yaml
  test/yamls/v1beta1/pipelineruns/pipelinerun-with-final-tasks.yaml
  test/yamls/v1beta1/pipelineruns/pipelinerun.yaml
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#6151 chore: add link to tekton v0.40 version
  docs/additional-configs.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#6099 [TEP100] Remove `Taskruns` and `Runs` Fields for `PipelineRunStatus`
  docs/pipeline-api.md
  docs/pipelineruns.md
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/pipelinerun_updatestatus_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/pipelinerun/timeout_test.go
  test/propagated_params_test.go
Labels: approved, lgtm, size/XXL, release-note, kind/misc

#6117 Pipelines Docs Cleanup
  docs/auth.md
  docs/bundle-resolver.md
  docs/cluster-resolver.md
  docs/compute-resources.md
  docs/conditions.md
  docs/container-contract.md
  docs/customruns.md
  docs/debug.md
  docs/deprecations.md
  docs/enabling-ha.md
  docs/events.md
  docs/git-resolver.md
  docs/hermetic.md
  docs/how-to-write-a-resolver.md
  docs/hub-resolver.md
  docs/install.md
  docs/labels.md
  docs/logs.md
  docs/matrix.md
  docs/metrics.md
  docs/migrating-from-knative-build.md
  docs/migrating-v1alpha1-to-v1beta1.md
  docs/pipeline-api.md
  docs/pipelineresources.md
  docs/pipelineruns.md
  docs/pipelines.md
  docs/podtemplates.md
  docs/resolution-getting-started.md
  docs/resolution.md
  docs/resolver-reference.md
  docs/resources.md
  docs/runs.md
  docs/taskruns.md
  docs/tasks.md
  docs/tekton-bundle-contracts.md
  docs/tekton-controller-performance-configuration.md
  docs/trusted-resources.md
  docs/variables.md
  docs/windows.md
  docs/workspaces.md
Labels: approved, lgtm, size/L, kind/documentation, release-note-none

#6119 add more error messages for results validation
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/taskrun/validate_resources.go
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#6129 validate emit results are defined in taskspec
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#6158 [TEP074] Cleanup variables.md after Removal of PipelineResources
  docs/variables.md
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#6163 Move Propagated Workspaces to list of beta features
  docs/additional-configs.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6121 update pre-requsites to include checking docker is installed
  docs/install.md
Labels: approved, lgtm, size/M, kind/documentation, ok-to-test, release-note-none

#5336 fix: possible error when 'stepTemplate' and 'steps' contain the same…
  docs/tasks.md
  pkg/apis/pipeline/v1/merge.go
  pkg/apis/pipeline/v1/merge_test.go
  pkg/apis/pipeline/v1beta1/merge.go
  pkg/apis/pipeline/v1beta1/merge_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note

#6069 [pkg/reconciler] clean up io/ioutil package
  pkg/reconciler/testing/configmap.go
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/cleanup

#6103 TEP-0076 (array results and indexing into array) promoted to beta 🎓
  docs/pipelines.md
  docs/tasks.md
  examples/v1beta1/pipelineruns/beta/pipelinerun-array-results-substitution.yaml
  examples/v1beta1/pipelineruns/beta/pipelinerun-param-array-indexing.yaml
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/pipeline/v1/result_validation.go
  pkg/apis/pipeline/v1/result_validation_test.go
  pkg/apis/pipeline/v1beta1/result_validation.go
  pkg/apis/pipeline/v1beta1/result_validation_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/validate_params.go
  pkg/reconciler/pipelinerun/resources/validate_params_test.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6026 Increase `timeout` in Conversion Integration Test to Prevent Flake
  test/conversion_test.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6164 Remove PipelineRunStatus from deprecation.md
  docs/deprecations.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6126 Add release info for v0.41.1
  releases.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6181 updating the list of beta features
  docs/additional-configs.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6169 update pipeline-object-param-and-result example
  examples/v1beta1/pipelineruns/alpha/pipeline-object-param-and-result.yaml
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#6170 update object-param-result example
  examples/v1beta1/taskruns/alpha/object-param-result.yaml
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#6134 Mark config-trusted-resources as deprecated
  docs/deprecations.md
  docs/trusted-resources.md
  pkg/apis/config/trusted_resources.go
Labels: approved, lgtm, size/S, release-note-action-required, kind/misc

#6187 Add v0.45.0 to releases.md
  releases.md
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#6062 Upgrade to knative/pkg 1.9
  README.md
  docs/install.md
  docs/pipeline-api.md
  go.mod
  go.sum
  hack/reference-docs-gen-config.json
  hack/update-deps.sh
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/import_tracker.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, release-note, kind/misc

#6184 typochanges in line 81 and 94. I have changed it to "ResourceRef" from "ResourseRef".
  pkg/reconciler/taskrun/resources/taskresourceresolution.go
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/cleanup

#6161 Skip `last-applied-configuration` annotation when merging them.
  pkg/reconciler/constant.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#6200 fix weight in update-reference-docs
  hack/update-reference-docs.sh
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6199 Add CustomRun to register.go
  pkg/apis/pipeline/register.go
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/cleanup

#6189 run codegen against latest main to update licenses and api doc
  docs/pipeline-api.md
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/resolution/clientset/versioned/fake/register.go
  pkg/client/resolution/clientset/versioned/scheme/register.go
  pkg/client/resource/clientset/versioned/fake/register.go
  pkg/client/resource/clientset/versioned/scheme/register.go
  third_party/cloud.google.com/go/iam/LICENSE
  third_party/cloud.google.com/go/kms/LICENSE
  third_party/github.com/Azure/go-autorest/autorest/to/LICENSE
  third_party/github.com/Azure/go-autorest/autorest/validation/LICENSE
  third_party/github.com/armon/go-metrics/LICENSE
  third_party/github.com/armon/go-radix/LICENSE
  third_party/github.com/aws/aws-sdk-go-v2/service/kms/LICENSE.txt
  third_party/github.com/cenkalti/backoff/v3/LICENSE
  third_party/github.com/fatih/color/LICENSE.md
  third_party/github.com/golang/snappy/LICENSE
  third_party/github.com/googleapis/enterprise-certificate-proxy/client/LICENSE
  third_party/github.com/googleapis/gax-go/v2/LICENSE
  third_party/github.com/grpc-ecosystem/grpc-gateway/v2/LICENSE.txt
  third_party/github.com/jellydator/ttlcache/v2/LICENSE
  third_party/github.com/mattn/go-colorable/LICENSE
  third_party/github.com/mattn/go-isatty/LICENSE
  third_party/github.com/mitchellh/go-testing-interface/LICENSE
  third_party/github.com/mitchellh/mapstructure/LICENSE
  third_party/github.com/oklog/run/LICENSE
  third_party/github.com/pierrec/lz4/LICENSE
  third_party/github.com/ryanuber/go-glob/LICENSE
  third_party/google.golang.org/api/LICENSE
  third_party/google.golang.org/api/internal/third_party/uritemplates/LICENSE
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6179 fix param array indexing validation error reason and error log
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#6205 Updated documentation of pipelines around approvals
  docs/pipelines.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#6188 TEP-0118: Added Matrix.Include field in preview mode
  docs/matrix.md
  docs/pipeline-api.md
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6215 Fix indent for the example of specifying Custom Task Spec
  docs/pipelines.md
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#6002 [TEP074] Remove Image pipelineResources
  cmd/controller/main.go
  cmd/imagedigestexporter/digest.go
  cmd/imagedigestexporter/digest_test.go
  cmd/imagedigestexporter/kodata/LICENSE
  cmd/imagedigestexporter/kodata/third_party
  cmd/imagedigestexporter/main.go
  config/controller.yaml
  examples/v1beta1/taskruns/optional-resources-with-clustertask.yaml
  examples/v1beta1/taskruns/optional-resources.yaml
  examples/v1beta1/taskruns/task-multiple-output-image.yaml
  examples/v1beta1/taskruns/task-output-image.yaml
  pkg/apis/pipeline/images.go
  pkg/apis/pipeline/images_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/resource_types.go
  pkg/apis/resource/resource.go
  pkg/apis/resource/v1alpha1/image/image_resource.go
  pkg/apis/resource/v1alpha1/image/image_resource_test.go
  pkg/apis/resource/v1alpha1/pipeline_resource_types.go
  pkg/apis/resource/v1alpha1/storage/gcs_test.go
  pkg/artifacts/artifact_storage_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/image_exporter.go
  pkg/reconciler/taskrun/resources/image_exporter_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/resources/output_resource_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/taskrun/validate_resources_test.go
  tekton/publish.yaml
  test/conversion_test.go
  test/helm_task_test.go
  test/kaniko_task_test.go
  test/ko_test.go
Labels: approved, lgtm, size/XXL, release-note-action-required, kind/misc

#6229 TEP-0118: Add exported functions for validating Matrix.Include and Matrix.Params
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#6239 [TEP074] Remove git-ssh Examples
  examples/v1beta1/taskruns/git-ssh-creds-without-known_hosts.yaml
  examples/v1beta1/taskruns/git-ssh-creds.yaml
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#6230 TEP-0118: Add validation for Matrix.Include.Params of type string
  docs/matrix.md
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#6234 Fix resolution getting started docs with correct parameters
  docs/resolution-getting-started.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#6225 Update Tekton development processes section URLs
  CONTRIBUTING.md
Labels: approved, lgtm, size/S, kind/documentation, ok-to-test, release-note-none

#6238 TEP-0118: Add validation for matrix pipeline context parameter variables
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none
