Repository tektoncd/pipeline, pull requests merged in 2023-08, with the labels that each got.

#6962 Fix Taskrun Failure for Preempted Pod of Taskrun
  pkg/reconciler/taskrun/taskrun.go
  test/premption_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6967 Add v0.50 to releases.md
  releases.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#7011 [release-v0.47.x] Fix Taskrun Failure for Preempted Pod of Taskrun
  pkg/reconciler/taskrun/taskrun.go
  test/premption_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6944 Add E2E Testing for Matrix
  test/matrix_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#7017 Make sure we use the correct namespace for remote Pipeline validation
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#7020 Fix typos and formatting in TaskRuns doc
  docs/taskruns.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#7012 Update Matrix Documentation for Results
  docs/matrix.md
  docs/pipelines.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#7016 Create a separate role for Events Controller
  config/200-role.yaml
  config/201-rolebinding.yaml
Labels: kind/bug, approved, lgtm, size/S, release-note

#7044 Fix release pipeline (publish-to-bucket)
  tekton/release-pipeline.yaml
Labels: kind/bug, approved, lgtm, size/XS, release-note

#6994 [TEP-0135] Improve workspace related documentation
  docs/workspaces.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#7050 docs: Update references to examples from v1beta1 to v1
  docs/api-spec.md
  docs/auth.md
  docs/developers/api-versioning.md
  docs/matrix.md
  docs/pipelineruns.md
  docs/pipelines.md
  docs/taskruns.md
  docs/tasks.md
  docs/workspaces.md
Labels: approved, lgtm, size/M, kind/documentation, ok-to-test, release-note-none

#6973 Add service for Resolvers - metrics, probes and tracing
  config/resolvers/resolvers-deployment.yaml
  config/resolvers/resolvers-service.yaml
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#6957 fix: refine error resean with invalid pipelinename in taskrunspecs
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/S, ok-to-test, release-note

#6942 Add webhook validation for remote Tasks
  pkg/pod/status.go
  pkg/reconciler/apiserver/apiserver.go
  pkg/reconciler/apiserver/apiserver_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/XL, release-note, kind/misc

#7079 Validate beta features for inline pipelines and tasks
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note
