Repository tektoncd/pipeline, pull requests merged in 2023-06, with the labels that each got.

#6754 [TEP-0091] add more no error test cases for taskrun and pipelinerun
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#6738 [TEP-0091] add v1 support for VerifyResource
  pkg/trustedresources/verify.go
  pkg/trustedresources/verify_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#6766 Sync V1 apis with V1beta1 changes
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/apis/pipeline/v1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1/result_validation.go
  pkg/apis/pipeline/v1/resultref.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#6744 add taskrun gauge metrics for k8s throttling because of defined resource quotas or k8s node constraints
  docs/metrics.md
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6777 Remove reconciler check for enable-tekton-oci-bundles flag
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/taskrun/resources/taskref.go
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#6757 [TEP-0091] update taskrun and pipelinerun condition based on VerificationResult
  docs/trusted-resources.md
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/trustedresources/verify.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6764 [TEP-0091] support remote v1 task verification
  docs/trusted-resources.md
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#6765 [TEP-0091] support remote v1 pipeline verification
  docs/trusted-resources.md
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#6781 Refactor TestReconcile_RemotePipelineRef bundle resolver test case
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#6785 Fix apiVersion of Task to v1 in v1 examples
  examples/v1/pipelineruns/pipelinerun.yaml
  examples/v1/taskruns/beta/bundles-resolver.yaml
  examples/v1/taskruns/beta/git-resolver.yaml
  examples/v1/taskruns/beta/hub-resolver.yaml
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#6778 Refactor test cases for remote TaskRef
  pkg/reconciler/taskrun/resources/taskref_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#6732 Enable beta features by default
  api_compatibility_policy.md
  config/config-feature-flags.yaml
  docs/additional-configs.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/pipelineref_validation_test.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/taskref_validation_test.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1/workspace_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/custom_task_test.go
Labels: approved, lgtm, size/M, release-note-action-required, kind/misc

#6741 TEP-0135: Refactor Affinity Assistant PVC creation
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/volumeclaim/pvchandler.go
  pkg/reconciler/volumeclaim/pvchandler_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#6791 Fix v1beta1 pipelineref bundle conversion to resolver
  pkg/apis/pipeline/v1beta1/pipelineref_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  test/conversion_test.go
  test/tektonbundles_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#6753 fix alpha propagated object params docs
  docs/pipelineruns.md
  docs/taskruns.md
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#6718 Cleanup: Use CustomRun instead of RunObject
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_updatestatus_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  pkg/reconciler/pipelinerun/resources/validate_dependencies_test.go
  test/custom_task_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/cleanup

#6803 Add apiVersions to TrustedResources Verification Helper Functions
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/trustedresources/verify_test.go
  test/trusted_resources_test.go
  test/trustedresources.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#6808 [release-v0.44.x] Fix v1beta1 pipelineref bundle conversion to resolver
  pkg/apis/pipeline/v1beta1/pipelineref_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  test/conversion_test.go
  test/tektonbundles_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6796 Add pod name to build_logs test output
  test/build_logs.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6779 Added clarification and fix the Metrics doc
  docs/metrics.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6786 Remove logic setting resolvers feature flag in e2e tests
  test/e2e-tests.sh
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#6771 Add Unit Tests for TestMissingResultWhenStepErrorIsIgnored and Update e2e test: TestFailingStepOnContinue
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  test/ignore_step_error_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#6825 Conversion webhook fix for tasks with nil StepTemplate
  pkg/apis/pipeline/v1beta1/task_conversion.go
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#6818 TEP-0135: add affinity assistant cleanup unit tests
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#6739 chore: Add PROBES_PORT environment variable and update targetPorts for existing services
  config/webhook.yaml
Labels: approved, lgtm, size/S, kind/documentation, ok-to-test, release-note-none

#6827 Clean up non-functional CloudEvents Metrics in Reconciler for Deprecated CloudEvents
  pkg/reconciler/taskrun/taskrun.go
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#6788 Add instructions for cherry-picking commits for patch releases
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#6821 Updating release doc with recent releases
  releases.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#6838 Remove refs, HEAD symlinks in resolvers kodata
  cmd/resolvers/kodata/HEAD
  cmd/resolvers/kodata/refs
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6840 Update broken links in api_compatibility_policy.md
  api_compatibility_policy.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6768 RFC: Update Go compatibility policy
  api_compatibility_policy.md
  docs/developers/api-changes.md
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#6843 Remove cloudevent metrics from documentation
  docs/metrics.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6441 Ignore tekton reserved annotations
  pkg/apis/pipeline/constant.go
  pkg/apis/pipeline/v1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1/taskrun_defaults.go
  pkg/apis/pipeline/v1/taskrun_defaults_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6565 Update pipelineTasks in Release-Pipeline to use Git Resolver
  tekton/release-pipeline.yaml
Labels: approved, lgtm, size/M, ok-to-test, release-note-none, kind/misc

#6792 Change ordering of ResolveResultRefs/ApplyTaskResults
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#6851 Update releases.md
  releases.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6735 Add instructions for picking commit in the release
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6603 Add support for consuming whole array results in matrix
  docs/matrix.md
  examples/v1beta1/pipelineruns/alpha/pipelinerun-with-matrix-and-results.yaml
  pkg/apis/pipeline/v1/matrix_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/matrix_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  test/custom-task-ctrls/wait-task-beta/example_customrun_matrix_results.yaml
Labels: kind/feature, approved, lgtm, size/XL, release-note

#6850 merge podTemplates instead of overriding
  docs/pipelineruns.md
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/apis/pipeline/v1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6849 Fix release pipeline
  tekton/release-pipeline.yaml
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#6852 Add Testing: Failed Matrix PipelineRun for Out Of Bounds Array Indexing Results
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#6801 Refactor failure logic in pipelinerun resolution
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/taskrun_types_test.go
  pkg/apis/pipeline/v1alpha1/run_types.go
  pkg/apis/pipeline/v1alpha1/run_types_test.go
  pkg/apis/pipeline/v1beta1/customrun_types.go
  pkg/apis/pipeline/v1beta1/customrun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
Labels: approved, lgtm, size/XL, release-note-none, kind/cleanup

#6861 [release-v0.44.x] merge podTemplates instead of override
  docs/pipelineruns.md
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/apis/pipeline/v1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6862 [release-v0.41.x] merge podTemplates instead of overriding
  docs/pipelineruns.md
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/apis/pipeline/v1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6864 Add compatibility policy for ResolutionRequests
  api_compatibility_policy.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6873 Reduce spam in integration test logs
  test/init_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#6865 Add set-security-context to feature flags docs
  docs/additional-configs.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6819 TEP-0135: implement per-pipelinerun coscheduling
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#6875 updating releases with 0.47.3
  releases.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none
