Repository tektoncd/pipeline, pull requests merged in 2023-07, with the labels that each got.

#6883 [TEP-0137] Add events config map
  config/config-events.yaml
  docs/additional-configs.md
  docs/deprecations.md
  pkg/apis/config/default.go
  pkg/apis/config/events.go
  pkg/apis/config/events_test.go
  pkg/apis/config/store.go
  pkg/apis/config/store_test.go
  pkg/apis/config/testdata/config-events-empty-values.yaml
  pkg/apis/config/testdata/config-events-empty.yaml
  pkg/apis/config/testdata/config-events-error.yaml
  pkg/apis/config/testdata/config-events.yaml
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/events/event_test.go
  test/controller.go
  test/controller_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-action-required

#6895 documenting the latest patch release - v0.44.4
  releases.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6898 Ignore SA in assertion
  test/custom_task_test.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6884 [TEP-0137] Rename customrun package
  cmd/controller/main.go
  cmd/events/main.go
  pkg/reconciler/notifications/customrun/controller.go
  pkg/reconciler/notifications/customrun/customrun.go
  pkg/reconciler/notifications/customrun/customrun_test.go
Labels: approved, lgtm, size/XS, release-note, kind/misc

#6902 cleaning up config-artifact-*
  config/200-role.yaml
  config/controller.yaml
  pkg/apis/pipeline/storagetypes.go
Labels: approved, lgtm, size/M, release-note, kind/cleanup

#6871 Fail upgrade tests when test script fails
  test/e2e-common.sh
  test/e2e-tests-upgrade.sh
Labels: kind/bug, approved, lgtm, size/S, area/testing, release-note-none

#6891 Fix units for metric taskrun_pod_latency
  docs/metrics.md
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#6866 Fail PipelineRun when it can't create Runs
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6855 Restore Upgrade Test Scenario2 by creating simple Task and Pipeline resources
  test/e2e-tests-upgrade.sh
  test/upgrade/simpleResources.yaml
  test/upgrade/simpleRuns.yaml
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#6893 [TEP-0135] Revert PVC creation
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/volumeclaim/pvchandler.go
  pkg/reconciler/volumeclaim/pvchandler_test.go
  test/affinity_assistant_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6917 Document that Workspaces can be unused
  docs/pipelineruns.md
  docs/workspaces.md
Labels: approved, lgtm, size/M, kind/documentation, ok-to-test, release-note-none

#6886 Fix PipelineRun reconciler panic for computed timeouts
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6925 Fix flaky Affinity Assistant test
  test/affinity_assistant_test.go
Labels: approved, lgtm, size/M, kind/flake, release-note-none

#6896 Add upgrade test against previous server version to prevent regressions
  test/e2e-tests-upgrade.sh
  test/upgrade_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#6887 Perform webhook validation for remote pipelines
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6929 [TEP-0135] coschedule isolate pipelinerun
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#6939 Do not require enable-api-fields=alpha for spire
  docs/spire.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-enforce-nonfalsifiability-bad-flag.yaml
  pkg/apis/config/testdata/feature-flags-enforce-nonfalsifiability-spire.yaml
  pkg/apis/config/testdata/feature-flags-spire-with-stable.yaml
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#6940 [TEP-0135] Purge finalizer and delete PVC
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/volumeclaim/pvchandler.go
  pkg/reconciler/volumeclaim/pvchandler_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#6954 Update Stability Level for CSI and Projected Volume Workspaces
  docs/additional-configs.md
  pkg/apis/pipeline/v1/workspace_validation.go
  pkg/apis/pipeline/v1/workspace_validation_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#6946 Fix logger Fatalf message
  pkg/termination/write_test.go
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/misc

#6934 Replace redundant function CheckAlphaOrBetaFields
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/task_validation.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#6813 Improve taskref_test coverage with more error test cases
  pkg/reconciler/taskrun/resources/taskref_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#6955 Fix flake of TestPipelineTaskTimeout
  test/timeout_test.go
Labels: approved, lgtm, size/XS, kind/flake, release-note-none

#6923 [RFC] Increase support window for v1beta1 CRDs to 1 year
  api_compatibility_policy.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#6933 Move feature flags testing functions into testing package
  pkg/apis/config/feature_flags.go
  pkg/apis/config/testing/featureflags.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/pipelineref_validation_test.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/taskref_validation_test.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1/workspace_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/L, release-note, kind/cleanup

#6876 Mark v1beta1 apis as deprecated
  api_compatibility_policy.md
  docs/deprecations.md
  docs/pipeline-api.md
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
Labels: approved, lgtm, size/M, kind/documentation, release-note-action-required

#6927 [TEP-0135] Coschedule per (Isolated) PipelineRun e2e support
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/affinity_assistant_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#6892 [TEP-0135] Update Affinity Assistant documentation
  config/config-feature-flags.yaml
  docs/additional-configs.md
  docs/affinityassistants.md
  docs/workspaces.md
Labels: approved, lgtm, size/L, kind/documentation, release-note-none

#6986 Remove warnings about matrix being non-functional
  docs/pipelines.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#7000 [cherry-pick release-v0.47.x] Fix PipelineRun reconciler panic for computed timeouts
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6982 Fail fast on invalid image
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6991 Mark disable-affinity-assistant as deprecated
  config/config-feature-flags.yaml
  docs/additional-configs.md
  docs/affinityassistants.md
  docs/deprecations.md
Labels: approved, lgtm, size/XS, release-note-action-required, kind/misc
