Repository tektoncd/pipeline, pull requests merged in 2023-05, with the labels that each got.

#6539 [TEP-0089] Add CSI volumes to the Pods which provide the SPIRE workload API
  pkg/pod/pod.go
  pkg/pod/pod_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#6585 Remove docstrings indicating that there is a 24h limit on timeouts
  docs/pipeline-api.md
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#6606 Fix conversion of non-object results declared in Tasks
  pkg/apis/pipeline/v1beta1/result_conversion.go
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#6553 [TEP-0089] SPIRE for non-falsifiable provenance. Setup the test environment.
  test/e2e-common.sh
  test/e2e-tests.sh
  test/testdata/patch/pipeline-controller-spire.json
  test/testdata/spire/config-spire.yaml
  test/testdata/spire/spiffe-csi-driver.yaml
  test/testdata/spire/spire-agent.yaml
  test/testdata/spire/spire-server.yaml
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#6622 Don't mark done PipelineRuns as timed out
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note, needs-cherry-pick

#6619 Refactor Sidecar Containers Construction If Script Exists
  pkg/pod/script.go
  pkg/pod/script_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#6638 Add validation for array indexing in finally when expressions
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#6613 check beta feature flag for v1 TaskSpec's ValidateParamArrayIndex
  docs/additional-configs.md
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#6568 Update documentation to reflect stability levels and deprecations
  api_compatibility_policy.md
  docs/README.md
  docs/additional-configs.md
  docs/auth.md
  docs/bundle-resolver.md
  docs/cluster-resolver.md
  docs/deprecations.md
  docs/developers/README.md
  docs/developers/local-setup.md
  docs/developers/pipelineresources.md
  docs/git-resolver.md
  docs/hub-resolver.md
  docs/migrating-v1beta1-to-v1.md
  docs/pipelineresources.md
  docs/pipelineruns.md
  docs/pipelines.md
  docs/resolution.md
  docs/taskruns.md
Labels: approved, lgtm, size/L, kind/documentation, release-note-none

#6621 move trusted resources verification after we resolve the remote resources
  docs/trusted-resources.md
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/trustedresources/verify.go
  pkg/trustedresources/verify_test.go
  test/trusted_resources_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/misc

#6642 Refactor validation functions for indexing into array params
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/cleanup

#6639 Cleanp - Adding a single variable for default configmaps.
  pkg/apis/config/default.go
  pkg/apis/config/feature_flags.go
  pkg/apis/config/metrics.go
  pkg/apis/config/spire_config.go
  pkg/apis/config/store.go
  pkg/apis/config/store_test.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/events/event_test.go
  pkg/reconciler/events/k8sevent/event_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#6643 Simplify + add docstrings for PipelineRun resolution
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#6646 Remove enable-api-fields validation for array index replacements
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#6650 Clean up Task parameter validation logic
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
Labels: approved, lgtm, size/XL, release-note, kind/cleanup

#6653 Split Pipeline validation tests into separate test classes
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/cleanup

#6661 Bug Fixes: Update Status for Matrixed PipelineTask
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/XL, release-note

#6652 Split array param indexing validation between reconciler and webhook
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/task_validation.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6660 Refactor validation of propagated parameters and workspaces
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#6663 [TEP-0091] add VerificationResult
  pkg/trustedresources/verify.go
Labels: kind/feature, approved, lgtm, size/S, release-note-none

#6623 Keeps Deprecated Fields in Step and StepTemplate When Switching Versions
  pkg/apis/pipeline/v1beta1/container_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1beta1/task_conversion.go
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/apis/version/conversion.go
  test/conversion_test.go
Labels: kind/bug, approved, lgtm, size/XL, release-note-none

#6671 Cleanup: Remove "substituted context" task validation
  pkg/apis/config/contexts.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#6677 Test refactor: separate Task validation tests for propagation
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/cleanup

#6395 don't return validation error when taskrun failed/skipped
  examples/v1beta1/pipelineruns/6139-regression.yaml
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  test/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note, needs-cherry-pick

#6644 remove beta flag check for v1beta1 object param,results and array result
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelineref_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/result_validation.go
  pkg/apis/pipeline/v1beta1/result_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/taskref_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6510 feat: support to produce results from a failed task
  docs/pipelines.md
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  test/task_results_from_failed_tasks_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6673 [TEP-0091] use VerificationResult in verify
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/trustedresources/verify.go
  pkg/trustedresources/verify_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6495 Promote the provenance field in status
  config/config-feature-flags.yaml
  docs/additional-configs.md
  docs/pipelineruns.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/conversion_test.go
  test/custom_task_test.go
  test/e2e-tests.sh
  test/larger_results_sidecar_logs_test.go
  test/propagated_params_test.go
  test/status_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6649 Refactor ResolvedPipelineTask and remove redundant fields
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  pkg/reconciler/pipelinerun/resources/validate_dependencies_test.go
Labels: approved, lgtm, size/XXL, release-note-none, kind/cleanup

#6700 Docs update: CSI + projected workspaces are beta
  docs/additional-configs.md
  docs/workspaces.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6692 Add results-from feature flag to config-feature-flags.yaml
  config/config-feature-flags.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#6684 Cleanup context-based validation of propagated params/workspaces
  pkg/apis/config/contexts.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/cluster_task_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#6596 update affinity assistant creation implementation
  config/200-clusterrole.yaml
  docs/additional-configs.md
  docs/developers/README.md
  docs/developers/affinity-assistant.md
  docs/workspaces.md
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6703 Add tests for ResolvedPipelineTask IsCancelled and IsCancelledForTimeout
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#6710 Validate pipelineTask params usage only when explicit declaration is required
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6704 clarify in docs to not use apiVersion for taskRef for non-customtask
  docs/pipelines.md
  pkg/reconciler/taskrun/resources/taskref_test.go
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6719 Consolidate validation for Task/Pipeline beta features
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/result_validation.go
  pkg/apis/pipeline/v1/result_validation_test.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#6717 add missing unit test case for warn mode verification policy.
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  test/trustedresources.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#6725 Add validation for beta features in v1 remote Tasks/Pipelines
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6675 fix: taskrun still fails even with onerror set to continue
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note

#6691 [TEP-0091] return VerificationResult from GetTask
  pkg/internal/resolution/resolved_meta.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6724 merge VerifyTask and VerifyPipeline into VerifyResource
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/trustedresources/errors.go
  pkg/trustedresources/verify.go
  pkg/trustedresources/verify_test.go
Labels: approved, lgtm, size/L, release-note-action-required, kind/cleanup

#6723 Cleanup outdated usage for functions in upgrade test
  test/e2e-tests-upgrade.sh
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#6701 Validate beta features only when v1 Tasks and Pipelines are defined
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#6750 Issue#6697 Fix tab formatting for documentation
  docs/pipelineruns.md
  docs/pipelines.md
  docs/taskruns.md
  docs/tasks.md
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#6736 [TEP-0091] return VerificationResult from GetPipeline
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinespec/pipelinespec.go
  pkg/reconciler/pipelinerun/pipelinespec/pipelinespec_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6617 Cleanup: Move array indexing validation out of apis package
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/param_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/param_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/resources/validate_params.go
  pkg/reconciler/pipelinerun/resources/validate_params_test.go
  pkg/reconciler/taskrun/resources/validate_params.go
  pkg/reconciler/taskrun/resources/validate_params_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, lgtm, size/XXL, release-note-none, kind/cleanup

#6747 move tep75 tep76 and tep 107 examples from alpha to beta
  examples/v1beta1/pipelineruns/beta/pipeline-emitting-results.yaml
  examples/v1beta1/pipelineruns/beta/pipeline-with-when-expressions-using-array-results.yaml
  examples/v1beta1/pipelineruns/beta/propagated-pipeline-object-param.yaml
  examples/v1beta1/taskruns/beta/emit-array-results.yaml
  examples/v1beta1/taskruns/beta/param_array_indexing.yaml
  examples/v1beta1/taskruns/beta/propagated-object-parameters.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup
