Repository tektoncd/pipeline, pull requests merged in 2023-11, with the labels that each got.

#7324 Disable HTTP/2 by updating knative/pkg
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS, release-note, kind/security

#7289 [TEP-0144] Add enum API field
  docs/pipeline-api.md
  hack/ignored-openapi-violations.list
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/param_conversion.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#7322 [TEP-0142] Add ResolverRef to Ref
  docs/pipeline-api.md
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1/container_validation.go
  pkg/apis/pipeline/v1/container_validation_test.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/container_conversion.go
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/container_validation.go
  pkg/apis/pipeline/v1beta1/container_validation_test.go
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#7328 [TEP-0142] Refactor extractStepActions
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#7317 TEP-0142: Introduce Params and Results into StepActions CRD
  docs/pipeline-api.md
  docs/stepactions.md
  hack/ignored-openapi-violations.list
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/param_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1alpha1/openapi_generated.go
  pkg/apis/pipeline/v1alpha1/result_defaults_test.go
  pkg/apis/pipeline/v1alpha1/result_types.go
  pkg/apis/pipeline/v1alpha1/result_validation.go
  pkg/apis/pipeline/v1alpha1/result_validation_test.go
  pkg/apis/pipeline/v1alpha1/stepaction_defaults.go
  pkg/apis/pipeline/v1alpha1/stepaction_types.go
  pkg/apis/pipeline/v1alpha1/stepaction_validation.go
  pkg/apis/pipeline/v1alpha1/stepaction_validation_test.go
  pkg/apis/pipeline/v1alpha1/swagger.json
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#7326 [TEP-0144] Validate TaskRun for Param Enum
  docs/taskruns.md
  docs/tasks.md
  examples/v1/taskruns/alpha/param-enum.yaml
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/taskrun/validate_taskrun.go
  pkg/reconciler/taskrun/validate_taskrun_test.go
  test/custom_task_test.go
  test/e2e-tests-kind-prow-alpha.env
  test/e2e-tests.sh
Labels: kind/feature, approved, lgtm, size/L, release-note

#7334 TEP-0142: Add syntax for providing params to StepActions
  docs/pipeline-api.md
  docs/stepactions.md
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/container_conversion.go
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#7331 change bundle resolver to use secret instead of service account
  config/resolvers/bundleresolver-config.yaml
  docs/bundle-resolver.md
  pkg/resolution/resolver/bundle/bundle.go
  pkg/resolution/resolver/bundle/config.go
  pkg/resolution/resolver/bundle/params.go
  pkg/resolution/resolver/bundle/resolver.go
  pkg/resolution/resolver/bundle/resolver_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-action-required

#7321 [TEP-0142] Remote Resolution for StepAction
  docs/stepactions.md
  examples/v1/taskruns/alpha/stepaction-git-resolver.yaml
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/reconciler/apiserver/apiserver.go
  pkg/reconciler/apiserver/apiserver_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#7341 Update ko to go 1.20 in release task
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/security

#7337 [TEP-0142] Add SecurityContext
  docs/pipeline-api.md
  docs/stepactions.md
  pkg/apis/pipeline/v1alpha1/openapi_generated.go
  pkg/apis/pipeline/v1alpha1/stepaction_types.go
  pkg/apis/pipeline/v1alpha1/swagger.json
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#7332 TEP-0142: Add support for params between Step and StepActions
  examples/v1/pipelineruns/alpha/stepaction-params.yaml
  examples/v1/taskruns/alpha/stepaction-params.yaml
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/reconciler/taskrun/resources/validate_params.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#7340 [TEP-0142] Add VolumeMounts to StepAction
  docs/pipeline-api.md
  docs/stepactions.md
  go.mod
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1alpha1/openapi_generated.go
  pkg/apis/pipeline/v1alpha1/stepaction_types.go
  pkg/apis/pipeline/v1alpha1/stepaction_validation.go
  pkg/apis/pipeline/v1alpha1/stepaction_validation_test.go
  pkg/apis/pipeline/v1alpha1/swagger.json
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/substitution/substitution.go
  pkg/substitution/substitution_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#7318 Fix capitalization inconsistency in reconciler
  pkg/reconciler/events/cache/cache.go
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/events/k8sevent/events.go
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  pkg/reconciler/pipelinerun/resources/validate_params.go
  pkg/reconciler/pipelinerun/timeout.go
  pkg/reconciler/taskrun/validate_taskrun.go
Labels: approved, lgtm, size/M, ok-to-test, release-note-none, kind/cleanup

#7345 [TEP-0142] Support default resolver for Ref to remote StepAction
  docs/stepactions.md
  pkg/apis/pipeline/v1/task_defaults.go
  pkg/apis/pipeline/v1/task_defaults_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#7348 chore: pkg import only once
  pkg/apis/pipeline/v1/merge.go
  pkg/apis/pipeline/v1/pipelinerun_types.go
Labels: approved, lgtm, size/S, ok-to-test, release-note-none, kind/cleanup

#7347 TEP-0142: Introduce Value in TaskResults
  docs/pipeline-api.md
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/result_types.go
  pkg/apis/pipeline/v1/result_validation.go
  pkg/apis/pipeline/v1/result_validation_test.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/result_conversion.go
  pkg/apis/pipeline/v1beta1/result_types.go
  pkg/apis/pipeline/v1beta1/result_validation.go
  pkg/apis/pipeline/v1beta1/result_validation_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#7344 Add direnv support with boilerplate
  .env.sample
  .envrc
  .gitignore
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#7355 docs: update upper limit for layers in a bundle
  docs/tekton-bundle-contracts.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#7356 Pin the distroless base image to a stable alpine
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note, kind/misc

#7363 Replace ubi9/ubi-minimal with busybox image
  examples/v1/taskruns/5080-entrypoint-init-regression.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#7366 Fix the controller and webhook images to use stable alpine
  tekton/publish.yaml
Labels: approved, lgtm, size/XS, release-note, needs-cherry-pick, kind/misc

#7315 Add credentials to HTTP resolver
  docs/git-resolver.md
  docs/http-resolver.md
  examples/v1/pipelineruns/beta/http-resolver-credentials.yaml
  pkg/resolution/resolver/framework/testing/fakecontroller.go
  pkg/resolution/resolver/http/params.go
  pkg/resolution/resolver/http/resolver.go
  pkg/resolution/resolver/http/resolver_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#7186 fix: the pr may lose finallyStartTime when pipeline controller is not synchronized to all current state
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note

#7395 Cleanup v1beta1 reference in pipelinerun reconciler
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#7389 Improve migration documentation
  docs/migrating-v1beta1-to-v1.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#7393 fix: move getFeatureFlagsBaseOnAPIFlag from custom_task_test to another file
  test/custom_task_test.go
  test/featureflags.go
Labels: approved, lgtm, size/L, ok-to-test, release-note-none, kind/cleanup

#7338 [TEP-0144] Validate PipelineRun for Param Enum
  config/config-feature-flags.yaml
  docs/additional-configs.md
  docs/pipeline-api.md
  docs/pipelineruns.md
  docs/pipelines.md
  docs/taskruns.md
  docs/tasks.md
  examples/v1/pipelineruns/alpha/param-enum.yaml
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#7349 TEP-0142: Surface step results via termination message
  cmd/entrypoint/main.go
  docs/pipeline-api.md
  docs/stepactions.md
  examples/v1/taskruns/no-ci/stepaction-results.yaml
  hack/ignored-openapi-violations.list
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/result_types.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/result_types.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod.go
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/result/result.go
  pkg/result/result_test.go
  test/clients.go
  test/stepaction_results_test.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#7414 TEP-0142: Surface step results via sidecar logs
  cmd/sidecarlogresults/main.go
  docs/stepactions.md
  examples/v1/taskruns/alpha/stepaction-results.yaml
  internal/sidecarlogresults/sidecarlogresults.go
  internal/sidecarlogresults/sidecarlogresults_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#7327 Add @jeromeJu as a pipelines maintainer
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#7427 Update release with v0.54.0
  releases.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#7386 Error sweep: refactor steps termination when failing TaskRun
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#7429 Remove .envrc and show an example in .envrc.sample
  .env.sample
  .envrc
  .envrc.sample
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#7425 Update release cheat sheet
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#7432 Fix some spelling in stepactions.md
  docs/stepactions.md
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#7405 Cleanup error message for Step container status
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#7441 Update StepActions Documentation
  docs/additional-configs.md
  docs/stepactions.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#7238 Tracing: Add credentialsSecret for basic authentication to remote endpoint
  config/config-tracing.yaml
  config/controller.yaml
  docs/developers/tracing.md
  pkg/apis/config/tracing.go
  pkg/apis/config/tracing_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/tracing/tracing.go
  pkg/tracing/tracing_test.go
  test/controller.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, ok-to-test, release-note, kind/misc

#7430 Do not require `enable-api-fields: alpha` for entrypoint cancellation
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, approved, lgtm, size/XS, release-note

#7445 Update Feature Flags Documentation
  docs/additional-configs.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#7403 Error sweep: add more context for PipelineRunCouldntGetPipeline error message
  pkg/reconciler/pipelinerun/pipelinespec/pipelinespec.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#7438 fix: resolve issue where resolutionrequest defaulted to v1alpha1 vs v1beta1
  pkg/apis/resolution/v1beta1/resolution_request_defaults.go
Labels: kind/bug, approved, lgtm, size/XS, release-note
