Repository tektoncd/pipeline, pull requests merged in 2023-04, with the labels that each got.

#6478 Update min k8s version to 1.24
  .github/pull_request_template.md
  DEVELOPMENT.md
  docs/api-spec.md
  docs/how-to-write-a-resolver.md
  docs/resolution-getting-started.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6471 Replace v1beta1.TaskObject with *v1beta1.Task in TaskRun Reconciler
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/trustedresources/verify.go
  pkg/trustedresources/verify_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#6260 fix taskrun failing with duplicate unique image found
  pkg/pod/entrypoint_lookup_impl.go
  pkg/pod/entrypoint_lookup_impl_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#6432 Migrate Propagated Workspaces to Stable
  docs/additional-configs.md
  docs/pipelineruns.md
  docs/taskruns.md
  examples/v1beta1/pipelineruns/propagating-workspaces.yaml
  examples/v1beta1/pipelineruns/propagating_workspaces_with_referenced_resources.yaml
  examples/v1beta1/taskruns/propagating_workspaces.yaml
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6445 Clarify ParamValue syntax
  docs/api-spec.md
  docs/pipeline-api.md
  hack/ignored-openapi-violations.list
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/swagger.json
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#6473 chore: cleanup unused functions in the resources
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
Labels: approved, lgtm, size/L, ok-to-test, release-note-none, kind/cleanup

#5831 Rename ConfigSource and Source to `RefSource`
  docs/bundle-resolver.md
  docs/cluster-resolver.md
  docs/git-resolver.md
  docs/how-to-write-a-resolver.md
  docs/pipeline-api.md
  docs/resolver-template/cmd/demoresolver/main.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/provenance.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1beta1/provenance.go
  pkg/apis/pipeline/v1beta1/provenance_conversion.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/apis/resolution/v1alpha1/resolution_request_types.go
  pkg/apis/resolution/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/resolution/v1beta1/resolution_request_types.go
  pkg/apis/resolution/v1beta1/zz_generated.deepcopy.go
  pkg/internal/resolution/resolved_meta.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/pipelinespec/pipelinespec.go
  pkg/reconciler/pipelinerun/pipelinespec/pipelinespec_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/remote/oci/resolver.go
  pkg/remote/oci/resolver_test.go
  pkg/remote/resolution/resolver.go
  pkg/remote/resolution/resolver_test.go
  pkg/remote/resolver.go
  pkg/resolution/resolver/bundle/bundle.go
  pkg/resolution/resolver/bundle/resolver_test.go
  pkg/resolution/resolver/cluster/resolver.go
  pkg/resolution/resolver/cluster/resolver_test.go
  pkg/resolution/resolver/framework/fakeresolver.go
  pkg/resolution/resolver/framework/interface.go
  pkg/resolution/resolver/framework/reconciler.go
  pkg/resolution/resolver/framework/reconciler_test.go
  pkg/resolution/resolver/git/resolver.go
  pkg/resolution/resolver/git/resolver_test.go
  pkg/resolution/resolver/hub/resolver.go
  pkg/resolution/resource/crd_resource.go
  pkg/resolution/resource/resource.go
  pkg/trustedresources/verify.go
  test/resolution.go
  test/status_test.go
Labels: approved, lgtm, size/XXL, release-note, kind/misc

#6434 Rename PipelineResourceResult to RunResult
  docs/pipeline-api.md
  hack/ignored-openapi-violations.list
  internal/sidecarlogresults/sidecarlogresults.go
  internal/sidecarlogresults/sidecarlogresults_test.go
  pkg/apis/pipeline/v1/result_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1beta1/resource_types.go
  pkg/apis/pipeline/v1beta1/resource_types_test.go
  pkg/apis/pipeline/v1beta1/result_types.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/spire/sign.go
  pkg/spire/spire.go
  pkg/spire/spire_mock.go
  pkg/spire/spire_mock_test.go
  pkg/spire/spire_test.go
  pkg/spire/verify.go
  pkg/termination/parse.go
  pkg/termination/parse_test.go
  pkg/termination/write.go
  pkg/termination/write_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/misc

#6439 Add RoundTrip to Conversion Integration Test
  test/conversion_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#6477 Cleanup: addressed various `nolint` items. 🧹 🧹 🧹
  pkg/pod/pod.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/trustedresources/verifier/verifier.go
  pkg/trustedresources/verify.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#6503 hotfix 0.41.x no logs in stdout/stderr if uses stdoutConfig
  cmd/entrypoint/runner.go
  cmd/entrypoint/runner_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6481 [TEP-0133] Apply default resolver to finally tasks
  pkg/apis/pipeline/v1/pipeline_defaults.go
  pkg/apis/pipeline/v1/pipeline_defaults_test.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  pkg/apis/pipeline/v1beta1/pipeline_defaults_test.go
Labels: kind/bug, approved, lgtm, size/XL, release-note

#6497 Sync v1 TaskRun StepSpecs and SidecarSpecs Merge with v1beta1 Overrides Merge
  pkg/apis/pipeline/v1/merge.go
  pkg/apis/pipeline/v1/merge_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#6499 [TEP-114] Remove the feature flag custom-task-version to stop supporting v1alpha1 Run
  config/config-feature-flags.yaml
  docs/additional-configs.md
  docs/pipelines.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/apis/config/testdata/feature-flags-invalid-custom-task-version.yaml
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/reconciler/pipelinerun/cancel_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/timeout_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/custom_task_test.go
Labels: approved, lgtm, size/XL, release-note-action-required, kind/cleanup

#6474 chore: add copyright header to source files
  cmd/entrypoint/namespaces.go
  cmd/entrypoint/namespaces_linux.go
  cmd/entrypoint/post_writer.go
  cmd/entrypoint/post_writer_test.go
  cmd/entrypoint/runner_test.go
  cmd/entrypoint/subcommands/init.go
  cmd/entrypoint/subcommands/init_test.go
  cmd/entrypoint/subcommands/step_init.go
  cmd/entrypoint/subcommands/step_init_test.go
  cmd/entrypoint/subcommands/subcommands_test.go
  cmd/entrypoint/waiter.go
  hack/reference-docs-template/placeholder.go
  hack/tools.go
  internal/sidecarlogresults/sidecarlogresults_test.go
  pkg/apis/pipeline/images_test.go
  pkg/apis/pipeline/v1/taskref_types_test.go
  pkg/apis/pipeline/v1beta1/container_conversion.go
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/param_conversion.go
  pkg/apis/pipeline/v1beta1/pipelineref_conversion.go
  pkg/apis/pipeline/v1beta1/resolver_conversion.go
  pkg/apis/pipeline/v1beta1/result_conversion.go
  pkg/apis/pipeline/v1beta1/taskref_conversion.go
  pkg/apis/pipeline/v1beta1/taskref_types_test.go
  pkg/apis/pipeline/v1beta1/workspace_conversion.go
  pkg/credentials/initialize_test.go
  pkg/pod/scripts_constants.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  pkg/reconciler/testing/logger.go
  pkg/remote/errors.go
  pkg/resolution/common/context_test.go
  pkg/spire/test/ca.go
  pkg/spire/test/errstrings/err_posix.go
  pkg/spire/test/fakebundleendpoint/server.go
  pkg/spire/test/fakeworkloadapi/workload_api.go
  pkg/spire/test/fakeworkloadapi/workload_api_posix.go
  pkg/spire/test/keys.go
  pkg/spire/test/pemutil/pem.go
  pkg/spire/test/x509util/util.go
  pkg/workspace/apply_test.go
  test/featureflags.go
  test/resolution.go
  tools/tools.go
Labels: approved, lgtm, size/XL, ok-to-test, release-note-none, kind/misc

#6301 [TEP074] Tombstone ResourceResult field with the removal of PipelineResources
  docs/deprecations.md
  docs/pipeline-api.md
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#6414 Migrate documentation to v1 API
  docs/migrating-v1beta1-to-v1.md
  docs/pipelineruns.md
  docs/pipelines.md
  docs/taskruns.md
  docs/tasks.md
Labels: approved, lgtm, size/XL, kind/documentation, release-note

#6484 Hygiene: enable `exhaustive` linter.
  .golangci.yml
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1beta1/param_types.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/credentials/dockercreds/creds.go
  pkg/credentials/dockercreds/creds_test.go
  pkg/credentials/gitcreds/creds.go
  pkg/credentials/gitcreds/creds_test.go
  pkg/pod/status.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/taskrun/resources/apply.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#6504 updating releases with the latest 0.41.2
  releases.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6509 Fix resolutionrequest conversion
  cmd/webhook/main.go
  pkg/apis/resolution/v1alpha1/resolution_request_conversion.go
  pkg/apis/resolution/v1alpha1/resolution_request_conversion_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6517 Fixed Broken Links in Cloud Events Documentation
  docs/events.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#6523 create multi-arch Wait Custom Task Controller image
  test/custom_task_test.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6508 TEP-0114: Remove support for v1alpha1.Run
  cmd/controller/main.go
  cmd/webhook/main.go
  config/200-clusterrole.yaml
  config/300-run.yaml
  docs/README.md
  docs/customruns.md
  docs/deprecations.md
  docs/pipelines.md
  docs/runs.md
  pkg/controller/filter.go
  pkg/controller/filter_test.go
  pkg/reconciler/events/cache/cache.go
  pkg/reconciler/events/cache/cache_test.go
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/events/cloudevent/cloudevent.go
  pkg/reconciler/events/cloudevent/interface.go
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/cancel_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/pipelinerun_updatestatus_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/timeout.go
  pkg/reconciler/pipelinerun/timeout_test.go
  pkg/reconciler/run/controller.go
  pkg/reconciler/run/run.go
  pkg/reconciler/run/run_test.go
  pkg/status/status.go
  pkg/status/status_test.go
  test/clients.go
  test/controller.go
  test/custom-task-ctrls/wait-task-alpha/README.md
  test/custom-task-ctrls/wait-task-alpha/cmd/controller/main.go
  test/custom-task-ctrls/wait-task-alpha/config/controller.yaml
  test/custom-task-ctrls/wait-task-alpha/go.mod
  test/custom-task-ctrls/wait-task-alpha/go.sum
  test/custom-task-ctrls/wait-task-alpha/pkg/reconciler/reconciler.go
  test/custom-task-ctrls/wait-task-alpha/pkg/reconciler/reconciler_test.go
  test/parse/yaml.go
  test/wait.go
Labels: approved, lgtm, size/XXL, release-note-action-required, kind/cleanup

#6514 Migrate v1beta1 RunResult to Unversioned Package
  docs/pipeline-api.md
  internal/sidecarlogresults/sidecarlogresults.go
  internal/sidecarlogresults/sidecarlogresults_test.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/resource_types.go
  pkg/apis/pipeline/v1beta1/resource_types_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/status.go
  pkg/result/result.go
  pkg/result/result_test.go
  pkg/spire/sign.go
  pkg/spire/spire.go
  pkg/spire/spire_mock.go
  pkg/spire/spire_mock_test.go
  pkg/spire/spire_test.go
  pkg/spire/verify.go
  pkg/termination/parse.go
  pkg/termination/parse_test.go
  pkg/termination/write.go
  pkg/termination/write_test.go
Labels: approved, lgtm, size/XL, release-note-none, kind/misc

#6541 Fix serviceAccountName in v1 Examples
  examples/v1/pipelineruns/no-ci/pipelinerun-taskrunspecs.yaml
  examples/v1beta1/pipelineruns/no-ci/pipelinerun-taskrunspecs.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6527 TEP-0089: Refactor setting of "enforce-nonfalsifiability" feature flag
  docs/spire.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#6546 Fix Timeouts Default in v1 PipelienRun
  pkg/apis/pipeline/v1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1/pipelinerun_defaults_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#6095 Fix for PipelineRuns getting stuck in the running state in the cluster
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/timeout.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6542 Remove TaskrunMetrics Blank Identifier in CustomRun Reconciler to Avoid Redundant TaskRun Informer Register
  pkg/reconciler/customrun/customrun.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6547 Keep securitycontext fields simple in e2e
  test/conversion_test.go
Labels: approved, lgtm, size/S, release-note, kind/misc

#6548 Add timeouts tests for v1beta1 PipelineRun Defaults
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#6293 refactor getTaskRunCreations in the pipelineRun reconciler test suite
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/L, area/testing, ok-to-test, release-note-none, kind/cleanup

#6554 [release-v0.44.x] Fix Timeouts Default in v1 PipelienRun
  pkg/apis/pipeline/v1/pipelinerun_defaults.go
  pkg/apis/pipeline/v1/pipelinerun_defaults_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#6531 Remove RunControllerName from the Codebase
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/cleanup

#6562 Fix v1beta1.CustomRun GVK
  pkg/apis/pipeline/v1beta1/customrun_types.go
Labels: approved, lgtm, size/XS, release-note, kind/cleanup

#6564 Add link to examples of good release notes to template
  .github/pull_request_template.md
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6569 Update wording for end-of-life in releases.md
  releases.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6566 Update development guide on creating new CRDs
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#6567 Add developer guidance for API changes to CustomRuns
  api_compatibility_policy.md
  docs/developers/api-changes.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6518 Hygiene: enabled presets and various linters.
  .golangci.yml
  cmd/entrypoint/main.go
  cmd/webhook/main.go
  pkg/apis/config/feature_flags.go
  pkg/apis/pipeline/controller.go
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/pipelineref_validation.go
  pkg/apis/pipeline/v1beta1/taskref_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/credentials/initialize.go
  pkg/pod/pod.go
  pkg/pod/status.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/resolution/resolver/hub/resolver.go
  pkg/result/result.go
  pkg/spire/verify.go
  pkg/status/status.go
  pkg/trustedresources/verifier/verifier.go
  pkg/trustedresources/verify.go
  test/controller.go
  test/duplicate_test.go
  test/resolvers_test.go
  test/step_output_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#6426 doc: added a note on pulling task image from private repo
  docs/tasks.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#6532 Update API compatibility policy for stable CRDs
  api_compatibility_policy.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6571 Remove v1alpha1 Runs Client setup in init test
  test/clients.go
  test/init_test.go
Labels: approved, lgtm, size/S, priority/critical-urgent, release-note-none, kind/misc

#6505 Custom task without api version return validation error
  docs/pipelines.md
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#6588 Allow references to ClusterTasks in v1 Pipeline Tasks
  docs/pipeline-api.md
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1/taskref_types.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#6529 Run events controller as separate binary
  cmd/events/kodata/LICENSE
  cmd/events/main.go
  config/200-clusterrole.yaml
  config/200-serviceaccount.yaml
  config/201-clusterrolebinding.yaml
  config/201-rolebinding.yaml
  config/events.yaml
  tekton/publish.yaml
Labels: approved, lgtm, size/L, release-note, kind/misc

#6577 Add Unit Tests for Array Results using [] notation
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#6516 Add matrix support for using references to entire PipelineRun array parameters
  docs/matrix.md
  examples/v1beta1/pipelineruns/alpha/pipelinerun-with-matrix-array-references.yaml
  pkg/apis/pipeline/v1/matrix_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/matrix_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/validate_params.go
  pkg/reconciler/pipelinerun/resources/validate_params_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none
