Repository tektoncd/pipeline, pull requests merged in 2023-01, with the labels that each got.

#5927 Enabled `thelper` linter.
  .golangci.yml
  pkg/apis/config/artifact_bucket_test.go
  pkg/apis/config/artifact_pvc_test.go
  pkg/apis/config/default_test.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/metrics_test.go
  pkg/apis/config/resolver/feature_flags_test.go
  pkg/apis/config/trusted_resources_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelineref_validation_test.go
  pkg/credentials/initialize_test.go
  pkg/entrypoint/entrypointer_test.go
  pkg/git/git_test.go
  pkg/internal/computeresources/limitrange/limitrange_test.go
  pkg/internal/computeresources/transformer_test.go
  pkg/pod/entrypoint_lookup_impl_test.go
  pkg/pullrequest/api_test.go
  pkg/reconciler/customrun/customrun_test.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/pipelinerun_updatestatus_test.go
  pkg/reconciler/resolutionrequest/resolutionrequest_test.go
  pkg/reconciler/run/run_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/reconciler/testing/configmap.go
  pkg/reconciler/testing/logger.go
  pkg/resolution/resolver/bundle/resolver_test.go
  pkg/resolution/resolver/git/resolver_test.go
  pkg/resolution/resolver/hub/resolver_test.go
  pkg/status/status_test.go
  test/artifact_bucket_test.go
  test/cluster_resource_test.go
  test/controller.go
  test/custom_task_test.go
  test/dag_test.go
  test/duplicate_test.go
  test/embed_test.go
  test/featureflags.go
  test/helm_task_test.go
  test/hermetic_taskrun_test.go
  test/init_test.go
  test/kaniko_task_test.go
  test/ko_test.go
  test/larger_results_sidecar_logs_test.go
  test/multiarch_utils.go
  test/parse/yaml.go
  test/pipelinefinally_test.go
  test/pipelinerun_test.go
  test/propagated_params_test.go
  test/registry_test.go
  test/retry_test.go
  test/status_test.go
  test/trusted_resources_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#5929 [docs] Added `go-licenses` to development setup.
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#5936 ChildReference status helper functions should support both CustomRuns and Runs
  pkg/status/status.go
  pkg/status/status_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#5935 Update golangci-lint in Makefile and tools/go.mod to v1.50.1
  Makefile
  tools/go.mod
  tools/go.sum
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#5939 Docs: Sync pipeline-api.md
  docs/pipeline-api.md
  third_party/github.com/LICENSE
  third_party/github.com/cloudflare/circl/LICENSE
  third_party/github.com/skeema/knownhosts/LICENSE
  third_party/github.com/skeema/knownhosts/NOTICE
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#5945 Register informers for v1 TaskRun and PipelineRun
  pkg/apis/pipeline/v1/register.go
Labels: kind/bug, approved, lgtm, size/XS, release-note, needs-cherry-pick

#5944 Use the golangci-lint configured in Makefile in build tests
  Makefile
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5893 [pkg/resolution] clean up io/ioutil package
  pkg/resolution/resolver/bundle/bundle.go
  pkg/resolution/resolver/git/resolver_test.go
Labels: approved, lgtm, size/S, ok-to-test, release-note-none

#5949 Sync taskrun_types for v1 storage release
  pkg/apis/pipeline/v1/taskrun_types.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5872 Add @wlynch as a pipelines maintainer
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#5864 [cmd/entrypoint] remove ioutil for new go version
  cmd/entrypoint/post_writer_test.go
  cmd/entrypoint/runner_test.go
  cmd/entrypoint/subcommands/cp_test.go
  cmd/entrypoint/subcommands/decode_script.go
  cmd/entrypoint/subcommands/decode_script_test.go
  cmd/entrypoint/subcommands/init_test.go
  cmd/entrypoint/waiter_test.go
Labels: approved, lgtm, size/M, ok-to-test, release-note-none, kind/cleanup

#5968 Fix embedded-status conversion for PipelineRuns
  pkg/apis/config/testing/feature_flags.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
Labels: kind/bug, approved, lgtm, size/L, priority/critical-urgent, release-note, needs-cherry-pick

#5957 Fix formatting of bug report template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#5961 Switch the Default Value of Feature Flag `custom-task-version` to `v1beta1`
  config/config-feature-flags.yaml
  docs/deprecations.md
  docs/install.md
  docs/pipelines.md
  pkg/apis/config/feature_flags.go
  pkg/reconciler/pipelinerun/cancel_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/timeout_test.go
Labels: approved, lgtm, size/L, release-note, kind/misc

#5937 Add `taskrun.status.cloudEvents` to deprecation.md
  docs/deprecations.md
  docs/pipeline-api.md
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_types.go
Labels: approved, lgtm, size/S, release-note, kind/misc

#5965 [TEP-0091] enable kms in trusted resources
  docs/trusted-resources.md
  pkg/trustedresources/verifier/verifier.go
  pkg/trustedresources/verifier/verifier_test.go
  vendor/github.com/sigstore/sigstore/pkg/signature/kms/fake/doc.go
  vendor/github.com/sigstore/sigstore/pkg/signature/kms/fake/signer.go
  vendor/modules.txt
Labels: kind/feature, approved, lgtm, size/M, release-note

#5975 TEP-0114: Remove Feature Flag `enable-custom-tasks`
  config/config-feature-flags.yaml
  docs/install.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-enable-api-fields-overrides-bundles-and-custom-tasks.yaml
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  test/custom_task_test.go
Labels: approved, lgtm, size/M, release-note, kind/misc

#5977 Cleanup resources of ClusterTask
  pkg/reconciler/taskrun/resources/taskspec.go
Labels: approved, lgtm, size/XS, ok-to-test, release-note, kind/cleanup

#5989 Fix PipelineRunStatus Reconciler for EmbeddedStatus Switch
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#5995 [TEP074] Remove CloudEvent pipelineResources
  docs/resources.md
  examples/v1beta1/taskruns/cloud-event.yaml
  pkg/apis/pipeline/v1beta1/resource_types.go
  pkg/apis/resource/resource.go
  pkg/apis/resource/v1alpha1/cloudevent/cloud_event_resource.go
  pkg/apis/resource/v1alpha1/cloudevent/cloud_event_resource_test.go
  pkg/apis/resource/v1alpha1/pipeline_resource_types.go
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, lgtm, size/XXL, release-note-action-required, kind/misc

#5996 [TEP074] Remove Cluster pipelineResources
  cmd/controller/main.go
  cmd/kubeconfigwriter/kodata/LICENSE
  cmd/kubeconfigwriter/kodata/third_party
  cmd/kubeconfigwriter/main.go
  config/controller.yaml
  docs/install.md
  docs/resources.md
  pkg/apis/pipeline/images.go
  pkg/apis/pipeline/v1beta1/resource_types.go
  pkg/apis/resource/resource.go
  pkg/apis/resource/v1alpha1/cluster/cluster_resource.go
  pkg/apis/resource/v1alpha1/cluster/cluster_resource_test.go
  pkg/apis/resource/v1alpha1/pipeline_resource_types.go
  pkg/apis/resource/v1alpha1/pipelineresource_validation.go
  pkg/apis/resource/v1alpha1/pipelineresource_validation_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/resources/taskresourceresolution_test.go
  test/cluster_resource_test.go
Labels: approved, lgtm, size/XXL, release-note-action-required, kind/misc

#5934 [TEP0100] Default to minimal embedded-status
  config/config-feature-flags.yaml
  docs/deprecations.md
  docs/pipelineruns.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/reconciler/pipelinerun/cancel_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/timeout_test.go
Labels: approved, lgtm, size/L, ok-to-test, release-note, kind/misc

#6018 Fully remove kubeconfigwriter image
  docs/install.md
  pkg/apis/pipeline/images.go
  pkg/apis/pipeline/images_test.go
  pkg/apis/resource/v1alpha1/storage/gcs_test.go
  pkg/artifacts/artifact_storage_test.go
  pkg/pod/status_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/resources/apply_test.go
  pkg/reconciler/taskrun/resources/input_resource_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  tekton/publish.yaml
Labels: approved, lgtm, size/S, release-note-none, kind/cleanup

#6007 make the webhook controller name configurable
  cmd/webhook/main.go
  config/webhook.yaml
Labels: kind/feature, approved, lgtm, size/L, release-note

#6013 Fix typo in deprecations.md
  docs/deprecations.md
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6004 Fix task parameter value substitution error due to `propagateParams`
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note-none

#6027 Use remote resolution in release pipeline
  tekton/release-pipeline.yaml
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#6028 Increase memory limit for remote resolvers deployment
  config/resolvers/resolvers-deployment.yaml
Labels: kind/bug, approved, lgtm, size/XS, release-note

#6040 TEP-0114: Switch to use FilterCustomRunRef - Wait Custom Task Beta
  test/custom-task-ctrls/wait-task-beta/cmd/controller/main.go
  test/custom-task-ctrls/wait-task-beta/go.mod
  test/custom-task-ctrls/wait-task-beta/go.sum
  test/custom-task-ctrls/wait-task-beta/pkg/reconciler/reconciler_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#6041 Fix example customrun.yaml
  test/custom-task-ctrls/wait-task-beta/example_customrun.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/cleanup

#6035 Add v0.44.0 to releases.md
  releases.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#5737 Add prow env for beta integration test
  test/README.md
  test/e2e-tests-kind-prow-beta.env
Labels: kind/feature, approved, lgtm, size/XS, release-note

#6047 Adds label kind/misc to dependentbot
  .github/dependabot.yml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#6031 Beta Example Tests
  test/path_filtering.go
  test/path_filtering_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#6052 Update task-level compute resources docs
  docs/pipelineruns.md
  docs/taskruns.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#6022 Update pipelineResources deprecation
  docs/deprecations.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6063 increase the timer for reading k8s event in test
  pkg/reconciler/events/k8sevent/events.go
Labels: approved, lgtm, size/S, kind/flake, release-note-none

#6059 Fix outdated remote resolution documentation
  docs/install.md
  docs/pipelineruns.md
  docs/pipelines.md
  docs/resolution.md
  docs/taskruns.md
Labels: approved, lgtm, size/L, kind/documentation, release-note-none

#6038 minor doc update for array and object results
  docs/pipelines.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6039 adding section for emitting array results
  docs/tasks.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#6050 Propagated Parameters - Stable
  docs/install.md
Labels: kind/feature, approved, lgtm, size/XS, release-note

#6070 Add details about deprecating feature flags `enable-custom-task` and `custom-task-version`
  docs/deprecations.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note

#6061 Fix converted legacy bundle->remote resolver syntax to be case-insensitive for kind
  pkg/resolution/resolver/bundle/bundle.go
  pkg/resolution/resolver/bundle/resolver_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#6017 Document behavior of feature-flag flips
  docs/install.md
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6030 Propagated Workspaces to Beta
  docs/pipelineruns.md
  docs/taskruns.md
  examples/v1beta1/pipelineruns/beta/propagating-workspaces.yaml
  examples/v1beta1/pipelineruns/beta/propagating_workspaces_with_referenced_resources.yaml
  examples/v1beta1/taskruns/beta/propagating_workspaces.yaml
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6051 Fix spammy logs
  pkg/reconciler/events/cloudevent/cloud_event_controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#6057 updating an example taskrun with array parameters
  docs/tasks.md
  examples/v1beta1/taskruns/array-default.yaml
Labels: approved, lgtm, size/L, kind/documentation, release-note-none

#6077 matrix with array results indexing
  examples/v1beta1/pipelineruns/alpha/pipelinerun-with-matrix-and-results.yaml
Labels: approved, lgtm, size/M, release-note-none, kind/misc
