Repository tektoncd/pipeline, pull requests merged in 2023-10, with the labels that each got.

#7169 Regression: fix results with out of order tasks
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#7149 Fix race condition in PVC deletion
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/volumeclaim/pvchandler.go
  pkg/reconciler/volumeclaim/pvchandler_test.go
  test/affinity_assistant_test.go
  test/wait.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#7168 Add @Yongxuanzhang as a pipelines maintainer
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#7171 update perl docker image with multi-arch tag
  examples/v1/taskruns/step-script.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#7176 Fix typo in documentation
  pkg/reconciler/pipelinerun/pipelinerun.go
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#7076 [TEP0138] RFC: Add feature graduation process documentation
  api_compatibility_policy.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6489 feat: TEP-0097 change in taskrun breakpoints api fields
  docs/pipeline-api.md
  docs/taskruns.md
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/taskrun_types_test.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/pod_test.go
  pkg/pod/script.go
  pkg/pod/script_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-action-required, lifecycle/stale

#7181 Add @chitrangpatel as an pipelines maintainer
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#7205 #7190 display name link fixed in pipelines.md
  docs/pipelines.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#7060 feat: add ability to include reason in count metrics
  config/config-observability.yaml
  docs/metrics.md
  pkg/apis/config/metrics.go
  pkg/apis/config/metrics_test.go
  pkg/apis/config/testdata/config-observability-reason.yaml
  pkg/pipelinerunmetrics/metrics.go
  pkg/pipelinerunmetrics/metrics_test.go
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: kind/feature, approved, lgtm, size/L, ok-to-test, release-note

#7206 Refactor version.ValidateEnabledAPIFields to config pkg
  pkg/apis/config/featureflags_validation.go
  pkg/apis/config/featureflags_validation_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipelineref_validation.go
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/taskref_validation.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/version/featureflags_validation.go
  pkg/apis/version/featureflags_validation_test.go
Labels: approved, lgtm, size/L, release-note, kind/misc

#7212 Extend release timeouts in release cheatsheet
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#7215 Increase the publish timeout
  tekton/release-pipeline.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#7194 Added note to install.md to use tektoncd/operator for production installs
  docs/install.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#7162 [TEP-0050] Add OnError field
  docs/pipeline-api.md
  docs/pipelines.md
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/pipeline_types.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion.go
  pkg/apis/pipeline/v1beta1/pipeline_conversion_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/swagger.json
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#7167 TEP-140: Produce Results in Matrix
  docs/matrix.md
  docs/variables.md
  examples/v1/pipelineruns/alpha/pipelinerun-with-matrix-context-variables.yaml
  examples/v1/pipelineruns/alpha/pipelinerun-with-matrix-emitting-results.yaml
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1/param_types_test.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
  pkg/reconciler/pipelinerun/resources/validate_params.go
  pkg/reconciler/pipelinerun/resources/validate_params_test.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#7209 #7027 Cleanup `cmp.Diff(want, got)` for all `diff.PrintWantGot()`
  pkg/apis/config/metrics_test.go
  pkg/apis/config/resolver/store_test.go
  pkg/apis/config/store_test.go
  pkg/apis/pipeline/internal/checksum/checksum_test.go
  pkg/apis/pipeline/v1/param_types_test.go
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1/result_defaults_test.go
  pkg/apis/pipeline/v1/task_types_test.go
  pkg/apis/pipeline/v1/taskrun_defaults_test.go
  pkg/apis/pipeline/v1/taskrun_types_test.go
  pkg/apis/pipeline/v1alpha1/run_types_test.go
  pkg/apis/pipeline/v1alpha1/run_validation_test.go
  pkg/apis/pipeline/v1beta1/customrun_types_test.go
  pkg/apis/pipeline/v1beta1/customrun_validation_test.go
  pkg/apis/pipeline/v1beta1/param_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_defaults_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/result_defaults_test.go
  pkg/apis/pipeline/v1beta1/task_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_defaults_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/pod/pod_test.go
  pkg/reconciler/pipeline/dag/dag_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/remote/oci/resolver_test.go
  pkg/resolution/resource/request_test.go
  pkg/substitution/substitution_test.go
  test/pipelinefinally_test.go
  test/trustedresources_test.go
Labels: approved, lgtm, size/L, ok-to-test, release-note-none, kind/cleanup

#7227 fix waiter test is flaky
  cmd/entrypoint/waiter.go
  pkg/entrypoint/entrypointer_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#7164 Promoting Matrix to Beta 🎉 🎓
  docs/additional-configs.md
  docs/matrix.md
  docs/pipelines.md
  examples/v1/pipelineruns/beta/pipelinerun-with-matrix-and-results.yaml
  examples/v1/pipelineruns/beta/pipelinerun-with-matrix-array-references.yaml
  examples/v1/pipelineruns/beta/pipelinerun-with-matrix-context-variables.yaml
  examples/v1/pipelineruns/beta/pipelinerun-with-matrix-emitting-results.yaml
  examples/v1/pipelineruns/beta/pipelinerun-with-matrix-include-explicit.yaml
  examples/v1/pipelineruns/beta/pipelinerun-with-matrix-include.yaml
  examples/v1/pipelineruns/beta/pipelinerun-with-matrix.yaml
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#7193 Add reviewers section to OWNERS file.
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#7234 [v0.50.x] Bump GRPC Go to 1.56.3 to fix CVE
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/internal/encoding/json/encode.go
  vendor/google.golang.org/protobuf/internal/encoding/text/encode.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/order/order.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/size.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS, release-note, kind/security

#7240 [0.47.x] Bump GRPC to v1.56.3
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/google.golang.org/grpc/CONTRIBUTING.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/alts/internal/handshaker/handshaker.go
  vendor/google.golang.org/grpc/credentials/alts/internal/handshaker/service/service.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/idle.go
  vendor/google.golang.org/grpc/internal/binarylog/binarylog.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/buffer/unbounded.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/envconfig/observability.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcsync/callback_serializer.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/serviceconfig/duration.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/logging.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/internal/encoding/json/encode.go
  vendor/google.golang.org/protobuf/internal/encoding/text/encode.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/order/order.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/size.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS, release-note, kind/security

#7233 Fix typos in DEVELOPMENT.md file
  DEVELOPMENT.md
Labels: approved, lgtm, size/S, kind/documentation, ok-to-test, release-note-none

#7225 [TEP-0104] Task-level Resource Requirements to beta
  docs/additional-configs.md
  docs/compute-resources.md
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/pod/pod.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#7100 TEP-0107: propagate results to embedded task spec
  docs/pipelineruns.md
  examples/v1/pipelineruns/propagating_results_implicit_resultref.yaml
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1/container_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/resultref.go
  pkg/apis/pipeline/v1/resultref_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  test/propagated_results_test.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#7254 Flake Test fix: Sort TaskRunResults
  test/propagated_results_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#7251 [TEP-0145] Add sanity check for CEL expression
  docs/pipelines.md
  pkg/apis/pipeline/v1/when_validation.go
  pkg/apis/pipeline/v1/when_validation_test.go
  pkg/apis/pipeline/v1beta1/when_validation.go
  pkg/apis/pipeline/v1beta1/when_validation_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#7256 Set public Tekton Hub API as default catalog
  config/resolvers/resolvers-deployment.yaml
  docs/hub-resolver.md
  go.mod
Labels: kind/feature, approved, lgtm, size/XS, release-note

#7272 fix wait entrypoint cancellation error log output.
  cmd/entrypoint/main.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#7255 [TEP-0145] Add CEL evaluation
  config/config-feature-flags.yaml
  docs/pipeline-api.md
  docs/pipelines.md
  examples/v1/pipelineruns/alpha/pipelinerun-with-cel-when-expressions.yaml
  go.mod
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/apis/pipeline/v1/when_types.go
  pkg/apis/pipeline/v1/when_types_test.go
  pkg/apis/pipeline/v1beta1/when_types.go
  pkg/apis/pipeline/v1beta1/when_types_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  test/custom_task_test.go
  test/e2e-tests-kind-prow-alpha.env
  test/e2e-tests.sh
Labels: kind/feature, approved, lgtm, size/XL, release-note

#7273 parameterize pipelineTask `displayName`
  docs/pipelines.md
  docs/variables.md
  examples/v1/pipelineruns/pipeline-with-displayname.yaml
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#7199 #6614 Add inclusive source scanning
  .github/workflows/woke.yml
  .wokeignore
  DEVELOPMENT.md
  Makefile
Labels: approved, lgtm, size/M, ok-to-test, release-note-none, kind/misc

#7286 Avoid unnecessary scans for codeql on non code
  .github/workflows/codeql-analysis.yml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#7188 fix: panic may occur when calculating the final task timeout waiting time
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note-none

#7279 [TEP-0144] Add feature flag and doc placeholder
  config/config-feature-flags.yaml
  docs/pipelines.md
  docs/tasks.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/apis/config/testdata/feature-flags-invalid-enable-param-enum.yaml
Labels: kind/feature, approved, lgtm, size/M, release-note

#7284 TEP-0142: Introduce StepAction referencing syntax in Steps
  docs/pipeline-api.md
  docs/stepactions.md
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/container_conversion.go
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#7299 Fix git resolver example
  examples/v1/pipelineruns/no-ci/git-resolver.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#7302 removed repeated word how-to-write-a-resolver.md
  docs/how-to-write-a-resolver.md
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/misc

#6799 remove GetUnsignedTask helper function and use var in each file
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/trustedresources/verify_test.go
  test/trustedresources.go
  test/trustedresources_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#7301 Update release with v0.53.0 LTS
  releases.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#7306 fixed issue #7282 changed broken link from release-pipeline-nightly.yaml to release-pipeline.yaml
  tekton/README.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#7239 Let the user pass a secret via a parameter for SCM API operations when using the git API resolver
  docs/git-resolver.md
  examples/v1/pipelineruns/no-ci/git-resolver-custom-secret.yaml
  pkg/resolution/resolver/git/params.go
  pkg/resolution/resolver/git/resolver.go
  pkg/resolution/resolver/git/resolver_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#7271 TEP-0142: Referencing StepActions in Steps
  docs/stepactions.md
  examples/v1/taskruns/alpha/stepaction.yaml
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/controller.go
  test/parse/yaml.go
Labels: kind/feature, approved, lgtm, size/XL, release-note
