Repository tektoncd/pipeline, pull requests merged in 2024-08, with the labels that each got.

#8184 pkg/taskrunmetrics/fake shouldn't be imported…
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#8187 {taskrun,pipelinerun}metrics: make sure config is up-to-date
  pkg/pipelinerunmetrics/metrics.go
  pkg/pipelinerunmetrics/metrics_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/taskrun/controller.go
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#8199 cluster-reslover: add support for StepAction
  pkg/apis/pipeline/v1beta1/stepaction_types.go
  pkg/resolution/resolver/cluster/resolver.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#8200 check namespace config for node throttle metric
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#8216 fix task name show `anonymous` in metric
  pkg/reconciler/taskrun/taskrun.go
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#8024 feat(matrix): Fix matrix param type mismatch problem for ref array result from customrun scenario
  pkg/reconciler/pipelinerun/resources/resultrefresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note-none

#8173 fix(pipelinerun): resolve issue where canceling active pipelinerun fails
  pkg/reconciler/pipelinerun/cancel.go
  test/cancel_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note

#8197 apply default-container-resource-requirements before LimitRange transformer
  pkg/internal/defaultresourcerequirements/transformer.go
  pkg/internal/defaultresourcerequirements/transformer_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, approved, lgtm, size/XXL, release-note

#7953 docs: fix links to Matrix examples
  docs/matrix.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#7391 TEP-0097 breakpoint before steps for taskrun
  cmd/entrypoint/main.go
  docs/debug.md
  docs/developers/taskruns.md
  docs/pipeline-api.md
  docs/taskruns.md
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/taskrun_types_test.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_types_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  pkg/pod/script.go
  pkg/pod/script_test.go
  pkg/pod/scripts_constants.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#8171 fix(taskrun): resolve issue with TaskRun not failing promptly after Pod OOM
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: kind/bug, approved, lgtm, size/S, ok-to-test, release-note

#8166 Add UID label to PipelineRun and TaskRun
  pkg/apis/pipeline/register.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#8226 Fix Artifact type to a pointer
  pkg/apis/pipeline/v1/artifact_types.go
  pkg/apis/pipeline/v1/artifact_types_test.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
  test/conversion_test.go
  test/larger_results_sidecar_logs_test.go
  test/matrix_test.go
  test/propagated_params_test.go
  test/propagated_results_test.go
  test/stepaction_results_test.go
  test/upgrade_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note
