Repository tektoncd/pipeline, pull requests merged in 2024-11, with the labels that each got.

#8344 Expose Resolvers Controller performance tuning configurations
  cmd/resolvers/main.go
Labels: kind/feature, approved, lgtm, size/S, release-note

#8356 Add `Failed Validation` group in message for the status message in PipelineRun
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#8376 fix(pipelinerun): resolve issue with PipelineRun not timing out successfully
  pkg/apis/pipeline/errors/errors.go
  pkg/reconciler/pipelinerun/cancel.go
  pkg/reconciler/pipelinerun/timeout.go
  test/timeout_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note-none

#8382 Fix StepAction support in Cluster resolver
  docs/cluster-resolver.md
  pkg/resolution/resolver/cluster/resolver.go
  pkg/resolution/resolver/cluster/resolver_test.go
Labels: kind/feature, approved, lgtm, size/M, ok-to-test, release-note

#8389 Use io.ReadFull to read the bundle content
  pkg/resolution/resolver/bundle/bundle.go
Labels: kind/bug, approved, lgtm, size/XS, release-note

#8401 Fixes git-resolver configuration for serverUrl and scmType
  pkg/remoteresolution/resolver/git/resolver_test.go
  pkg/resolution/resolver/git/resolver.go
  pkg/resolution/resolver/git/resolver_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none
