Repository tektoncd/pipeline, pull requests merged in 2024-07, with the labels that each got.

#7051 fix: the label is set to the wrong pipeline name
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: approved, lgtm, size/M, kind/documentation, ok-to-test, release-note

#7746 feat: introduce when expressions to steps
  cmd/entrypoint/main.go
  docs/pipeline-api.md
  docs/stepactions.md
  examples/v1/taskruns/alpha/stepaction-when.yaml
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1/merge.go
  pkg/apis/pipeline/v1/merge_test.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/when_types.go
  pkg/apis/pipeline/v1/when_validation.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/container_conversion.go
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/merge.go
  pkg/apis/pipeline/v1beta1/merge_test.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_conversion_test.go
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/when_types.go
  pkg/apis/pipeline/v1beta1/when_validation.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/container/step_replacements.go
  pkg/container/step_replacements_test.go
  pkg/entrypoint/entrypointer.go
  pkg/entrypoint/entrypointer_test.go
  pkg/pod/entrypoint.go
  pkg/pod/entrypoint_test.go
  test/step_when_test.go
Labels: kind/feature, approved, lgtm, size/XXL, release-note

#8078 chore: remove unsupported configurations `ScopeWhenExpressionsToTask`
  pkg/apis/config/feature_flags.go
Labels: approved, lgtm, size/S, ok-to-test, release-note-none, kind/misc

#8084 Handle error conditions in CheckMissingResultReferences
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note

#8077 Create release v0.61.0.
  releases.md
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#8090 Promote `onerror` Tasks to beta
  docs/additional-configs.md
  examples/v1/pipelineruns/beta/ignore-task-error.yaml
  pkg/apis/pipeline/v1/pipeline_types_test.go
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_types_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  test/ignore_task_error_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#8027 Correct error message to differentiate the cause
  pkg/apis/pipeline/v1beta1/task_conversion.go
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8072 Fix error message when a PipelineRun param is missing
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/S, ok-to-test, release-note

#8089 Perform matrix results validation on only result ref params
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#8098 Released patch release: v0.59.2
  releases.md
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#8102 Fix step action force replacing with default param
  pkg/reconciler/taskrun/resources/apply.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note

#8109 update the doc since the `onError` is now promoted
  docs/pipelines.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#7788 fix:when debug.breakpoints.onFailure is an empty string, redundant volumes appear
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/pod/pod.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note

#7958 Set readOnlyRootFilesystem as true in Controllers and Webhook
  config/controller.yaml
  config/events.yaml
  config/webhook.yaml
Labels: approved, lgtm, size/XS, release-note, kind/security

#8122 Update min kubernetes version in the install doc
  docs/install.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#8119 [release-v0.59.x] Perform matrix results validation on only result ref params
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#8120 [release-v0.56.x] Perform matrix results validation on only result ref params
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#8121 [release-v0.53.x] Perform matrix results validation on only result ref params
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#8111 document `failureIgnored`
  docs/taskruns.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#8052 feat(K8s native sidecar): Add support for Kubernetes native Sidecars
  config/config-feature-flags.yaml
  docs/additional-configs.md
  docs/pipeline-api.md
  docs/tasks.md
  examples/v1/taskruns/sidecar-ready-script.yaml
  examples/v1/taskruns/sidecar-ready.yaml
  go.mod
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/apis/config/testdata/feature-flags-invalid-enable-kubernetes-sidecar.yaml
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1/container_types_test.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/status.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/e2e-tests-kind-prow-alpha.env
  test/e2e-tests.sh
  test/featureflags.go
  test/sidecar_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#8108 DryRunValidate returns the mutated object
  pkg/reconciler/apiserver/apiserver.go
  pkg/reconciler/apiserver/apiserver_test.go
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/taskrun/resources/taskref.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#8127 access taskRun `reason` in addition to `status` in finally task
  docs/variables.md
  examples/v1/pipelineruns/beta/ignore-task-error.yaml
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#8106 Capture Remote StepAction Location in TaskRun Status
  docs/pipeline-api.md
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/pod/entrypoint.go
  pkg/pod/status.go
  pkg/pod/status_test.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#8103 Add isBuildArtifact field to Artifacts
  docs/artifacts.md
  docs/pipeline-api.md
  examples/v1/taskruns/alpha/produce-consume-artifacts.yaml
  go.mod
  pkg/apis/pipeline/v1/artifact_types.go
  pkg/apis/pipeline/v1/artifact_types_test.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1beta1/artifact_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  test/artifacts_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#8147 fix(taskrun): block taskrun spec updates once the taskrun has started
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note

#8149 fix(pipelinerun): block pipelinerun spec updates once the pipelinerun has started
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note

#8056 fix: If the finally timeout is set to 0s, the `reconciler` calculates the next queue entry time according to the pipeline timeout.
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note
