Repository tektoncd/pipeline, pull requests merged in 2024-12, with the labels that each got.

#8412 Remove bad links from StepActions TOC
  docs/stepactions.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#8414 Updated releases.md for v0.66.0
  releases.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#8375 tekton: fix bugfix-release.sh script
  tekton/bugfix-release.sh
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8411 Run e2e tests in GHA
  .github/workflows/e2e-matrix.yml
  .gitignore
  hack/setup-kind.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#8415 chore: fix some function name in comment
  pkg/apis/pipeline/v1/param_types.go
  pkg/apis/pipeline/v1beta1/param_types.go
  test/featureflags.go
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/misc

#8417 Add /retest chatops command
  .github/workflows/chatops_retest.yaml
  .github/workflows/slash.yml
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#8419 Fix getting the commit sha from comment event
  .github/workflows/chatops_retest.yaml
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#8420 Remove extra pip symbol
  .github/workflows/chatops_retest.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8421 Ignore failures when rerunning jobs
  .github/workflows/chatops_retest.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8423 Improve gha k8s e2e tests names
  .github/workflows/chatops_retest.yaml
  .github/workflows/e2e-matrix.yml
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#8437 typo fix
  docs/install.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none
