Repository tektoncd/pipeline, pull requests merged in 2024-06, with the labels that each got.

#7982 Fix Validation Error Merging StepTemplates with StepRef
  examples/v1/taskruns/beta/stepactions-steptemplate.yaml
  pkg/apis/pipeline/v1/merge.go
  pkg/apis/pipeline/v1/merge_test.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1beta1/merge.go
  pkg/apis/pipeline/v1beta1/merge_test.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#8004 Fix the document: Task Level Comp Res is beta
  docs/taskruns.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#8016 Fix: Identify workspace usage in a Task
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#8020 [release-v0.53.x] Fix: Identify workspace usage in a Task
  pkg/workspace/apply.go
  pkg/workspace/apply_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#8044 Fix: Example Test point to Catalog StepAction
  examples/v1/taskruns/beta/stepaction-git-resolver.yaml
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#8030 README.md: fix Kubernetes min version
  README.md
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#7969 Bundle resolver can use ServiceAccount for auth
  config/resolvers/200-clusterrole.yaml
  config/resolvers/bundleresolver-config.yaml
  pkg/remoteresolution/resolver/bundle/resolver_test.go
  pkg/resolution/resolver/bundle/bundle.go
  pkg/resolution/resolver/bundle/config.go
  pkg/resolution/resolver/bundle/params.go
  pkg/resolution/resolver/bundle/resolver.go
  pkg/resolution/resolver/bundle/resolver_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note

#8041 Tests before promoting LargerResults via Sidecarlogs to Beta
  test/larger_results_sidecar_logs_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#8029 fix: resolve issue where results may not be obtained from sidecar logs
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note

#8053 Document that task results are not enforced
  docs/pipelines.md
  docs/tasks.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#8043 Promote Larger Results via Sidecar Logs to Beta
  config/config-feature-flags.yaml
  docs/additional-configs.md
  docs/tasks.md
  examples/v1/taskruns/beta/large-task-result.yaml
  test/e2e-tests-kind-prow-beta.env
  test/featureflags.go
Labels: kind/feature, approved, lgtm, size/XS, release-note

#8047 Remove bobcatfish and lbernick from OWNERS 😿
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8051 Cleanup resolved object before validating through dry-run
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/taskrun/resources/taskref.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#8065 [release-v0.53.x] Cleanup resolved object before validating through dry-run
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/taskrun/resources/taskref.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#8063 [release-v0.59.x] Cleanup resolved object before validating through dry-run
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/taskrun/resources/taskref.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#8064 [release-v0.56.x] Cleanup resolved object before validating through dry-run
  pkg/reconciler/pipelinerun/resources/pipelineref.go
  pkg/reconciler/taskrun/resources/taskref.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#8023 Add a flag on controllers to configure resyncPeriod
  cmd/controller/main.go
  docs/tekton-controller-flags.md
  pkg/apis/pipeline/options.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#8006 [TEP-0094] Promote taskrun.spec's stepSpecs and sidecarSpecs to beta
  docs/additional-configs.md
  docs/taskruns.md
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note-none
