Repository tektoncd/pipeline, pull requests merged in 2024-03, with the labels that each got.

#7697 fix:add missing documentation link
  docs/additional-configs.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#7722 fix: avoid panic when used pipelineRef or pipelineSpec in pipeline task
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note

#7703 TEP 0147: add inputs/outputs to stepState
  docs/pipeline-api.md
  hack/ignored-openapi-violations.list
  pkg/apis/pipeline/v1/artifact_types.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/artifact_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  pkg/apis/pipeline/v1beta1/taskrun_conversion_test.go
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#7683 implementing TEP-0150 - `displayName` in `childReferences`
  docs/matrix.md
  docs/pipeline-api.md
  docs/pipelines.md
  examples/v1/pipelineruns/beta/pipelinerun-with-matrix.yaml
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go
  pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate.go
  pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#7742 fix: pipeline execution status test case index error
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/apis/pipeline/v1/pipeline_validation_test.go
  pkg/apis/pipeline/v1beta1/pipeline_validation.go
  pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note-none

#7796 Remove conversion configuration for `ClusterTask`
  config/300-crds/300-clustertask.yaml
Labels: kind/bug, approved, lgtm, size/XS, release-note

#7795 Do not register `StepAction` for conversion
  cmd/webhook/main.go
Labels: kind/bug, approved, lgtm, size/XS, release-note

#7757 Fix: Merge StepTemplate with Step containing Results and Params
  pkg/apis/pipeline/v1/merge.go
  pkg/apis/pipeline/v1/merge_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#7790 Fix: update golangci-lint docs link
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#7741 updating releases file to include 0.53.4 and 0.56.2
  releases.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#7755 fix: the params in step replace other fields in step that are not in stepaction
  pkg/apis/pipeline/v1alpha1/stepaction_types.go
  pkg/reconciler/taskrun/resources/taskspec.go
  pkg/reconciler/taskrun/resources/taskspec_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note

#7728 .github/workflows: make codeql a bit quicker
  .github/workflows/codeql-analysis.yml
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#7813 [StepActions] when using a stepTemplate the ref gets removed
  pkg/apis/pipeline/v1/merge.go
  pkg/apis/pipeline/v1/merge_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note-none
