Repository tektoncd/pipeline, pull requests merged in 2025-04, with the labels that each got.

#8672 Move Step `when` expressions documentation from StepActions to Tasks documetnation.
  docs/stepactions.md
  docs/tasks.md
Labels: approved, lgtm, size/L, kind/documentation, release-note-none

#8605 chore: param enum usage example for stepaction
  examples/v1/taskruns/beta/stepaction-params.yaml
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#8635 fix: add stepaction as a valid kind in the hub resolver
  pkg/remoteresolution/resolver/hub/resolver_test.go
  pkg/resolution/resolver/hub/resolver.go
  pkg/resolution/resolver/hub/resolver_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#8537 feat: add support for authenticated git clone
  docs/git-resolver.md
  pkg/remoteresolution/resolver/git/resolver.go
  pkg/resolution/resolver/git/config.go
  pkg/resolution/resolver/git/params.go
  pkg/resolution/resolver/git/resolver.go
  pkg/resolution/resolver/git/resolver_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#8600 feat(pipeline): allow variable substitution in pipeline.tasks[].onError
  docs/variables.md
  pkg/apis/pipeline/v1/pipeline_validation.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/apply.go
  pkg/reconciler/pipelinerun/resources/apply_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#8650 Update link to section on overriding task requests
  docs/taskruns.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#8674 Consume release pipeline images and task bundles from GHCR
  tekton/publish.yaml
  tekton/release-cheat-sheet.md
  tekton/release-pipeline.yaml
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#8699 Add v0.70 to the releases doc and fix dates of v0.64 and v0.69 releases
  releases.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#8683 fix: handle subPath directory creation errors gracefully
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#8343 misc: promote `keep-pod-on-cancel` to beta
  pkg/apis/config/feature_flags.go
  test/e2e-tests-kind-prow-alpha.env
  test/e2e-tests-kind-prow-beta.env
  test/e2e-tests.sh
  test/featureflags.go
Labels: approved, lgtm, size/S, release-note, kind/misc

#8546 feat: promote StepActions to GA
  config/300-crds/300-pipelinerun.yaml
  config/300-crds/300-stepaction.yaml
  config/300-crds/300-task.yaml
  config/300-crds/300-taskrun.yaml
  config/config-feature-flags.yaml
  docs/additional-configs.md
  docs/pipeline-api.md
  docs/stepactions.md
  examples/v1/pipelineruns/stepaction-params.yaml
  examples/v1/taskruns/stepaction-params.yaml
  examples/v1/taskruns/stepaction-passing-results.yaml
  examples/v1/taskruns/stepaction-results.yaml
  examples/v1/taskruns/stepaction.yaml
  examples/v1/taskruns/stepactions-steptemplate.yaml
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/apis/config/testdata/feature-flags-invalid-enable-step-actions.yaml
  pkg/apis/config/testdata/feature-flags-step-actions.yaml
  pkg/apis/pipeline/v1/container_types.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/result_types.go
  pkg/apis/pipeline/v1/result_validation.go
  pkg/apis/pipeline/v1/result_validation_test.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/types/result_types.go
  pkg/apis/pipeline/v1beta1/container_types.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/result_validation.go
  pkg/apis/pipeline/v1beta1/result_validation_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/task_validation.go
  pkg/apis/pipeline/v1beta1/task_validation_test.go
  pkg/pod/entrypoint_test.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/artifacts_test.go
  test/e2e-tests-kind-prow-alpha.env
  test/e2e-tests-kind-prow-beta.env
  test/e2e-tests-kind-prow-feature-flags.env
  test/e2e-tests.sh
  test/featureflags.go
  test/per_feature_flags_test.go
  test/step_when_test.go
  test/stepaction_results_test.go
  test/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#8719 Remove temporary `GOPATH` generation in in `update-codegen.sh` and `update-openapigen.sh`.
  hack/setup-temporary-gopath.sh
  hack/update-codegen.sh
  hack/update-openapigen.sh
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#8693 Add ghcr.io migration banner to README.md.
  README.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none
