Repository tektoncd/pipeline, pull requests merged in 2025-05, with the labels that each got.

#8743 Add @waveywaves as a maintainer
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8685 Move Steps and Sidecars validation to `container_validation.go`.
  pkg/apis/pipeline/v1/container_validation.go
  pkg/apis/pipeline/v1/container_validation_test.go
  pkg/apis/pipeline/v1/task_validation.go
Labels: approved, lgtm, size/XL, release-note-none, kind/cleanup

#8746 fix: Ensure retryable errors during validation do not fail Runs
  docs/resolver-reference.md
  pkg/reconciler/apiserver/apiserver.go
  pkg/reconciler/apiserver/apiserver_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
  pkg/remoteresolution/resolver/framework/interface.go
  pkg/resolution/common/errors.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#8745 Migration to golangci-lint v2…
  .github/workflows/ci.yaml
  .golangci.yml
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#8710 Refactor sidecar validation to implement apis.Validatable.
  pkg/apis/pipeline/v1/container_validation.go
  pkg/apis/pipeline/v1/container_validation_test.go
  pkg/apis/pipeline/v1/task_types.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#8761 Update releases.md after v1.0.0
  releases.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#8744 fix(docs): correct documentation link errors related to sidecar-logs
  docs/tasks.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none

#8714 Raise test coverage in `task_validation.go` and `container_validation.go`.
  pkg/apis/pipeline/v1/container_validation.go
  pkg/apis/pipeline/v1/task_validation_test.go
Labels: approved, lgtm, size/L, ok-to-test, release-note-none, kind/cleanup

#8717 Refactor Step validation to implement apis.Validatable.
  pkg/apis/pipeline/v1/container_validation.go
  pkg/apis/pipeline/v1/task_types.go
  pkg/apis/pipeline/v1/task_validation.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/task_validation.go
Labels: approved, lgtm, size/M, release-note-none, kind/cleanup

#8709 Add oomkilled reason
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: kind/bug, approved, lgtm, size/XS, ok-to-test, release-note

#8767 docs: add more explicit language in the Pipelines in Pipelines docs
  docs/pipelines-in-pipelines.md
Labels: approved, lgtm, size/XS, kind/documentation, release-note-none
