Repository tektoncd/pipeline, pull requests merged in 2025-01, with the labels that each got.

#8465 fix: avoid panic when validate enum param with special matrix task
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: kind/bug, approved, lgtm, size/S, ok-to-test, release-note

#8447 fix: minor version check for sidecar logic
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test, release-note-none

#8451 [release-v0.56.x] .github/workflows: backport e2e workflows
  .github/workflows/e2e-matrix.yml
  hack/setup-kind.sh
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#8461 Fixed `make goimports`
  Makefile
Labels: approved, lgtm, size/XS, ok-to-test, release-note-none, kind/misc

#8454 .github/workflows: run e2e-matrix on all pull-request
  .github/workflows/e2e-matrix.yml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8480 Migrate golangci-lint to a github workflow
  .github/workflows/golangci-lint.yaml
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#8366 Make resolvers' maximum resolution timeout configurable
  config/config-defaults.yaml
  pkg/apis/config/default.go
  pkg/apis/config/default_test.go
  pkg/reconciler/resolutionrequest/controller.go
  pkg/reconciler/resolutionrequest/resolutionrequest.go
  pkg/reconciler/resolutionrequest/resolutionrequest_test.go
  pkg/resolution/resolver/bundle/config.go
  pkg/resolution/resolver/bundle/resolver.go
  pkg/resolution/resolver/bundle/resolver_test.go
  test/resolver-with-timeout/README.md
  test/resolver-with-timeout/config/resolver_with_timeout_deployment.yaml
  test/resolver-with-timeout/go.mod
  test/resolver-with-timeout/go.sum
  test/resolver-with-timeout/resolver/main.go
  test/resolver-with-timeout/resolver/main_test.go
  test/resolver-with-timeout/taksrun-resolver-with-timeout.yaml
Labels: approved, lgtm, size/XL, release-note-none, kind/misc

#8489 Fix dead admission-webhook blog link in developer docs
  docs/developers/controller-logic.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#8510 Add PipelineRun pipeline-timeout note to pipeline docs
  docs/pipelines.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#8540 Fix deprecated golangci-lint configuration
  .golangci.yml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8399 fix(computeresource/tasklevel): Fixed a bug where abnormal calculatio…
  pkg/internal/computeresources/tasklevel/tasklevel.go
  pkg/internal/computeresources/tasklevel/tasklevel_test.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test, release-note-none

#8545 tekton: fix micro typo on release-cheat-sheet
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, size/XS, release-note-none, kind/misc
