Repository tektoncd/pipeline, pull requests merged in 2025-07, with the labels that each got.

#8629 Add a tool to generate the release name
  tekton/release-cheat-sheet.md
  tekton/release_names.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#8863 Re-register metrics only during real update
  pkg/pipelinerunmetrics/metrics.go
  pkg/pipelinerunmetrics/metrics_test.go
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#8875 Stop emitting deprecated metrics
  docs/metrics.md
  pkg/pipelinerunmetrics/metrics.go
  pkg/pipelinerunmetrics/metrics_test.go
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: approved, lgtm, size/L, release-note, kind/misc

#8861 Resolvers: remove default TEKTON_HUB_API URI
  config/resolvers/resolvers-deployment.yaml
Labels: approved, lgtm, size/XS, release-note, kind/cleanup

#8880 Add Stanislav (twoGiants) as reviewer to Tekton Pipeline repository.
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8901 efficient polling in `waitForStepsToFinish`
  config/config-defaults.yaml
  docs/additional-configs.md
  internal/sidecarlogresults/sidecarlogresults.go
  internal/sidecarlogresults/sidecarlogresults_test.go
  pkg/apis/config/default.go
  pkg/apis/config/default_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  test/e2e-tests.sh
Labels: kind/bug, approved, lgtm, size/L, release-note

#8909 refactor getSidecarLogPollingInterval()
  internal/sidecarlogresults/sidecarlogresults.go
  internal/sidecarlogresults/sidecarlogresults_test.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#8890 Feature: Allow THREADS_PER_CONTROLLER env var to override default threads-per-controller value
  cmd/controller/main.go
  cmd/resolvers/main.go
  docs/tekton-controller-performance-configuration.md
Labels: kind/feature, approved, lgtm, size/S, release-note

#8920 Move ConfigMap helpers to testing framework and cleanup :broom: `pipelinerun_test.go` :broom:.
  pkg/pod/pod_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/resolutionrequest/resolutionrequest_test.go
  pkg/reconciler/testing/configmap.go
Labels: approved, lgtm, size/L, release-note-none, kind/cleanup

#8926 exponential backoff in `taskRun` controller
  pkg/controller/errors.go
  pkg/controller/errors_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note
