Repository tektoncd/pipeline, pull requests merged in 2025-02, with the labels that each got.

#8559 releases.md: add 0.68.0 LTS and update other releases
  releases.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#8562 fix: resolve panic issue in pipeline controller caused by CustomRun
  pkg/reconciler/pipelinerun/resources/validate_dependencies.go
  pkg/reconciler/pipelinerun/resources/validate_dependencies_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#8570 .github/workflows: force go to 1.23 for the lint job
  .github/workflows/golangci-lint.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8444 fix broken link to tutorials.md page
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS, kind/documentation, ok-to-test, release-note-none

#8577 .github/workflows: add a build and test workflows
  .github/workflows/ci.yaml
  .github/workflows/e2e-matrix.yml
  .github/workflows/golangci-lint.yaml
  Makefile
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#8583 [release-v0.68.x] .github/workflows: add a build and test workflows
  .github/workflows/ci.yaml
  .github/workflows/e2e-matrix.yml
  .github/workflows/golangci-lint.yaml
  Makefile
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#8580 [release-v0.59.x] .github/workflows: add a build and test workflows
  .github/workflows/ci.yaml
  .github/workflows/e2e-matrix.yml
  Makefile
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#8569 fix: Move when condition to higher priority
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
  pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
Labels: kind/bug, approved, lgtm, size/S, ok-to-test, release-note

#8186 Add feature flag `set-security-context-read-only-root-filesystem` to set readOnlyRootFilesystem for containers
  config/config-feature-flags.yaml
  docs/additional-configs.md
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/apis/config/testdata/feature-flags-invalid-set_security_context_read_only_root_filesystem.yaml
  pkg/internal/affinityassistant/affinityassistant_types.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/pod/script.go
  pkg/pod/script_test.go
  pkg/pod/security_context_config.go
  pkg/pod/security_context_config_test.go
  pkg/pod/workingdir_init.go
  pkg/pod/workingdir_init_test.go
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
Labels: kind/feature, approved, lgtm, size/XL, ok-to-test, release-note
