Repository tektoncd/pipeline, pull requests merged in 2025-03, with the labels that each got.

#8604 .github/workflow: add only-new-issues on lint
  .github/workflows/ci.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8606 chore: add yaml linting to pre-commit
  .pre-commit-config.yaml
Labels: approved, lgtm, size/XS, release-note-none, kind/misc

#8340 Refactor pipelinerun metrics tests
  pkg/pipelinerunmetrics/metrics_test.go
Labels: approved, lgtm, size/L, release-note-none, kind/misc

#8641 fix: Fix remote task params default-value substitution
  examples/v1/taskruns/default_task_params.yaml
  pkg/reconciler/taskrun/resources/taskref.go
  pkg/reconciler/taskrun/resources/taskref_test.go
  pkg/reconciler/taskrun/resources/taskspec.go
  test/taskrun_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#8542 cleanup: breakup the pkg/credentials into writer and matcher + ensure non corev1 usage in entrypoint for FIPs compliance
  cmd/entrypoint/main.go
  pkg/credentials/common/constants.go
  pkg/credentials/dockercreds/creds.go
  pkg/credentials/dockercreds/creds_test.go
  pkg/credentials/gitcreds/basic.go
  pkg/credentials/gitcreds/creds.go
  pkg/credentials/gitcreds/creds_test.go
  pkg/credentials/gitcreds/ssh.go
  pkg/credentials/matcher/matcher.go
  pkg/credentials/matcher/matcher_test.go
  pkg/credentials/writer/writer.go
  pkg/credentials/writer/writer_test.go
  pkg/entrypoint/entrypointer.go
  pkg/pod/creds_init.go
Labels: approved, lgtm, size/XL, release-note, kind/cleanup

#8661 Fix wrong entry in development documentation and other minor documentation corrections.
  DEVELOPMENT.md
  Makefile
  test/README.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#8662 Document `ko` settings for kind clusters with and without a local registry.
  DEVELOPMENT.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#8574 Add configuration for custom bundle resolver backoff
  docs/bundle-resolver.md
  pkg/resolution/resolver/bundle/bundle.go
  pkg/resolution/resolver/bundle/config.go
  pkg/resolution/resolver/bundle/resolver_test.go
Labels: kind/feature, approved, lgtm, size/L, ok-to-test, release-note
