Repository tektoncd/pipeline, pull requests merged in 2025-09, with the labels that each got.

#9012 Disable the Gitea e2e tests temporarily to unblock
  test/resolvers_gitea_test.go
  test/resolvers_test.go
Labels: approved, lgtm, size/XL, release-note-none

#8997 [release-v1.3.x] check `initContainers` for kubernetes sidecar implementation
  pkg/pod/status.go
  pkg/pod/status_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#9017 [release-v1.0.x] Disable the Gitea e2e tests temporarily to unblock
  test/resolvers_gitea_test.go
  test/resolvers_test.go
Labels: approved, lgtm, size/XL, release-note-none

#9000 [release-v1.3.x] Do not fail PipelineRun if pvc creation error is because of exceeded quotas
  pkg/reconciler/pipelinerun/affinity_assistant.go
  pkg/reconciler/pipelinerun/affinity_assistant_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/volumeclaim/pvchandler.go
  pkg/reconciler/volumeclaim/pvchandler_test.go
Labels: approved, lgtm, size/L, release-note-none

#9024 [release-v1.0.x] fix: allow finalizer updates on completed TaskRun and PipelineRuns
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
Labels: approved, lgtm, size/XL, release-note-none

#9022 document 1.3.2 patch
  releases.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#8965 Add Support for managedBy field in TaskRun and PipelineRun
  config/300-crds/300-pipelinerun.yaml
  config/300-crds/300-taskrun.yaml
  docs/pipelineruns.md
  docs/taskruns.md
  pkg/apis/pipeline/register.go
  pkg/apis/pipeline/v1/openapi_generated.go
  pkg/apis/pipeline/v1/pipelinerun_types.go
  pkg/apis/pipeline/v1/pipelinerun_validation.go
  pkg/apis/pipeline/v1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1/swagger.json
  pkg/apis/pipeline/v1/taskrun_types.go
  pkg/apis/pipeline/v1/taskrun_validation.go
  pkg/apis/pipeline/v1/taskrun_validation_test.go
  pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1beta1/openapi_generated.go
  pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
  pkg/apis/pipeline/v1beta1/swagger.json
  pkg/apis/pipeline/v1beta1/taskrun_types.go
  pkg/apis/pipeline/v1beta1/taskrun_validation.go
  pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
  pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/controller_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/controller_test.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note
